### ISSUE TITLE
cobbler 2.6.1 centos7 No signature matched in

### ISSUE THREAD

**Issue by martin201404** [cobbler/cobbler#1028]
add patch:
patch https://github.com/cobbler/cobbler/commit/56acc66ffee28090fad2d6cf831c10a0d7f6516c
patch https://github.com/cobbler/cobbler/pull/1026

cobbler import --name=centos-7.0-x86_64 --path=/mnt 
task started: 2014-07-10_090226_import
task started (id=Media import, time=Thu Jul 10 09:02:26 2014)
Found a candidate signature: breed=redhat, version=rhel6
Found a candidate signature: breed=redhat, version=rhel7
Found a candidate signature: breed=redhat, version=fedora20
Found a candidate signature: breed=redhat, version=cloudlinux6
Found a candidate signature: breed=redhat, version=fedora16
Found a candidate signature: breed=redhat, version=fedora17
Found a candidate signature: breed=redhat, version=fedora18
Found a candidate signature: breed=redhat, version=fedora19
No signature matched in /var/www/cobbler/ks_mirror/centos-7.0-x86_64
!!! TASK FAILED !!!
tail /var/log/cobbler/cobbler.log  
Thu Jul 10 09:05:30 2014 - DEBUG | received on stderr:

**Comment by ycs0220** [comment]
why?
