### ISSUE TITLE
import centos 7 to cobbler

### ISSUE THREAD

**Issue by cleonte** [cobbler/cobbler#1029]
Hi Cobbler Team,

i'm trying to import a centos7 iso into cobbler, when doing this i get this message

cobbler import --breed=redhat --name=CentOS7-64 --arch=x86_64 --path=/media/
task started: 2014-07-10_203241_import
task started (id=Media import, time=Thu Jul 10 20:32:41 2014)
Found a candidate signature: breed=redhat, version=rhel6
Found a candidate signature: breed=redhat, version=rhel7
Found a candidate signature: breed=redhat, version=fedora20
Found a candidate signature: breed=redhat, version=fedora16
Found a candidate signature: breed=redhat, version=fedora17
Found a candidate signature: breed=redhat, version=fedora18
Found a candidate signature: breed=redhat, version=fedora19
No signature matched in /var/www/cobbler/ks_mirror/CentOS7-64-x86_64

i have this version of cobbler

cobbler version
Cobbler 2.4.4
  source: ?, ?
  build time: Tue Apr 22 15:28:37 2014

any ideas?

Cheers,
Cristi

**Comment by bishopolis0** [comment]
# rpm -q cobbler
cobbler-2.6.3-1.el6.noarch

    # wget -O- -q http://cobbler.github.io/signatures/latest.json | less

I'm not seeing a c7 sig in here, but I do see a rhel7 one.  The diff from the stock RPM-delivered sigs shows just the removal of vivid, f22, etc; no additions.

After updating the sigs:
    # wget -O- -q \
    http://cobbler.github.io/signatures/latest.json \
    | tee \
      /etc/cobbler/distro_signatures.json \
      /var/lib/cobbler/distro_signatures.json \
     > /dev/null

It seems to still fail:
    # cobbler import --name centos7 --path /mnt/loopISOmount/
task started: 2015-07-24_113802_import
task started (id=Media import, time=Fri Jul 24 11:38:02 2015)
No signature matched in /var/www/cobbler/ks_mirror/centos7
!!! TASK FAILED !!!

Feel free NOT to reopen this (but tease gently) if it's just dumb user error on my part.  Any questions you have, I'd be happy to answer (stock c6/epel6 box, mostly).

**Comment by belimor** [comment]
@bishopolis0:

`service cobbler restart` - should fix the problem
