### ISSUE TITLE
On 2.6.3, I had to make a couple of changes to run.

### ISSUE THREAD

**Issue by MichaelTiernan** [cobbler/cobbler#1076]
I wiped and reloaded a machine for the purpose of running some of my own tests.

During this process, I had to install 'xinetd' for tftp to work and I had to locate and install python-tornado.noarch also. I'd have expected to be notified of these requirements/dependancies when adding the RPMs.

I also had to modify the /etc/cobbler/tftpd.template
From what was included to:

```
# default: off
# description: The tftp server serves files using the trivial file transfer \
#   protocol.  The tftp protocol is often used to boot diskless \
#   workstations, download configuration files to network-aware printers, \
#   and to start the installation process for some operating systems.
# server_args     = -B 1380 -v -s $args
# server          = $binary
service tftp
{
    disable         = no
    socket_type     = dgram
    protocol        = udp
    wait            = yes
    user            = $user
    server          = /usr/sbin/tftpd.py
    server_args     = $args
    per_source      = 11
    cps             = 100 2
    flags           = IPv4
}
```

Key change was the server and server args lines.

(I also didn't know where the '$binary' value was configured.)

**Comment by SchoolGuy** [comment]
2.6.3 is outdated and this issue is very old let's close it and open a new one for 2.8.5 or 3.1.1 if this is still applicable.
