### ISSUE TITLE
Please fix your website masthead. 

### ISSUE THREAD

**Issue by hickey** [cobbler/cobbler#1134]
I tried sending this to webmaster@cobblerd.org, but just received a bounced message back. 
----
This has been going on for a couple of weeks now and it is driving me a little crazy. When I visit your page in any browser (Firefox, Chrome and Safari have been tried) your masthead overlays the the page menu so that half the menu is not accessible. Seems that you would have fixed this by now as it is pretty obvious. Here is a sample of one of your pages to illustrate what I am talking about. 

http://picpaste.com/Installing_Cobbler.png

**Comment by jmaas** [comment]
Fixed.
