### ISSUE TITLE
[FC20] Failing to fetch kickstart from standalone iso

### ISSUE THREAD

**Issue by trexx** [cobbler/cobbler#1136]
Hi there,

I've created a standalone Fedora 20 iso using Cobbler 2.4.4 however when attempting to boot from it, it seems to have trouble finding the kickstart file:
dracut-initqueue: Warning: failed to fetch kickstart from cdrom:/isolinux/Fedora-20-i386.cfg

After doing some digging I came across this bug report / comment which assisted me.
https://bugzilla.redhat.com/show_bug.cgi?id=963003#c15

Editing the path at the boot menu to include double colons (cdrom::/isolinux/Fedora-20-i386.cfg) allows the image to boot and the install to progress. To note, this does not effect PXE boot or netboot images.

I've made an edit to my cobbler install here https://github.com/cobbler/cobbler/blob/15b4d6132cb0bdcee2ee04d7a2637bf401b74f6b/cobbler/action_buildiso.py#L472 to workaround the issue.

**Comment by SchoolGuy** [comment]
Fedora 20 is long EOL. I will close this. If we have this problem with more recent versions we can create a new bug.
