### ISSUE TITLE
Enable pxe boot flag for systems?

### ISSUE THREAD

**Issue by Jenpatrick** [cobbler/cobbler#1157]
Hi.
I know that cobbler can be set to power on/off (reset) the machine.  But i'd like to know if there's a way to slip in an option to tell ipmi to boot the machine via pxe?

By default the machine is set to boot from disk (that's what is configured in the Bios). If I want to reinstall, I would try to setting the machine next time reboot from pxe, just one time.

So I need run

ipmitool -U user -P pass -H 1.2.3.4 chassis bootdev pxe  (manually)

It'd be nice if cobbler supported an option to set the pxe flag.  This way, if I have the case of having hundreds of machines, I _don't_ have to go into the bios manually for each one, and set them to network boot first.  They can be set to the factory default of Boot: CD/Hard Disk/Network and cobbler is telling them via an option to just ONCE set the boot order to pxe.

Can you guys implement this?

Thanks.
JLP

**Comment by watologo1** [comment]
> I don't have to go into the bios manually for each one

This is impossible. At least for cobbler and legacy x86.
This could work with UEFI (the tool is called efibootmanager) where you can tell the BIOS from OS to network boot next time.

But still, IMO this is nothing for cobbler. You simply have to set your machine to network boot to integrate. Can this request get closed?

**Comment by opoplawski** [comment]
I'm of too minds here.  Certainly the standard mode of operation is to configure machines to always PXE boot, and then the default menu will boot from the hard drive unless the system is marked for reinstall in cobbler.

But the idea of being able to leverage IPMI to enable PXE so as to not have to make manual system configuration changes on individual machines has its attraction.  However I think this is going to need someone to champion it and create a PR for it, so I think it could be closed unless someone is interested in taking it on.  I'm not up for it.

**Comment by watologo1** [comment]
As discussed. Closing as the request is 4 years old and won't work on legacy (non UEFI) platforms at all.
And on legacy systems this support was suggested.

**Comment by owenmann** [comment]
Hold on a minute - not only is it possible, but I've done it! See: https://lists.fedorahosted.org/pipermail/cobbler-devel/2012-January/002604.html
Google "ipmitool chassis bootdev pxe".
I actually did add the button to the GUI back then, but then Cobbler 2.x came out and I couldn't figure out how to port my patch to the new web framework.
My co-workers and I are in the final stages of choosing a deployment solution, and coincidentally this came up. So 🤞 we might be able to work on this.

**Comment by watologo1** [comment]
Indeed.
Looks very convenient if this works reliable. I'll try it on the next new machine. I was used to configure this through the BIOS settings.
But this only needs to be done or say should only be done once, right?
Then cobblerd is always on full control. On a "local" boot, legacy BIOSes would simply continue with the next boot device (which should be the disk then).
I would suggest an ipmitool script example, setting up boot to PXE, configuring serial console, if executed local (-I open), it could even set username/password for later cobblerd accesses.

**Comment by owenmann** [comment]
It's not even that complicated. It's the equivalent of "Press F12 for the next boot only".
