### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1169]
Include the manuals within the main source tree
Use sphinx, markdown
Readthedocs.org

**Comment by mxjeff** [comment]
Please add http xmlrpc api documentation as well :)

**Comment by SchoolGuy** [comment]
Readthedocs for Cobbler is live for master. Backports still need to be done. Koan is under review from @brejoc.

XMLRPC Documentation is not done but will be added as soon as possible.

**Comment by SchoolGuy** [comment]
Koan was merged a few days ago. Backports need to be done. Some goes for xmlrpc docs...

**Comment by SchoolGuy** [comment]
Porting the Docs from cobbler.github.io to rtd was successful and the PR's for Koan are open.

**Comment by SchoolGuy** [comment]
So everything is done expect the api docs. This is in progress with #2206 after it is merged we can close this.

**Comment by SchoolGuy** [comment]
The corresponding PR was merged. Everything else we now need to do can be solved otherwise.
