### ISSUE TITLE
manage_dhcp: 1 / [dhcp] module = manage_dnsmasq doesn't start dnsmasq

### ISSUE THREAD

**Issue by igalic** [cobbler/cobbler#1244]
i'm trying to configure cobbler to use dnsmasq as dhcpserver. my plan is to only bootstrap (pxe boot) from there, and then set static ips.

however, cobbler doesn't start dnsmasq.
cobbler check seems fine, despite an output of `dnsmasq --help` in the log.

checking cobbler/modules/manage_dnsmasq.py, it would appear i would need the "real" dnsmasq package installed, which would provide an actual service.
but even then no configuration file is written from the template.

**Comment by jmaas** [comment]
Need to verify this.

**Comment by jmaas** [comment]
you must enable the dnsmasq service first.
then cobbler can restart it properly after a `cobbler sync`.

cant reproduce, and this is an old issue.

closing.
