### ISSUE TITLE
bug in kicktart_start snippet

### ISSUE THREAD

**Issue by lflaks** [cobbler/cobbler#1252]
I've been looking into this snippet and noticed that condition 
`# else if $breed == 'vmware'` is checked twice in the first part of it. I am not very familiar with vmware installs, so I don't know which one is correct and which should be removed.

**Comment by SchoolGuy** [comment]
You were right. The two else ifs were identical. I removed one.

**Comment by SchoolGuy** [comment]
Closed via #2367
