### ISSUE TITLE
Add scripts to cobbler_web like snippets and kickstarts

### ISSUE THREAD

**Issue by spicysomtam** [cobbler/cobbler#1259]
ubuntu/debian seeding. The debian installer does not allow pre and post blocks in the seed file like kickstart, so you need to put all of this in the pre and post seed files, which are kept in the cobbler scripts dir. Can we have a cobbler_web option so we can edit these from the web interface?

**Comment by jmaas** [comment]
copied to cobbler/cobbler-web repo.
