### ISSUE TITLE
Create a Makefile target to create .deb (Debian/Ubuntu) packages 

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1279]
Cobbler already has a 'rpms' target in Makefile to build rpm packages, it makes sense to do the same for .deb packages.

**Comment by gregswift** [comment]
If you want to steal it...

https://github.com/gregswift/makefiles/blob/master/Makefile.python#L85-L102

**Comment by SchoolGuy** [comment]
This is now part in our cross-distro specfile and done via docker-compose thus we can see this as done.
