### ISSUE TITLE
Refactor Nexenta's automatic installation file generation

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1280]
Issues:
- Nexenta's automated installation file (aka installation profile) in kickstarts dir should have no system info in its name or content, it should be only a template as we have in kickstart/autoyast/preseed templates
- Nexenta's automated installation file should be generated on the fly by service.py using profile/system data to fill in the template, as it is done to generate kickstart/autoyast/preseed files

**Comment by SchoolGuy** [comment]
Explicit Nexenta support was removed with 2a5694efae53685226fa3041f4b002e1ad70f712, thus I will close this issue.
