### ISSUE TITLE
Support DHCP/TFTP proxy in Cobbler

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1290]
DHCP protocol is restricted to one subnet, as a system broadcasts to find a DHCP server, broadcast is only supported in the data link layer in TCP/IP protocol stack and therefore can only reach current subnet. 

If user desires that Cobbler manages DHCP server (most common case) and systems are in more than one subnet, user must either (1) have one vlan/network interface per each subnet, (2) manuall setup a DHCP server in other subnets and forward DHCP requests to Cobbler server or (3) have a Cobbler instance per subnet. Currently, I do a combination of (1) and (3) in my Cobbler setup. It would be simpler if, instead of doing (3), Cobbler would automatically manage DHCP configuration file in the DHCP server in each subnet.

The same could be done for content provided by TFTP server to reduce the network latency of downloading boot loader conf/initrd/kernel to system and thus decrease OS installation time. If useful, this could be extended to other protocols.

A similar concept exists in the Foreman tool: "smart proxy" (http://theforeman.org/manuals/1.6/index.html)

**Comment by SchoolGuy** [comment]
So nothing has moved here in half a decade... Thus I would like to close this. Refactoring the Cobbler Server to manage remote services would require us to redo the architecture. Thus I will close this as the benefit does not reflect the needs of the majority currently.
