### ISSUE TITLE
configuration file/option for whitelisting directories in web_root

### ISSUE THREAD

**Issue by Hefeweizen** [cobbler/cobbler#1295]
I'm mounting /var/www/cobbler from NFS.  It's Netapp, so there's a '.snapshot' directory.  'cobbler sync' wants to remove/clean-up this directory.  Nothing happens, as .snapshot is read-only, but there's a noticable delay as the command runs.

At first blush, the change is simple: whitelist the directory in action_sync.py.  However, I'm not a fan of this approach because a version upgrade could lose this change. More preferable, I believe, would be a file with whitelisted directories.  Thoughts?

**Comment by jasonmechler** [comment]
This has regressed, at least in the 2.8 version that ships with CentOS7. I had to hack up action_sync.py to avoid it trying to cleanup .snapshot. Is the correct mechanism to re-open this issue or open a new one?
