### ISSUE TITLE
Cobbler 2.6.5: Failed to import OVS-3.3.1 due to no signature matched

### ISSUE THREAD

**Issue by rluan** [cobbler/cobbler#1297]
see below output:
[root@cobbler ~]# cobbler import --path=/mnt --name=OVS-3.3.1 --arch=x86_64
task started: 2014-09-29_191731_import
task started (id=Media import, time=Mon Sep 29 19:17:31 2014)
Found a candidate signature: breed=redhat, version=rhel6
Found a candidate signature: breed=redhat, version=rhel7
Found a candidate signature: breed=redhat, version=rhel5
Found a candidate signature: breed=redhat, version=fedora20
Found a candidate signature: breed=redhat, version=cloudlinux6
Found a candidate signature: breed=redhat, version=fedora16
Found a candidate signature: breed=redhat, version=fedora17
Found a candidate signature: breed=redhat, version=fedora18
Found a candidate signature: breed=redhat, version=fedora19
No signature matched in /var/www/cobbler/ks_mirror/OVS-3.3.1-x86_64
!!! TASK FAILED !!!
[root@cobbler ~]# cobbler --version
Cobbler 2.6.5
  source: ?, ?
  build time: Fri Aug 15 18:00:00 2014
and I just get this ISO file from oracle:
http://www.oracle.com/technetwork/server-storage/vm/downloads/ovm-2227363.html
would you pls look into this issue and fix it? Thanks!

**Comment by acanlord** [comment]
Any Eta on this? Would be great to have ovs3.x included.

I  tried the steps mentioned by rluan but got a json error the following.
"initrd_file":"initrd(.)\.img",
I replaced it with  "initrd_file":"initrd(.*)\\.img",
That get's it to import but its still failing with the following.

task started (id=Media import, time=Tue Nov 24 17:39:03 2015)
Found a candidate signature: breed=redhat, version=ovs3
No signature matched in /var/www/cobbler/ks_mirror/OVS-3.3.3
!!! TASK FAILED !!!
Any suggesntions?
