### ISSUE TITLE
"--dns-name" flag not creating a DNS Entry

### ISSUE THREAD

**Issue by zparihar** [cobbler/cobbler#1315]
Hey guys!

I'm wondering if someone could help me out.  I'm having troubles with the "--dns-name" flag.

I'm running RHEL 6.5  - 64 Bit with the following packages:

cobbler-2.6.3-1.el6.noarch
dhcp-4.1.1-38.P1.el6.x86_64
bind-9.8.2-0.17.rc1.el6_4.6.x86_64

The Cobbler Servers IP address is 192.168.2.138

Here is my Cobbler files:

/etc/cobbler/settings : http://pastebin.com/X0C3w6pQ
/etc/cobbler/named.template: http://pastebin.com/cTEKZ9s0
/etc/cobbler/zone_templates/dev.bamsas.com: http://pastebin.com/59E9FrTj

When I create a  system by running the following:

cobbler system add --name=bam-first-install-test --profile=bam-initial-test --mac=00:50:56:ba:73:52 --ip-address=192.168.2.170 --dns-name=vm-test.dev.bamsas.com --interface=eth0 --hostname=vm-test.dev.bamsas.com

I don't see a zone file created on my local bind server after I run a 'cobbler sync'

What am I doing wrong?

**Comment by GreatSUN** [comment]
same problem here...

pastebins:
/etc/cobbler/settings http://pastebin.com/2mtPYqfR
/cat /etc/cobbler/named.template http://pastebin.com/MYC4Yu61
/etc/cobbler/zone_templates/etcd.kubernetes.internal http://pastebin.com/kJH8dnWq

any idea, what I did wrong here?

**Comment by GreatSUN** [comment]
sad but true, now it is again not working anymore... Please follow up with any idea. Thanks

**Comment by GreatSUN** [comment]
got it working finally... you need to have a static ip defined for the iface, so that a dns is defined for this
