### ISSUE TITLE
service cobblerd status does not work on CentOS 6.5

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1317]
Using code from master branch.

When service is running, service cobblerd status outputs:
cobblerd dead but subsys locked

Debugging, I found that the root cause is that "service cobblerd status" runs "pidof -x cobblerd" and this command outputs nothing. This is related to the executable name and hashbang in python script, according to: http://www.linuxquestions.org/questions/programming-9/pidof-x-python-script-not-always-working-4175492559/ .  It looks like this will break "service cobblerd status" on any Red Hat 6 based distro. Replacing current hashbang with "#!/usr/bin/python" fixed the issue.

This was broken in commit fed2a428774b6a0334f62c2f38a3835c406a048a. What is the benefit of using env instead of python directly? I recommend we use the previous hashbang in cobblerd service.

Jörgen, you agree?

**Comment by jmaas** [comment]
master is targeted at el7+, debian8 etc, all systemd based right now.
no need to bother with stupid init scripts anymore ;)

**Comment by SchoolGuy** [comment]
Let's close this one. If status would not work in the current supported releases, then we need new bug reports or this one reopned with new information.
