### ISSUE TITLE
post_install_network_config_deb sets null hwaddress

### ISSUE THREAD

**Issue by spicysomtam** [cobbler/cobbler#1322]
cobbler 2.6.3.
Which prevents network interface coming up.

Senario: set static ip for server, which does not need a mac address. cobbler writes /etc/network/interfaces with hwadress set to no value. On boot network does not come up because of invalid interfaces file.

Work around/fix: 
edit/make copy of post_install_network_config_deb .
Add if statement around block that writes hwaddress:

#if $mac != ""
echo "   hwaddress $mac" >> /etc/network/interfaces
#end if

**Comment by jmaas** [comment]
Yes, i will do this for the next release.

**Comment by jmaas** [comment]
I have submitted this to my local copy of the release28 since this change was bundled with the removal of interface types: master/slave and the subnet field.

**Comment by jmaas** [comment]
Now the quickfix is also in release26.
