### ISSUE TITLE
Modification of management screen template definitions.

### ISSUE THREAD

**Issue by MichaelTiernan** [cobbler/cobbler#1325]
I'm not sure how else to describe it in a short line. To simplify this, I'm going to post the contents of the email exchange we had on the mailing list.

> On 09/17/2014 10:25 AM, Michael Tiernan wrote:
> 
> > As just an aside, may I express displeasure with the fact that the
> > templating currently "reads" as "Source" = "Target" instead of the more
> > logical "Target" = "Source"
> > 
> > Currently the syntax for the templates reads as if you were saying
> > 3+5=x instead of x=3+5
> 
> Sorry. I didn't mean the contents of the templates, I mean the template
> definitions as given to Cobbler in the "Management" screen.
> 
> Here's a template definition for one of my cobbler profiles:
>   /var/lib/cobbler/templates/ntp_conf.tmpl=/etc/ntp.conf
> 
> It _reads_ logically as:
>   Create the file "{source file on cobbler server}"
>   from the file "/etc/ntp.conf"
> 
> Whereas one would _expect_ it to read:
>   /etc/ntp.conf=/var/lib/cobbler/templates/ntp_conf.tmpl
> 
> i.e:  ${Target} = ${Source}
> 
> While writing this, it occurs to me that should we have the option, it
> would be "logical" the way it is written if it said:
>    ${Source} => ${Target}
> 
> The difference being the visible "direction of movement" shown by the
> arrowhead. Either "->" or "=>" would produce the same thing.
> 
> Again, just an opinion.

As I was composing this ticket, a thought occurs to me, another variation of the GUI which may address this would be to use a two text field entry for each template file definition.

![example](https://cloud.githubusercontent.com/assets/7912879/4791106/7b870030-5dd9-11e4-8372-88c876a472d3.png)

**Comment by SchoolGuy** [comment]
Since the GUI will be removed with 3.3.0, we will recompose everything. Thus I will close this one and we will open another one in the web repo if needed.
