### ISSUE TITLE
Distro import doc mentions distro can be imported from an ISO file, but it cannot

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1337]
In http://www.cobblerd.org/manuals/2.6.0/3/2/4_-_Import.html, I read: "This mirrors content based on a DVD image, an ISO file, a tree on a mounted filesystem, an external rsync mirror or SSH location.". Points:
- most DVD images are in ISO format, so "a DVD image, an ISO file" is confusing imho 
- Cobbler does not import a distro from an ISO file or other CD/DVD image file formats

Two possible solutions:
- Improve code to mount an ISO if an ISO filepath is provided as input
- Improve doc

I prefer the former one.

**Comment by watologo1** [comment]
Sigh.., above link is dead:
 http://www.cobblerd.org/manuals/2.6.0/3/2/4_-_Import.html

But why don't you simply loop mount the iso into a directory and pass the mounted directory as distro path?
It does not make sense to implement this step into python code. This makes it unnecessary complicated.

mount /../openSUSE-Tumbleweed/openSUSE-Tumbleweed-DVD-x86_64-Snapshot20191210-Media.iso /mnt -o loop

# ls /mnt/
.treeinfo  CHECKSUMS.asc  GPLv2.txt  README      SUSEgo.png  boot  gpg-pubkey-307e3d54-5aaa90a5.asc  gpg-pubkey-3dbdc284-53674dd4.asc  noarch    x86_64
CHECKSUMS  EFI            GPLv3.txt  SUSEgo.ico  SUSEgo.svg  docu  gpg-pubkey-39db7c82-5847eb1f.asc  media.1                           repodata

**Comment by SchoolGuy** [comment]
Okay this one seems then to be resolved and also outdated. Closing for just mentioned reasons.
