### ISSUE TITLE
Centralize kernel command line generation

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1343]
This is currently split between action_buildiso.py and tftpgen.py. Definition of several kernel options (eg ks) is duplicated in both modules. Apply DRY and have one common method to build kernel options.

**Comment by jmaas** [comment]
@alanoe do you still have this somewhere?

**Comment by watologo1** [comment]
I moved a tiny bit into this direction by renaming the func in utils to a general (not distro specific) kopts function:

```
-        # SUSE is not using 'text'. Instead 'textmode' is used as kernel option.
-        utils.suse_kopts_textmode_overwrite(distro, kopts)
+        # SUSE and other distro specific kernel additions or modificatins
+        utils.kopts_overwrite(system, distro, kopts, self.settings)

```

This issue is rather old, the code you have/had is probably outdated?
If not, please submit/paste.

I close this one for now cleanup/overview reasons.
