### ISSUE TITLE
d6888de3176829a6f19e15fd72911eeddbe0f08b completely wipes working installations

### ISSUE THREAD

**Issue by nacc** [cobbler/cobbler#1344]
The $subject commit changes the name from ks_mirror to distro_mirror. Unfortunately, there is existing code that deletes non-Cobbler controlled directories, which ks_mirror is now one of. Thus, this commit led to all of my existing kickstart mirror (50GB of data or so) being deleted. This code should either not delete anything (what if a user had put other data in that directory?) or you should have _added_ directories being controlled by Cobbler with some warning in place for historical places.

**Comment by SchoolGuy** [comment]
That is a conversion error from 2014. Let's not bother for this one.
