### ISSUE TITLE
repo config files not deleted on distro delete

### ISSUE THREAD

**Issue by nacc** [cobbler/cobbler#1370]
cobbler/modules/manage_import_signatures.py::yum_repo_adder -> yum_repo_scanner -> yum_process_comps_file creates files like:

```
        fname = os.path.join(self.settings.webdir, "distro_mirror", "config", "%s-%s.repo" % (distro.name, counter))
```

but cobbler/collection_distros.py::remove does not remove those files.

**Comment by JohanElmis** [comment]
I did run into this issue as well with Cobbler 2.6.11 yesterday.

I have made a cobbler distro copy - and then changed initrd, kernel and ksmeta   values for the new distro.
Still the Rsyncd.conf -file had a path pointing to the old distro - and that's what was synced out to all the site-specific cobbler-servers.
I deleted the distros, and made a cobbler sync - but the faulty distros were still present in the rsync config. Took me a while to find out that the distros in the rsync-file is "built" from what's in /var/www/cobbler/links
After deleting the bad symlinks there - I could create new distros with the add-command that are working just fine.
But these links should really be managed both while copying/edit - but definitly when deleting the distro.

**Comment by JohanElmis** [comment]
Examples:
cobbler distro copy --name=CentOS-7.2-x86_64 --newname=CentOS-7.3-x86_64
cobbler distro edit --name=CentOS-7.3-x86_64 --initrd="/var/www/cobbler/ks_mirror/CentOS-7.3-x86_64/images/pxeboot/initrd.img"
cobbler distro edit --name=CentOS-7.3-x86_64 --kernel="/var/www/cobbler/ks_mirror/CentOS-7.3-x86_64/images/pxeboot/vmlinuz"
..
cobbler sync
# results in this snippet in /etc/rsyncd.conf
[distro-CentOS-7.3-x86_64]
    path    = /raid/cobbler/ks_mirror/CentOS-7.2-x86_64
    comment = Cobbler Distro CentOS-7.3-x86_64

ll /var/www/cobbler/links/
lrwxrwxrwx 1 root root 44 Dec 16 02:18 CentOS-7.3-x86_64 -> /var/www/cobbler/ks_mirror/CentOS-7.2-x86_64

As the link is not removed - it will not update it either. - and everything from within cobbler looks just fine. (which makes it really hard to find.)

**Comment by hbokh** [comment]
Also in Cobbler 3.1.1.
Distro named "Test" will leave these behind when deleted.
```
/var/www/cobbler/images/Test
/var/www/cobbler/images/Test/initrd.gz
/var/www/cobbler/images/Test/linux
/var/www/cobbler/links/Test
```

**Comment by watologo1** [comment]
@loreson :
Can you have a look at hbokh recent comment:

/var/www/cobbler/images/*/*

It would be great if you can have a closer look at possibilities to link linux/initrd if possible...
This is rather important for us for rolling releases like Tumbleweed or if in devel phase.

**Comment by SchoolGuy** [comment]
@loreson @watologo1 Will work on this happen or can I unassign him/you again?

**Comment by nodeg** [comment]
@hbokh I was not able to reproduce this on `master` on openSUSE Leap 15.2. 

```shell
❯ mount
(...)
/home/dom/CentOS-8.3.2011-x86_64-dvd1.iso on /home/dom/centos_dvd type iso9660 (ro,relatime,nojoliet,check=s,map=n,blocksize=2048)

❯ cobbler version
Cobbler 3.2.0
  source: 4eef9800, Thu Mar 4 08:41:33 2021 +0100
  build time: Thu Mar  4 12:11:46 2021

~
❯ cobbler import --name=test --path=/home/dom/centos_dvd
task started: 2021-03-04_131800_import
task started (id=Media import, time=Thu Mar  4 13:18:00 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=redhat, version=rhel8
Found a matching signature: breed=redhat, version=rhel8
Adding distros from path /srv/www/cobbler/distro_mirror/test:
creating new distro: test-x86_64
trying symlink: /srv/www/cobbler/distro_mirror/test -> /srv/www/cobbler/links/test-x86_64
creating new profile: test-x86_64
associating repos
checking for rsync repo(s)
checking for rhn repo(s)
checking for yum repo(s)
starting descent into /srv/www/cobbler/distro_mirror/test for test-x86_64
processing repo at : /srv/www/cobbler/distro_mirror/test/AppStream
need to process repo/comps: /srv/www/cobbler/distro_mirror/test/AppStream
looking for /srv/www/cobbler/distro_mirror/test/AppStream/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/test/AppStream/repodata
processing repo at : /srv/www/cobbler/distro_mirror/test/BaseOS
need to process repo/comps: /srv/www/cobbler/distro_mirror/test/BaseOS
looking for /srv/www/cobbler/distro_mirror/test/BaseOS/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/test/BaseOS/repodata
*** TASK COMPLETE ***

~ 48s
❯ cobbler distro list                                   
   test-x86_64

~
❯ cobbler profile list
   test-x86_64

~
❯ ll /srv/www/cobbler/distro_mirror 
total 0
drwxr-xr-x 1 root root  72 2021-03-04 13:18 config
dr-xr-xr-x 1 root root 152 2020-11-18 22:39 test

~
❯ ll /srv/www/cobbler/links        
total 4.0K
lrwxrwxrwx 1 root root 35 2021-03-04 13:18 test-x86_64 -> /srv/www/cobbler/distro_mirror/test

~
❯ cobbler distro copy --name=test-x86_64 --newname=test2-x86_64

~
❯ cobbler distro list                                          
   test-x86_64
   test2-x86_64

~
❯ ll /srv/www/cobbler/distro_mirror 
total 0
drwxr-xr-x 1 root root  72 2021-03-04 13:18 config
dr-xr-xr-x 1 root root 152 2020-11-18 22:39 test

~
❯ ll /srv/www/cobbler/links        
total 8.0K
lrwxrwxrwx 1 root root 35 2021-03-04 13:20 test2-x86_64 -> /srv/www/cobbler/distro_mirror/test
lrwxrwxrwx 1 root root 35 2021-03-04 13:18 test-x86_64 -> /srv/www/cobbler/distro_mirror/test

~
❯ cobbler distro remove --name=test-x86_64
exception on server: 'removal would orphan profile: test-x86_64'

~
❯ cobbler profile remove --name=test-x86_64

~
❯ cobbler distro remove --name=test-x86_64 

~
❯ cobbler distro list                     
   test2-x86_64

~
❯ ll /srv/www/cobbler/distro_mirror 
total 0
drwxr-xr-x 1 root root  72 2021-03-04 13:18 config
dr-xr-xr-x 1 root root 152 2020-11-18 22:39 test

~
❯ ll /srv/www/cobbler/links        
total 4.0K
lrwxrwxrwx 1 root root 35 2021-03-04 13:20 test2-x86_64 -> /srv/www/cobbler/distro_mirror/test

~
❯ cobbler distro remove --name=test2-x86_64

~
❯ ll /srv/www/cobbler/distro_mirror        
total 0
drwxr-xr-x 1 root root 72 2021-03-04 13:18 config

~
❯ ll /srv/www/cobbler/links                
total 0

~
```
When removing only `test-x86_64`, the folder `/srv/www/cobbler/distro_mirror/test` still exists due to the existing link of the copy `test2-x86_64`. The link for `test-x86_64` was correctly removed. After removing `test2-x86_64` the folder `/srv/www/cobbler/distro_mirror/test` was also deleted.
So I think the behaviour of `cobbler distro remove` seems to be correct. When editing the created copy like @JohanElmis did above, though, those changes are not correctly stored within the folders of the copy. But this is another issue I will open in a few minutes.
@hbokh Could you do a quick test on `master`, please?

**Comment by hbokh** [comment]
> @hbokh Could you do a quick test on `master`, please?

This has been over a year...
Unfortunately I don't have the tests / infra available anymore to do this **quick**. I have to set that all up again, which I am not planning to ATM. Sorry...

**Comment by SchoolGuy** [comment]
@hbokh No problem. Then we check at a later point. The next release will take a while definitively...
