### ISSUE TITLE
Impossible to get system power status from XMLRPC

### ISSUE THREAD

**Issue by theunraveler** [cobbler/cobbler#1384]
Hello,

It seems that after https://github.com/cobbler/cobbler/commit/38dbd5c7badb5ca0a600b71d27c6486890b01f58, the entire power system can only be accessed via background tasks in the XMLRPC interface. This makes sense for power operations like `power_on`, `power_off`, and `reboot`, but makes retrieving the power status of a system very hard.

Unless I'm mistaken, in order to get the power status, you need to do the following (pseudo-code):

```
task_id = client.background_power_system(systems: ['my_system'], power: 'status')
# Once the task is completed...
event_log = client.get_event_log(task_id)
# Parse the log messages to get the status.
```

As you can see, this is extremely brittle, and provides for a pretty ugly API experience. Any chance of bringing back the `client.power_system` method, or implementing a seperate `client.power_status(system)` method?

Thanks!

**Comment by SchoolGuy** [comment]
So to get the power status you can be called with `status`.

https://cobbler.readthedocs.io/en/latest/code-autodoc/cobbler.html#cobbler.remote.CobblerXMLRPCInterface.power_system
