### ISSUE TITLE
Ubuntu/Debian permission error in cobbler-2.6.6-1

### ISSUE THREAD

**Issue by mech422** [cobbler/cobbler#1385]
Next issue - This repeats endlessly in the apache error log (its only a warning thoug):
```
warning: Failed to read auxiliary vector, /proc not mounted?
```
A quick google seems to indicate it occurs when chroots don't include /proc ?

Lastly - cobbler check always whines the loaders are missing, no matter how often I 'get-loaders':
```
root@bunsen:/etc/apache2/conf.d# cobbler check
The following are potential configuration items that you may want to fix:

1 : some network boot-loaders are missing from /var/lib/cobbler/loaders, you may run 'cobbler get-loaders' to download them, or, if you only want to handle x86/x86_64 netbooting, you may ensure that you have installed a *recent* version of the syslinux package installed and can ignore this message entirely.  Files in t...
```
I haven't bother trying to figure this one out yet...

One more permission 'error' - reposync tries to chown files to the 'apache' user (which is www-data on debian/ubuntu):
```
Downloaded 41514 MiB in 10013s at 4245.54 kiB/s.
Everything OK. Moving meta files ...
All done.

received on stderr:
running: chown -R root:apache /srv/www/cobbler/repo_mirror/debian-7.3.0-netinst-x86_64
received on stdout:
received on stderr: chown: invalid group: âroot:apacheâ

running: chmod -R 755 /srv/www/cobbler/repo_mirror/debian-7.3.0-netinst-x86_64
received on stdout:
received on stderr:
*** TASK COMPLETE ***
```
This should be harmless as 755 allows the www-data user to read the files anyway ...
Might be nice to add a config option for setting the user cobbler_web runs under ?

**Comment by jmaas** [comment]
Removed cobbler-web issues and copied that as a new issue to cobbler/cobbler-web.

**Comment by jmaas** [comment]
The missing boot-loader warning has been fixed in master by deleteing the elilo loader check. Elilo support has been dropped in master.
