### ISSUE TITLE
modprobe conf file handling in network setups with bonding is incorrect in RHEL 7+

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1394]
RHEL 7 uses /etc/modprobe.d/* instead of /etc/modprobe.conf and post_install_network_config snippet in Cobbler always tries to access /etc/modprobe.conf. Thus, network setup of a system with bonded network devices will fail.

**Comment by acjohnson** [comment]
This bug report isn't quite valid. RHEL 7 actually uses NetworkManager by default to manage network interfaces including bonding configurations. According to the RHEL 7 Networking Guide the bond interface file (ifcfg-bond#) needs to have two NetworkManager aware options set:
<pre>
TYPE=Bond
BONDING_MASTER=yes
</pre>
Once this gets added to the file the bonding module gets loaded by NetworkManager automatically.

Here is the code I've added to my post_install_network_config snippet to work around this for now:
```python
        #if ($osversion == "rhel7" and $iface_type == "bond")
echo "TYPE=Bond" >> $devfile
echo "BONDING_MASTER=yes" >> $devfile
        #end if
        #if $iface_type != "bridge"
            #unless ($osversion == "rhel7" and $iface_type == "bond")
echo "TYPE=Ethernet" >> $devfile
            #end unless
        #end if
```
Ref: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Network_Bonding_Using_the_Command_Line_Interface.html#sec-Create_a_Channel_Bonding_Interface

**Comment by jmaas** [comment]
Patch merged, closing

**Comment by acjohnson** [comment]
Thank you for fixing this!
