### ISSUE TITLE
Possible to get "/dev/disk/by-path" for making Raid 10 pre-seed?

### ISSUE THREAD

**Issue by jenlp** [cobbler/cobbler#1395]
Hi.
It doesn't seem possible to grok what the disk order is across multiple raid controllers, being presented as JBOD.  Is it possible to have cobbler using some logic to "list" "/dev/disk/by-path" during the install and have a RAID 10 array built with interleaving from the results that it sees?  

Example:
mdadm -C data -l 10 -n 16 --name="data" --layout=n2 --chunk=256K /dev/sdc1 /dev/sdl1 /dev/sdd1 /dev/sdm1 /dev/sde1 /dev/sdn1 /dev/sdf1 /dev/sdk1 /dev/sdg1 /dev/sdo1 /dev/sdh1 /dev/sdp1 /dev/sdi1 /dev/sdq1 /dev/sdj1 /dev/sdr1 (interleaving across 2 controllers with 16 drives for RAID 10)

Can cobbler grok/drop down somehow to figure this out, and then present it to the pre-seed file?  If it can't, can we get this functionality put it?

Thanks.

**Comment by alanoe** [comment]
On 01/29/2015 04:44 PM, Jen P wrote:
>
> It doesn't seem possible to grok what the disk order is across 
> multiple raid controllers, being presented as JBOD. Is it possible to 
> have cobbler using some logic to "list" "/dev/disk/by-path" during the 
> install and have a RAID 10 array built with interleaving from the 
> results that it sees?
>

If the distro installer supports RAID setup, Cobbler should support it. 
If you need
to run a Linux shell command before installation so you are able to 
generate the
corresponding automated installation file (kickstart/autoyast/preseed)'s 
directive,
you probably can  do it at the pre installation code block. You may save the
generated directive in a file during the pre-installation block and 
include it in the
installation file body. Cobbler does something similar with network 
configuration
in the sample kickstart file.


Regards,
Alan Evangelista
