### ISSUE TITLE
cobbler check outputs incorrect warnings in CentOS 7

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1396]
Errors found:

2 : Unknown distribution type, cannot check for running service cobblerd
(...)
4 : Apache (httpd) is not installed and/or in path
5 : debmirror package is not installed, it will be required to manage
debian deployments and repositories

imho 5 is valid, as debmirror is not available in CentOS7 repositories. However, 2 and 4 are wrong (Apache web server is installed in default path)

**Comment by jmaas** [comment]
Works for me in master.
Problem does exist in 2.6. Simple patch coming up.

**Comment by giumbai** [comment]
.. i still  have the same issue, how can it be closed?

**Comment by opoplawski** [comment]
Because it is fixed in 2.6.8.  You can get 2.6.9 from epel-testing:

yum --enablerepo=epel-testing upgrade

Test and leave feedback here: https://admin.fedoraproject.org/updates/FEDORA-EPEL-2015-6209/cobbler-2.6.9-1.el7
