### ISSUE TITLE
koan incompatible with virt-install in Fedora 21

### ISSUE THREAD

**Issue by sdherr** [cobbler/cobbler#1398]
virt-install in Fedora 21 has been re-architected to use the osinfo system to provide known variants instead of maintaining the list itself. This unfortunately means it is incompatible with current koan. Attempting to install a virtual guest on a Fedora 21 host will fail with error:

ERROR    Error validating install location: Distro 'generic26' does not exist in our dictionary

This is because:
1) virt-install no longer recognizes the generic26 variant
2) some of the varients that virt-install does recognize have changed format, eg from 'rhel6' to 'rhel6.0'. If installing a kickstart that contains one of the 'old' variants, koan sees it's not recognized anymore and defaults to generic26, which is also not recognized.

A pull request that fixes this issue will be incoming shortly.

**Comment by jmaas** [comment]
Merged, closing
