### ISSUE TITLE
Redhat rescue mode via cobbler

### ISSUE THREAD

**Issue by tdlee** [cobbler/cobbler#14]
Imagine a Redhat box installed with cobbler.  Sometime later, imagine it in trouble and needing "rescue mode" to diagnose it.  It would be very useful to be able to do something like: "cobbler system edit --name=poorly --rescue-mode=true".  (Or perhaps "... --netboot-enabled=rescue-mode".)

Having this available as a simple flag would be very useful;  the user shouldn't be required to set up all sorts of profiles.  (If the implementation requires different internal profile functionality, this ought to be transparent to the typical user.)

See email thread 'redhat "rescue mode"?', started 2011/12/06.

**Comment by brianjmurrell** [comment]
@stiqs: It should be close if not exact.  The RHEL6 rescue mode for example will (optionally?) try to mount your on-disk filesystem(s) and use tools from them.

But yeah, profiles are perfectly reasonable here.

I guess what might be nice is provided, canned profiles for known distributions that automatically get added when you import a distro.
