### ISSUE TITLE
Cobbler .deb packages flatten existing config

### ISSUE THREAD

**Issue by Zetten** [cobbler/cobbler#1401]
It seems that upgrading Cobbler via the .deb package causes existing config to be overwritten with the package versions where the files exist. This is... inconvenient. I'm not sure if the same happens with .rpm packages but the rest of my environment is Debian-based so I haven't had a chance to investigate yet.

I guess the best approach would be to allow dpkg to handle certain directories of configuration (https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html). It seems pretty straightforward: create a `conffiles` file in the `debian/` directory with a list of files which should be treated specially in the case where local modifications have been made.

**Comment by jmaas** [comment]
Yes, this is very inconvenient to say to least :(
Can you confirm you are using the packages provided by the cobbler project?
Thanks for the report.

Groeten,
Jörgen

**Comment by Zetten** [comment]
Yep, this is with the official packages.

In order to get newer Cobbler versions than available in the official distro repos I was hacking together my own .debs for a little while before they came along, so they're much appreciated! For this to happen the first time I tried upgrading was a bit of a surprise.

I'm not sure how the downstream distro packages handle configuration overlays (it doesn't seem as simple as the 'conffiles' approach, but perhaps they could be used as reference.

Debian (possibly): http://anonscm.debian.org/cgit/collab-maint/cobbler.git/tree/debian
Ubuntu: http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/cobbler/trusty/files/head:/debian/

I'll take a glance over it myself and see if I can figure it out, but a more experienced .deb maintainer would probably be far more efficient.

**Comment by jmaas** [comment]
Would be awesoms if you could contribute in this way :).There are some more
open issues wrt packaging on non rpm based systems, i need to spend some
time in debian & ubuntu again.

On Thu, Feb 5, 2015 at 12:54 PM, Peter van Zetten <notifications@github.com>
wrote:

> Yep, this is with the official packages.
>
> In order to get newer Cobbler versions than available in the official
> distro repos I was hacking together my own .debs for a little while before
> they came along, so they're much appreciated! For this to happen the first
> time I tried upgrading was a bit of a surprise.
>
> I'm not sure how the downstream distro packages handle configuration
> overlays (it doesn't seem as simple as the 'conffiles' approach, but
> perhaps they could be used as reference.
>
> Debian (possibly):
> http://anonscm.debian.org/cgit/collab-maint/cobbler.git/tree/debian
> Ubuntu:
> http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/cobbler/trusty/files/head:/debian/
>
> I'll take a glance over it myself and see if I can figure it out, but a
> more experienced .deb maintainer would probably be far more efficient.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1401#issuecomment-73034844>.
>



-- 
Grtz,
Jörgen Maas

**Comment by sylphid8** [comment]
Looks like debian is starting to package upstream. I would like to propose that packaging itself should be left to upstream.

**Comment by jmaas** [comment]
You mean, leave packaging to downstream?

**Comment by sylphid8** [comment]
yes, words.... i should learn to use them correctly sometime.

**Comment by jmaas** [comment]
Yes, i'm considering dropping packaging from the official repo. Only
focussing on proper python/pip installations.
I will keep packaging myself (downstream) though... but will have to mark
those packages as unofficial on cobblerd.org.

@alanoe @opoplawski what do you think?

On Sat, Apr 18, 2015 at 3:39 PM, Scott Coil <notifications@github.com>
wrote:

> yes, words.... i should learn to use them correctly sometime.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1401#issuecomment-94165464>.
>



-- 
Grtz,
Jörgen Maas

**Comment by Zetten** [comment]
I never did get a chance to look at this, sorry about that :(

The main issue I see with downstream packaging is that unless the maintainer is on the ball the packages can end up woefully out of date. Already the not-yet-published Debian cobbler package is a point release behind, and Ubuntu is only offering 2.4.1.

But on the other hand I do agree that packages should be largely distro-agnostic at the top level.

So publishing the authoritative releases through pypi/cpan/gem/whatever is probably the best way forward in my view. :+1:

These platforms tend to already have well-defined processes for creating OS packages for most distributions. And something like [fpm](https://github.com/jordansissel/fpm) is a simple option for when a distribution doesn't publish or doesn't update.

**Comment by alanoe** [comment]
On 04/12/2015 04:40 PM, Scott Coil wrote:
>
> Looks like debian is starting to package upstream. I would like to 
> propose that packaging itself should be left to upstream.
>

I have not understood exactly what you meant with "debian is starting to 
package upstream" and how it affects us.
Debian only creates .deb packages for the software included in Debian 
distributions and afaik Cobbler package is
not included in Debian. What has changed? You mean Debian is now 
offering a build infrastructure so that developers
can build .deb packages? If this is it, this does not change the fact 
that someone must create the .deb control files,
so the argument does not influence the packaging upstream discussion.


Regards,
Alan Evangelista

**Comment by alanoe** [comment]
On 04/18/2015 11:06 AM, Jörgen Maas wrote:
> Yes, i'm considering dropping packaging from the official repo. Only
> focussing on proper python/pip installations.
> I will keep packaging myself (downstream) though... but will have to mark
> those packages as unofficial on cobblerd.org.
>
> @alanoe @opoplawski what do you think?

"Dropping packaging from the official repo" == stop being responsible 
for rpm/deb
packages creation or removing rpm spec and deb control files from 
repository?
I am ok with the former to reduce maintenance burden, but I think we 
should keep
the rpm spec and deb control files so people have a centralized point of 
access
and patching of these files.


Regards,
Alan Evangelista

**Comment by sylphid8** [comment]
Debian has a submitted package for cobbler 2.6.6 in sid. They are *not* using using the control files from the git tree. IMHO package maintenance is better left to the distributions where they know their build systems better. It also frees up cobbler maintainers to focus on cobbler code. Time could be better spent in cobbler fixing distro dependent issues (absolute paths and static username anyone?) rather than packaging problems.

**Comment by opoplawski** [comment]
I don't have strong opinions.  Looking at an upstream spec file can give hints as to what upstream is thinking, but we rarely can use it directly.  I think most people prefer to get their debs/rpms from their distributions.

**Comment by alanoe** [comment]
Ah I didnt know Debian was packaging Cobbler.  Thank you for clarifying. Some points relevant to the discussion:

1) Distributions' latest Cobbler versions are usually outdated. For instance, there is no 2.6.7 deb package. 

2) Debian could stop packaging Cobbler at any time.

3) Is Red Hat/Fedora packaging Cobbler too?

SY> Time could be better spent in cobbler fixing distro dependent issues (absolute paths and static username anyone?) rather than packaging problems.

How will I test Cobbler installation in different distributions if I dont have rpm spec and deb control files to install Cobbler in them?

**Comment by jmaas** [comment]
@alanoe testing by developers is easiest using the Makefile (build, install, webtest, etc)

I agree that (reference) packages should be provided, i am just not sure they should be official / endorsed packages. Perhaps it's better to have some trusted Cobbler users provide them.

Having done the packaging for a while now i can say it's very hard to create proper packages for all platforms. Distros tend to have differences in packaging policies, etc. It's also another great burden to test those packages for every release: http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/

**Comment by opoplawski** [comment]
I'm currently packaging cobbler for Fedora and Fedora EPEL.

**Comment by Zetten** [comment]
If the .deb package is expected to continue to be published, the simplest fix to this issue is simply to add a `debian/conffiles` file containing the files which should be handled by dpkg as configuration. If the package is built with debhelper I think this automatically happens([1]) but adding the file manually ought to work as well.

The expected content would simply be one file per line, something like:
```
/etc/cobbler/cobbler.conf
/etc/cobbler/settings
...
```

I'm not sure how much of the content of `/etc/cobbler` is expected to be user-managed (presumably not all of it), or I would add the file myself.

[1]: https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles

**Comment by jmaas** [comment]
Currently we have no resources to provide packages.
Sorry about that.
