### ISSUE TITLE
MAC address isn't being extracted from the system's name

### ISSUE THREAD

**Issue by Glueon** [cobbler/cobbler#1412]
In order to try out new features I have downloaded current version of cobbler from the git repo instead of installing the one currently in a form of RPM (2.6.7).   
You have a documented feature that if a being added system's name is a MAC address - it's going to be automatically extracted and assigned to the netowrk card. This does not seem to work now.    
Have you removed this feature and haven't updated the documentation?

**Comment by jmaas** [comment]
If you are running on master that is probably the case.
For 3.0 the entire documentation will be rewritten.
