### ISSUE TITLE
"production" distro_signatures.json incompatible with current releases

### ISSUE THREAD

**Issue by brianjmurrell** [cobbler/cobbler#1413]
In 4cde33e36a67f43ff5b705f4b82c1087afa9c2d0 the format of the `distro_signatures.json` file was modified and then a new version of that file pushed to http://www.cobblerd.org/signatures/latest.json, I suppose so that `cobbler signature update` would work with code on master.  But who in a production environment can run their infrastructure on a moving target such as master?

So that change of course breaks all production installations using a release of Cobbler prior to Oct. 3, 2014 since they cannot read the new format.  This of course is sub-optimal, if not outright unacceptable.

So, http://www.cobblerd.org/signatures/latest.json needs to be reverted to the old format since that's where old/current existing installations of Cobbler will expect to find that file in that format.

Then master needs to be updated to pull it's new version from a different location.  It could be http://www.cobblerd.org/signatures/latest-v2.json perhaps.  Or you could think to the future a bit and maybe build the version into the path like: http://www.cobblerd.org/v2/signatures/latest.json or http://www.cobblerd.org/signatures/v2/latest.json, etc.

**Comment by jmaas** [comment]
Big error indeed, last commit to the website was reverted. Indeed the code in master must be changed so that we can version the signatures. Thanks for the feedback. Please report any other issues you may have! Thanks

**Comment by bill-mcgonigle** [comment]
Did this revert pull in an old version?  Fedora 21 isn't in latest.json, for instance.

**Comment by a-nldisr** [comment]
http://www.cobblerd.org/signatures/latest.json is missing Fedora 21 (and 22, but 22 is released per today)

**Comment by jmaas** [comment]
This has been fixed, indeed fedora21 (and 20) got lost somewhere.
Support for 22 needs to be added still, need time to test.
Feel free to submit patches though :)

On Wed, May 27, 2015 at 12:57 PM, Rogier Dikkes <notifications@github.com>
wrote:

> http://www.cobblerd.org/signatures/latest.json is missing Fedora 21 (and
> 22, but 22 is released per today)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1413#issuecomment-105868822>.
>



-- 
Grtz,
Jörgen Maas

**Comment by bill-mcgonigle** [comment]
@jmaas : I'm seeing two Fedora 20's in the current live?

**Comment by jmaas** [comment]
Darn, you're right :S
Should be fixed now.
I guess it's time for a vacation ;)
Thanks!

On Fri, May 29, 2015 at 6:20 PM, Bill McGonigle <notifications@github.com>
wrote:

> @jmaas <https://github.com/jmaas> : I'm seeing two Fedora 20's in the
> current live?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1413#issuecomment-106862140>.
>



-- 
Grtz,
Jörgen Maas
