### ISSUE TITLE
Reposync excludes not working

### ISSUE THREAD

**Issue by ghost** [cobbler/cobbler#1414]
I believe 4cba821006adde5afb8d9ff10f90a54ec9a8a4fb was a mistake and needs reverted. Currently the reposync function will not work with excludes. However the excludes will make it to the config.repo file for clients. This was fixed based in #218 originally.

**Comment by khm** [comment]
This worked in the 2.6.x releases until 2.6.7.  Is there going to be a 2.6.x release to fix this?

**Comment by jmaas** [comment]
Fixed, this will be in the next 2.8 bugfix release.
