### ISSUE TITLE
make devinstall not working on Ubuntu 14.04.2 LTS. 1 line error in Makefile

### ISSUE THREAD

**Issue by kb3dow** [cobbler/cobbler#1416]
root@cobbler:~/cobbler# lsb_release -a
    No LSB modules are available.
    Distributor ID:     Ubuntu
    Description:        Ubuntu 14.04.2 LTS
    Release:    14.04
    Codename:   trusty
    -----------------
    root@cobbler:~/cobbler# make devinstall
    ... snip ...
    copying /tmp/cobbler_settings/devinstall/rsync.template to //etc/cobbler/rsync.template
    if [ -n "`getent passwd apache`" ] ; then \
                chown -R apache //var/www/cobbler; \
        elif [ -n "`getent passwd wwwrun`" ] ; then \
                chown -R wwwrun //usr/share/cobbler/web/cobbler_web; \
        elif [-n "`getent passwd www-data`"] ; then \
                chown -R www-data //usr/share/cobbler/web/cobbler_web; \
        fi
    /bin/sh: 5: [-n: not found
    ----------------------
    I fixed 1 line in the Makefile to correct the issue
    root@cobbler:~/cobbler# git diff Makefile
    diff --git a/Makefile b/Makefile
    index c91cf76..02fb940 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -64,7 +64,7 @@ restorestate:
                    chown -R apache $(DESTDIR)/var/www/cobbler; \
            elif [ -n "`getent passwd wwwrun`" ] ; then \
                    chown -R wwwrun $(DESTDIR)/usr/share/cobbler/web/cobbler_web; \
    -       elif [-n "`getent passwd www-data`"] ; then \
    +       elif [ -n "`getent passwd www-data`" ] ; then \
                    chown -R www-data $(DESTDIR)/usr/share/cobbler/web/cobbler_web; \
            fi
            if [ -d $(DESTDIR)/var/www/cobbler ] ; then \
    ----------------

    That made it work.
~

**Comment by jmaas** [comment]
Fixed in release26 and master branches.
