### ISSUE TITLE
make webtest not working on Ubuntu 14.04.2 LTS. Makefile error

### ISSUE THREAD

**Issue by kb3dow** [cobbler/cobbler#1417]
root@cobbler:~/cobbler# lsb_release -a
    No LSB modules are available.
    Distributor ID:     Ubuntu
    Description:        Ubuntu 14.04.2 LTS
    Release:    14.04
    Codename:   trusty

    root@cobbler:~/cobbler# make webtest
    ... snip snip ...
    make[1]: Leaving directory `/root/cobbler'
    make restartservices
    make[1]: Entering directory `/root/cobbler'
    if [ -x /sbin/service ] ; then \
                # Red Hat-based or Suse-based
    /bin/sh: 2: Syntax error: end of file unexpected
    make[1]: *** [restartservices] Error 2
    make[1]: Leaving directory `/root/cobbler'
    make: *** [webtest] Error 2

    After fixing the Makefile

    root@cobbler:~/cobbler# git diff
    diff --git a/Makefile b/Makefile
    index c91cf76..05f1143 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -88,16 +88,13 @@ webtest: devinstall
     # Check if we are on Red Hat, Suse or Debian based distribution
     restartservices:
            if [ -x /sbin/service ] ; then \
    -               # Red Hat-based or Suse-based
                    /sbin/service cobblerd restart; \
                if [ -f /etc/init.d/httpd ] ; then \
    -                       # Red Hat-based
                            /sbin/service httpd restart; \
                    else \
    -                       # Suse-based
                            /sbin/service apache2 restart; \
    +                fi \
            else \
    -               # Debian / Ubuntu
                    /usr/sbin/service cobblerd restart; \
                    /usr/sbin/service apache2 restart; \
            fi
-----------------
That fixed it.

**Comment by jmaas** [comment]
Fix applied to release26.
