### ISSUE TITLE
cobbler 2.6.7 fails to import CentOS 7 DVD

### ISSUE THREAD

**Issue by scbunn** [cobbler/cobbler#1426]
I tried importing the CentOS 7 DVD on a fresh cobbler 2.6.7 install and it fails.  This cobbler instance is running on the latest CentOS7 release

```
[root@cobber /]# cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core)

[root@cobbler /]# cobbler --version
Cobbler 2.6.7
  source: ?, ?
  build time: Wed Dec 31 17:01:16 2014
```

```
[root@cobbler /]# cobbler import --path=/mnt --name=centos7
task started: 2015-03-16_164407_import
task started (id=Media import, time=Mon Mar 16 16:44:07 2015)
Found a candidate signature: breed=redhat, version=rhel6
Found a candidate signature: breed=redhat, version=rhel7
Found a matching signature: breed=redhat, version=rhel7
Adding distros from path /var/www/cobbler/ks_mirror/centos7:
creating new distro: centos7-x86_64
trying symlink: /var/www/cobbler/ks_mirror/centos7 -> /var/www/cobbler/links/centos7-x86_64
creating new profile: centos7-x86_64
Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'kickstart not found: None'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 87, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 231, in runner
    self.logger
   File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 938, in import_tree
    return import_module.run(path,mirror_name,network_root,kickstart_file,arch,breed,os_version)
   File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_import_signatures.py", line 140, in run
    os.path.walk(self.path, self.distro_adder, distros_added)
   File "/usr/lib64/python2.7/posixpath.py", line 246, in walk
    walk(name, func, arg)
   File "/usr/lib64/python2.7/posixpath.py", line 246, in walk
    walk(name, func, arg)
   File "/usr/lib64/python2.7/posixpath.py", line 238, in walk
    func(arg, top, names)
   File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_import_signatures.py", line 255, in distro_adder
    adtls.append(self.add_entry(dirname,kernel,initrd))
   File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_import_signatures.py", line 349, in add_entry
    profile.set_kickstart(self.kickstart_file)
   File "/usr/lib/python2.7/site-packages/cobbler/item_profile.py", line 211, in set_kickstart
    raise CX(_("kickstart not found: %s") % kickstart)

!!! TASK FAILED !!!
[root@cobber /]#
```

**Comment by alanoe** [comment]
On 03/16/2015 08:49 PM, Stephen Bunn wrote:
>
> I tried importing the CentOS 7 DVD on a fresh cobbler 2.6.7 install 
> and it fails. This cobbler instance is running on the latest CentOS7 
> release
>
> |[root@cobber /]# cat /etc/redhat-release
> CentOS Linux release 7.0.1406 (Core)
>
> [root@cobbler /]# cobbler --version
> Cobbler 2.6.7
>    source: ?, ?
>    build time: Wed Dec 31 17:01:16 2014
> |
> |[root@cobbler /]# cobbler import --path=/mnt --name=centos7
> task started: 2015-03-16_164407_import
> task started (id=Media import, time=Mon Mar 16 16:44:07 2015)
> Found a candidate signature: breed=redhat, version=rhel6
> Found a candidate signature: breed=redhat, version=rhel7
> Found a matching signature: breed=redhat, version=rhel7
> Adding distros from path /var/www/cobbler/ks_mirror/centos7:
> creating new distro: centos7-x86_64
> trying symlink: /var/www/cobbler/ks_mirror/centos7 -> /var/www/cobbler/links/centos7-x86_64
> creating new profile: centos7-x86_64
> Exception occured: <class 'cobbler.cexceptions.CX'>
> Exception value: 'kickstart not found: None'
> Exception Info:
>    File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 87, in run
>      rc = self._run(self)
>     File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 231, in runner
>      self.logger
>     File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 938, in import_tree
>      return import_module.run(path,mirror_name,network_root,kickstart_file,arch,breed,os_version)
>     File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_import_signatures.py", line 140, in run
>      os.path.walk(self.path, self.distro_adder, distros_added)
>     File "/usr/lib64/python2.7/posixpath.py", line 246, in walk
>      walk(name, func, arg)
>     File "/usr/lib64/python2.7/posixpath.py", line 246, in walk
>      walk(name, func, arg)
>     File "/usr/lib64/python2.7/posixpath.py", line 238, in walk
>      func(arg, top, names)
>     File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_import_signatures.py", line 255, in distro_adder
>      adtls.append(self.add_entry(dirname,kernel,initrd))
>     File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_import_signatures.py", line 349, in add_entry
>      profile.set_kickstart(self.kickstart_file)
>     File "/usr/lib/python2.7/site-packages/cobbler/item_profile.py", line 211, in set_kickstart
>      raise CX(_("kickstart not found: %s") % kickstart)
>
> !!! TASK FAILED !!!|

Are you using Cobbler's default distro_signatures.json or you have 
changed it? Could you confirm
if the value of default_kickstart attribute in rhel7 OS in rhel breed is
"/var/lib/cobbler/kickstarts/sample_end.ks" in 
/etc/config/distro_signatures.json?


Regards,
Alan Evangelista

**Comment by scbunn** [comment]
Thanks @alanoe 

I actually solved this late last night by doing a complete reinstall, but since you mentioned the distro_signatures.json its clear what happened.  I was under the assumption that default.ks was the default "default." and had removed sample_end.ks.

**Comment by alanoe** [comment]
This is indeed confusing. We could improve those kickstart files names to make this more intuitive.
