### ISSUE TITLE
RFE: Be able to use dnf instead of yum

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#1427]
https://bugzilla.redhat.com/show_bug.cgi?id=1156552

Fedora 22 is planning to switch over to dnf from yum as per

https://fedoraproject.org/wiki/Changes/ReplaceYumWithDNF

It would be good if we could configure cobbler to use dnf instead of yum.

**Comment by jmaas** [comment]
i agree. but first i want to see a "platform or runtime abstraction layer". so we have one place to add new runtime/distro support into. stuff is now scattered throughout cobbler codebase and is causing many bugs/regressions.

**Comment by alanoe** [comment]
Agreed, Jorgen. imho Cobbler requires some refactoring before *any* new features are added to it, mainly to make it distro-agnostic and move some features (eg config management) out of core and into plugins. I recommend we do not work on this RFE now.

btw I know I commited to work on these improvements, I'll comeback to Cobbler development in the end of this month.

**Comment by jmaas** [comment]
dnf support already merged into the tree, using the old methods.
i'm closing this issue, there's another issue for the abstraction layer.
also fixes to cobbler check are about to be committed which improve the dnf case a bit.
