### ISSUE TITLE
createrepo version comparison is broken

### ISSUE THREAD

**Issue by robinbowes** [cobbler/cobbler#1453]
This breaks on Fedora as createrepo is up to 0.10.3 and 0.10.3 < 0.9.7:
```
                        if createrepo_ver >= "0.9.7":
                            mdoptions.append("--deltas")
                        else:
                            self.logger.error("this repo has presto metadata; you must upgrade createrepo to >= 0.9.7 first and then need to resync the repo through cobbler.")
```
It should use a version comparison.

**Comment by jmaas** [comment]
note to self: http://stackoverflow.com/questions/11887762/how-to-compare-version-style-strings

**Comment by robinbowes** [comment]
Yeah, that looks legit.

I'd have sent you a PR but I'm not all that fluent in pytohn.

**Comment by jmaas** [comment]
Fix in master, release28 and release26
