### ISSUE TITLE
cobbler 2.6.3 - centos 6.6 - No signature matched

### ISSUE THREAD

**Issue by sgundluri** [cobbler/cobbler#1456]
Hi 

I copied CentOS-6.6-x86_64-bin-DVD1.iso under /mnt directory and executed following command. It is failing with "No signature matched" error. I updated distro signatures and also rebooted server, but no luck.

Any idea?

cobbler import --path=/mnt --name=CentOS-6.6-x86_64 --arch=x86_64
task started: 2015-04-27_222314_import
task started (id=Media import, time=Mon Apr 27 22:23:14 2015)
No signature matched in /var/www/cobbler/ks_mirror/CentOS-6.6-x86_64
!!! TASK FAILED !!!

**Comment by jmaas** [comment]
you need to mount the ISO manually; mount -o loop /path/to/iso /destination
