### ISSUE TITLE
Add Cobbler 2.6.8 to EPEL repository

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1469]
I do not know the process and I am not sure about who usually does it (Orion?), but having only Cobbler 2.6.7 in EPEL repository is confusing to users

**Comment by opoplawski** [comment]
Updates have been filed:

https://admin.fedoraproject.org/updates/FEDORA-EPEL-2015-6209/cobbler-2.6.8-1.el7
https://admin.fedoraproject.org/updates/FEDORA-EPEL-2015-6207/cobbler-2.6.8-1.el6

users will need to enable epel-testing to install.   Testers should give feedback as well.

**Comment by jmaas** [comment]
Thanks Orion!

On Tue, May 12, 2015 at 10:26 PM, Orion Poplawski <notifications@github.com>
wrote:

> Closed #1469 <https://github.com/cobbler/cobbler/issues/1469>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1469#event-303208299>.
>



-- 
Grtz,
Jörgen Maas
