### ISSUE TITLE
Cobbler generated CentOS/RHEL ISOs hangs at isolinux boot menu...

### ISSUE THREAD

**Issue by acjohnson** [cobbler/cobbler#1473]
Hello cobbler devs, I am looking for someone familiar with the cobbler iso builder code in action_buildiso.py in cobbler v2.6.x

We would like to make cobbler build an iso that auto boots for a single system to tie in with our build automation.

However cobbler appears to want to generate an iso for multiple systems by default and it seems impossible to get it to create an iso that will auto boot at the isolinux menu for a single system.

Currently our work around is the modify the code in action_buildiso.py on lines 204-205:

From:
```python
cfg.write("LABEL %s\n" % system.name)
cfg.write("  MENU LABEL %s\n" % system.name)
```
To:
```python
cfg.write("LABEL linux\n")
cfg.write("  MENU LABEL linux\n")
```

Then we change the ONTIMEOUT line in /etc/cobbler/iso/buildiso.template:

From:
```shell
ONTIMEOUT local
```
To:

```shell
ONTIMEOUT linux
```

Are we missing something obvious or is there no native way to do this in cobbler currently?

**Comment by alanoe** [comment]
On 05/13/2015 06:45 PM, acjohnson wrote:
>
> I am looking for someone familiar with the cobbler iso builder code in 
> action_buildiso.py in cobbler v2.6.x
>
> We would like to make cobbler build an iso that auto boots for a 
> single system to tie in with our build automation.
>
> However cobbler appears to want to generate an iso for multiple 
> systems by default and it seems impossible to get it to create an iso 
> that will auto boot at the isolinux menu for a single system.
>
> Currently our work around is the modify the code in action_buildiso.py 
> on lines 204-205:
>
> From:
>
> cfg.write("LABEL%s\n"  %  system.name)
> cfg.write("   MENU LABEL%s\n"  %  system.name)
>
> To:
>
> cfg.write("LABEL linux\n")
> cfg.write("   MENU LABEL linux\n")

profiles and systems can be seen as specializations of a distro 
installation. afaik the idea in the ISO builder is
to put all distro installations variations available in a Cobbler server 
in the ISO. For instance, each boot loader option
created from a system contain a kickstart/autoyast/preseed URL in the 
kernel command line which is
specific to that system.

I do not know how isolinux boot loader handles several entries with same 
label, it wont simply show identical entries
in the boot loader menu? How this helps you in auto booting into the 
desired boot loader option?

cobbler buildiso --systems <mysystem> in Cobbler CLI does not do what 
you want?


Regards,
Alan Evangelista

**Comment by acjohnson** [comment]
Another person on my team was able to get this working by adding the following line to /etc/cobbler/iso/buildiso.template:
```shell
MENU HIDE
```

Our working buildiso.template file is as follows:
```shell
DEFAULT menu.c32
PROMPT 0
#Enables autoboot:
MENU HIDE
MENU TITLE Cobbler | http://www.cobblerd.org/
TIMEOUT 200
TOTALTIMEOUT 6000
```

Then we just run the cobbler buildiso command as Alan suggested which is exactly how we were building the ISO originally.

With the `MENU HIDE` line isolinux is now able to boot the only entry in the boot menu as intended.
