### ISSUE TITLE
All template files regenerated on fetch (CPU maxed)

### ISSUE THREAD

**Issue by DawgTool** [cobbler/cobbler#1475]
Hi All,

I might be wrong here, but it appears that when cobbler receives a request via the api it regenerated all of the templates for a given system (and all the sub profiles).  I have between 50-100 templates that is regenerated on every fetch. it takes several hours to do a image. This seems crazy to me. Is there something I am missing?

Thanks

**Comment by DawgTool** [comment]
for template in templates.keys():
            dest = templates[template]
            if dest is None:
               continue

            # If we're looking for a single template, skip if this ones
            # destination is not it.
            if not write_file and ( path is None or path != dest ):
               self.logger.debug("skip : %s" % template)
               continue

**Comment by DawgTool** [comment]
Seems to have fixed the problem

**Comment by alanoe** [comment]
Which API request, which template? Cobbler uses templates for several different purposes. From the code block you posted, it seems you are talking about the built-in configuration management templates. Yes, they are all written at once. That could be improved indeed, patches submissions are welcome.

**Comment by SchoolGuy** [comment]
Because of the lack of information and inactivity I will close this issue.
