### ISSUE TITLE
pre_install_network_config will not work when two nic has same mac address

### ISSUE THREAD

**Issue by Firxiao** [cobbler/cobbler#1478]
![thumb_img_0666_1024](https://cloud.githubusercontent.com/assets/2361088/7863310/333133f2-058e-11e5-9c4f-486526d4fe99.jpg)
![thumb_img_0667_1024](https://cloud.githubusercontent.com/assets/2361088/7863312/34dcf75e-058e-11e5-8cd2-69244d9fdf71.jpg)
![thumb_img_0668_1024](https://cloud.githubusercontent.com/assets/2361088/7863454/12e3582c-058f-11e5-83b2-f5c0b5f7cf6d.jpg)

 and I have tried the lasted pre_install_network_config.

**Comment by alanoe** [comment]
1) Two network interfaces should not have the same MAC address

2) You are using an incorrect kickstart syntax. Please take a look at kickstart file documentation before proceeding. This is *not* a Cobbler problem.

Closing issue.

I already asked you to post questions to the Cobbler mailing list and not here. If you insist in requesting support in the issue tracker, I'll close your issues directly.

**Comment by Firxiao** [comment]
Ok I would use mail to post  questions.
