### ISSUE TITLE
Flags/Settings for 'rsync' commands.

### ISSUE THREAD

**Issue by MichaelTiernan** [cobbler/cobbler#1480]
It seems that in the settings, this setting:

```
  # replication rsync options for repos set to override default value of "-avzH"
  replicate_repo_rsync_options: "-avzH"
is ignored and actually set in:
  /usr/lib/python2.6/site-packages/cobbler/action_reposync.py
by:
  # FIXME: wrapper for subprocess that logs to logger
  cmd = "rsync -rltDv --copy-unsafe-links --delete-after
```

I may very well be wrong. My apologies if that's the case. If not this should be documented and/or corrected. At minimum, documented in the settings file until it is addressed.

**Comment by jmaas** [comment]
you are right, should be fixed.
i'll take a look at this one.

**Comment by jmaas** [comment]
well, it seems the settings configuration option is only meant for replication between cobbler instances.
but i don like the hardcoded one for repo mirroring...

**Comment by bowlerct** [comment]
I will submit a pull request for this soon. On my build from branch v3.1.2 I moved those rsync options to settings and also added a field "rsync options" to repo for individual support.  I will need to look more closely at the setting reposync_rsync_flags but I think it was being used for something else.
