### ISSUE TITLE
  Add scripts to cobbler_web like snippets and kickstarts

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1482]
ubuntu/debian seeding. The debian installer does not allow pre and post blocks in the seed file like kickstart, so you need to put all of this in the pre and post seed files, which are kept in the cobbler scripts dir. Can we have a cobbler_web option so we can edit these from the web interface?

Migrated from: cobbler/#1259

**Comment by SchoolGuy** [comment]
The webinterface will be removed with 3.3.0 and thus I will close this issue. A new interface will be created when the Team has time and resources for it.
