### ISSUE TITLE
Cobbler UI resizable window reverts to default size when refreshed

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1484]
When looking at system event logs via the UI (i.e. reposync output) the re-sizable text box that houses the log output is tiny. If you re-size it, and then refresh to get the updated log, the text box reverts back to it's original size.

Copied from cobbler/#688

**Comment by 36below** [comment]
The "offending" file is: /usr/share/cobbler/web/cobbler_web/templates/eventlog.tmpl

If you change:
<textarea rows="40" cols="120" name="eventlog" id="eventlog">
to
<textarea rows="40" cols="120" name="eventlog" id="eventlog" style="width:95%; height:50%">

Then it "sticks" however after upgrading, the change will be lost again.

**Comment by SchoolGuy** [comment]
The webinterface will be removed with 3.3.0 and thus I will close this issue. A new interface will be created when the Team has time and resources for it.
