### ISSUE TITLE
django 1.7 support

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1488]
With django 1.7 when accessing the web interface I get:

AppRegistryNotReady at /

Apps aren't loaded yet.

[Tue May 12 09:06:11.621573 2015] [wsgi:error] [pid 32530] No handlers could be found for logger "django.request"

Looks like one replaces:
replace

import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()

with

from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()

But I'm not sure how to do this in a backwards compatible way, if possible. Changing this certainly breaks cobbler-web on django 1.4

**Comment by jmaas** [comment]
Hi,
I have no knowledge about django and limited knowledge about python but found the solution due to
some google research:

replace in /usr/share/cobbler/web/cobbler.wsgi:
import django.core.handlers.wsgi
_application = django.core.handlers.wsgi.WSGIHandler()

by:
from django.core.wsgi import get_wsgi_application
_application = get_wsgi_application()

**Comment by cybojanek** [comment]
@jmaas your fixed worked for me as well, running Centos 7

**Comment by tritonblaster** [comment]
Fix also django 1.8 support

**Comment by geertn** [comment]
This fix worked for me to enable it to run under django 1.8.7

**Comment by kwizart** [comment]
This change is broken for me on python-django-1.8.8-1.el7.noarch (CentOS 7)
The correct fix seems on the pull request as documented by the django project.

Please report testing
