### ISSUE TITLE
cobbler fails to add repo with 'unkown repo name' error

### ISSUE THREAD

**Issue by jameskyle** [cobbler/cobbler#149]
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:        12.04
Codename:       precise

kernel info: 3.2.0-20-generic #33-Ubuntu SMP Tue Mar 27 16:42:26 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

Command: cobbler repo add --arch=x86_64 --breed=apt --comment="main ubuntu mirror" --keep-updated --mirror=http//mirror.anl.gov --name="precise-x86_64"

Result:

    tail -f /var/log/cobbler/cobbler.log 
    Mon Apr 23 10:38:49 2012 - INFO | find_items; ['repo']
    Mon Apr 23 10:38:49 2012 - INFO | REMOTE version; user(cobbler)
    Mon Apr 23 10:38:58 2012 - DEBUG | get_items; ['repo']
    Mon Apr 23 10:38:58 2012 - DEBUG | done with get_items; ['repo']
    Mon Apr 23 10:39:10 2012 - DEBUG | get_items; ['repo']
    Mon Apr 23 10:39:10 2012 - DEBUG | done with get_items; ['repo']
    Mon Apr 23 10:39:17 2012 - DEBUG | get_items; ['repo']
    Mon Apr 23 10:39:17 2012 - DEBUG | done with get_items; ['repo']
    Mon Apr 23 11:20:02 2012 - DEBUG | get_items; ['repo']
    Mon Apr 23 11:20:02 2012 - DEBUG | done with get_items; ['repo']
    Mon Apr 23 11:20:51 2012 - DEBUG | REMOTE CLI Authorized; user(?)
    Mon Apr 23 11:20:51 2012 - DEBUG | get_item; ['repo', 'ANL_Mirror']
    Mon Apr 23 11:20:51 2012 - DEBUG | done with get_item; ['repo', 'ANL_Mirror']
    Mon Apr 23 11:20:51 2012 - INFO | Exception occured: <class 'cobbler.cexceptions.CX'>                                                                                                                                                                 [298/336]
    Mon Apr 23 11:20:51 2012 - INFO | Exception value: 'internal error, unknown repo name ANL_Mirror'
    Mon Apr 23 11:20:51 2012 - INFO | Exception Info:
      File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 862, in xapi_object_edit
        handle = self.get_item_handle(object_type, object_name)
       File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 655, in get_item_handle
        raise CX("internal error, unknown %s name %s" % (what,name))

**Comment by jmaas** [comment]
On 2.6.7 i get this; btw you need to specify 'yes' to --keep-updated
```
[root@cobbler-stable ~]# cobbler repo add --arch=x86_64 --breed=apt --comment="main ubuntu mirror" --keep-updated=yes --mirror=http//mirror.anl.gov --name="precise-x86_64"
[root@cobbler-stable ~]# cobbler repo list
   precise-x86_64
```

**Comment by jmaas** [comment]
Since this is from 2012 i'm closing this issue. Please contact us if you disagree.
