### ISSUE TITLE
power managment

### ISSUE THREAD

**Issue by alvinstarr** [cobbler/cobbler#1491]
on Centos 6.6 fence-agents does not work the way that action_power.py exepcts.
the following seems to be true for fence_ipmilan 3.1.5

 if rc == 0 or rc == 2:
                # If the desired state is actually a query for the status
                # return different information than command return code
                if desired_state == 'status':
                    match = re.match('(._Chassis._=._)(on|off)._', output, re.IGNORECASE)

**Comment by SchoolGuy** [comment]
Just for future reference I will drop this here: https://github.com/ClusterLabs/fence-agents/blob/master/doc/FenceAgentAPI.md#agent-operations-and-return-values

We need to align this with our code.

**Comment by SchoolGuy** [comment]
Fixed through https://github.com/cobbler/cobbler/pull/2464
