### ISSUE TITLE
create a platform/runtime abstraction layer

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1494]
now all distro specific stuff is hardcoded into the codebase
causing bugs and regressions

we want a single file to edit when adding support for a new os/distro to run cobbler on.

**Comment by alanoe** [comment]
I'm interested in developing this feature, assigning it to me.

**Comment by SchoolGuy** [comment]
I think we can close this because most things are dynamic and those things which aren't, will be eliminated with each release as part of tackling tech-debt. Thus closing this one because of the lack of specific information.
