### ISSUE TITLE
pre_install_network_config broke with 2.6.8 

### ISSUE THREAD

**Issue by requiemsallure** [cobbler/cobbler#1496]
I recently upgraded from 2.6.7 to 2.6.8.  My system is not production, although I do use it for demos.  I like to keep it up to date as much as possible and that is both a blessing and a curse... in any-case. 

Although it doesn't seem that there have been any changes to the snippet itself and as such I do not believe that there is a problem with that in particular.  However the pre_install_network_config snippet has likely been broken by some other change and and so currently doesn't render in cheetah for registered machines.  I do not have any insight as to why and the errors that I have seen are not of any use. 

This affects all RHEL derivatives that I have tried which essentially means Cent6.6, Cent7, Fedora21.  I assume it affects systems other than this providing they use this snippet.  My only unaffected systems are ESXI and Ubuntu.

I isolated it by removing snippets one at a time.  If it is included in the kick-start it breaks the boot sequence when cheetah tries to render the kick-start.  This can be seen by just attempting to view the kick-start within the systems screen.  

Furthermore, this is isolated to already registered systems only, new systems install fine.  This is seen by selecting either your default system from the system screen or any of the kick-starts from your profile screen.  In the end either of those render correctly.  

The error that cheetah outputs is this... 
```
Tue Jun  9 00:30:44 2015 - INFO | generate_kickstart
Tue Jun  9 00:30:44 2015 - ERROR |
# *** ERROR ***
#
# There is a templating error preventing this file from rendering correctly.
#
# This is most likely not due to a bug in Cobbler and is something you can fix.
#
# Look at the message below to see what things are causing problems.
#
# (1) Does the template file reference a $variable that is not defined?
# (2) is there a formatting error in a Cheetah directive?
# (3) Should dollar signs ($) be escaped that are not being escaped?
#
# Try fixing the problem and then investigate to see if this message goes
# away or changes.
#
#
# 'gateway'
#   File "/usr/lib/python2.6/site-packages/cobbler/templar.py", line 208, in render_cheetah
#     data_out = t.respond()
#
#   File "cheetah_DynamicallyCompiledCheetahTemplate_1433777444_59_17242.py", line 262, in respond
#
#   File "cheetah_DynamicallyCompiledCheetahTemplate_1433777444_59_17242.py", line 109, in __errorCatcher7
#
#   File "<string>", line 1, in <module>
#
#   File "/usr/lib/python2.6/site-packages/cobbler/template_api.py", line 170, in SNIPPET
#     result = BuiltinTemplate.SNIPPET(self, file)
#
#   File "DynamicallyCompiledCheetahTemplate.py", line 85, in SNIPPET
#
#   File "/usr/lib64/python2.6/site-packages/Cheetah/Template.py", line 1601, in _handleCheetahInclude
#     self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
#
#   File "cheetah_DynamicallyCompiledCheetahTemplate_1433777441_18_31064.py", line 202, in respond
#

Tue Jun  9 00:30:44 2015 - INFO | Exception occured: <class 'cobbler.cexceptions.CX'>
Tue Jun  9 00:30:44 2015 - INFO | Exception value: 'Error templating file, check cobbler.log for more details'
Tue Jun  9 00:30:44 2015 - INFO | Exception Info:
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1055, in generate_kickstart
    return self.api.generate_kickstart(profile,system)
   File "/usr/lib/python2.6/site-packages/cobbler/api.py", line 694, in generate_kickstart
    return self.kickgen.generate_kickstart_for_system(system)
   File "/usr/lib/python2.6/site-packages/cobbler/kickgen.py", line 257, in generate_kickstart_for_system
    return self.generate_kickstart(profile=p, system=s)
   File "/usr/lib/python2.6/site-packages/cobbler/kickgen.py", line 293, in generate_kickstart
    data = self.templar.render(raw_data, meta, None, obj)
   File "/usr/lib/python2.6/site-packages/cobbler/templar.py", line 116, in render
    data_out = self.render_cheetah(raw_data, search_table, subject)
   File "/usr/lib/python2.6/site-packages/cobbler/templar.py", line 215, in render_cheetah
    raise CX("Error templating file, check cobbler.log for more details")
```

I do not not know where the error comes from originally or how the template system works, so I am stuck at a point where I can't move much further on my own.  

I am grateful for any and all help.

**Comment by jmaas** [comment]
Try: https://github.com/cobbler/cobbler/commit/af8c7ad9e42df41da4521df761a09be7cafe2f4d

**Comment by jmaas** [comment]
Can you provide feedback if the mentioned patch resolved your problems?
If so, i can release 2.6.9 with this fix included making your life a bit easier :)

**Comment by jmaas** [comment]
2.6.9 has been released with the fix for this issue applied.
