### ISSUE TITLE
cobblerd.org down (since yesterday, almost 24 hours now I think)

### ISSUE THREAD

**Issue by jringoot** [cobbler/cobbler#1500]
cobblerd.org  appears down (since yesterday, almost 24 hours now I think), I checked from multiple networks.

I found out when trying to download the loaders:

```
root@saruman:~# cobbler get-loaders
task started: 2015-06-10_103147_get_loaders
task started (id=Download Bootloader Content, time=Wed Jun 10 10:31:47 2015)
path /var/lib/cobbler/loaders/README already exists, not overwriting existing content, use --force if you wish to update
path /var/lib/cobbler/loaders/COPYING.elilo already exists, not overwriting existing content, use --force if you wish to update
path /var/lib/cobbler/loaders/COPYING.yaboot already exists, not overwriting existing content, use --force if you wish to update
downloading http://www.cobblerd.org/loaders/COPYING.syslinux to /var/lib/cobbler/loaders/COPYING.syslinux
Exception occured: <class 'urlgrabber.grabber.URLGrabError'>
Exception value: [Errno 14] PYCURL ERROR 6 - "Could not resolve host: www.cobblerd.org"
Exception Info:
  File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 87, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 181, in runner
    return self.remote.api.dlcontent(self.options.get("force",False), self.logger)
   File "/usr/lib/python2.7/dist-packages/cobbler/api.py", line 739, in dlcontent
    return grabber.run(force)
   File "/usr/lib/python2.7/dist-packages/cobbler/action_dlcontent.py", line 83, in run
    urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 618, in urlgrab
    return default_grabber.urlgrab(url, filename, **kwargs)
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 982, in urlgrab
    return self._retry(opts, retryfunc, url, filename)
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 886, in _retry
    r = apply(func, (opts,) + args, {})
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 968, in retryfunc
    fo = PyCurlFileObject(url, filename, opts)
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1063, in __init__
    self._do_open()
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1355, in _do_open
    self._do_grab()
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1485, in _do_grab
    self._do_perform()
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1342, in _do_perform
    raise err

!!! TASK FAILED !!!
root@saruman:~# 

```

It appears very bad: even DNS requests on cobblerd.org don't respond:
No problem here:
```
~$ dig redhat.com

; <<>> DiG 9.9.5-9-Ubuntu <<>> redhat.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23525
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;redhat.com.			IN	A

;; ANSWER SECTION:
redhat.com.		60	IN	A	209.132.183.105

;; Query time: 9 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Wed Jun 10 10:35:18 CEST 2015
;; MSG SIZE  rcvd: 55

```

but here
___
:~$ dig cobblerd.org

; <<>> DiG 9.9.5-9-Ubuntu <<>> cobblerd.org
;; global options: +cmd
;; connection timed out; no servers could be reached
___

**Comment by jmaas** [comment]
works for me, from .NL

it's nice to know that the current maintainers have no control over domain
name and dns services.


On Wed, Jun 10, 2015 at 10:39 AM, jringoot <notifications@github.com> wrote:

> cobblerd.org appears down (since yesterday, almost 24 hours now I think),
> I checked from multiple networks.
>
> I found out when trying to find download the loaders:
>
> root@saruman:~# cobbler get-loaders
> task started: 2015-06-10_103147_get_loaders
> task started (id=Download Bootloader Content, time=Wed Jun 10 10:31:47 2015)
> path /var/lib/cobbler/loaders/README already exists, not overwriting existing content, use --force if you wish to update
> path /var/lib/cobbler/loaders/COPYING.elilo already exists, not overwriting existing content, use --force if you wish to update
> path /var/lib/cobbler/loaders/COPYING.yaboot already exists, not overwriting existing content, use --force if you wish to update
> downloading http://www.cobblerd.org/loaders/COPYING.syslinux to /var/lib/cobbler/loaders/COPYING.syslinux
> Exception occured: <class 'urlgrabber.grabber.URLGrabError'>
> Exception value: [Errno 14] PYCURL ERROR 6 - "Could not resolve host: www.cobblerd.org"
> Exception Info:
>   File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 87, in run
>     rc = self._run(self)
>    File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 181, in runner
>     return self.remote.api.dlcontent(self.options.get("force",False), self.logger)
>    File "/usr/lib/python2.7/dist-packages/cobbler/api.py", line 739, in dlcontent
>     return grabber.run(force)
>    File "/usr/lib/python2.7/dist-packages/cobbler/action_dlcontent.py", line 83, in run
>     urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)
>    File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 618, in urlgrab
>     return default_grabber.urlgrab(url, filename, **kwargs)
>    File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 982, in urlgrab
>     return self._retry(opts, retryfunc, url, filename)
>    File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 886, in _retry
>     r = apply(func, (opts,) + args, {})
>    File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 968, in retryfunc
>     fo = PyCurlFileObject(url, filename, opts)
>    File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1063, in __init__
>     self._do_open()
>    File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1355, in _do_open
>     self._do_grab()
>    File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1485, in _do_grab
>     self._do_perform()
>    File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1342, in _do_perform
>     raise err
>
> !!! TASK FAILED !!!
> root@saruman:~#
>
>
> It appears very bad: even DNS requests on cobblerd.org don't respond:
> No problem here:
>
> ~$ dig redhat.com
>
> ; <<>> DiG 9.9.5-9-Ubuntu <<>> redhat.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23525
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
>
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 512
> ;; QUESTION SECTION:
> ;redhat.com.            IN  A
>
> ;; ANSWER SECTION:redhat.com.     60  IN  A   209.132.183.105
>
> ;; Query time: 9 msec
> ;; SERVER: 127.0.1.1#53(127.0.1.1)
> ;; WHEN: Wed Jun 10 10:35:18 CEST 2015
> ;; MSG SIZE  rcvd: 55
>
>
> but here
> ------------------------------
>
> :~$ dig cobblerd.org
>
> ; <<>> DiG 9.9.5-9-Ubuntu <<>> cobblerd.org
> ;; global options: +cmd
> ;; connection timed out; no servers could be reached
> ------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1500>.
>



-- 
Grtz,
Jörgen Maas

**Comment by zarya** [comment]
It does not work from .nl vodaphone mobile. and also not from a ziggo/upc connection see the dig +trace

zarya@tankstation:~$ dig +trace www.cobblerd.org

; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> +trace www.cobblerd.org
;; global options: +cmd
.			3600000	IN	NS	M.ROOT-SERVERS.NET.
.			3600000	IN	NS	I.ROOT-SERVERS.NET.
.			3600000	IN	NS	A.ROOT-SERVERS.NET.
.			3600000	IN	NS	H.ROOT-SERVERS.NET.
.			3600000	IN	NS	G.ROOT-SERVERS.NET.
.			3600000	IN	NS	F.ROOT-SERVERS.NET.
.			3600000	IN	NS	E.ROOT-SERVERS.NET.
.			3600000	IN	NS	B.ROOT-SERVERS.NET.
.			3600000	IN	NS	K.ROOT-SERVERS.NET.
.			3600000	IN	NS	L.ROOT-SERVERS.NET.
.			3600000	IN	NS	D.ROOT-SERVERS.NET.
.			3600000	IN	NS	C.ROOT-SERVERS.NET.
.			3600000	IN	NS	J.ROOT-SERVERS.NET.
;; Received 228 bytes from 192.168.1.2#53(192.168.1.2) in 2462 ms

org.			172800	IN	NS	a0.org.afilias-nst.info.
org.			172800	IN	NS	a2.org.afilias-nst.info.
org.			172800	IN	NS	b0.org.afilias-nst.org.
org.			172800	IN	NS	b2.org.afilias-nst.org.
org.			172800	IN	NS	c0.org.afilias-nst.info.
org.			172800	IN	NS	d0.org.afilias-nst.org.
;; Received 436 bytes from 199.7.83.42#53(199.7.83.42) in 245 ms

cobblerd.org.		86400	IN	NS	ns2.sngx.net.
cobblerd.org.		86400	IN	NS	ns1.sngx.net.
dig: couldn't get address for 'ns2.sngx.net': no more

**Comment by jringoot** [comment]
Thank you for your quick reply Jörgen, 

I think though I am not the only one with this issue, I tried a couple other lookups with dig  (and nslookup) and no luck in finding an IP for cobblerd.org (not on whois, 
http://whois.domaintools.com/cobblerd.org)

On
http://ip-lookup.net/domain.php I get this for  cobblerd.org:

```
No IP address found for the domain 'cobblerd.org'
(no DNS answer). 
```

As a workaround for me
Can you tell me which nameserver you use?
Or can you tell me which IP-address you get for cobblerd.org?

Thanks a lot,

Joost

**Comment by alanoe** [comment]
cobblerd.org is not working here either

**Comment by jackhamm** [comment]
It's not loading on an AT&T phone in the SF Bay Area either. 

Typed with my thumbs

**Comment by jmaas** [comment]
Same here now, i've mailed the domain owner and dns maintainer (James).

We could choose to drop the cobblerd.org domain and just use
cobbler.github.com ?


On Wed, Jun 10, 2015 at 8:29 PM, Jack Hamm <notifications@github.com> wrote:

> It's not loading on an AT&T phone in the SF Bay Area either.
>
> Typed with my thumbs
>
> > On Jun 10, 2015, at 11:15 AM, Alan Evangelista <notifications@github.com>
> wrote:
> >
> > cobblerd.org is not working here either
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1500#issuecomment-110864915>.
>



-- 
Grtz,
Jörgen Maas

**Comment by dmick** [comment]
cobblerd.org uses nameservers ns[12].sngx.net. which seem to be the problems.   sgnx.net. is registered at dreamhost.com, nameservers ns[1-4].webfaction.com.   Those nameservers answer NXDOMAIN for ns[12].sgnx.net.  Admin
email is sgnx.net@proxy.dreamhost.com.  I've dropped them a note.

**Comment by lae** [comment]
Manually adding 199.27.75.133 for www.cobblerd.org to your hosts file/local dns server should suffice for the time being, I guess.

**Comment by santosh0705** [comment]
using cobbler.github.com is better option for downloading updated files.

**Comment by jringoot** [comment]
Thanks for the IP lae! 
And thanks to Jörgen and Dmick for proceeding in the full resolution, by contacting the DNS responsibles.
(note to self: check in later to see if DNS issue is fixed and remove/comment host-entry of cobblerd.org from /etc/hosts)
Works for me:

```
root@saruman:~# echo "199.27.75.133     www.cobblerd.org cobblerd.org" >> /etc/hosts
root@saruman:~# cobbler get-loaders
task started: 2015-06-11_080800_get_loaders
task started (id=Download Bootloader Content, time=Thu Jun 11 08:08:00 2015)
path /var/lib/cobbler/loaders/README already exists, not overwriting existing content, use --force if you wish to update
path /var/lib/cobbler/loaders/COPYING.elilo already exists, not overwriting existing content, use --force if you wish to update
path /var/lib/cobbler/loaders/COPYING.yaboot already exists, not overwriting existing content, use --force if you wish to update
path /var/lib/cobbler/loaders/COPYING.syslinux already exists, not overwriting existing content, use --force if you wish to update
downloading http://www.cobblerd.org/loaders/elilo-3.8-ia64.efi to /var/lib/cobbler/loaders/elilo-ia64.efi
downloading http://www.cobblerd.org/loaders/yaboot-1.3.14-12 to /var/lib/cobbler/loaders/yaboot
downloading http://www.cobblerd.org/loaders/pxelinux.0-3.86 to /var/lib/cobbler/loaders/pxelinux.0
downloading http://www.cobblerd.org/loaders/menu.c32-3.86 to /var/lib/cobbler/loaders/menu.c32
downloading http://www.cobblerd.org/loaders/grub-0.97-x86.efi to /var/lib/cobbler/loaders/grub-x86.efi
downloading http://www.cobblerd.org/loaders/grub-0.97-x86_64.efi to /var/lib/cobbler/loaders/grub-x86_64.efi
*** TASK COMPLETE ***
root@saruman:~#
```

**Comment by lae** [comment]
@santosh0705 How are you using cobbler.github.com? As far as I can tell, it redirects to cobblerd.org:
```
lae@soleil:~$ curl cobbler.github.com/loaders -L
curl: (6) Could not resolve host: www.cobblerd.org
```

**Comment by santosh0705** [comment]
@lae this was my opinion to overcome this kind of issues in future. The cobbler.github.com GitHub Pages site is configured for custom domain, check this: https://github.com/cobbler/cobbler.github.com/blob/master/CNAME

It need to be deleted to use cobbler.github.com.

Other option could be creating a new GitHub Pages site for downloading files like cobbler-files.github.com and this will only host all the files which are downloaded on-demand from cobbler.

**Comment by lae** [comment]
Oh, if we're talking about solutions, we could use something like https://bintray.com/ for loaders distribution. Perhaps we should also make it possible to host mirrors and not have a host hardcoded in action_dlcontent.py but instead specified in /etc/cobbler/settings.

**Comment by santosh0705** [comment]
@lae I second you...

**Comment by alanoe** [comment]
@lae Since I started to develop for Cobbler, this is the first time I see problems with cobbled.org, so I dont know if this is enough to justify a change of the primary host from cobblerd.org to somewhere else (eg bintray.com). I agree with the second suggestion of allowing mirrors and not hardcode host in action_dlcontent.py. Could you pls open a separate issue for that?

**Comment by jmaas** [comment]
Still no response from James.

On Thu, Jun 11, 2015 at 3:05 PM, Alan Evangelista <notifications@github.com>
wrote:

> @lae <https://github.com/lae> Since I started to develop for Cobbler,
> this is the first time I see problems with cobbled.org, so I dont know if
> this is enough to justify a change of the primary host from cobblerd.org
> to somewhere else (eg bintray.com). I agree with the second suggestion of
> allowing mirrors and not hardcode host in action_dlcontent.py. Could you
> pls open a separate issue for that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1500#issuecomment-111125631>.
>



-- 
Grtz,
Jörgen Maas

**Comment by jmaas** [comment]
enough is enough. i cant geld a hold of the dns maintainer.
so, i'm going to change dl locations from cobblerd.org to cobbler.github.com

**Comment by jringoot** [comment]
I noticed that the domain registrar is godaddy.com, (on http://whois.domaintools.com/cobblerd.org).
I have also domains registered there, they offer free DNS service with the contract: for the same 7 $/year I can always transfer the DNS-authority of a domain to their DNS servers or choose another one I own or delegate. 
I did that once, they just warned (in the configuration panel) that I should consider 48hrs for the NS-records concerning the authoritative DNS-servers to propagate through the internet(=refresh all DNS-servers DNS-caches)

The owner of the domain may  do that as a temporary or permanent workaround.

**Comment by jmaas** [comment]
unfortunately, the domain owner cant be reached.
and by using private resources, like domains, we are setting up for failure in the future all over again.
we have reverted to using the github nameservers.
also released cobblerr 2.4.9 and 2.6.9 to drop the use of the cobblerd.org domain.
closing this issue.

**Comment by ronabop** [comment]
Unfortunately, for things like existing .deb and .rpm files, this problem is going to persist for quite a while, so to keep the noise down, probably needs resolutions/solutions posted in FAQ's, front pages of the various websites, etc.

**Comment by kjtanaka** [comment]
The version I got with `yum install cobbler` is Cobbler 2.6.3, and `cobbler get-loaders` still fails. 

```
echo "199.27.75.133     www.cobblerd.org cobblerd.org" >> /etc/hosts
cobbler get-loaders --force
task started: 2015-06-24_150844_get_loaders
task started (id=Download Bootloader Content, time=Wed Jun 24 15:08:44 2015)
downloading http://www.cobblerd.org/loaders/README to /var/lib/cobbler/loaders/README
Exception occured: <class 'urlgrabber.grabber.URLGrabError'>
Exception value: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Exception Info:
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 87, in run
    rc = self._run(self)
   File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 181, in runner
    return self.remote.api.dlcontent(self.options.get("force",False), self.logger)
   File "/usr/lib/python2.6/site-packages/cobbler/api.py", line 749, in dlcontent
    return grabber.run(force)
   File "/usr/lib/python2.6/site-packages/cobbler/action_dlcontent.py", line 83, in run
    urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)
   File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 618, in urlgrab
    return default_grabber.urlgrab(url, filename, **kwargs)
   File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 985, in urlgrab
    return self._retry(opts, retryfunc, url, filename)
   File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 886, in _retry
    r = apply(func, (opts,) + args, {})
   File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 971, in retryfunc
    fo = PyCurlFileObject(url, filename, opts)
   File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 1066, in __init__
    self._do_open()
   File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 1360, in _do_open
    self._do_grab()
   File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 1490, in _do_grab
    self._do_perform()
   File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 1347, in _do_perform
    raise err

!!! TASK FAILED !!!
```

Is there a way to make it work?

**Comment by jmaas** [comment]
Yes, update to 2.6.9.
See http://cobbler.github.io/downloads/2.6.x.html

On Wed, Jun 24, 2015 at 9:12 PM, Koji Tanaka <notifications@github.com>
wrote:

> The version I got with yum install cobbler is Cobbler 2.6.3, and cobbler
> get-loaders still fails.
>
> echo "199.27.75.133     www.cobblerd.org cobblerd.org" >> /etc/hosts
> cobbler get-loaders --force
> task started: 2015-06-24_150844_get_loaders
> task started (id=Download Bootloader Content, time=Wed Jun 24 15:08:44 2015)
> downloading http://www.cobblerd.org/loaders/README to /var/lib/cobbler/loaders/README
> Exception occured: <class 'urlgrabber.grabber.URLGrabError'>
> Exception value: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
> Exception Info:
>   File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 87, in run
>     rc = self._run(self)
>    File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 181, in runner
>     return self.remote.api.dlcontent(self.options.get("force",False), self.logger)
>    File "/usr/lib/python2.6/site-packages/cobbler/api.py", line 749, in dlcontent
>     return grabber.run(force)
>    File "/usr/lib/python2.6/site-packages/cobbler/action_dlcontent.py", line 83, in run
>     urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)
>    File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 618, in urlgrab
>     return default_grabber.urlgrab(url, filename, **kwargs)
>    File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 985, in urlgrab
>     return self._retry(opts, retryfunc, url, filename)
>    File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 886, in _retry
>     r = apply(func, (opts,) + args, {})
>    File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 971, in retryfunc
>     fo = PyCurlFileObject(url, filename, opts)
>    File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 1066, in __init__
>     self._do_open()
>    File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 1360, in _do_open
>     self._do_grab()
>    File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 1490, in _do_grab
>     self._do_perform()
>    File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 1347, in _do_perform
>     raise err
>
> !!! TASK FAILED !!!
>
> Is there a way to make it work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1500#issuecomment-114983929>.
>



-- 
Grtz,
Jörgen Maas

**Comment by kjtanaka** [comment]
Thanks. Do you think it's going to be on the yum repository any time soon? Or is a rpm package already available elsewhere?

**Comment by jmaas** [comment]
Orion did submit new packges, they are probably in epel-testing
I'm not familiar with the epel process though...

On Wed, Jun 24, 2015 at 9:47 PM, Koji Tanaka <notifications@github.com>
wrote:

> Thanks. Do you think it's going to be on the yum repository any time soon?
> Or is a rpm package already available elsewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1500#issuecomment-114991294>.
>



-- 
Grtz,
Jörgen Maas

**Comment by opoplawski** [comment]
yum --enablerepo=epel-testing upgrade

Test and leave feedback here: https://admin.fedoraproject.org/updates/FEDORA-EPEL-2015-6207/cobbler-2.6.9-1.el6

**Comment by banmawangqin** [comment]
thx jmaas, I use sudo apt-get autoremove cobbler ,removed cobbler2.4.4 and install 2.6.11, it works well now.

**Comment by m6969p** [comment]
just installed cobbler, ran check, wanting it to get the loaders

cannot resolve www.cobblerd.com

tried name servers (8.8.8.8, my ISP's, my dedicated servers in NJ and TX): same

well, wanted to use cobbler to manage my systems (like sync repos, installed SW, re-install)

here is how I fixed it:

apt-get purge cobbler

**Comment by jmaas** [comment]
too bad ubuntu is shipping an ancient version of cobbler.

**Comment by m6969p** [comment]
too bad the maintainers of cobbler do not enable their software to run
on a modern ubuntu because they don't know debian, and insist on
'bleeding edge full of bugs' latest releases of some dependencies ...

of course, it's always the others, keep playing the finger pointing
game ...

**Comment by jmaas** [comment]
i'm not sure what you're talking about; we provide packages for debian & ubuntu.
if you have a problem with the packages let us know and provide some details...

http://cobbler.github.io/downloads/2.6.x.html

also, cobbler is targeted mainly at rhel; hardly bleeding edge full of bugs...

**Comment by m6969p** [comment]
I have no problem with the package, I fixed it and published my fix to a package that over two years published an inactive URL in an important part (from 2.4 to 2.56.3, fixed in 2.56.9 supposedly).

I fixed it my way because of a request some time ago, in a similar thread, 'to keep the noise down' while nothing was fixed.

So, no problem here.....  just typical open source.....

**Comment by lae** [comment]
If the inactive URL you're referring to is to the one on cobblerd.org, the URL was not inactive for the period of two years in those releases. This issue was opened and resolved shortly after that (I was using it in prod). There are maintenance branches for 2.4 and 2.6 side by side, so.

There's nothing maintainers can do about people who are MIA.

**Comment by m6969p** [comment]
you just can't accept your product has been rejected for bad quality,
you do have to put in personal insults, your answer here has no productive content, it solely serves to again place negative personal attacking items.
get a grip, I won't recommend cobbler to any of my customers to use.
I looked at it over a year ago and it was a reject, again, it is a reject. See you in two years from now.

**Comment by lae** [comment]
nice trolling - p.s. this isn't my product, I stopped using cobbler but you're spamming everyone on this list with notifications
