### ISSUE TITLE
Triggers for background tasks 

### ISSUE THREAD

**Issue by shaishaw** [cobbler/cobbler#1502]
In some specific conditions it is required some triggers to be executed on before and after of a background task execution. e.g we wanted to send a report after the cobbler import task has been completed.

**Comment by santosh0705** [comment]
We achieved this by running a separate process which monitor the background task till it got finished or failed. BTW we have done this in our custom application which use cobbler using XMLRPC.
Its a nice idea to have triggers so we don't have to depend on the external processes.

To admins: could you please mark this as a feature request.

**Comment by jmaas** [comment]
Can you tell us what custom app is using Cobbler ? 
From your point of view, what are the areas that should be improved for using cobbler-as-a-service?

**Comment by santosh0705** [comment]
We are building a customised system provisioning application on the top of Cobbler.

**Comment by SchoolGuy** [comment]
This is possible since https://github.com/cobbler/cobbler/pull/1517 and thus can be closed. If there is a bug with it we need to open a new ticket.
