### ISSUE TITLE
Update Cobbler web site reference in README.md

### ISSUE THREAD

**Issue by ac427** [cobbler/cobbler#1508]
the website link http://www.cobblerd.org/ referenced in  README.md  is broken for many days now
https://github.com/cobbler/cobbler

**Comment by alanoe** [comment]
This was already covered by https://github.com/cobbler/cobbler/issues/1500  , cobblerd.org is no longer the official Cobbler web site. I'll edit issue description to remove cobblerd.org reference from README.md

**Comment by jmaas** [comment]
Done.

On Tue, Jun 16, 2015 at 8:04 PM, Alan Evangelista <notifications@github.com>
wrote:

> This was already covered by #1500
> <https://github.com/cobbler/cobbler/issues/1500> , cobblerd.org is no
> longer the official Cobbler web site. I'll edit issue description to remove
> cobblerd.org reference from README.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1508#issuecomment-112515964>.
>



-- 
Grtz,
Jörgen Maas

**Comment by ac427** [comment]
cool!  Thanks for quick responses and providing updated url

**Comment by jmaas** [comment]
thanks for reporting! please do keep involved :)
