### ISSUE TITLE
Why coobler official website inaccessible

### ISSUE THREAD

**Issue by codeat** [cobbler/cobbler#1509]

**Comment by codeat** [comment]
I executed "cobbler get-loaders" command error.

**Comment by jmaas** [comment]
the domain cobblerd.org is no longer used.

please upgrade to the latest supported version of cobbler (2.6.9 or 2.4.9)


On Fri, Jun 19, 2015 at 11:17 AM, Pc <notifications@github.com> wrote:

> I executed "cobbler get-loaders" command error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1509#issuecomment-113443059>.
>



-- 
Grtz,
Jörgen Maas

**Comment by codeat** [comment]
@jmaas Before I use epel installed centos6,thx.

**Comment by jmaas** [comment]
@opoplawski  can you update cobbler to 2.6.9 in EPEL for epel 6 and 7 please?

the cobblerd.org issue is causing issues for users, would be nice of some of the pain can be resolved downstream.

**Comment by opoplawski** [comment]
New updates have been submitted: https://admin.fedoraproject.org/updates/search/cobbler

**Comment by bill-mcgonigle** [comment]
built and installed the update from koji and 'cobbler signature update' works again for me.  Left karma.

**Comment by jmaas** [comment]
good to hear!
