### ISSUE TITLE
Selecting "<<None>>" as a profile for a system causes an error.

### ISSUE THREAD

**Issue by MichaelTiernan** [cobbler/cobbler#1510]
While working on systems I selected "None" as the profile to assign to a system. It seems reasonable especially since it is an option provided by the UI but when I trigger a 'cobbler sync' I get an error (which IMNSHO) is not handled well.

A trace gives me:

```
generating PXE configuration files
Exception occured: <class 'cexceptions.CX'>
Exception value: 'system xxxxxxxxx references a missing profile '
Exception Info:
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 87, in run
    rc = self._run(self)
   File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 186, in runner
    return self.remote.api.sync(self.options.get("verbose",False),logger=self.logger)
   File "/usr/lib/python2.6/site-packages/cobbler/api.py", line 779, in sync
    return sync.run()
   File "/usr/lib/python2.6/site-packages/cobbler/action_sync.py", line 114, in run
    self.tftpd.sync(self.verbose)
   File "/usr/lib/python2.6/site-packages/cobbler/modules/manage_in_tftpd.py", line 191, in sync
    self.pxegen.write_all_system_files(x, menu_items)
   File "/usr/lib/python2.6/site-packages/cobbler/pxegen.py", line 218, in write_all_system_files
    raise CX("system %(system)s references a missing profile %(profile)s" % { "system" : system.name, "profile" : system.profile})

!!! TASK FAILED !!!
```

So that leaves me with ~~two~~ three comments:
- I would expect that the value of "None" would be valid which will allow a system entry to exist without any specifics other than the hardware itself.
- I would expect that if an invalid profile name snuck into the UI that the underlying structure of the system would handle it more smoothly.
- If the UI offers a choice it shouldn't be invalid.

**Comment by jmaas** [comment]
The None value is not valid to use, a system always need a parent (profile / image).
I tested in 2.8.1 and the ui does not save systems with a None profile.

I guess <<None>> should read like, <please select a value>

Closing this issue.
