### ISSUE TITLE
Setting group definition in users.conf

### ISSUE THREAD

**Issue by jmsurjono** [cobbler/cobbler#1512]
So I'm trying to use the api to create new cobbler records when new servers come up. And i'm authenticating against ldap and use the authz_ownership module for authorization. And i'm trying to set up groups within the users.conf file and doesn't seem to work. I've set it up exactly like the way that was posted on the documentation here. I've tested and seen it work when i place a user directly under the [admins] group to create a new system record but when i try to define another group and place the user there it gives me the error of not being an authenticated user.

Any help would be appreciated. Thanks

users.conf:
````
[admins]
admin = ""
cobbler = ""

[autod]
autod = 
````

Error:
````
Traceback (most recent call last):
  File "create_cobb_record", line 39, in <module>
    main()
  File "create_cobb_record", line 18, in main
    server.modify_system(system_id,"name","apitest",token)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1201, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1492, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1255, in request
    return self._parse_response(h.getfile(), sock)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1395, in _parse_response
    return u.close()
  File "/usr/lib64/python2.6/xmlrpclib.py", line 839, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<class 'cobbler.cexceptions.CX'>:'authorization failure for user autod'">
````

**Comment by pascal-chenevas** [comment]
Hi ! ,

have you tired with a user which has a different name as your group ?

Example :

```
[admins]
admin = ""
cobbler = ""

[autod]
usr_autod = ""
```

**Comment by kflavin** [comment]
I'm experiencing a similar issue.  With "myuser" under "admins" in users.conf, I'm able to login to the Cobbler WebUI against LDAP, and make changes to distros, profiles, etc.

However, if I move "myuser" under "mygroup", I'm no longer able to create new records, or edit existing ones owned by "mygroup".  My users.conf looks like this:

    [admins]
    admin = ""
    cobbler = ""
    
    [mygroup]
    myuser = ""

In cobbler.log, I see an exception:

    DEBUG | authorize; ['myuser', 'modify_system', <cobbler.item_system.System instance at 0x7faad8101c68>, 'name', 0]
    DEBUG | REMOTE myuser authorization result: 0; user(?)
    INFO | Exception occured: <class 'cobbler.cexceptions.CX'>
    INFO | Exception value: 'authorization failure for user myuser'
    INFO | Exception Info:
      File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 2080, in _dispatch
        return method_handle(*params)
       File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 830, in modify_item
        self.check_access(token, "modify_%s"%what, obj, attribute)
       File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1851, in check_access
        raise CX("authorization failure for user %s" % user)

**Comment by SchoolGuy** [comment]
So since the feature itself is here working I will close this one. The bug Kyle mentioned is separately existing.
