### ISSUE TITLE
Importing RHEL 7.1 issue

### ISSUE THREAD

**Issue by wadudmiah** [cobbler/cobbler#1515]
Hello, I am having an issue importing RHEL 7.1 into Cobbler:

root@ldtdsrstadm DEV # mount -o loop ./rhel-server-7.1-x86_64-dvd.iso /mnt/cdromroot@ldtdsrstadm DEV # ls /mnt/cdrom/
EFI     Packages                    addons      release-notes
EULA    RPM-GPG-KEY-redhat-beta     images      repodata
GPL     RPM-GPG-KEY-redhat-release  isolinux
LiveOS  TRANS.TBL                   media.repo
root@ldtdsrstadm DEV # cobbler import --path=/mnt/cdrom --name=rhel71-x86_64    task started: 2015-07-27_144508_import
task started (id=Media import, time=Mon Jul 27 14:45:08 2015)
Found a candidate signature: breed=redhat, version=rhel6
Found a candidate signature: breed=redhat, version=fedora16
Found a candidate signature: breed=redhat, version=fedora17
Found a candidate signature: breed=redhat, version=fedora18
No signature matched in /local/1/cobbler/ks_mirror/rhel71-x86_64
!!! TASK FAILED !!!

Any help will be greatly appreciated. 

root@ldtdsrstadm DEV # cobbler version
Cobbler 2.6.3
  source: ?, ?
  build time: Fri Jul 18 22:59:43 2014

**Comment by a-nldisr** [comment]
Have you tried signature update?

**Comment by wadudmiah** [comment]
Hi,

I upgraded my version of Cobbler:

root@ldtdsrstadm DEV # cobbler version
Cobbler 2.6.9
  source: ?, ?
  build time: Fri Jun 12 07:42:24 2015

But I am still getting the same error message. What do you mean by "signature update"?

**Comment by wadudmiah** [comment]
Hi again, my host does not have internet connection so I downloaded the latest.json file manually. Is there a way I can tell cobbler to use the file from the local file system?

Thanks in advance,

**Comment by wadudmiah** [comment]
Hi again, sorry go keep posting so many messages. I've managed to update the distro signatures. Thanks for directing me in the right direction!
