### ISSUE TITLE
Cobbler fails to add system because token expiration fails

### ISSUE THREAD

**Issue by bgeihsgt** [cobbler/cobbler#1516]
We have a web service wrapping the Cobbler command line tool and we are seeing intermittent problems where Cobbler will fail to add a system because it throws on expiring tokens.  It appears to be some kind of race condition where the same token is getting expired by multiple parties (I'm not familiar with Cobbler's architecture or how concurrency works in Python, so I'm not even sure if that statement makes sense).

Here are the cobbler logs when we see the failure:

```
Wed Jul 29 12:14:28 2015 - INFO | REMOTE new_item(system); user(<DIRECT>)
Wed Jul 29 12:14:28 2015 - INFO | Exception Info:
 File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 2080, in _dispatch
   return method_handle(*params)
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 892, in xapi_object_edit
   self.check_access(token,"xedit_%s" % object_type, token)
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1843, in check_access
   validated = self.__validate_token(token)
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1787, in __validate_token
   self.__invalidate_expired_tokens()
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1753, in __invalidate_expired_tokens
   del self.token_cache[token]
```

**Comment by bgeihsgt** [comment]
Anyone have any thoughts on this one?  Thanks.

**Comment by krogon-intel** [comment]
It is not only for adding new system. I faced that during `edit --netboot-enabled=true` and it is connected with running it in parallel. It is KeyError exception in python: `INFO | Exception occured: <type 'exceptions.KeyError'>`

**Comment by SchoolGuy** [comment]
So we have a token expiration after the default timeout of 3600s (or 1h). After this you need to re-login to fix this. The default of this may be changed https://cobbler.readthedocs.io/en/latest/cobbler-conf.html#auth-token-expiration

**Comment by SchoolGuy** [comment]
Also you can of course expire that token explicetly via https://cobbler.readthedocs.io/en/latest/code-autodoc/cobbler.html#cobbler.remote.CobblerXMLRPCInterface.logout

**Comment by SchoolGuy** [comment]
I think we can close this since the information provided doesn't give enough context to see what is happening here. Thus closing. If the problem persists, I would kindly ask you to reopen this with more information.
