### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by corpix** [cobbler/cobbler#1519]
I have read some articles about cobbler and I'm very impressed. But, do you have screenshots?

**Comment by a-nldisr** [comment]
The interface currently looks like: 
![image](https://cloud.githubusercontent.com/assets/1867776/9055302/0aae1266-3a8a-11e5-8944-72d98736c9ab.png)
Cobblers power to be is in the command line.

**Comment by jmaas** [comment]
We dont have screenshots available, but it's simple to install cobbler+cobbler-web from eg. EPEL.
