### ISSUE TITLE
Fedora22 DVD will not import cause of missing signature

### ISSUE THREAD

**Issue by platinumdon** [cobbler/cobbler#1523]
After I udated the signature update url in settings I still can not import the Fedora 22 Server DVD. The error is "No signature matched in /var/www/cobbler/ks_mirror/Fedora22" Looks like the signature data has not been updated yet

output of import

[dad@dads ~]$ sudo cobbler import --path=/mnt/Fedora22 --name=Fedora22-Server --arch=x86_64                                                                                  
task started: 2015-08-12_092013_import                                                                                                                                       
task started (id=Media import, time=Wed Aug 12 09:20:13 2015)                                                                                                                
Found a candidate signature: breed=redhat, version=rhel6                                                                                                                     
Found a candidate signature: breed=redhat, version=rhel7                                                                                                                     
Found a candidate signature: breed=redhat, version=fedora21                                                                                                                  
Found a candidate signature: breed=redhat, version=fedora20                                                                                                                  
Found a candidate signature: breed=redhat, version=cloudlinux6                                                                                                               
Found a candidate signature: breed=redhat, version=fedora16                                                                                                                  
Found a candidate signature: breed=redhat, version=fedora17                                                                                                                  
Found a candidate signature: breed=redhat, version=fedora18                                                                                                                  
Found a candidate signature: breed=redhat, version=fedora19                                                                                                                  
No signature matched in /var/www/cobbler/ks_mirror/Fedora22-Server-x86_64

**Comment by samjuvonen** [comment]
Please document how to edit the signatures locally or make it pull from user's own repo. I've tried editing the file in both /var/lib/cobbler/ and /etc/cobbler, but it won't pick up the changes.

**Comment by alanoe** [comment]
@samjuvonen, have you restarted cobbler daemon after editing the signatures file? iirc signatures are loaded from hard disk to RAM on Cobbler startup.

**Comment by samjuvonen** [comment]
Thanks, I got it to work. What is the difference between signatures in /etc/cobbler and /var/...? The update signatures script clobbers the file in /var. I enabled scm and checked it into the git repo so merging changes should work now.

**Comment by opoplawski** [comment]
On 09/23/2015 06:46 PM, Sami Juvonen wrote:
> Thanks, I got it to work. What is the difference between signatures in
> /etc/cobbler and /var/...? The update signatures script clobbers the file in
> /var. I enabled scm and checked it into the git repo so merging changes should
> work now.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1523#issuecomment-142770104>.
> 

At this point I think /etc/cobbler/distro_signature.json is completely unused
and probably should be removed.

-- 
Orion Poplawski
Technical Manager                     303-415-9701 x222
NWRA, Boulder/CoRA Office             FAX: 303-415-9702
3380 Mitchell Lane                       orion@nwra.com
Boulder, CO 80301                   http://www.nwra.com

**Comment by jmaas** [comment]
Support for Fedora22 and 23 has been added, you can use the online update feature to get the signatures.
