### ISSUE TITLE
error: illegal IP address string passed to inet_aton

### ISSUE THREAD

**Issue by saphoooo** [cobbler/cobbler#1528]
cobbler-web-2.6.9-1.el6
cobbler-2.6.9-1.el6
on CentOS release 6.7 (Final)
I get an error when I try to install CentOS 7 with static ip: install failed with error:
error: illegal IP address string passed to inet_aton
I can reproduce the issue in kickstart, when the device is not set:
network --bootproto=static --ip=192.168.1.3 --netmask=255.255.255.0 --hostname=centos7.example.com --gateway=192.168.1.1 --nameserver=192.168.1.2 -> give the same error
network --bootproto=static --device=enp0s3 --ip=192.168.1.3 --netmask=255.255.255.0 --hostname=centos7.example.com --gateway=192.168.1.1 --nameserver=192.168.1.2 -> install the system
So I guess there is some issue with network_config snippet when used with CentOS7+ Fedora 20+

**Comment by opoplawski** [comment]
Looks like https://bugzilla.redhat.com/show_bug.cgi?id=1147181  there's an update image here: https://jkonecny.fedorapeople.org/redhat/rhel7_infiniband3.img

**Comment by saphoooo** [comment]
Looks like but not the same; I haven't an issue with kickstart, but with the network snippet which don't take all arguments to correctly bootstrap the server: in my system config, all is well defined (ip, netmask and so on), but I got the issue; but not manually.

**Comment by jmaas** [comment]
there's too little information to check if this is still relevant. since there are no other/current issues regarding the network snippets i'm closing this issue.

if this problem is still present on 2.8.0 please let me know.
