### ISSUE TITLE
Error in dnsmaq.template

### ISSUE THREAD

**Issue by bengelbj** [cobbler/cobbler#1534]
Hi Cobbler-Team,

We just recognized an error in the dnsmasq.template. The dhcp option 3, used for the next_server, is not the next tftp server, it's the default gateway. Next tftp server is option 66.

Following change is needed in the file cobbler/templates/etc/dnsmasq.template:
- dhcp-option=3,$next_server
- dhcp-option=66,$next_server

The next parts are not tested yet.
It would be great to extend the cobbler/cobbler/modules/manage_dnsmasq.py with:
        metadata = {
            "insert_cobbler_system_definitions": system_definitions.get("default", ""),
            "date": time.asctime(time.gmtime()),
            "cobbler_server": self.settings.server,
            "next_server": self.settings.next_server,
-          "default_gateway": self.settings.default_gateway,
      }
  and file cobbler/config/cobbler/settings with something like that:
  # The default gateway used in dnsmasq.template
  default_gateway: 10.100.100.1
  Then the line with dhcp option 3 can look like these:
- dhcp-option=3,$next_server
- dhcp-option=66,$default_gateway
- dhcp-option=66,$next_server

Kind regards,
Björn

**Comment by jmaas** [comment]
Will verify and fix this before the next release.

**Comment by jmaas** [comment]
Fixed the option number. Thanks!
I guess no-one is using dnsmasq ;)
