### ISSUE TITLE
Importing Debian Testing

### ISSUE THREAD

**Issue by thehunt33r** [cobbler/cobbler#1538]
Hi !

I am trying to import Debian Testing with Cobbler. However it fails due to the missing signatures : 
````
received on stderr: 
No signature matched in /var/www/cobbler/ks_mirror/Debian-Testing-x86_64
!!! TASK FAILED !!!
````

I have tried modifying distro_signatures.json by duplicating the jessie signature with the testing keyword : 
````
"testing": {
    "signatures":["dists"],
    "version_file":"Release",
    "version_file_regex":"Codename: stretch",
    "kernel_arch":"linux-headers-(.*)\\.deb",
    "kernel_arch_regex":null,
    "supported_arches":["i386","amd64"],
    "supported_repo_breeds":["apt"],
    "kernel_file":"vmlinuz(.*)",
    "initrd_file":"initrd(.*)\\.gz",
    "isolinux_ok":false,
    "default_autoinstall":"sample.seed",
    "kernel_options":"",
    "kernel_options_post":"",
    "boot_files":[]
   }
````

After that and issuing a cobbler signature reload, I have an error according to which my json is invalid. However I have checked it and it doesn't seem to have any problem : http://paste.fedoraproject.org/264396/41621594/raw/

Complete log : http://pastebin.com/K2pycyXB

I still get the same issue.

Is there a solution ?

Thanks !

**Comment by pascal-chenevas** [comment]
Hi,

according to your link, you have written the "testing" signature like this : 
```
"testing": {
    "signatures":["dists"],
    "version_file":"Release",
    "version_file_regex":"Codename: stretch",
    "kernel_arch":"linux-headers-(.*)\\.deb",
    "kernel_arch_regex":null,
    "supported_arches":["i386","amd64"],
    "supported_repo_breeds":["apt"],
    "kernel_file":"vmlinuz(.*)",
    "initrd_file":"initrd(.*)\\.gz",
    "isolinux_ok":false,
    "default_autoinstall":"sample.seed",
    "kernel_options":"",
    "kernel_options_post":"",
    "boot_files":[]
   }
  },
```
For the "jessie" signature is defined like this : 
```
"jessie": {
    "signatures":["dists"],
    "version_file":"Release",
    "version_file_regex":"Codename: jessie",
    "kernel_arch":"linux-headers-(.*)\\.deb",
    "kernel_arch_regex":null,
    "supported_arches":["i386","amd64"],
    "supported_repo_breeds":["apt"],
    "kernel_file":"vmlinuz(.*)",
    "initrd_file":"initrd(.*)\\.gz",
    "isolinux_ok":false,
    "default_kickstart":"/var/lib/cobbler/kickstarts/sample.seed",
    "kernel_options":"",
    "kernel_options_post":"",
    "boot_files":[]
   },
```

Is that normal that you have a { more for the "testing" signature as for the Jessie ? : 

This : 

```
  "boot_files":[]
   }
  },
```

instead of : 

```
"boot_files":[]
   },
```

Can you also try to add the following line to the signature ? : 

```
 "default_kickstart":"/var/lib/cobbler/kickstarts/sample.seed", 
```

Kind regards

**Comment by thehunt33r** [comment]
Hi !

Thanks for your answer. However if I'm not mistaken (and after checking with an editor for the brackets pairing), this left-over bracket is the bracket closing the "debian" section of the file.

I will try to include the kickstart line when I get back to work on Monday.

Thanks !

**Comment by jmaas** [comment]
If you have a working signature for Debian testing please post it here, or better yet send a pull request :).

**Comment by jmaas** [comment]
Debian stretch has been added to the signatures. You can update with ``cobbler signature update``
