### ISSUE TITLE
Systemd: Kickstarted systems with non-kernelname space network interface names keep ifcfg-eth* files. 

### ISSUE THREAD

**Issue by a-nldisr** [cobbler/cobbler#1544]
Hi, 

Currently we are running into the following issue: 

OS: Centos 7 - 7.1 - Fedora21 - Fedora22. 
We found out that OS with systemd have issues changing interface names. Changing the kernel names is fundamentally racy (if you rename eth0 to wlan0 and another card with name wlan0 appears in the middle of this, you get trouble). We tried to fix this with setting strict udev rules generated with cobbler, however we kept running into the issue: 

```
error changing net interface name eth1 to eth0: File exists
```

Thus we changed the interface names from eth0 to mgt, eth1 to prod, eth2 to rep0 etc. 

We however found out that after the systems first boot the eth0-4+ files in /etc/sysconfig/network-scripts/ifcfg-eth\* are not deleted. We have resolved this with some scripts to resolve this with a rm -f on the eth interfaces but it aint pretty. 

To break it down: 
We use interfaces not related to eth or wlan or any other kernel related interface names. 
We however have these interfaces after a kickstart. 
This is bad because we get two interfaces with the same mac address. 

Cobbler version 2.6.7

**Comment by Ed-0x1b** [comment]
I think systemd starts with the traditional ethX interfaces, but quickly renames them according to:
https://wiki.freedesktop.org/www/Software/systemd/PredictableNetworkInterfaceNames/
The files in /network-scripts/ continue to exist, but are ignored by a running systemd machine. You might not want to rm them if the interfaces have any config settings there.
Renaming an interface on a systemd machine should be done with a .device unit file, but  I don't know how deployed that part of systemd has progressed nor if Cobbler works with it. Check this out:
https://superuser.com/questions/914646/renaming-network-interface-with-systemd

On a running machine, you should use the  "biosdevname" style naming for bound interfaces, declaring CPU affinity for apps & containers etc. etc. So, rename these to mgt, prod and rep2 - if you want them to be predictable.

Unit files are handy - but again this may be a post Cobbler config or a feature yet to be? duno

**Comment by SchoolGuy** [comment]
Is this one still relevant with current Fedora versions?

**Comment by a-nldisr** [comment]
I moved away from this position with this setup and haven't used Cobbler since. Sorry, cannot tell you.

**Comment by SchoolGuy** [comment]
Then I will close this one. If anyone has this issue please open a new one with a more current environment.
