### ISSUE TITLE
Renaming interfaces through the webinterface leads to double mac entries. 

### ISSUE THREAD

**Issue by a-nldisr** [cobbler/cobbler#1546]
Cobbler version cobbler-2.6.9-7.1.noarch
Host OS: 6.7 Centos
Django: Django14-1.4.21-1.el6.noarch

How to replicate: 
Intermittent issue, however it occurs often.
Create system with 4-10 interfaces, save and cobbler sync. 
Then when its done you decide interface monkey0 needs to become giraffe1. Click rename button and rename to new name. 
Save, go back to the system. 

Now you will have interface monkey0 and interface giraffe1 with both the same mac address. 

Issue does not occur with commandline interactions.

**Comment by SchoolGuy** [comment]
The webinterface will be removed with 3.3.0 and thus I will close this issue. A new interface will be created when the Team has time and resources for it.
