### ISSUE TITLE
FR: Don't make initrd mandatory so arbitrary distros (e.g., memtest86+) more easily imported

### ISSUE THREAD

**Issue by pwhack** [cobbler/cobbler#1551]
Perhaps I'm doing it wrong but I've never understood the requirement for the initrd to be specified in a distro. Certainly it's used in the vast majority of cases and major distributions but some helpful utility distros like memtest86+ do not have initrd images and hackery is needed to prevent Cobbler from trying to enforce the requirement. Perhaps this is something signatures could control?

Thanks for your consideration of this feature request.

**Comment by SchoolGuy** [comment]
Closed via #3077

**Comment by pwhack** [comment]
Vielen Danken, @SchoolGuy!
