### ISSUE TITLE
where is the documentation

### ISSUE THREAD

**Issue by Madko** [cobbler/cobbler#1553]
http://www.cobblerd.org/manuals/ => error 404 github
Is it normal?

**Comment by jmaas** [comment]
the cobblerd.org domain is not in use any longer.
please use http://cobbler.github.io/


On Wed, Oct 7, 2015 at 1:40 PM, Madko <notifications@github.com> wrote:

> http://www.cobblerd.org/manuals/ => error 404 github
> Is it normal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1553>.
>



-- 
Grtz,
Jörgen Maas
