### ISSUE TITLE
cobbler signature update fails to follow 301 redirect.

### ISSUE THREAD

**Issue by eclay11** [cobbler/cobbler#1554]
Hello,  I'm experiencing issues when running "cobbler signature update" on my cobbler server.  It appears that the url http://cobbler.github.com/signatures/latest.json is where it's trying to pull the file from but curl isn't able to get this file without using the -L option.

# curl http://cobbler.github.com/signatures/latest.json
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

# curl -L http://cobbler.github.com/signatures/latest.json
{"breeds":
 {
  "redhat": {
   "rhel4": {
    "signatures":["RedHat/RPMS","CentOS/RPMS"],
    "version_file":"(redhat|sl|centos)-release-4(AS|WS|ES)[\\.-]+(.*)\\.rpm",
    "version_file_regex":null,
    "kernel_arch":"kernel-(.*).rpm",
    "kernel_arch_regex":null,
    "supported_arches":["i386","x86_64","ppc","ppc64"],
    "supported_repo_breeds":["rsync", "rhn", "yum"],
    "kernel_file":"vmlinuz(.*)",

I've attempted to manually create the /etc/cobbler/distro_signatures.json file but haven't found a way to apply it and running cobbler signature update attempts to first download it.  Is there a method to manually update the distro_signatures.json file and have it take affect?

**Comment by jmaas** [comment]
Can you please try changing /usr/lib/python-x.y/site-packages/cobbler/settings.py

cobbler.github.com to cobbler.github.io
restart cobblerd and try again?

**Comment by jmaas** [comment]
If its more convenient you can also checkout the release26 branch

**Comment by eclay11** [comment]
That seemed to work.  I changed the following line.
orig
"signature_url"                       : ["http://www.cobblerd.org/signatures/latest.json","str"],
to
"signature_url"                       : ["http://cobbler.github.io/signatures/latest.json","str"],

Is there an upgrade path from 2.4.6 to 2.6.x?  Will it run on centos 5.11?

Thanks for the help.

**Comment by jmaas** [comment]
Cobbler 2.6 does not run on EL 5,  it requires python 2.6 and iirc EL 5
ships with a python 2.4 version

On Thu, Oct 8, 2015 at 8:36 PM, eclay11 <notifications@github.com> wrote:

> That seemed to work. I changed the following line.
> orig
> "signature_url" : ["http://www.cobblerd.org/signatures/latest.json","str
> "],
> to
> "signature_url" : ["http://cobbler.github.io/signatures/latest.json","str
> "],
>
> Is there an upgrade path from 2.4.6 to 2.6.x? Will it run on centos 5.11?
>
> Thanks for the help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/issues/1554#issuecomment-146647996>.
>



-- 
Grtz,
Jörgen Maas

**Comment by jmaas** [comment]
Also cobbler 2.4.x is not really supported any longer.

The upgrade from 2.4 to 2.6 should be fairly easy, just read the 2.6.x
release notes from bottom up.

On Thu, Oct 8, 2015 at 8:51 PM, Jörgen Maas <jorgen.maas@gmail.com> wrote:

> Cobbler 2.6 does not run on EL 5,  it requires python 2.6 and iirc EL 5
> ships with a python 2.4 version
>
> On Thu, Oct 8, 2015 at 8:36 PM, eclay11 <notifications@github.com> wrote:
>
>> That seemed to work. I changed the following line.
>> orig
>> "signature_url" : ["http://www.cobblerd.org/signatures/latest.json","str
>> "],
>> to
>> "signature_url" : ["http://cobbler.github.io/signatures/latest.json","str
>> "],
>>
>> Is there an upgrade path from 2.4.6 to 2.6.x? Will it run on centos 5.11?
>>
>> Thanks for the help.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cobbler/cobbler/issues/1554#issuecomment-146647996>.
>>
>
>
>
> --
> Grtz,
> Jörgen Maas
>



-- 
Grtz,
Jörgen Maas

**Comment by jmaas** [comment]
Fix committed in release26 branch, will be included in the next release
