### ISSUE TITLE
Setting default tftpboot filename in manage_isc.py breaks EFI PXE booting

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#1558]
manage_isc.py will set interface["filename"] to "/pxelinux.0", which then gets put into each system's dhcpd.conf entry by dhcpd.template:
~~~~~
            #else
        filename "$iface.filename";
            #end if
~~~~~
This breaks the automatic setting of filename to grub/gru-x86_64.efi by the preamble in dhcpd.template.  Commenting out that line allowed it get the grub-x86_64.efi file.

Also, booting would not work with the grub-x86_64.efi image obtained from cobbler get-loaders.  I needed to use /boot/efi/EFI/redhat/grub.efi from grub-0.97-93.el6.x86_64.

**Comment by dmick** [comment]
If 1565 is merged, is this issue resolved?

**Comment by jmaas** [comment]
No, not really. If we want this fix to get to users we need to backport to release28 branch.

**Comment by jmaas** [comment]
Backported to release28, so this fix will be in the next release.
