### ISSUE TITLE
Support Oracle Linux

### ISSUE THREAD

**Issue by woofdunlap** [cobbler/cobbler#1562]
Cobbler check doesn't know about Oracle Linux.  Also, /usr/bin/dnf doesn't exist in Oracle Linux 6, so the reposync check fails.   utils.check_dist() returns "oracle linux server" on Oracle Linux 6

**Comment by jmaas** [comment]
We could easily support that since it's just another rhel clone.

**Comment by johol** [comment]
Attached patch to latest 3.2.1 tar file fixed this issue for me

[cobbler-3.2.1-add-oracle-linux-distro.txt](https://github.com/cobbler/cobbler/files/6110731/cobbler-3.2.1-add-oracle-linux-distro.txt)
