### ISSUE TITLE
cobbler_api: 500 Internal Server Error

### ISSUE THREAD

**Issue by sigmoul** [cobbler/cobbler#1566]
Hi,

I get the following error when trying to invoke the command "cobbler check" :

$>cobbler check
httpd does not appear to be running and proxying cobbler, or SELinux is in the way. Original traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cobbler/cli.py", line 252, in check_setup
    s.ping()
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1243, in request
    headers
ProtocolError: <ProtocolError for 10.5.3.105:443/cobbler_api: 500 Internal Server Error>

It's a fresh install from EPEL repository on a RedHat 6.7 :
 - Python 2.6.6
 - Django 1.4.21
 - Selinux is disabled
 - Both apache and cobblerd are running
 - Python is listening on port 25151 and I can telnet it :
 netstat -nap | grep 25151
 tcp        0      0 127.0.0.1:25151             0.0.0.0:*                   LISTEN      11701/python2

  telnet 127.0.0.1 25151
 Trying 127.0.0.1...
 Connected to 127.0.0.1.
 Escape character is '^]'.
 ^]
 telnet> quit
 Connection closed.

Accessing to the web GUI results in the same error message :

ProtocolError at /
<ProtocolError for 10.5.3.105:443/cobbler_api: 500 Internal Server Error>
Request Method:	GET
Request URL:	https://cobbler.mydomain.com/cobbler_web/
Django Version:	1.4.21
Exception Type:	ProtocolError
Exception Value:	
<ProtocolError for 10.5.3.105:443/cobbler_api: 500 Internal Server Error>
Exception Location:	/usr/lib64/python2.6/xmlrpclib.py in request, line 1243
Python Executable:	/usr/bin/python
Python Version:	2.6.6
Python Path:	
['/usr/share/cobbler/web/cobbler_web',
 '/usr/share/cobbler/web',
 '/usr/lib64/python26.zip',
 '/usr/lib64/python2.6',
 '/usr/lib64/python2.6/plat-linux2',
 '/usr/lib64/python2.6/lib-tk',
 '/usr/lib64/python2.6/lib-old',
 '/usr/lib64/python2.6/lib-dynload',
 '/usr/lib64/python2.6/site-packages',
 '/usr/lib64/python2.6/site-packages/gtk-2.0',
 '/usr/lib/python2.6/site-packages',
 '/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info']
Server time:	Mon, 2 Nov 2015 17:08:15 +0100

Thank you for your help,

Regards.

**Comment by sigmoul** [comment]
I solved the issue,

The following Apache module was missing in my configuration : 

 mod_proxy_http

My bad...

Regards,

**Comment by harishhs** [comment]
Can you please provide the steps you used to install and configure mod_proxy_http?
