### ISSUE TITLE
External proxy URL not being used when fetching repomd.xml

### ISSUE THREAD

**Issue by brianjmurrell** [cobbler/cobbler#1569]
Using cobbler 2.6.9, when doing for example: `cobbler reposync --only local-toolkit_el6-x86_64` for a repo that has a _External proxy URL_ defined, that proxy URL is not being given to `urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)` in `RepoSync.yum_sync()`.  `proxies` at that point is `{'http': ''}`.

I suppose, for whatever reason, `self.settings.proxy_url_ext` does not actually have the repo's _External proxy URL_ value populated into it.

**Comment by spicysomtam** [comment]
We are getting this too after a cobbler upgrade (2.6.3 to 2.6.11). We were using an env variable to set http_proxy and this was working before. Even tried the new proxy setting in the repo. Now we get this:

> setting repo environment: http_proxy=http://proxy1.somewhere.com:8080
received on stderr: 
Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'failed to fetch http://mirror.centos.org/centos/7/extras/x86_64/repodata/repomd.xml'
Exception Info:
  File "/usr/lib/python2.6/site-packages/cobbler/utils.py", line 126, in die
    raise CX(msg)
Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'failed to fetch http://mirror.centos.org/centos/7/extras/x86_64/repodata/repomd.xml'
Exception Info:
  File "/usr/lib/python2.6/site-packages/cobbler/action_reposync.py", line 126, in run
    self.sync(repo)
   File "/usr/lib/python2.6/site-packages/cobbler/action_reposync.py", line 170, in sync
    return self.yum_sync(repo)
   File "/usr/lib/python2.6/site-packages/cobbler/action_reposync.py", line 458, in yum_sync
    utils.die(self.logger, "failed to fetch %s" % src)
   File "/usr/lib/python2.6/site-packages/cobbler/utils.py", line 134, in die
    raise CX(msg)

**Comment by Ed-0x1b** [comment]
try setting your curl config (/etc/curlrc) to use the proxy  - everything
else just ends up delegating to curl, usually without the directions to use
your proxy.

**Comment by spicysomtam** [comment]
Thought I had updated this. Anyhow, here goes again:

I tried the curlrc, but that did not fix the issue. Debugging it shows that the proxy setting on the repo (not an env var) was not being propogated through (proxy_url_ext ?). I think this was mentioned by another poster. In the end I had to modify action_reposync.py and hard code a proxy. Thus a bug that needs fixing?

        # grab repomd.xml and use it to download any metadata we can use
        proxies = {}
        proxies['http'] = self.settings.proxy_url_ext
        proxies={ 'http' : 'http://proxy1.somewhere.com:8080' }
        #self.logger.debug("proxy_url_ext=%s" % self.settings.proxy_url_ext)

        src = repo_mirror + "/repodata/repomd.xml"
        dst = temp_path + "/repomd.xml"
        try:
            urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)
        except:
            utils.die(self.logger, "failed to fetch %s" % src)

**Comment by jmaas** [comment]
Need to verify if this problem is still present in 2.8.0

**Comment by jmaas** [comment]
The fix in master hasn't been backported to 2.8.

**Comment by jmaas** [comment]
Fix should be in 2.8.2.
