### ISSUE TITLE
During RHEL6 pxe EFI installation, the system gets stuck on "Trying to allocate 1005 pages for VMLINUZ error"

### ISSUE THREAD

**Issue by toomer** [cobbler/cobbler#1572]
I assume this is know Cobbler problem. 
When I was using the default cobbler loaders my installation was stuck after kernel is loaded on the below error:
       "Trying to allocate 1005 pages for VMLINUZ error"

After I google this problem I found out that workaround for this will be to add the slash image splash.xpm.gz to grub configuration. That helped indeed, details: https://gist.github.com/cwacek/5910195

I have spend some more time investigating this as when I configured UEFI PXE environment manually I didn't need to do that workaround. 
It turns out that  problems is with the grub-x86_64.efi loader. After I change it with the default from the RHEL6 DVD: EFI/BOOT/BOOTX64.efi the splash image wasn't required. I assume that default cobbler loader grub-x86_64.efi don't have splash image in it. 

Would you please consider updating the default  grub-x86_64.efi ?

**Comment by jmaas** [comment]
Yes, they are seriousely outdated.
I will get to this!

**Comment by slgray** [comment]
Hi @toomer I have the same problem. I use the BOOTX64.efi  from RHEL-6.6 DVD. Still get this error. Can you tell which version DVD you use, thanks.

**Comment by slgray** [comment]
According to the document about “PXE Boot for EFI" from redhat the splash is not included in BOOTX64.efi.

[Configuring PXE Boot for EFI](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/s1-netboot-pxe-config-efi.html)

Here is a sample config file
```
default=0
timeout=1
splashimage=(nd)/splash.xpm.gz
hiddenmenu
title RHEL
        root (nd)
        kernel /rawhide-x86_64/vmlinuz
        initrd /rawhide-x86_64/initrd.img
```

**Comment by zdudic** [comment]
Is this doc helpful ?
http://etcfstab.com/oraclelinux/cobbler_uefi_install.html

**Comment by slgray** [comment]
I think "splash.xpm.gz" is still need. 
Without this file I got a boot menue like this:
![borken menue](http://ww3.sinaimg.cn/large/81f0a352gw1f4i1kxkci7j20l709j0sz.jpg)

And this menue with  "splash.xpm.gz" 
![menue](http://ww1.sinaimg.cn/large/81f0a352gw1f4i1lhg4pgj20ic09qq3u.jpg)

**Comment by jmaas** [comment]
I have updated the cobbler GRUB-legacy loader to 0.97-93 provided with Fedora 17, after F17 they switched to GRUB2. Support for GRUB2 is on my todo list, but requires more work/time. It should be easy to try that loader by using `cobbler get-loaders`

For now i'm testing with the latest GRUB-legacy loader provided with RHEL 6.9-beta. If that works for my use-case (problem) i will update the loaders to that version.

**Comment by jmaas** [comment]
Loaders updated to those found in RHEL 6.9-BETA,
You can update with `cobbler get-loaders`
