### ISSUE TITLE
cobbler: error: option --virt-disk-driver: invalid choice: 'qcow2'

### ISSUE THREAD

**Issue by brianjmurrell** [cobbler/cobbler#1588]
Yet, if I create the system with ```--virt-disk-driver=raw``` and then go into the GUI and change it to ```qcow2```, ```koan``` successfully reads that and successfully create a qcow2 disk based VM.

This is Cobbler 2.6.9.

**Comment by opoplawski** [comment]
Please paste the full command and output.

**Comment by jmaas** [comment]
Cant reproduce on master.
Will re-open when further information is provided
