### ISSUE TITLE
Fedora23 Import

### ISSUE THREAD

**Issue by 0xHM** [cobbler/cobbler#1589]
Any experience ?

>[root@builderf22 Fedora23] $ cobbler signature update
task started: 2015-11-30_083042_sigupdate
task started (id=Updating Signatures, time=Mon Nov 30 08:30:42 2015)
Successfully got file from http://cobbler.github.com/signatures/2.6.x/latest.json
*** TASK COMPLETE ***
[root@builderf22 Fedora23] $ cobbler import --name=fedora23 --arch=x86_64 --path=/mnt
task started: 2015-11-30_083048_import
task started (id=Media import, time=Mon Nov 30 08:30:48 2015)
No signature matched in /var/www/cobbler/ks_mirror/fedora23-x86_64
!!! TASK FAILED !!!

**Comment by opoplawski** [comment]
What media are you trying to import?

**Comment by 0xHM** [comment]
ISO from getfedora.org

**Comment by opoplawski** [comment]
Yeah, which iso *exactly*.  Note that cobbler doesn't work with "Live" images, only traditional install media.

**Comment by tunaman** [comment]
I'm having the same issue, the import fails from the server DVD iso (https://download.fedoraproject.org/pub/fedora/linux/releases/23/Server/x86_64/iso/Fedora-Server-DVD-x86_64-23.iso)

```
cobbler import --path=/mnt --name=Fedora_23-x86_64
task started: 2015-12-17_142014_import
task started (id=Media import, time=Thu Dec 17 14:20:14 2015)
Found a candidate signature: breed=redhat, version=rhel6
Found a candidate signature: breed=redhat, version=rhel7
Found a candidate signature: breed=redhat, version=fedora21
Found a candidate signature: breed=redhat, version=fedora20
Found a candidate signature: breed=redhat, version=fedora22
Found a candidate signature: breed=redhat, version=cloudlinux6
Found a candidate signature: breed=redhat, version=fedora16
Found a candidate signature: breed=redhat, version=fedora17
Found a candidate signature: breed=redhat, version=fedora18
Found a candidate signature: breed=redhat, version=fedora19
No signature matched in /xxx/xxx/xxx/ks_mirror/Fedora_23-x86_64
!!! TASK FAILED !!!
```

**Comment by tunaman** [comment]
after adding fedora23 manually to /var/lib/cobbler/distro_signatures.json it works fine.

**Comment by opoplawski** [comment]
You shouldn't need to add it manually.  "cobbler signature update" should do the trick if needed, though the fedora23 signature is in 2.6.10 so updating to that should also work.
