### ISSUE TITLE
Where is --cobbler?

### ISSUE THREAD

**Issue by Marco208** [cobbler/cobbler#1590]
--clobber

This option allows "add" to overwrite an existing system with the same name, so use it with caution.

cobbler: error: no such option: --cobbler

Where is --cobbler? I installed using EPEL repository and using version 2.6.10

**Comment by scroogie** [comment]
The attribute was called "clobber", not "cobbler", but it was removed in f6604a1d3d68d8b87ec551bbdb5dec00b7febfad.

**Comment by jmaas** [comment]
Correct; and removed only from master which has sadly no documentation  yet.
