### ISSUE TITLE
distro_signatures.json missing sles12sp1

### ISSUE THREAD

**Issue by hddang1** [cobbler/cobbler#1597]
Hi, I am trying to import sles12 sp1 into Cobbler but got the "No signature matched in /var/www/cobbler/ks_mirror/sles12-sp1-gmc3-x86_64" error.   It doesn’t appear that sles12sp1 exist in distro_signatures.json.  Thank you

**Comment by jmaas** [comment]
Committed to code in the 2.8 and master branches.
Online available for Cobbler 2.4, 2.6, 2.8 (not released) and 3.0 (not released)

**Comment by hddang1** [comment]
Great!   Thank you.
