### ISSUE TITLE
TFTP server

### ISSUE THREAD

**Issue by krogon-intel** [cobbler/cobbler#1602]
Hi,
What are the pros/cons of choosing tftp-server or cobbler python daemon (manage_in_tftpd vs. manage_tftpd_py)?. I tried to search for any information in documentation but this section [1] is empty for every release.

[1] http://cobbler.github.io/manuals/2.6.0/3/4/4_-_Managing_TFTP.html

**Comment by jmaas** [comment]
I think the best tested option is using tftp-server.
I have never seen any commits after the initial commits on the python tftpd

The pros of the python version is that cobbler doesnt have to copy kernel/initrd to the tftp root directory.

**Comment by SchoolGuy** [comment]
Our internal tftp server will be faded out as soon as possible because we never had a look. If we will continue to use it, we will split it and then document everyting. Thus this issue here is not relevant anymore.
