### ISSUE TITLE
Install from source documentation

### ISSUE THREAD

**Issue by birish2** [cobbler/cobbler#1604]
I was trying to install the latest master branch from source, but the result was an internal server error. After some searching I came across this:
http://blog.gmane.org/gmane.linux.installation.cobbler.devel/month=20150901
I'm able to access the web page after setting the SEKRET_KEY field at /usr/lib/python2.7/site-packages/cobbler/web/settings.py

Also, I've tried building the rpm's but that resulted in other errors when accessing the web page. 
I did notice server non-documented dependencies required for devel/rpm build. Maybe these should be added to the documentation?
pykickstart 
pyflakes
python-pep8
python-sphinx
rpm-build

**Comment by jmaas** [comment]
Developer Guide has been updated. Thanks for reporting!
