### ISSUE TITLE
can't install cobbler by epel

### ISSUE THREAD

**Issue by ThkerLee** [cobbler/cobbler#1608]
document by http://cobbler.github.io/manuals/2.6.0/2/2/2_-_RHEL_and_CentOS.html

rpm -Uvh http://mirrors.yun-idc.com/epel//7/x86_64/e/epel-release-7-5.noarch.rpm
yum install cobbler
[root@localhost ~]# yum install cobbler >>l.txt
错误：软件包：cobbler-2.6.10-1.el6.noarch (epel)
          需要：python-simplejson
[root@localhost ~]# cat l.txt 
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
 * epel: mirrors.opencas.cn
正在解决依赖关系
--> 正在检查事务
---> 软件包 cobbler.noarch.0.2.6.10-1.el6 将被 安装
--> 正在处理依赖关系 yum-utils，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 tftp-server，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 rsync，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 python-simplejson，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 python-netaddr，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 python-cheetah，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 mod_wsgi，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 httpd，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 genisoimage，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 createrepo，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在处理依赖关系 PyYAML，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
--> 正在检查事务
---> 软件包 PyYAML.x86_64.0.3.10-11.el7 将被 安装
--> 正在处理依赖关系 libyaml-0.so.2()(64bit)，它被软件包 PyYAML-3.10-11.el7.x86_64 需要
---> 软件包 cobbler.noarch.0.2.6.10-1.el6 将被 安装
--> 正在处理依赖关系 python-simplejson，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
---> 软件包 createrepo.noarch.0.0.9.9-23.el7 将被 安装
--> 正在处理依赖关系 python-deltarpm，它被软件包 createrepo-0.9.9-23.el7.noarch 需要
--> 正在处理依赖关系 libxml2-python，它被软件包 createrepo-0.9.9-23.el7.noarch 需要
--> 正在处理依赖关系 deltarpm，它被软件包 createrepo-0.9.9-23.el7.noarch 需要
---> 软件包 genisoimage.x86_64.0.1.1.11-23.el7 将被 安装
--> 正在处理依赖关系 libusal = 1.1.11-23.el7，它被软件包 genisoimage-1.1.11-23.el7.x86_64 需要
--> 正在处理依赖关系 libusal.so.0()(64bit)，它被软件包 genisoimage-1.1.11-23.el7.x86_64 需要
--> 正在处理依赖关系 librols.so.0()(64bit)，它被软件包 genisoimage-1.1.11-23.el7.x86_64 需要
---> 软件包 httpd.x86_64.0.2.4.6-40.el7.centos 将被 安装
--> 正在处理依赖关系 httpd-tools = 2.4.6-40.el7.centos，它被软件包 httpd-2.4.6-40.el7.centos.x86_64 需要
--> 正在处理依赖关系 /etc/mime.types，它被软件包 httpd-2.4.6-40.el7.centos.x86_64 需要
--> 正在处理依赖关系 libaprutil-1.so.0()(64bit)，它被软件包 httpd-2.4.6-40.el7.centos.x86_64 需要
--> 正在处理依赖关系 libapr-1.so.0()(64bit)，它被软件包 httpd-2.4.6-40.el7.centos.x86_64 需要
---> 软件包 mod_wsgi.x86_64.0.3.4-12.el7_0 将被 安装
---> 软件包 python-cheetah.x86_64.0.2.4.4-5.el7.centos 将被 安装
--> 正在处理依赖关系 python-markdown，它被软件包 python-cheetah-2.4.4-5.el7.centos.x86_64 需要
---> 软件包 python-netaddr.noarch.0.0.7.5-7.el7 将被 安装
---> 软件包 rsync.x86_64.0.3.0.9-17.el7 将被 安装
---> 软件包 tftp-server.x86_64.0.5.2-12.el7 将被 安装
---> 软件包 yum-utils.noarch.0.1.1.31-34.el7 将被 安装
--> 正在处理依赖关系 python-kitchen，它被软件包 yum-utils-1.1.31-34.el7.noarch 需要
--> 正在检查事务
---> 软件包 apr.x86_64.0.1.4.8-3.el7 将被 安装
---> 软件包 apr-util.x86_64.0.1.5.2-6.el7 将被 安装
---> 软件包 cobbler.noarch.0.2.6.10-1.el6 将被 安装
--> 正在处理依赖关系 python-simplejson，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
---> 软件包 deltarpm.x86_64.0.3.6-3.el7 将被 安装
---> 软件包 httpd-tools.x86_64.0.2.4.6-40.el7.centos 将被 安装
---> 软件包 libusal.x86_64.0.1.1.11-23.el7 将被 安装
---> 软件包 libxml2-python.x86_64.0.2.9.1-6.el7_2.2 将被 安装
--> 正在处理依赖关系 libxml2 = 2.9.1-6.el7_2.2，它被软件包 libxml2-python-2.9.1-6.el7_2.2.x86_64 需要
---> 软件包 libyaml.x86_64.0.0.1.4-11.el7_0 将被 安装
---> 软件包 mailcap.noarch.0.2.1.41-2.el7 将被 安装
---> 软件包 python-deltarpm.x86_64.0.3.6-3.el7 将被 安装
---> 软件包 python-kitchen.noarch.0.1.1.1-5.el7 将被 安装
--> 正在处理依赖关系 python-chardet，它被软件包 python-kitchen-1.1.1-5.el7.noarch 需要
---> 软件包 python-markdown.noarch.0.2.4.1-1.el7.centos 将被 安装
--> 正在检查事务
---> 软件包 cobbler.noarch.0.2.6.10-1.el6 将被 安装
--> 正在处理依赖关系 python-simplejson，它被软件包 cobbler-2.6.10-1.el6.noarch 需要
---> 软件包 libxml2.x86_64.0.2.9.1-5.el7_1.2 将被 升级
---> 软件包 libxml2.x86_64.0.2.9.1-6.el7_2.2 将被 更新
---> 软件包 python-chardet.noarch.0.2.2.1-1.el7_1 将被 安装
--> 解决依赖关系完成
 您可以尝试添加 --skip-broken 选项来解决该问题
 您可以尝试执行：rpm -Va --nofiles --nodigest

[root@localhost ~]# python
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import simplejson
>>>

**Comment by opoplawski** [comment]
Are you on EL7 or EL6? There seems to be some inconsistency here.  And I don't read that language.

**Comment by jmaas** [comment]
Can not reproduce. If this is still an issue for your, please provide useable information.
Closing this issue.
