### ISSUE TITLE
WebUI roles?

### ISSUE THREAD

**Issue by vratinov** [cobbler/cobbler#1629]
Folks,

I was wondering if there is a way to create roles for WebUI. I don't want everyone logging into WebUI to have full unrestricted roles. Basically I'm trying to figure out a way to have a way for users to login and bootstrap their instances with a set of available templates. I want to limit access to objects like the person who logged in can only see the system he or she kickstarted and this person cannot change available distros, etc. Is there a way to do this that you guys can point me to? 

Thanks,
Vadim

**Comment by alanoe** [comment]
On 01/28/2016 12:04 PM, vratinov wrote:
> I was wondering if there is a way to create roles for WebUI I don't 
> want everyone logging into WebUI to have full unrestricted roles 
> Basically I'm trying to figure out a way to have a way for users to 
> login and bootstrap their instances with a set of available templates 
> I want to limit access to objects like the person who logged in can 
> only see the system he or she kickstarted and this person cannot 
> change available distros, etc Is there a way to do this that you guys 
> can point me to?

There is an authorization module in Cobbler's source code which should 
support read/write permissions in distros, systems, profiles, kickstart 
templates and snippets. I have never used it, so I do not know if it is 
working in latest Cobbler version.

I have developed a more detailed Cobbler ACL which breaks "write" 
permissions in system in 2 roles: user and administrator. Users may 
update provisioning-related attributes such as profile, kernel options, 
kickstart metadata, "netboot enabled" flag and restart the system, 
administrators can update all other attributes such as system networking 
and power management information. imho this is more useful in a shared 
environment than binary read/write ACL. However, I have not submitted 
this feature upstream yet.


Regards,
Alan Evangelista

**Comment by vratinov** [comment]
I'd like to be able to create a system object as a normal "user" not just update an existing one. So the admin creates the profiles, distros, repos and etc but users can should be able to use WebUI to create system objects based on the options that the admin created.

**Comment by alanoe** [comment]
As I mentioned, there is no admin/user role ACL in upstream Cobbler, only read (view) / write (create/update) permissions. If you are requesting anything more than that, this would be a feature request. You can implement yourself or wait until someone do it.

FYI As Cobbler has few developers currently, new features are rarely developed.

**Comment by SchoolGuy** [comment]
The webinterface will be removed with 3.3.0 and thus I will close this issue. A new interface will be created when the Team has time and resources for it.
