### ISSUE TITLE
SLES-11-SP3 is not able to find repository during install

### ISSUE THREAD

**Issue by wulfgarpro** [cobbler/cobbler#1632]
When I try and boot a koan provisioned SLES-11-SP3 VM, I can't get passed the following:

![Imgur](http://i.imgur.com/S8eZQuP.png)

**cobbler report:**

> systems:
> \==========
> Name                           : test_sles_1
> TFTP Boot Files                : {}
> Comment                        : 
> Enable gPXE?                   : 0
> Fetchable Files                : {}
> Gateway                        : 
> Hostname                       : 
> Image                          : 
> IPv6 Autoconfiguration         : False
> IPv6 Default Device            : 
> Kernel Options                 : {'install': 'http://172.17.0.5/cblr/ks_mirror/SLES-11-SP3/'}
> Kernel Options (Post Install)  : {}
> Kickstart                      : <<inherit>>
> Kickstart Metadata             : {}
> LDAP Enabled                   : False
> LDAP Management Type           : authconfig
> Management Classes             : []
> Management Parameters          : <<inherit>>
> Monit Enabled                  : False
> Name Servers                   : []
> Name Servers Search Path       : []
> Netboot Enabled                : True
> Owners                         : ['admin']
> Power Management Address       : 
> Power Management ID            : 
> Power Management Password      : 
> Power Management Type          : ack_manual
> Power Management Username      : 
> Profile                        : sles11_test
> Proxy                          : <<inherit>>
> Red Hat Management Key         : <<inherit>>
> Red Hat Management Server      : <<inherit>>
> Repos Enabled                  : False
> Server Override                : <<inherit>>
> Status                         : production
> Template Files                 : {}
> Virt Auto Boot                 : 0
> Virt CPUs                      : <<inherit>>
> Virt Disk Driver Type          : <<inherit>>
> Virt File Size(GB)             : <<inherit>>
> Virt Path                      : <<inherit>>
> Virt PXE Boot                  : 0
> Virt RAM (MB)                  : <<inherit>>
> Virt Type                      : xenpv

There's a similar issue reported here: https://github.com/cobbler/cobbler/issues/765, but as you can see in the above report, I've added the _install_ kernel option.

**Comment by nacc** [comment]
You should be able to drop to a shell in the installer and see what the installer errored out on in the logs?

**Comment by SchoolGuy** [comment]
So this can virtually mean anything. From wrongly configured repositories, to a router being down, ... Thus closing this one.
