### ISSUE TITLE
OL5 / RHEL5 Support in autoinstall_snippets/autoinstall_start

### ISSUE THREAD

**Issue by Klaas-** [cobbler/cobbler#1635]
A change was introduced in:
https://github.com/cobbler/cobbler/commit/e8116ca2567a209c1df74a8b31f817436716588d#diff-0f74685e5796b829a86375fd6f53c62e

migrating from wget to curl. this breaks functionality oracle linux 5 (5.8) installs because curl is not shipped within iso

**Comment by jmaas** [comment]
This is indeed an unfortunate change.

Lucky for the few EL5 users out there (i hope) it's quite easy to edit the snippets yourself.
This will not be fixed by reverting back to wget. Sorry.
