### ISSUE TITLE
cobbler fail to find tinycore signature

### ISSUE THREAD

**Issue by pangxudong** [cobbler/cobbler#1636]
hi, I edit /var/lib/cobbler/distro_signatures.json to add a tinycore signature: 

_"tinycore": {
   "test": {
    "signatures":["boot"],
      "version_file": "platform",
      "version_file_regex": null,
      "supported_arches":["x86_64"],
      "supported_repo_breeds":["tcz"],
      "kernel_file":"(linux|vmlinuz(.*))",
      "initrd_file":"boot/core.gz",
      "kernel_arch": "",
      "kernel_arch_regex": null,
      "isolinux_ok":false,
      "kernel_options":"",
      "kernel_options_post":"",
      "boot_files":[],
      "default_kickstart":""
   }
  },_

and when i run "sudo cobbler signature report " it also contains a tinycore signature:

_tinycore:
	test_

but when I import the tinycore image, it seems cobbler can't find the right signature, and returns an error:

_task started: 2016-02-29_020038_import
task started (id=Media import, time=Mon Feb 29 02:00:38 2016)
Found a candidate signature: breed=tinycore, version=test
Found a candidate signature: breed=redhat, version=rhel6
Found a matching signature: breed=redhat, version=rhel6
Adding distros from path /var/www/cobbler/ks_mirror/TinyCore-test-x86_64:
skipping import, as distro name already exists: TinyCore-test-x86_64
No distros imported, bailing out
!!! TASK FAILED !!!_

is this a bug or  my mistake?

**Comment by nacc** [comment]
I'm not sure what you are asking? It actually found two candidate signatures (including your tinycore one), but the rhel6 was taken as matching (not sure why).

The error wasn't with signatures, it was, as quite clearly stated "skipping import, as distro name already exists: TinyCore-test-x86_64"

**Comment by jmaas** [comment]
Based on remark made by  nacc i'm closing this issue. If you think it's still an issue with Cobbler please let me know and i will re-open. fwiw, tinycore isnt officially supported.
