### ISSUE TITLE
cobbler replication and non standard http port

### ISSUE THREAD

**Issue by mihkelvain** [cobbler/cobbler#1637]
Hi.

In our environment I can't use standard ports for http and https. So I configured http to run on 88 and https on 444. Troubles come when I try to set up replication. As a temporary solution (and with the help of #cobbler@freenode), I had to modify on slave
/usr/lib/python2.7/site-packages/cobbler/action_replicate.py
Changed lines:

self.uri = '%s://%s:88/cobbler_api' % (protocol,self.master)
and 
self.local = xmlrpclib.Server("http://127.0.0.1:88/cobbler_api")

Then 
cobbler replicate --master=amaster-server --sync-all
works.
Since cobbler has http_port variable, could we please use that var on those lines too?

**Comment by jmaas** [comment]
Yes, we should !

**Comment by jmaas** [comment]
it's a bit more work than that to do it properly.
the client should get a port parameter, we can not assume the client and server use the same port numbers.

**Comment by jmaas** [comment]
Also backported to release28, this will be in 2.8.1
