### ISSUE TITLE
Task ID is not unique.

### ISSUE THREAD

**Issue by thereallukl** [cobbler/cobbler#1646]
When running actions in automated manner on large number of hosts multiple `power reboot` actions have same task ids.

I believe that task_id should be generated with something like UUID (or at least with milisecond granularity) to avoid confusion.

**Comment by jmaas** [comment]
I agree.

**Comment by jmaas** [comment]
this will be an invasive change, therefor target 3.0

**Comment by SchoolGuy** [comment]
So we could do this in theory: https://docs.python.org/3/library/uuid.html

Downside: We would lose the time in the name of the task. But we could add this as an attribute and the logs have timestamps as attributes anyway. We would just need to document this.

We are generating the task id here: https://github.com/cobbler/cobbler/blob/master/cobbler/remote.py#L438

If we change this we should in theroy be able to have this solved. More investigation still to be done...

**Comment by brejoc** [comment]
@schoolguy Would only us humans benefit from this or is this causing errors?

**Comment by SchoolGuy** [comment]
@brejoc I will check on Monday but I guess that this may cause concurrency errors if the names are used for looking up tasks.

**Comment by SchoolGuy** [comment]
Okay I finally will be able to take care of this. Fix will be bundled with the fix for #3164
