### ISSUE TITLE
RHEL 7 Hostname not set correctly in example snippets.

### ISSUE THREAD

**Issue by Asysadmin** [cobbler/cobbler#1653]
Summary: Cobbler 2.6.10 is setting the hostname wrong for RHEL 7 systems.

Steps to reproduce: 
Create an entry under "Systems" and in "Networking(Global)" set a hostname in the "Hostname" field.

Research:
Cobbler will set that hostname by adding it to /etc/sysconfig/network. While this is correct for RHEL6, is is wrong for RHEL7.

Under RHEL 7 (per redhat)* The correct way to set the hostname is:
hostnamectl set-hostname name

Note: It appears that (once I fixed a bug in my config) the hostname is getting set even though we are not following the RHEL recommended way of doing this in RHEL7.

*Ref: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec_Configuring_Host_Names_Using_hostnamectl.html

**Comment by nacc** [comment]
Can you clarify after your last update? It seems like the RHEL 7 hostname *is* set correctly? Just not being done in the recommended by RH way?

**Comment by Asysadmin** [comment]
You are correct that it is getting set. But per the RHEL documentation  what the script is doing is not supported, and we are doing should not work. 

It would probably be best if we did some sort of RHEL6/RHEL7 check and then called an appropriate action.

**Comment by nacc** [comment]
I think you are reading the documentation too literally -- nothing in that page says what the current script does should not work, on my first reading? Can you quote such a section?

Tbh, this sounds like a nice-to-have (feel free to send a PR), but it would need thorough testing that that command is available in all environments.

**Comment by Asysadmin** [comment]
I looked again with a fresh viewpoint, and your right. While they recommend using the new method to make the change it looks like as long as the file gets updated that works to.

So go ahead and reject this change as user error. :-)

**Comment by dkanbier** [comment]
@Asysadmin could you elaborate on the bug you fixed in the config? I'm facing the same issue..
