### ISSUE TITLE
System management is locked by the application pid 4406 (y2base).   

### ISSUE THREAD

**Issue by hddang1** [cobbler/cobbler#1654]
Hi, 

I am trying to run a zypper update by putting the commands into a shelf script and then execute it from
a snippet.   This method didn't work.  The ks-scripts.log shows the error "System management is locked by 
the application with pid 4406 (y2base).  Close this application before trying again."   When I use the 
same strategy for RHEL7.0 installation, it worked.  Does anyone have suggestions how to make the zypper 
update script work?

script_sles_update.sh:

zypper addrepo http://....  security
zypper clean
zypper --gpg-auto-import-keys refresh
zypper --non-interactive update

snippet:

cd /root
wget server:/script_sles_update.sh
chmod +x script_sles_update.sh
/root/script_suse-12-11.sh

Thank you.

**Comment by nacc** [comment]
https://www.suse.com/documentation/sles-12/book_autoyast/data/createprofile_scripts.html

I don't believe you can safely do anything during the install (in particular invoking zypper or even assuming zypper is available). The above seems better to do as a post-script.

**Comment by hddang1** [comment]
post-script is where I placed the snippet.   Any other suggestions?   Thanks

**Comment by nacc** [comment]
Can you please provide your full XML? The above link does mention "If you would like to call zypper in the pre-install script you will have to set the environment variable ZYPP_LOCKFILE_ROOT="/var/run/autoyast" in order to prevent conflicts with the running YAST process."

**Comment by hddang1** [comment]
Below are my shell script, snippet and kickstart.    Thank you.

script_suse-12-11.sh
uname -r
cd /etc/zypp/repos.d
mv *.repo /tmp
zypper addrepo http://<link here>/suse/SLES12.REL/ia32e/patches/ security
zypper repos
zypper clean
zypper --gpg-auto-import-keys refresh
zypper --non-interactive update





=====================================
snippet:  'post_install_kernel_update_sles12'

#if $breed == "suse"
 <script>
        <network_needed config:type="boolean">true</network_needed>
        <interpreter>shell</interpreter>
        <filename>post_install_kernel_update_sles12</filename>
        <source><![CDATA[
$SNIPPET('log_ks_sles')
#end if

#
#set $osver = $os_version.upper()
#if $osver.startswith('SLES12')
#set $osver = 'SLES12'
#end if

cd /root
wget $PKG_ADDR:/script_suse-12-11.sh
chmod +x script_suse-12-11.sh
/root/script_suse-12-11.sh

 

#if $breed == "suse"
]]></source>
      </script>
#end if

========================================
Kickstart:

<?xml version="1.0"?>

<!DOCTYPE profile>
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
$SNIPPET('local_vars')
<add-on>
    <add_on_products config:type="list">
      <listentry>
        <media_url><![CDATA[http://$server/cobbler/ks_mirror/SLE-12-SDK-DVD-x86_64-GM-DVD1]]></media_url>
        <media_url><![CDATA[http://$server/cobbler/ks_mirror/SLE-12-SDK-DVD-x86_64-GM-DVD2]]></media_url>
        <media_url><![CDATA[http://$server/cobbler/ks_mirror/SLE-12-SDK-DVD-x86_64-GM-DVD3]]></media_url>
        <product>sle-sdk</product>
        <product_dir>/</product_dir>
      </listentry>
    </add_on_products>
  </add-on>
  <bootloader>
    <device_map config:type="list">
      <device_map_entry>
        <firmware>hd0</firmware>
        <linux>/dev/sda</linux>
      </device_map_entry>
    </device_map>
    <global>
      <activate>true</activate>
      <append> ksdevice=bootif text resume=/dev/sda1 splash=silent quiet showopts</append>
      <append_failsafe>showopts apm=off noresume edd=off powersaved=off nohz=off highres=off processor.max_cstate=1 nomodeset x11failsafe</append_failsafe>
      <boot_boot>false</boot_boot>
      <boot_extended>false</boot_extended>
      <boot_mbr>false</boot_mbr>
      <boot_root>true</boot_root>
      <default>0</default>
      <distributor>SLES12</distributor>
      <generic_mbr>true</generic_mbr>
      <gfxmode>auto</gfxmode>
      <os_prober>false</os_prober>
      <terminal>gfxterm</terminal>
      <timeout config:type="integer">8</timeout>
      <vgamode/>
    </global>
    <loader_type>grub2</loader_type>
    <sections config:type="list"/>
  </bootloader>
  
  
  
  
  <deploy_image>
    <image_installation config:type="boolean">false</image_installation>
  </deploy_image>
  <firewall>
    <enable_firewall config:type="boolean">false</enable_firewall>
    <start_firewall config:type="boolean">false</start_firewall>
  </firewall>
  
  <general>
    <ask-list config:type="list"/>
    <mode>
      <confirm config:type="boolean">false</confirm>
	  <final_reboot config:type="boolean">true</final_reboot>
    </mode>
    <proposals config:type="list"/>
    <signature-handling>
      <accept_file_without_checksum config:type="boolean">true</accept_file_without_checksum>
      <accept_non_trusted_gpg_key config:type="boolean">true</accept_non_trusted_gpg_key>
      <accept_unknown_gpg_key config:type="boolean">true</accept_unknown_gpg_key>
      <accept_unsigned_file config:type="boolean">true</accept_unsigned_file>
      <accept_verification_failed config:type="boolean">false</accept_verification_failed>
      <import_gpg_key config:type="boolean">true</import_gpg_key>
    </signature-handling>
  </general>
 
   <host>
    <hosts config:type="list">
      <hosts_entry>
        <host_address>127.0.0.1</host_address>
        <names config:type="list">
          <name>localhost</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>127.0.0.2</host_address>
        <names config:type="list">
          <name>${hostname}.site $hostname</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>::1</host_address>
        <names config:type="list">
          <name>localhost ipv6-localhost ipv6-loopback</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>fe00::0</host_address>
        <names config:type="list">
          <name>ipv6-localnet</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>ff00::0</host_address>
        <names config:type="list">
          <name>ipv6-mcastprefix</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>ff02::1</host_address>
        <names config:type="list">
          <name>ipv6-allnodes</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>ff02::2</host_address>
        <names config:type="list">
          <name>ipv6-allrouters</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>ff02::3</host_address>
        <names config:type="list">
          <name>ipv6-allhosts</name>
        </names>
      </hosts_entry>
    </hosts>
  </host>

  
  <iscsi-client>
    <initiatorname></initiatorname>
    <targets config:type="list"/>
    <version>1.0</version>
  </iscsi-client>
  
  $SNIPPET('kdump_sles11')
   <keyboard>
    <keymap>us</keymap>
  </keyboard>
  <language>
    <language>en_US</language>
    <languages></languages>
  </language>
  
  
  <login_settings/>
  <networking>
$SNIPPET('interfaces_pre_sles11')
  </networking>
    <nis>
    <netconfig_policy>auto</netconfig_policy>
    <nis_broadcast config:type="boolean">false</nis_broadcast>
    <nis_broken_server config:type="boolean">false</nis_broken_server>
    <nis_domain></nis_domain>
    <nis_local_only config:type="boolean">false</nis_local_only>
    <nis_options></nis_options>
    <nis_other_domains config:type="list"/>
    <nis_servers config:type="list"/>
    <slp_domain/>
    <start_autofs config:type="boolean">false</start_autofs>
    <start_nis config:type="boolean">false</start_nis>
  </nis>
  
  <ntp-client>
    <ntp_policy>auto</ntp_policy>
    <peers config:type="list"/>
    <start_at_boot config:type="boolean">true</start_at_boot>
    <start_in_chroot config:type="boolean">false</start_in_chroot>
    <sync_interval config:type="integer">5</sync_interval>
    <synchronize_time config:type="boolean">false</synchronize_time>
  </ntp-client>
  <partitioning config:type="list">
#if $getVar('hp', 'false').lower() == 'true'
        $SNIPPET('partitioning_sles11')
#else
        $SNIPPET('partitioning_sles')
#end if
  </partitioning>

  <report>
    <errors>
      <log config:type="boolean">true</log>
      <show config:type="boolean">true</show>
      <timeout config:type="integer">0</timeout>
    </errors>
    <messages>
      <log config:type="boolean">true</log>
      <show config:type="boolean">true</show>
      <timeout config:type="integer">10</timeout>
    </messages>
    <warnings>
      <log config:type="boolean">true</log>
      <show config:type="boolean">true</show>
      <timeout config:type="integer">10</timeout>
    </warnings>
    <yesno_messages>
      <log config:type="boolean">true</log>
      <show config:type="boolean">true</show>
      <timeout config:type="integer">10</timeout>
    </yesno_messages>
  </report>
    <runlevel>
    <default>3</default>
  </runlevel>
  <services-manager>
    <default_target>graphical</default_target>
    <services>
      <disable config:type="list"/>
      <enable config:type="list">
        <service>sshd</service>
      </enable>
    </services>
  </services-manager>
  <software>
    <image/>
    <instsource/>
$SNIPPET('sles12_packages')
    <patterns config:type="list">
      <pattern>32bit</pattern>
      <pattern>Basis-Devel</pattern>
      <pattern>Minimal</pattern>
      <pattern>apparmor</pattern>
      <pattern>base</pattern>
      <pattern>documentation</pattern>
      <pattern>gnome-basic</pattern>
      <pattern>x11</pattern>
    </patterns>
  </software>
  <timezone>
    <hwclock>UTC</hwclock>
    <timezone>America/New_York</timezone>
  </timezone>
  <user_defaults>
    <expire></expire>
    <home>/home</home>
    <inactive>-1</inactive>
    <shell>/bin/bash</shell>
    <skel>/etc/skel</skel>
  </user_defaults>
  <users config:type="list">
    <user>
      <encrypted config:type="boolean">true</encrypted>
      <fullname>root</fullname>
      <gid>0</gid>
      <home>/root</home>
      <password_settings>
        <expire/>
        <flag/>
        <inact/>
        <max/>
        <min/>
        <warn/>
      </password_settings>
      <shell>/bin/bash</shell>
      <uid>0</uid>
 

#if $CURRENT_PLATFORM == 'TS'
#raw
	  <user_password>secret1</user_password> 
#end raw
#else
#raw
	  <user_password>secret2</user_password> 
#end raw
#end if
      <username>root</username>
    </user>
	
	<user>
      <encrypted config:type="boolean">false</encrypted>
      <username>test1</username>
      <home>/home/test1</home>
      <user_password>secret3</user_password>
    </user>


  </users>
  
  <scripts>
	<pre-scripts config:type="list">
	  <script>
        <interpreter>shell</interpreter>
        <filename>kickstart_start</filename>
        <source><![CDATA[$SNIPPET('kickstart_start')]]></source>
      </script>  
    </pre-scripts> 
    
	<post-scripts config:type="list">
	

$SNIPPET('post_install_kernel_update_sles12')

#set global $wrappedscript = 'post_cleanup_grubconfig_menu.lst'
$SNIPPET('post_sles_scriptwrapper')
#set global $wrappedscript = 'kickstart_done'
$SNIPPET('post_sles_scriptwrapper')

    </post-scripts>  
  </scripts>
</profile>

**Comment by nacc** [comment]
Try with verbatim markup (put all of it between \`\`\` and \`\`\`
```
stuff goes here
```

**Comment by hddang1** [comment]
Good trick.   Below are my shell script, snippet and kickstart.  Thanks.

``` 

script_suse-12-11.sh
uname -r
cd /etc/zypp/repos.d
mv *.repo /tmp
zypper addrepo http://<link here>/suse/SLES12.REL/ia32e/patches/ security
zypper repos
zypper clean
zypper --gpg-auto-import-keys refresh
zypper --non-interactive update





=====================================
snippet:  'post_install_kernel_update_sles12'


#if $breed == "suse"
 <script>
        <network_needed config:type="boolean">true</network_needed>
        <interpreter>shell</interpreter>
        <filename>post_install_kernel_update_sles12</filename>
        <source><![CDATA[
$SNIPPET('log_ks_sles')
#end if

#
#set $osver = $os_version.upper()
#if $osver.startswith('SLES12')
#set $osver = 'SLES12'
#end if

cd /root
wget $PKG_ADDR:/script_suse-12-11.sh
chmod +x script_suse-12-11.sh
/root/script_suse-12-11.sh

 

#if $breed == "suse"
]]></source>
      </script>
#end if

========================================
Kickstart:

<?xml version="1.0"?>
<!--


<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
$SNIPPET('local_vars')
<add-on>
    <add_on_products config:type="list">
      <listentry>
        <media_url><![CDATA[http://$server/cobbler/ks_mirror/SLE-12-SDK-DVD-x86_64-GM-DVD1]]></media_url>
        <media_url><![CDATA[http://$server/cobbler/ks_mirror/SLE-12-SDK-DVD-x86_64-GM-DVD2]]></media_url>
        <media_url><![CDATA[http://$server/cobbler/ks_mirror/SLE-12-SDK-DVD-x86_64-GM-DVD3]]></media_url>
        <product>sle-sdk</product>
        <product_dir>/</product_dir>
      </listentry>
    </add_on_products>
  </add-on>
  <bootloader>
    <device_map config:type="list">
      <device_map_entry>
        <firmware>hd0</firmware>
        <linux>/dev/sda</linux>
      </device_map_entry>
    </device_map>
    <global>
      <activate>true</activate>
      <append> ksdevice=bootif text resume=/dev/sda1 splash=silent quiet showopts</append>
      <append_failsafe>showopts apm=off noresume edd=off powersaved=off nohz=off highres=off processor.max_cstate=1 nomodeset x11failsafe</append_failsafe>
      <boot_boot>false</boot_boot>
      <boot_extended>false</boot_extended>
      <boot_mbr>false</boot_mbr>
      <boot_root>true</boot_root>
      <default>0</default>
      <distributor>SLES12</distributor>
      <generic_mbr>true</generic_mbr>
      <gfxmode>auto</gfxmode>
      <os_prober>false</os_prober>
      <terminal>gfxterm</terminal>
      <timeout config:type="integer">8</timeout>
      <vgamode/>
    </global>
    <loader_type>grub2</loader_type>
    <sections config:type="list"/>
  </bootloader>
  
  
  
  
  <deploy_image>
    <image_installation config:type="boolean">false</image_installation>
  </deploy_image>
  <firewall>
    <enable_firewall config:type="boolean">false</enable_firewall>
    <start_firewall config:type="boolean">false</start_firewall>
  </firewall>
  
  <general>
    <ask-list config:type="list"/>
    <mode>
      <confirm config:type="boolean">false</confirm>
	  <final_reboot config:type="boolean">true</final_reboot>
    </mode>
    <proposals config:type="list"/>
    <signature-handling>
      <accept_file_without_checksum config:type="boolean">true</accept_file_without_checksum>
      <accept_non_trusted_gpg_key config:type="boolean">true</accept_non_trusted_gpg_key>
      <accept_unknown_gpg_key config:type="boolean">true</accept_unknown_gpg_key>
      <accept_unsigned_file config:type="boolean">true</accept_unsigned_file>
      <accept_verification_failed config:type="boolean">false</accept_verification_failed>
      <import_gpg_key config:type="boolean">true</import_gpg_key>
    </signature-handling>
  </general>
 
   <host>
    <hosts config:type="list">
      <hosts_entry>
        <host_address>127.0.0.1</host_address>
        <names config:type="list">
          <name>localhost</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>127.0.0.2</host_address>
        <names config:type="list">
          <name>${hostname}.site $hostname</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>::1</host_address>
        <names config:type="list">
          <name>localhost ipv6-localhost ipv6-loopback</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>fe00::0</host_address>
        <names config:type="list">
          <name>ipv6-localnet</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>ff00::0</host_address>
        <names config:type="list">
          <name>ipv6-mcastprefix</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>ff02::1</host_address>
        <names config:type="list">
          <name>ipv6-allnodes</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>ff02::2</host_address>
        <names config:type="list">
          <name>ipv6-allrouters</name>
        </names>
      </hosts_entry>
      <hosts_entry>
        <host_address>ff02::3</host_address>
        <names config:type="list">
          <name>ipv6-allhosts</name>
        </names>
      </hosts_entry>
    </hosts>
  </host>

  
  <iscsi-client>
    <initiatorname></initiatorname>
    <targets config:type="list"/>
    <version>1.0</version>
  </iscsi-client>
  
  $SNIPPET('kdump_sles11')
   <keyboard>
    <keymap>us</keymap>
  </keyboard>
  <language>
    <language>en_US</language>
    <languages></languages>
  </language>
  
  
  <login_settings/>
  <networking>
$SNIPPET('interfaces_pre_sles11')
  </networking>
    <nis>
    <netconfig_policy>auto</netconfig_policy>
    <nis_broadcast config:type="boolean">false</nis_broadcast>
    <nis_broken_server config:type="boolean">false</nis_broken_server>
    <nis_domain></nis_domain>
    <nis_local_only config:type="boolean">false</nis_local_only>
    <nis_options></nis_options>
    <nis_other_domains config:type="list"/>
    <nis_servers config:type="list"/>
    <slp_domain/>
    <start_autofs config:type="boolean">false</start_autofs>
    <start_nis config:type="boolean">false</start_nis>
  </nis>
  
  <ntp-client>
    <ntp_policy>auto</ntp_policy>
    <peers config:type="list"/>
    <start_at_boot config:type="boolean">true</start_at_boot>
    <start_in_chroot config:type="boolean">false</start_in_chroot>
    <sync_interval config:type="integer">5</sync_interval>
    <synchronize_time config:type="boolean">false</synchronize_time>
  </ntp-client>
  <partitioning config:type="list">
#if $getVar('hp', 'false').lower() == 'true'
        $SNIPPET('partitioning_sles11')
#else
        $SNIPPET('partitioning_sles')
#end if
  </partitioning>

  <report>
    <errors>
      <log config:type="boolean">true</log>
      <show config:type="boolean">true</show>
      <timeout config:type="integer">0</timeout>
    </errors>
    <messages>
      <log config:type="boolean">true</log>
      <show config:type="boolean">true</show>
      <timeout config:type="integer">10</timeout>
    </messages>
    <warnings>
      <log config:type="boolean">true</log>
      <show config:type="boolean">true</show>
      <timeout config:type="integer">10</timeout>
    </warnings>
    <yesno_messages>
      <log config:type="boolean">true</log>
      <show config:type="boolean">true</show>
      <timeout config:type="integer">10</timeout>
    </yesno_messages>
  </report>
    <runlevel>
    <default>3</default>
  </runlevel>
  <services-manager>
    <default_target>graphical</default_target>
    <services>
      <disable config:type="list"/>
      <enable config:type="list">
        <service>sshd</service>
      </enable>
    </services>
  </services-manager>
  <software>
    <image/>
    <instsource/>
$SNIPPET('sles12_packages')
    <patterns config:type="list">
      <pattern>32bit</pattern>
      <pattern>Basis-Devel</pattern>
      <pattern>Minimal</pattern>
      <pattern>apparmor</pattern>
      <pattern>base</pattern>
      <pattern>documentation</pattern>
      <pattern>gnome-basic</pattern>
      <pattern>x11</pattern>
    </patterns>
  </software>
  <timezone>
    <hwclock>UTC</hwclock>
    <timezone>America/New_York</timezone>
  </timezone>
  <user_defaults>
    <expire></expire>
    <home>/home</home>
    <inactive>-1</inactive>
    <shell>/bin/bash</shell>
    <skel>/etc/skel</skel>
  </user_defaults>
  <users config:type="list">
    <user>
      <encrypted config:type="boolean">true</encrypted>
      <fullname>root</fullname>
      <gid>0</gid>
      <home>/root</home>
      <password_settings>
        <expire/>
        <flag/>
        <inact/>
        <max/>
        <min/>
        <warn/>
      </password_settings>
      <shell>/bin/bash</shell>
      <uid>0</uid>
 

#if $CURRENT_PLATFORM == 'TS'
#raw
	  <user_password>secret1</user_password> 
#end raw
#else
#raw
	  <user_password>secret2</user_password> 
#end raw
#end if
      <username>root</username>
    </user>
	
	<user>
      <encrypted config:type="boolean">false</encrypted>
      <username>testuser</username>
      <home>/home/testuser</home>
      <user_password>secret3</user_password>
    </user>


  </users>
  
  <scripts>
	<pre-scripts config:type="list">
	  <script>
        <interpreter>shell</interpreter>
        <filename>kickstart_start</filename>
        <source><![CDATA[$SNIPPET('kickstart_start')]]></source>
      </script>  
    </pre-scripts> 
    
	<post-scripts config:type="list">
	

$SNIPPET('post_install_kernel_update_sles12')

$SNIPPET('post_cleanup_services')
#set global $wrappedscript = 'post_cleanup_grubconfig_menu.lst'
$SNIPPET('post_sles_scriptwrapper')
#set global $wrappedscript = 'kickstart_done'
$SNIPPET('post_sles_scriptwrapper')

    </post-scripts>  
  </scripts>
</profile

 ```

**Comment by nacc** [comment]
Is there a reason you're not using the $wrappedscript method for your shell script? Afaict, it has no runtime need to be interpreted or substitute any variables, etc. I've never tested or used any other format of snippet with suse.

e.g.:
```
<post-scripts config:type="list">
  #set global $wrappedscript = 'script_suse-12-11.sh'
  $SNIPPET('suse_scriptwrapper.xml')

Also what is
post_sles_scriptwrapper?

It might be better if you provided the rendered autoyast file. Is there a reason you have modified it in this way? What version of suse are you trying to install. There are lots of references to kickstart, but suse does not support kickstart (and doesn't need the kickstart_start or kickstart_done snippets).

**Comment by hddang1** [comment]
No particular reason, I just didn't know about the $wrappedscript.   The XML file (not kickstarts) was created long time ago by somebody else.   Looks like post_sles_scriptwrapper.xml executes the script set for $warppedscript.   I am trying to install SLES12 and SLES12SP1.   

I just tried the method of setting the global variable, but got an error - " Error: no snippet data for script_suse-12-11.sh"  
            #set global $wrappedscript = 'script_suse-12-11.sh'
            $SNIPPET('post_sles_scriptwrapper')



``` 
post_sles_scriptwrapper

      <script>
##        <debug config:type="boolean">true</debug>
##        <feedback config:type="boolean">false</feedback>
##        <location></location>
        <network_needed config:type="boolean">true</network_needed>
        <interpreter>shell</interpreter>
#set $filename = $wrappedscript.replace('/', '_')
        <filename>$filename</filename>
        <source><![CDATA[
$SNIPPET('log_ks_sles')
$SNIPPET($wrappedscript)
]]></source>
      </script>

```
snippet 'log_ks_sles':

set -x -v
exec 1>>/root/ks-scripts.log 2>&1

**Comment by nacc** [comment]
Would it be possible to model your XML on sample_autoyast.xml more closely?

Specifically, don't make your own snippet that in turn pulls in XML, it's super hard to read for me :) 

Did you put script_suse-12-11.sh in your snippets directory?

**Comment by hddang1** [comment]
Hi, sorry I have been testing kernel security patch update on existing systems, which is related to this XML that I need to make Cobbler to work for future install.    I like your suggestion to start from the basic.   I'll try that and report back.   Thank you.

**Comment by hddang1** [comment]
Hi, I used the sample_autoyast.xml and just inserted the line $SNIPPET('post_install_kernel_update_sles12').    The file script_suse-12-11.sh is in file server which the first thing the snippet does is to copy it over.   I do see in the ks-scripts.log that the file gets copied over and executed.   But it failed the same error when trying to execute the command "zypper addrepo."  

Below is the XML file.

Thank you.   
```
<?xml version="1.0"?>
<!--

 Copyright (c) 2011 Novell
 Uwe Gansert ug@suse.de

 This software is licensed to you under the GNU General Public License,
 version 2 (GPLv2). There is NO WARRANTY for this software, express or
 implied, including the implied warranties of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 along with this software; if not, see
 http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

-->
<!DOCTYPE profile>
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
  <deploy_image>
    <image_installation config:type="boolean">false</image_installation>
  </deploy_image>
  ## without the next 6 lines autoyast will ask for confirmation bevore installation
  <general>
    <mode>
      <confirm config:type="boolean">false</confirm>
      <final_reboot config:type="boolean">true</final_reboot>	
    </mode>
  </general>
  $SNIPPET('hosts.xml')
  $SNIPPET('kdump.xml')
  <keyboard>
    <keymap>english</keymap>
  </keyboard>
  <language>
    <language>en_US</language>
    <languages></languages>
  </language>
  <login_settings/>
  $SNIPPET('networking.xml')
  <runlevel>
    <default>3</default>
  </runlevel>
  <users config:type="list">
    <user>
      <encrypted config:type="boolean">true</encrypted>
      <fullname>root</fullname>
      <gid>0</gid>
      <home>/root</home>
      <password_settings>
        <expire></expire>
        <flag></flag>
        <inact></inact>
        <max></max>
        <min></min>
        <warn></warn>
      </password_settings>
      <shell>/bin/bash</shell>
      <uid>0</uid>
	<user_password>$6$Fl1uVhybJHCR$U0D1RfG/tXSQcnV3K.LyrWBawSg53b/WbGvjVXsfWvm8raCrmHIE3vH.WuVbMOuFiIZaqbOf6Pdv4bVZwBx3A/
      <username>root</username>
    </user>
  </users>
  <scripts>
## we have to include the pre-scripts tag to get kickstart_start included
<pre-scripts config:type="list">
## SuSE has an annoying habit on ppc64 of changing the system
## boot order after installation. This makes it non-trivial to
## automatically re-install future OS. If you want to workaround
## this, un-comment out the following two lines and the two
## lines in the post-scripts section:
#set global $wrappedscript = 'save_boot_device'
## $SNIPPET('suse_scriptwrapper.xml')
</pre-scripts>
<post-scripts config:type="list">

## This plugin wrapper provides the flexibility to call pure shell
## snippets which can be used directly on kickstart and with with
## wrapper on SuSE.
##
## To use it
## - exchange name_of_pure_shell_snippet with the name of this shell snippet
## - and remove the '##' in front of the line with suse_scriptwrapper.xml
##
#set global $wrappedscript = 'name_of_pure_shell_snippet'
## $SNIPPET('suse_scriptwrapper.xml')
## SuSE has an annoying habit on ppc64 of changing the system
## boot order after installation. This makes it non-trivial to
## automatically re-install future OS. If you want to workaround
## this, un-comment out the following two lines and the two
## lines in the pre-scripts section:
#set global $wrappedscript = 'restore_boot_device'
## $SNIPPET('suse_scriptwrapper.xml')

$SNIPPET('post_install_kernel_update_sles12')
	
    </post-scripts>
  </scripts>
</profile>
```

**Comment by jmaas** [comment]
Well, this really is an autoyast issue. Not a Cobbler bug perse.
You might want to try the mailing list for further assistance.
