### ISSUE TITLE
modidy profile error to use xmlrpc

### ISSUE THREAD

**Issue by wangmingweikong** [cobbler/cobbler#1655]
When I modify profile attributes with XMLRPC,I found that has a error .My Cobbler version is 2.6.11,and My source code are:
`import xmlrpclib`
`server = xmlrpclib.Server("http://192.168.12.14/cobbler_api")`
`token = server.login("cobbler","cobbler")`
`handle = server.get_profile_handle("CentOS-7.0-x86_64",token)`
`a = server.modify_profile(handle,"name","testCentOS",token)`
`b = server.save_profile(handle,token)`
When executing the above code,I found that a new profile has been created.

**Comment by nacc** [comment]
I believe the expected API is server.rename_profile(), no?

Can you provide the cobbler.log from when you run the above?

**Comment by SchoolGuy** [comment]
We don't support 2.6.x anymore, so I will close this one. The current XMLRPC Api is tested in travis, so I expect that your usecase will work.
