### ISSUE TITLE
How to resolve this dracut shell problem.

### ISSUE THREAD

**Issue by dilshath** [cobbler/cobbler#1661]
I am using centos 7 in physical machine. Unfortunately I partition the /dev/sda2 disk which contains /root/swap/home system directories so it showing this errors,

Dracut Error:

[ OK ] Reached target Paths.
[ OK ] Reached target Basic System.
dracut-initqueue[372]: Warning: Could not boot.
[ OK ] Started Show Plymouth Boot Screen.
[ OK ] Reached target Paths.
[ OK ] Reached target Basic System.
dracut-initqueue[372]: Warning: Could not boot.
dracut-initqueue[372]: Warning: /dev/centos/root does not exist.
dracut-initqueue[372]: Warning: /dev/centos/swap does not exist.
dracut-initqueue[372]: Warning: /dev/mapper/centos-root does not exist.
Starting Dracut Emergency Shell...
Warning: /dev/centos/root does not exist
Warning: /dev/centos/swap does not exist
Warning: /dev/mapper/centos-root does not exist

Generating "/run/initramfs/rdsosreport.txt"

Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.

dracut#

Anybody know how to fix the problem,please help me.

**Comment by jmaas** [comment]
I dont know, this really isnt a Cobbler issue.
You could try our maillinglist though!
