### ISSUE TITLE
FR: Datacenter Management and Rackscale Deployment Support

### ISSUE THREAD

**Issue by requiemsallure** [cobbler/cobbler#1669]
I had this Idea about a month ago, and have been thinking on how it could be realized using Cobbler... to be honest this may simply require a whole new software package... however there would still be some pieces that would require changing in Cobbler.

The image that I have for this does a few things, however Ill work from the top down.  

---

First, it reworks the interface for cobbler-web in that instead of having a only single System page for all registered systems, you would have an additional page that allows you to list and define Rack Systems.  This brings up an essential question... how does one define a rack?

While I do not know if it is the best way... I personally would use the Management TOR Switches.  Therefore, within the Rack Systems page, you would define systems for switch ports as desired.  Then as cobbler intercepts a DHCP/PXE request and once the DHCP portion has been completed, but before handing the request to the TFTP server, cobbler sends a SNMP Multicast to the switches on the management network to discover who has "REQUESTER_MAC" and then send the appropriate files based on Switch/Port.  

If the defined switch is not defined as a Rack System (or the user has disabled the Rack System feature) we use standard cobbler procedures.

---

I don't believe that I have everything that would be needed worked out yet.  However I wanted to check what the Cobbler Team thought of this idea.  I would be more than willing to assist in its implementation, however as I only started Python this year I am a bit lacking.  As such, best case scenario I am looking to collaborate on this.  

Please let me know what you think.

**Comment by gregmark** [comment]
I think this an interesting idea, although I think the lead developers have been careful not to turn Cobbler into a Rack Management utility. Having said that, allowing plugins or something like that to give Cobbler some extensibility to satisfy more use cases. In other words, keep Cobbler lean and mean but also agnostic with respect to other functionality that makes sense in certain environments.

Cobbler needs to evolve :)

**Comment by SchoolGuy** [comment]
Future discussions about the web-ui and web-ux should be done now in: #2342
