### ISSUE TITLE
Failing to import Ubuntu 16.04

### ISSUE THREAD

**Issue by five0va** [cobbler/cobbler#1677]
I have Ubuntu 14.04 imported just fine, but when I attempt to import Ubuntu 16.04 (done the same exact way), the task fails. Attached is the output.

[ubuntu1604-cobbler.txt](https://github.com/cobbler/cobbler/files/332045/ubuntu1604-cobbler.txt)

**Comment by ploupas** [comment]
This worked for me: https://github.com/cobbler/cobbler/pull/1658/files#r60871940

**Comment by five0va** [comment]
Awesome, thanks ploupas!

**Comment by YouAreTheOneLove** [comment]
hi ,guys,could you  show me how to install ubuntu14.04-server by auto.?

**Comment by YouAreTheOneLove** [comment]
please email me:  a604937025@outlook.com   . i have been in trouble for two weeks , thx
