### ISSUE TITLE
Cobbler edit profile command with the key --in-place mangle kernel options with '=~'

### ISSUE THREAD

**Issue by ASyriy** [cobbler/cobbler#1681]
Editing a cobbler profile kernel options with the key --in-place for the kernel options (which originally didn't have an assignment =value) follows to the adding assignment the '~' value.

For example:
Original kernel options (please put your attention to the 'toram' and 'debug' options):
-------------------------------------------------------------------------------
initrd=/images/ubuntu_bootstrap/initrd.img ksdevice=bootif console=ttyS0,9600 console=tty0 toram debug
-------------------------------------------------------------------------------

After executing the cobbler command:
-------------------------------------------------------------------------------
cobbler profile edit --name ubuntu_bootstrap --kopts="console=tty0 console=ttyS0,115200 iommu=off" --in-place
-------------------------------------------------------------------------------

Will be mangled to (please put attention to the 'toram' and 'debug' options):
-------------------------------------------------------------------------------
initrd=/images/ubuntu_bootstrap/initrd.img ksdevice=bootif console=ttyS0,115200 console=tty0 iommu=off toram=~ debug=~
-------------------------------------------------------------------------------

Adding =~ to the 'toram' kernel option changes the option from a flag (means downloading file system into the RAM) to the name of the file-system file (with the name '~') and triggers kernel panic on the nodes.

**Comment by ASyriy** [comment]
I have created the pull request.
https://github.com/cobbler/cobbler/pull/1682

Please review

**Comment by jmaas** [comment]
Merged

**Comment by jmaas** [comment]
Thanks for contributing!!
