### ISSUE TITLE
Cobbler sync fails on systemd systems if "service" is not installed

### ISSUE THREAD

**Issue by tigerpaws2** [cobbler/cobbler#1685]
as is the case in the docker container implementation of cobbler here: https://github.com/ContainerSolutions/docker-cobbler?__hstc=137489263.10558a28489c3392c90356ca62160898.1471286471934.1471286471934.1471286471934.1&__hssc=137489263.1.1471286471934&__hsfp=1495062989

```
unning post-sync triggers
running python triggers from /var/lib/cobbler/triggers/sync/post/*
running python trigger cobbler.modules.sync_post_restart_services
running: dhcpd -t -q
received on stdout: 
received on stderr: 
running: service dhcpd restart
received on stdout: 
received on stderr: /bin/sh: service: command not found

running: service named restart
received on stdout: 
received on stderr: /bin/sh: service: command not found
```

**Comment by jmaas** [comment]
I have this issue fixed in a local tree for master (3.0).
Need to see if we can fix this for release28 branch

**Comment by opoplawski** [comment]
@jmaas What are your plans here?  I'm looking at some other changes that need to be made for systemd and it would be good to coordinate?

**Comment by jmaas** [comment]
@opoplawski i have the beginnings of a runtime abstraction layer. basically you get a config file per os/version which tells where things are, what commands to use. the goal is that when a new distro wants to support Cobbler no code changes are necessary.

i will try to push it to a development branch in the coming days.

**Comment by jmaas** [comment]
@opoplawski but i really dont want to make such a big change in the 2.8 tree. but 2.8 surely does need to get a decent fix for systemd/service/whatnot. especially considering we need to support 2.8 for quite some time

so what did you have in mind ?

**Comment by mpsOxygen** [comment]
If there any workaround for this? I'm trying to get cobbler up and running on a Fedora 30 server and the sync fails because it does not know to use systemctl instead of service.

**Comment by brejoc** [comment]
@mpsOxygen The easiest fix would probably be to build cobbler form the current master tree.

**Comment by jccleaver** [comment]
Using the service provides maximal compatibility across all RH variants, though. Would it not be easier to just keep that as a requirement?

**Comment by opoplawski** [comment]
I have no idea if /sbin/service will ever disappear, but I think cobbler should move to systemd at some point.  As for Fedora packages, I'm just going to explicitly require /sbin/service for now.  I'm not planning on updating Fedora 30 to cobbler 3.

**Comment by SchoolGuy** [comment]
Yes we will need systemctl asap, I agree. Ideally we could check with `service cobblerd status` and `systemctl status cobblerd` what is installed.

**Comment by hbokh** [comment]
In the meantime, on Debian 10:

```
root@cobbler:~# service cobblerd status
● cobblerd.service - Cobbler Helper Daemon
   Loaded: loaded (/lib/systemd/system/cobblerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-02-16 10:51:21 UTC; 12min ago
  Process: 12004 ExecStartPost=/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi (code=exited, status=0/SUCCESS)
 Main PID: 12003 (cobblerd)
    Tasks: 1 (limit: 2356)
   Memory: 30.8M
   CGroup: /system.slice/cobblerd.service
           └─12003 /usr/bin/python3 /usr/bin/cobblerd -F

Feb 16 10:51:21 cobbler systemd[1]: Starting Cobbler Helper Daemon...
Feb 16 10:51:21 cobbler systemd[1]: Started Cobbler Helper Daemon.

root@cobbler:~# service cobblerd condrestart
cobblerd: unrecognized service
```

https://github.com/cobbler/cobbler/blob/master/config/rotate/cobblerd_rotate#L13

**Comment by SchoolGuy** [comment]
I believe this is already fixed but we should check explicitly before the next release.
