### ISSUE TITLE
Cobbler 2.6.x repository signing keys have expired

### ISSUE THREAD

**Issue by http-418** [cobbler/cobbler#1689]
I'm not sure who maintains the official repository of apt packages for Cobbler 2.6 series, but the apt signing key has expired.  This makes it impossible to do an 'authenticated' install from the mirror: 

http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26

**Comment by jmaas** [comment]
i will take a look into that... unfortunately, after the weekend :(

**Comment by jmaas** [comment]
This issue has been fixed for the 2.8 release packages.
Cobbler 2.6 is now EOL.
