### ISSUE TITLE
[Question] Modernize Web GUI

### ISSUE THREAD

**Issue by kkirsche** [cobbler/cobbler#1691]
Hey Cobbler,

Was curious if there was any interest even in potentially doing some work on the web GUI to make it more modern using HTML5 instead of XHTML 1, CSS3, responsive design, etc. I believe that a more modern user experience I believe will make Cobbler an easier sell to less technical management teams where they will make some decisions based on the experience a web interface provides.

Before trying to prep something like this for git or potentially just do it for my own use, does this sound like something of potential interest?

**Comment by jmaas** [comment]
Yes this is something that would be great :).

But it also requires people to maintain it for a while after it has been merged/released. 
Would you be interested to maintain (at least) that part of Cobbler?

**Comment by kkirsche** [comment]
Hey @jmaas, certainly wouldn't be opposed to helping to maintain it, though I'd want to ensure that the frameworks and tools chosen are ones that in general the Cobbler team would be comfortable with. Generally speaking I think relying on only one person to maintain something as critical as the UI / UX is a risky decision if currently there are multiple team members who are comfortable with the existing stack.

With that said, does the team have any preferences for things like frameworks?

**Comment by jmaas** [comment]
There's not really a team comfortable with the current cobbler-web implementation :)

Or either we move to a more native Django app architecture, or we decouple even further by providing a REST api and use eg. Angular for the frontend. I'm open for any suggestions!

**Comment by opoplawski** [comment]
Something needs to be done, as the current UI won't work with Fedora 25, see issue #1717

**Comment by kkirsche** [comment]
Personally I'm more comfortable with the concept of APIs as it would allow better modularizarion and would give a separation of concerns. It would also allow for an API that is also used by the UI giving end users the ability to leverage it for their own needs.

In terms of front end frameworks, I'd be more a fan of using React or Vue as they are closer to native JavaScript than Typescript is which would allow more users to contribute. Typescript my concern would be that it requires more overhead to learn than JSX or vanilla JavaScript. I'm fine with either if there is a preference.

**Comment by Ed-0x1b** [comment]
just my 2¢

1. the choice of front end framework (plain JavaScript is my preference btw) should be made with an eye to deployments. If using JS, a deployment out to desktops with Electron is an option as would a deployment toward Android and iOS devices with Ionic/Phonegap.
2. API +1
3. Also, I think Cobbler front end development should aim at the most potential developers - JS has an easy on ramp for new contributors.

**Finally - big thanks to all the Cobbler devs**

**Comment by alanoe** [comment]
Django (server-side) + JS + JQuery seems ok to me. What do we gain in changing that? Sincerely, I do not understand why invest effort in changing Cobbler web UI frameworks unless there is a very good reason for it, specially considering that we have few developers. 

Cobbler biggest TODOs currently IMHO are improving the plugin engine, moving specific features (eg puppet integration) from core code to plugins and releasing Cobbler 3. We should focus.

OP> Something needs to be done, as the current UI won't work with Fedora 25

We just need to update UI code to work with newer Django versions, a simple patch should solve it.

**Comment by kkirsche** [comment]
That's understandable @alanoe though I wouldn't be willing personally to develop a major change based primarily on JQuery. I wouldn't mind including it for a framework like bootstrap, but that's not something I would be willing to work on. If that's the desire, I understand the reasoning, just wouldn't be something I would be willing to contribute.

**Comment by almusaddar** [comment]
How about use something like https://almsaeedstudio.com/themes/AdminLTE/index2.html with Cobbler v3

**Comment by kkirsche** [comment]
@almusaddar I wouldn't recommend AdminLTE for this use case due to it's license:

```
AdminLTE is an open source project by Almsaeed Studio that is licensed under MIT. Almsaeed Studio reserves the right to change the license of future releases.
```

With a license that can change, I'd argue the team would end up in a slight legal gray area if the upstream project goes away.

**Comment by heroin-moose** [comment]
Bump.

**Comment by SchoolGuy** [comment]
Future discussions about the web-ui and web-ux should be done now in: #2342
