### ISSUE TITLE
cobbler_web expired session before login

### ISSUE THREAD

**Issue by piemouce** [cobbler/cobbler#1692]
Hi,

using Cobbler 2.6.6 when I try to access to the webpage, the following message is displayed below the login/pwd fields :
Sorry, either you need to login or your session expired.

If I try to login, the same message appears and if I put a wrong pwd I have a correct message saying :
Login failed, please try again

I have checked the date on all machines (It is ok) and nothing special in :
**/var/log/cobbler/cobbler.log**
_\- Wrong login_
Wed Sep 14 15:14:27 2016 - INFO | authenticate; ['toto', False]
Wed Sep 14 15:14:27 2016 - INFO | Exception occured: <class 'cobbler.cexceptions.CX'>
Wed Sep 14 15:14:27 2016 - INFO | Exception value: 'login failed (toto)'
Wed Sep 14 15:14:27 2016 - INFO | Exception Info:
  File "/usr/lib/python2.6/site-packages/cobbler/utils.py", line 126, in die
    raise CX(msg)
- _correct login_
  Wed Sep 14 15:24:10 2016 - INFO | authenticate; ['cobbler', True]

Trying to check a solution on the web, I found nothing really matching with my case but verifying the code, this problem seems link to an invalid token session but no idea how I can continue to investigate...

Thanks

**Comment by furbaez** [comment]
check your file system maybe /var needs more space

**Comment by SchoolGuy** [comment]
We don't maintain the 2.6.x version anymore actively. Please consider upgrading to the latest version to get more help from us.

**Comment by wadewang389** [comment]
ensure your /var/ directoy have more space
