### ISSUE TITLE
CentOS 6.7 kickstart fails when including 'Base' repo

### ISSUE THREAD

**Issue by YuJunping** [cobbler/cobbler#1698]
A fatal error occurred when installing the <rpm.hdr object at 0x4981cd0> package. This could indicate errors when reading the installation media. Installation cannot continue
Somebody out there experiencing the same ?

**Comment by opoplawski** [comment]
You are really going to need to give a lot more context.  Also, discussion like this really belongs on the mailling list until the determination is made that there is an issue with cobbler itself.

**Comment by YuJunping** [comment]
Error Installing Package
A fatal error occurred when installing the  \<rpm.hdr object at 0x7f9cf5f4f9b0\>  package.  This could indicate errors when reading the installation media. Installation cannot continue.

                                       Exit installer

[root@cobbler ~]# cobbler profile report
Name                           : CentOS-6.7-x86_64
TFTP Boot Files                : {}
Comment                        : 
DHCP Tag                       : default
Distribution                   : CentOS-6.7-x86_64
Enable gPXE?                   : 0
Enable PXE Menu?               : 1
Fetchable Files                : {}
Kernel Options                 : {'biosdevname': '0', 'net.ifnames': '0'}
Kernel Options (Post Install)  : {}
Kickstart                      : /var/lib/cobbler/kickstarts/Centos-6.7-x86_64.ks
Kickstart Metadata             : {}
Management Classes             : []
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Owners                         : ['admin']
Parent Profile                 : 
Internal proxy                 : 
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
**Repos                          : ['Centos-6-x86_64-Base']**
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : 1
Virt Bridge                    : xenbr0
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : 5
Virt Path                      : 
Virt RAM (MB)                  : 512
Virt Type                      : kvm

If the cobbler profile report  **Repos: []**, there is no problem

**Comment by jmaas** [comment]
Probably a corruption in your repo. Please provide more information on the mailinglist.
Thanks!
