### ISSUE TITLE
Add metadata parameter for zone in manage_bind.py module

### ISSUE THREAD

**Issue by cinglese** [cobbler/cobbler#1700]
[https://github.com/cobbler/cobbler/blob/master/cobbler/modules/manage_bind.py](https://github.com/cobbler/cobbler/blob/master/cobbler/modules/manage_bind.py)

When using multiple zones, it would be helpful to have an additional metadata parameter to use titled "zonename" which uses the zone variable.

Lines 499-506 become:
for (zone, hosts) in forward.iteritems():
            metadata = {
                'cobbler_server': cobbler_server,
                'serial': serial,
                **'zonename': zone,**
                'zonetype': 'forward',
                'cname_record': '',
                'host_record': ''
            }

Lines 541-548 become:
for (zone, hosts) in reverse.iteritems():
            metadata = {
                'cobbler_server': cobbler_server,
                'serial': serial,
                **'zonename': zone,**
                'zonetype': 'reverse',
                'cname_record': '',
                'host_record': ''
            }

**Comment by jmaas** [comment]
This FR is available in the upcoming 2.8.1 release
Thanks for contributing!
