### ISSUE TITLE
Two systems have to get the same package versions at update

### ISSUE THREAD

**Issue by frankenstein91** [cobbler/cobbler#1701]
we have a test and prod system and it is needed that we patch the test systems 2 weeks before the prod systems. 
But on the same Cobbler server we have systems that need the latest version of the packages every day.

Can someone explain me how i can set up this?
Can you tell me if it is possible to "freeze" the cobbler repo for some systems only, but still make a reposync for other?

Thank you for your help

**Comment by jmaas** [comment]
It's a good question, but this is not the right place for it. Please join the mailinglist! You might get a nice solution from the Cobbler community.

Having said that, Cobbler really doesn't provide any means to freeze repos. Personally i use snapshots on a ZFS based system to do just that.
