### ISSUE TITLE
GUI missing option for Management Classes

### ISSUE THREAD

**Issue by MichaelTiernan** [cobbler/cobbler#1702]
Using the cli I can set a systems "Management Classes" to "<<inherit>>" but the gui doesn't allow/provide that option.

**Comment by jmaas** [comment]
Can you please explain why you want to use <> as a value?
Sounds like an easy fix which might get into 2.8.

**Comment by MichaelTiernan** [comment]
Seems that there's an error in my message.... Sorry...
It should be the value of `<<inherit>>`
Let's see if this makes it through this comment...

**Comment by jmaas** [comment]
Ok, that actually makes sense, also the drinking part! :)

**Comment by jmaas** [comment]
this was broken anyway.

```
diff --git a/cobbler/remote.py b/cobbler/remote.py
index 26950c6..3938e0b 100644
--- a/cobbler/remote.py
+++ b/cobbler/remote.py
@@ -541,11 +541,11 @@ class CobblerXMLRPCInterface:
     def get_image(self,name,flatten=False,token=None,**rest):
         return self.get_item("image",name,flatten=flatten)
     def get_mgmtclass(self,name,flatten=False,token=None,**rest):
-        return self.get_mgmtclass("mgmtclass",name,flatten=flatten)
+        return self.get_item("mgmtclass",name,flatten=flatten)
     def get_package(self,name,flatten=False,token=None,**rest):
-        return self.get_package("package",name,flatten=flatten)
+        return self.get_item("package",name,flatten=flatten)
     def get_file(self,name,flatten=False,token=None,**rest):
-        return self.get_file("file",name,flatten=flatten)
+        return self.get_item("file",name,flatten=flatten)
 
     def get_items(self, what):
         """
```

**Comment by jmaas** [comment]
above fix has been pushed to release28.

testing shows that when you dont specifiy a mgmt class it gets inherited from the parent object.
so i dont think this is really an issue

**Comment by jmaas** [comment]
i'm not sure if adding <<inherit>> explicitly to the webui brings any benefit, perhaps some more consistency. i'm moving this into the backlog and marking this as a usability issue

**Comment by MichaelTiernan** [comment]
Just for the record, other pulldowns in the GUI _do_ provide an option for "`<<inherit>>`" as a setting.

**Comment by opoplawski** [comment]
This doesn't appear to be working for me with 2.8.1 and a sub-profile:

````
# cobbler profile report --name=sl-7-x86_64-laptop
Management Classes             : ['laptop']
Parent Profile                 : sl-7-x86_64
# cobbler system report --name=akialoa 
Management Classes             : []
Profile                        : sl-7-x86_64-laptop
````

**Comment by SchoolGuy** [comment]
The webinterface will be removed with 3.3.0 and thus I will close this issue. A new interface will be created when the Team has time and resources for it.
