### ISSUE TITLE
Ubuntu 14.04 Repository Key Expired

### ISSUE THREAD

**Issue by jwbrown77** [cobbler/cobbler#1703]
Hello,

I am attempting to install Cobbler 2.6 from the Ubuntu 14.04 repository listed here:

http://cobbler.github.io/downloads/2.6.x.html

Here are some details on the system I am installing on:

```
uname -a
Linux provisioning-vm 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/issue
Ubuntu 14.04.5 LTS \n \l
```

I import the repository key and add the repository as follows:

```
wget -qO - http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/xUbuntu_14.04/Release.key | sudo apt-key add -
sudo add-apt-repository "deb http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/xUbuntu_14.04/ ./"
```

However, apt-get update reports that the key is expired:

```
apt-get update
...
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
Fetched 481 B in 7s (65 B/s)
Reading package lists... Done
W: GPG error: http://download.opensuse.org ./ Release: The following signatures were invalid: KEYEXPIRED 1467802578
```

apt-key reports:

```
pub   2048R/2589A1ED 2014-04-28 [expired: 2016-07-06] <------
uid                  home:libertas-ict OBS Project <home:libertas-ict@build.opensuse.org>
```

And attempting to install reports:

```
apt-get install cobbler
...
0 upgraded, 207 newly installed, 0 to remove and 0 not upgraded.
Need to get 108 MB of archives.
After this operation, 316 MB of additional disk space will be used.
Do you want to continue? [Y/n]
WARNING: The following packages cannot be authenticated!
  cobbler
Install these packages without verification? [y/N]
E: Some packages could not be authenticated
```

I did find an Openstack code review where this is also mentioned:

https://review.openstack.org/#/c/349662/

It can be worked around by adding the "DEBIAN_FRONTEND=noninteractive" environment variable, but it would be ideal to fix the key.

Thanks in advance.

**Comment by jmaas** [comment]
I'm currently in the process of looking for alternatives to OBS.
This is on the wishlist for Cobbler 2.8.0, please have patience :)

**Comment by jwbrown77** [comment]
@jmaas - thanks - for now it's easy enough to work around in my environment.  But figured you'd want to know. 😄

**Comment by jmaas** [comment]
2.8.0 packages are now available on OBS, issues with the key is fixed.
