### ISSUE TITLE
release26 source installation problem at Ubuntu

### ISSUE THREAD

**Issue by SatoshiStr** [cobbler/cobbler#1707]
Hi.
I installed cobbler release26 with source code at ubuntu sever 14.04, and Apache Sever doesn't sever for URL:80/cobbler.
To fix it, I copy /etc/apache2/conf-available/cobbler.conf to /etc/apache2/conf-enabled/cobbler.conf.
Is it a problem that should be fixed in source code?

**Comment by jmaas** [comment]
Hi, not really i suppose. Normally enabling a new vhost is left to the administrator or it could be done by the package. I'll leave this issue open to review the documentation and improve on that.

Thanks for reporting!

**Comment by jmaas** [comment]
Checked documentation for this, and i found:
http://cobbler.github.io/manuals/2.8.0/2/3_-_Installing_From_Source.html

it does indeed not mention to enable the vhost.
should be documented.

**Comment by jmaas** [comment]
Change commited to the 2.6 and 2.8 docs.
Will be available with the next website update as part of 2.8.2 release.
