### ISSUE TITLE
UEFI PXE

### ISSUE THREAD

**Issue by brockbackups** [cobbler/cobbler#1712]
I have searched and searched and can not find anything about how to setup Cobbler to allow UEFI systems to boot via PXE with CentOS 7. Anyone have any suggestions?

**Comment by jmaas** [comment]
Install Cobbler, get the appropiate loaders ("cobbler get-loaders"), import a distro ("cobbler import"), define a profile/system ("cobbler system add") and run sync ("cobbler sync"). then pxe boot system and see what happens. ofcourse a gazillion things can go wrong. This issue tracker is for bugs, not user questions. Please join the mailing list if you want help! Thanks :)

**Comment by shake** [comment]
I use the cobbler 2.8 ,uefi test ,work perfect. if you test in vm, you need to consider

https://redmine.pfsense.org/issues/5046

you also can modify the efi template, make it perfect.

# cat /etc/cobbler/pxe/efidefault.template 
default=0
timeout=10
title local
        quit
$grub_menu_items
