### ISSUE TITLE
Management Classes - Parameters

### ISSUE THREAD

**Issue by haeac** [cobbler/cobbler#1716]
### Issue / Question

Trying to use the Parameters / Variables in Management classes but they don't seem to be included when I query the system using dumpvars:

`cobbler system dumpvars --name=test-01-v`

I'm setting the values as follows:

`var1 = "value1" var2="value2"`

These don't show up in the mgmt_parameters like the kernel parameters etc,. Is there a special way to query the parameters in the Kickstart template? Apologies but the documentation is not very clear on this.
### Version Report

OS: CentOS Linux release 7.2.1511 (Core)
Kernel version: 3.10.0-327.36.2.el7.x86_64
Cobbler version: 2.6.11

**Comment by opoplawski** [comment]
yeah, they seem pretty useless since they do not appear to be passed to the kickstart template in any way.  I only see the list of management classes for the system.

cobbler 2.8.2

**Comment by SchoolGuy** [comment]
Since this question was answered I will close this one. If there is more information needed please reopen!
