### ISSUE TITLE
Creating ESX systems, missing boot.cfg

### ISSUE THREAD

**Issue by nazunalika** [cobbler/cobbler#1718]
Created esxi 5.5 distro and profile in cobbler. Creating systems by choosing it in the menu work without an issue. However, when I create a system, I always get met with this error:

```
Configuration error while parsing /boot.cfg
Fatal error: 15 (not found)
```

However, I looked between both the pxelinux.cfg/default and the one of the system and I noticed something odd. 

```
LABEL esxi55-x86_64
        kernel /images/esxi55-x86_64/mboot.c32
        MENU LABEL esxi55-x86_64
        ipappend 2
        append -c /images/esxi55-x86_64/cobbler-boot.cfg
```

In the system...

```
default linux
prompt 0
timeout 1
label linux
        kernel /images/esxi55-x86_64/mboot.c32
        ipappend 2
        append /images/esxi55-x86_64/vmkboot.gz BOOTIF=01-52-54-00-81-4a-44 ks=http://10.100.0.1/cblr/svc/op/ks/system/generic  lang=  text  --- /images/esxi55-x86_64/vmkernel.gz --- /images/esxi55-x86_64/sys.vgz --- /images/esxi55-x86_64/cim.vgz --- /images/esxi55-x86_64/ienviron.vgz --- /images/esxi55-x86_64/install.vgz
```

The piece that's missing here is this at the start of the append line: `-c /images/esxi55-x86_64/cobbler-boot.cfg`

I can see in /etc/cobbler/pxe/pxesystem_esxi.template that it would make sense why this is missing. I can put the -c $img_path/cobbler-boot.cfg in here just fine...

```
default linux
prompt 0
timeout 1
label linux
        kernel $kernel_path
        ipappend 2
        append $img_path/vmkboot.gz $append_line --- $img_path/vmkernel.gz --- $img_path/sys.vgz --- $img_path/cim.vgz --- $img_path/ienviron.vgz --- $img_path/install.vgz
```

Is this a bug or is this intended? If it's intended, why?

**Comment by jmaas** [comment]
probably a bug! thanks for reporting, i will check it in the near future.

**Comment by nishiokay** [comment]
@nazunalika @jmaas I have PRed this issue and it was already merged.
https://github.com/cobbler/cobbler/pull/1705
Could you use Cobbler 2.8.0 release?

**Comment by jmaas** [comment]
Love to hear if the problem in Cobbler 2.8.0 is really solved
