### ISSUE TITLE
Wrong gateway settings auto generated by cobbler DHCP management settings

### ISSUE THREAD

**Issue by hanyunfan** [cobbler/cobbler#1719]
I am using cobbler 2.6.11 and dnsmasq as both DNS and DHCP server, all there installed on same system 10.10.0.2, but the gateway is 10.10.0.1. 

I have set the manage DHCP to enable in cobbler settings file. and in the /etc/cobbler/dhcp.template file
I have the line: 
option routers             10.10.0.1;
But every time when I do cobbler sync, it will automatically change the /etc/dnsmasq.conf back to the wrong one:
dhcp-option=3,10.10.0.2 
I was expecting:
dhcp-option=3,10.10.0.1

I was thinking Cobbler is using the next_server in your code to set the default gateway from DHCP server, Could someone help to confirm and change the code.

Thanks in advance,
Frank

**Comment by jmaas** [comment]
dhcp.template and dnsmasq.conf have no relation.

dhcp.template is for ISC DHCPD
dnsmasq.template is for dnsmasq.

$next_server is the IP of the cobbler server, not the gateway.
i never used dnsmasq with cobbler, does $gateway not work?

**Comment by jmaas** [comment]
Closing this issue as it seems like an user error. If you still think this is a bug, please provide some more  information here and i will re-open.
