### ISSUE TITLE
Cannot import Fedora 25 (i386)

### ISSUE THREAD

**Issue by AlpNek** [cobbler/cobbler#1724]
$ cobbler import --path=/media/Local/Repo/Fedora25-i386 --arch=i386 --name=Fedora25-i386 --breed=redhat --os-version=rhel7
task started: 2016-11-29_124845_import
task started (id=Media import, time=Tue Nov 29 12:48:45 2016)
Found a candidate signature: breed=redhat, version=rhel7
No signature matched in /var/www/cobbler/ks_mirror/Fedora25-i386
!!! TASK FAILED !!!

The DVD iso that I downloaded does not appear to have any sig in it. Is it possible to import without a sig? Can it be ignored?

Thanks,
Ken

**Comment by AlpNek** [comment]
Ok, got it working (after trolling through several forums...). Here is what I did:

I added a new os-version "fedora25" under breed "redhat" in /var/lib/cobbler/distro_signatures.json, then restarted cobblerd and then imported as:
$ cobbler import --path=/media/Local/Repo/Fedora25-i386 --arch=i386 --name=Fedora25-i386 --breed=redhat --os-version=fedora25

Cheers.

**Comment by jmaas** [comment]
you could also have upgraded to 2.8.0 ;)

**Comment by AlpNek** [comment]
Ah ok ... thanks! :)
