### ISSUE TITLE
Download URLs

### ISSUE THREAD

**Issue by omahonyb** [cobbler/cobbler#1728]
Just an FYI a good few oif the download links [eg CentOS & RHEL] dont work from the page. Pointed at the wrong path. They are still available if you browse the repos though

**Comment by almusaddar** [comment]
Yes, http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler28/CentOS_CentOS-7/

**Comment by omahonyb** [comment]
I know, I was able to get it. Was just a heads up....

**Comment by jmaas** [comment]
Thanks, fixed!
