### ISSUE TITLE
CentOS 7.3, anaconda, sample.ks

### ISSUE THREAD

**Issue by jjbailey** [cobbler/cobbler#1737]
Anaconda bombs out when testing sample.ks.  The complaint is %end is missing in three places.  These changes fix it.

$ diff -c sample.ks.orig sample.ks
*** sample.ks.orig      Sat Jan 23 04:48:41 2016
--- sample.ks   Fri Dec 23 19:54:48 2016
***************
*** 46,55 ****
--- 46,57 ----
  $SNIPPET('pre_install_network_config')
  # Enable installation monitoring
  $SNIPPET('pre_anamon')
+ %end
  
  %packages
  $SNIPPET('func_install_if_enabled')
  $SNIPPET('puppet_install_if_enabled')
+ %end
  
  %post --nochroot
  $SNIPPET('log_ks_post_nochroot')
***************
*** 73,75 ****
--- 75,78 ----
  # Start final steps
  $SNIPPET('kickstart_done')
  # End final steps
+ %end

**Comment by opoplawski** [comment]
Don't use sample.ks, use sample_end.ks

**Comment by jjbailey** [comment]
Ok, I see that.  Thanks.

Jack

**Comment by jmaas** [comment]
I suppose it's time to remove sample.ks from the tree.

**Comment by jmaas** [comment]
Master branch:
Renamed sample.ks to sample_legacy.ks documented that this file should be used for EL4, 5 and Fedora < 8. Renamed sample_end.ks to sample.ks

For 2.8.x the kickstart files will have a warning header so that users wont make that mistake again, hopefully ;)
