### ISSUE TITLE
ESXi 6.5 Signature

### ISSUE THREAD

**Issue by grdavies** [cobbler/cobbler#1742]
Hi,

I've been trying to add an additional signature for ESXi 6.5 (with the view to pulling may changes once locally tested), but seem to have run into a snag...

It looks like the format of s.v00 has changed in 6.5 - when I manually uncompress the file and cat it I get garbage instead of readable text like in previous releases.

```
[~]# /usr/bin/file s.v00.5.5
s.v00.5.5: tar archive
[~]# /usr/bin/file s.v00.6.5
s.v00.6.5: XZ compressed data
```

Thanks in advance for any help.

Ross

**Comment by Sniper677** [comment]
As your file is compressed, you have to run '**xz -d s.v00.6.5**' to get it uncompressed.

**Comment by jmaas** [comment]
6.5 signature request in #1757
