### ISSUE TITLE
Cobbler ubuntu16.04 DEBs are empty

### ISSUE THREAD

**Issue by wojtas911** [cobbler/cobbler#1744]
Hi,
wget http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler28/xUbuntu_16.04/all/cobbler_2.8.0-1_all.deb

root@cobbler:/tmp# dpkg -X cobbler_2.8.0-1_all.deb /tmp/deb
./
./usr/
./usr/share/
./usr/share/doc/
./usr/share/doc/cobbler/
./usr/share/doc/cobbler/changelog.Debian.gz
root@cobbler:/tmp# 

That's all folks.

**Comment by wojtas911** [comment]
I tough that could be my mistake, so i download the deb for ubuntu14.10 
wget http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/xUbuntu_14.10/all/cobbler_2.6.11-1_all.deb
make test
dpkg -X cobbler_2.6.11-1_all.deb /tmp/deb2|wc -l
640

Thanks

**Comment by haad** [comment]
There are multiple issues with cobbler28 on 16.04 to get it installed you have to install old package (python-support) which no longer exist in 16.04. I have created PR for that https://github.com/cobbler/cobbler/pull/1749

**Comment by jmaas** [comment]
this is a dupe for #1736 

progress will be tracked here, #1736 fill be closed.

**Comment by haad** [comment]
@jmaas last comment is confusing #1736 is closed already and this one is the only one left open.

**Comment by haad** [comment]
Any update here I would love to update to cobbler-2.8. If you need some help let me know.

**Comment by jmaas** [comment]
yes, i could use some help :)

haven't got the time to look at this one... but i consider it a blocker issue for 2.8.1.

**Comment by haad** [comment]
@jmass do you know how I can build cobbler deb files ? what is the process to build them from source ? I was not able to fine documentation/script in official repository.

**Comment by cao** [comment]
@jmaas: Is there anything that can be done to speed up the process of getting this fixed? We are happy to help out here to get this fixed and 2.8.1 released. It blocks us from rolling out cobbler, as we do not want to roll out cobbler 2.6 at this point anymore.

The issue appears to be fixed in master, though there seems to be a significant divergence between the release28 and master branch to cherry-pick the specific commits that fix the issue. Unfortunately, it is not clear how to build the Debian packages from source either, as there does not seem to exist any documentation on it? The Makefile does not help either, and the typical Debian-way fails too.

**Comment by haad** [comment]
Yeah my guess is that deb building is done on external service where is no access to scripts anymore. Maybe if we develop new sets of controls scripts in side repo. We can switch it to new way, but it looks like old one is lost.

**Comment by jmaas** [comment]
the packages were indeed built on the openSUSE Build Service (https://build.opensuse.org). Somehow package building started failing for Debian/Ubuntu. I can't seem to find out why....

If someone has the skills to contribute the necessary files inside the repo and create a `make debs` target in the Makefile that would be awesome. I can then consider hosting packages on packagecloud.io instead of the openSUSE Build Service.

I was eventually able to build packages from the source tree by using `debuild`

**Comment by haad** [comment]
Can you share original files ? just to stay compatible with them

**Comment by cao** [comment]
@jmaas How do you want to handle it?

master evolved quite a bit over release28, would you prefer a pull request on master or release28? Are there plans to prepare release28 by picking some commits from master for a 2.8.1 release?

master would generally be the more appropriate target, but it would also be a lot of work to backport the fix to release28 branch for a 2.8.1 release. A fix to release28 would allow for a faster 2.8.1 release, but would require a similar amount of work to port it to master.

**Comment by jmaas** [comment]
@haad 
original files for cobbler 2.6.11 (which worked) https://build.opensuse.org/package/show/home:libertas-ict:cobbler26/cobbler-2.6.11

for cobbler 2.8.0: https://build.opensuse.org/package/show/home:libertas-ict:cobbler28/cobbler-2.8.0

@cao targetting master seems like the best way forward, even though we want to get 2.8.1 asap. i think backporting from a working master should not be too difficult :)

**Comment by sgurumurthy** [comment]
I am  looking for a cobbler package working with Ubuntu 16.04.  The 2.8.0-1 package fails. Does anyboyd know the fix for this issue

**Comment by sgurumurthy** [comment]
@jmaas, any help is much appreciated

**Comment by Gargravarr2112** [comment]
Just to add, the Debian 7.0 and 8.0 packages are the same. Something seems to have gone very wrong with the .deb packaging system. I'm using 2.6 for now. Can you remove the 2.8 packages and post up a notice that 2.8 is not yet available for Debian-based distros?

**Comment by sgurumurthy** [comment]
@Gargravarr2112 , are using 2.6 with Xenial? Does it work in Ubuntu 16.04?
Can you please give me the link to the working package?
I did not find 2.6 working with Ubuntu 16.04

**Comment by Gargravarr2112** [comment]
@sgurumurthy sorry no, I'm using 2.6 on Devuan, which is Debian 7.0/Jessie based. You could download the source tarball and use checkinstall to build yourself a .deb.

**Comment by sgurumurthy** [comment]
@Gargravarr2112 , Can u pls point me to the location of the source tar ball?

**Comment by Gargravarr2112** [comment]
@sgurumurthy actually I misread, you could get the .deb from here: http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/xUbuntu_14.04/all/cobbler_2.6.11-1_all.deb Although it says 14.04, it will probably work on Xenial.

**Comment by sgurumurthy** [comment]
@Gargravarr2112 , this package does not work in ubuntu 16.04. I am struggling to to find a working cobbler package or source with ubuntu 16.04

**Comment by sgurumurthy** [comment]
@Gargravarr2112 , I got the trusty cobbler-2.6.11-1 debian working with Ubuntu 16.04. Needed
 some tweaks

**Comment by jmaas** [comment]
We dont have the resources to work on packaging.
Sorry!
