### ISSUE TITLE
Cobbler v2.8 iPXE/gPXE Internal Server Error

### ISSUE THREAD

**Issue by dbstephens** [cobbler/cobbler#1746]
I have a specific requirement to utilize iPXE/gPXE for provisioning and have my DHCP server referring iPXE to the following URL, per the documentation --

http://<cobbler server ip>/cblr/svc/op/gpxe/system/foo

Unfortunately, this URL is returning an Apache 500 Internal Server Error, rather than providing the correct template for iPXE continue to boot from. My Apache error_log contains the following when the host attempts to connect to the above URL --

~~
[Wed Jan 18 10:40:45.885309 2017] [:error] [pid 10824] [remote ip:108] mod_wsgi (pid=10824): Exception occurred processing WSGI script '/var/www/cobbler/svc/services.py'.
[Wed Jan 18 10:40:45.885475 2017] [:error] [pid 10824] [remote ip:108] Traceback (most recent call last):
[Wed Jan 18 10:40:45.885527 2017] [:error] [pid 10824] [remote ip:108]   File "/var/www/cobbler/svc/services.py", line 90, in application
[Wed Jan 18 10:40:45.885612 2017] [:error] [pid 10824] [remote ip:108]     content = func( **form )
[Wed Jan 18 10:40:45.885641 2017] [:error] [pid 10824] [remote ip:108]   File "/usr/lib/python2.7/site-packages/cobbler/services.py", line 88, in gpxe
[Wed Jan 18 10:40:45.885687 2017] [:error] [pid 10824] [remote ip:108]     data = self.remote.generate_gpxe(profile, system)
[Wed Jan 18 10:40:45.885703 2017] [:error] [pid 10824] [remote ip:108]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
[Wed Jan 18 10:40:45.885760 2017] [:error] [pid 10824] [remote ip:108]     return self.__send(self.__name, args)
[Wed Jan 18 10:40:45.885774 2017] [:error] [pid 10824] [remote ip:108]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
[Wed Jan 18 10:40:45.885802 2017] [:error] [pid 10824] [remote ip:108]     verbose=self.__verbose
[Wed Jan 18 10:40:45.885816 2017] [:error] [pid 10824] [remote ip:108]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
[Wed Jan 18 10:40:45.885844 2017] [:error] [pid 10824] [remote ip:108]     return self.single_request(host, handler, request_body, verbose)
[Wed Jan 18 10:40:45.885865 2017] [:error] [pid 10824] [remote ip:108]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1306, in single_request
[Wed Jan 18 10:40:45.885892 2017] [:error] [pid 10824] [remote ip:108]     return self.parse_response(response)
[Wed Jan 18 10:40:45.885906 2017] [:error] [pid 10824] [remote ip:108]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1482, in parse_response
[Wed Jan 18 10:40:45.885932 2017] [:error] [pid 10824] [remote ip:108]     return u.close()
[Wed Jan 18 10:40:45.885952 2017] [:error] [pid 10824] [remote ip:108]   File "/usr/lib64/python2.7/xmlrpclib.py", line 794, in close
[Wed Jan 18 10:40:45.885981 2017] [:error] [pid 10824] [remote ip:108]     raise Fault(**self._stack[0])
[Wed Jan 18 10:40:45.886048 2017] [:error] [pid 10824] [remote ip:108] Fault: <Fault 1: "<type 'exceptions.AttributeError'>:'NoneType' object has no attribute 'get_conceptual_parent'">
~~

My Cobbler instance is running on CentOS 7 and was installed using the packages provided in your repositories.

Cobbler 2.8.0
  source: ?, ?
  build time: Thu Nov 24 20:08:36 2016

Thanks,
Daniel

**Comment by jmaas** [comment]
Did this work for you on 2.6.x ??

**Comment by hbokh** [comment]
FYI Cobbler 2.6.11 throws up a similar error:

```
Mon Mar  6 10:49:43 2017 - INFO | Exception occured: <type 'exceptions.AttributeError'>
Mon Mar  6 10:49:43 2017 - INFO | Exception value: 'NoneType' object has no attribute 'get_conceptual_parent'
Mon Mar  6 10:49:43 2017 - INFO | Exception Info:
  File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 2080, in _dispatch
    return method_handle(*params)
   File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 1920, in sync
    return self.api.sync()
   File "/usr/lib/python2.7/dist-packages/cobbler/api.py", line 779, in sync
    return sync.run()
   File "/usr/lib/python2.7/dist-packages/cobbler/action_sync.py", line 132, in run
    self.write_dhcp()
   File "/usr/lib/python2.7/dist-packages/cobbler/action_sync.py", line 218, in write_dhcp
    self.dhcp.write_dhcp_file()
   File "/usr/lib/python2.7/dist-packages/cobbler/modules/manage_dnsmasq.py", line 112, in write_dhcp_file
    distro  = profile.get_conceptual_parent()
```

**Comment by leader716** [comment]
I had a similar issue with the nopxe command, http:///cblr/svc/op/nopxe/system/foo. I found that a single system was still linked to a deleted profile. Once I assigned a good profile to that system, I no longer received a 500.

**Comment by jmaas** [comment]
i think it has to do with system object without a proper parent object (profile / image).
on 2.8.1 this feature seems to work.

```
[root@cobbler ~]# cobbler version
Cobbler 2.8.1
  source: 4499f7e, Sun Sep 10 16:43:02 2017 +0200
  build time: Sat Sep 16 08:14:17 2017
[root@cobbler ~]# curl -k https://192.168.124.10/cblr/svc/op/gpxe/system/duh
#!gpxe
kernel http://192.168.124.10:80/cobbler/images/fedora26-x86_64/vmlinuz
imgargs vmlinuz  ksdevice=bootif lang=  repo=http://192.168.124.10/cblr/links/fedora26-x86_64 kssendmac text  ks=http://192.168.124.10/cblr/svc/op/ks/system/duh
initrd http://192.168.124.10:80/cobbler/images/fedora26-x86_64/initrd.img
boot
[root@cobbler ~]# 
``` 
 i will close this issue, please contact me if you have more information pointing to a bug in cobbler.
thanks!
