### ISSUE TITLE
Autodiscovery fails

### ISSUE THREAD

**Issue by vatine** [cobbler/cobbler#1753]
When using /cblt/svc/op/find_autobuild and provided MAC address as the method for providing kickstart files, cobbler fails to provide a kickstart file and instead just gives an error.

This is down to the kickstart file being fetched by first finding the relevant system and doing (essentially) a recursive fetch and serving the resulting document. Unfortunately, the constructed URL starts "http//" rather than "http://".

**Comment by jmaas** [comment]
Fixed in master and release28 branch. Thanks again!
