### ISSUE TITLE
Add support for syslinux 6 for PXE and buildiso

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1756]

**Comment by jmaas** [comment]
Docs: https://wiki.archlinux.org/index.php/syslinux

**Comment by jmaas** [comment]
syslinux6 support added to buildiso, work on BIOS. not yet for UEFI

**Comment by jmaas** [comment]
added support to the pxe code for syslinux6

**Comment by ollelindberg** [comment]
The lack of UEFI support is starting to show. We always switch from UEFI to Legacy when deploying from Cobbler but today this failed on a new Dell Latitude E7490. Turns out that model (or perhaps BIOS version) don't support booting from internal devices (HD, SSD, NVMe) in Legacy mode.

**Comment by hagaluly** [comment]
there is support in UEFI! from ver 2.8 >
