### ISSUE TITLE
try to use -standalone option but got exception: genisoimage: Permission denied. Unable to open disc image file '/root/generated.iso'

### ISSUE THREAD

**Issue by romanglz** [cobbler/cobbler#1759]
hi , 
im try to use out modified ubuntu iso to do this i need to use option -stadalone (to prevent from cobbler install ubuntu from official site)
the command is: 
cobbler buildiso --standalone --distro=Axxana_3.13.x_22-x86_64
using cobbler version: 
Cobbler 2.6.10
  source: ?, ?
  build time: Thu Oct  1 17:05:44 2015

the exception that i got is: 
Using OEM_C000.DEB;1 for  /var/cache/cobbler/buildiso/pool/main/u/ubiquity/oem-config_2.18.8.9_all.deb (oem-config-debconf_2.18.8.9_all.deb)
Using WIREL000 for  /var/cache/cobbler/buildiso/pool/main/w/wireless-tools (wireless-regdb)
Using LIBJS000.DEB;1 for  /var/cache/cobbler/buildiso/pool/main/y/yui3/libjs-yui3-min_3.5.1-1ubuntu3_all.deb (libjs-yui3-full_3.5.1-1ubuntu3_all.deb)
Using LIBJS001.DEB;1 for  /var/cache/cobbler/buildiso/pool/main/y/yui3/libjs-yui3-full_3.5.1-1ubuntu3_all.deb (libjs-yui3-common_3.5.1-1ubuntu3_all.deb)
Using UBUNT000.SEE;1 for  /var/cache/cobbler/buildiso/preseed/ubuntu-server.seed (ubuntu-server-minimalvm.seed)
Using UBUNT001.SEE;1 for  /var/cache/cobbler/buildiso/preseed/ubuntu-server-minimalvm.seed (ubuntu-server-minimal.seed)
genisoimage: Permission denied. Unable to open disc image file '/root/generated.iso'.

Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'mkisofs failed'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/utils.py", line 126, in die
    raise CX(msg)

Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'mkisofs failed'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 88, in run
    c = self._run(self)
   File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 158, in runner
    self.logger
   File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 1043, in build_iso
    iso=iso, profiles=profiles, systems=systems, buildisodir=buildisodir, distro=distro, standalone=standalone, source=source, exclude_dns=exclude_dns, mkisofs_opts=mkisofs_opts
   File "/usr/lib/python2.7/site-packages/cobbler/action_buildiso.py", line 589, in run
    utils.die(self.logger,"mkisofs failed")
   File "/usr/lib/python2.7/site-packages/cobbler/utils.py", line 134, in die
    raise CX(msg)

!!! TASK FAILED !!!

any ideas ?

**Comment by jmaas** [comment]
you need mkisofs/genisoimage installed.

Can't reproduce! If this still persists please let me know and provide more information about your environment.
