### ISSUE TITLE
preseed debian: WARNING **: mirror does not support the specified release (jessie)

### ISSUE THREAD

**Issue by julenl** [cobbler/cobbler#1771]
Cobbler 2.8.0 on CentOS 7
Provisioning a Debian 8 machine with the _sample.seed_ file gets stuck while configuring apt, with the message :

```
[!!] Configure the package manager
Bad archive mirror
An error has been detected while trying to use the specified Debian archive mirror.
...
```

The TTY4 says:
```
choose-mirror[5124]: wget -q http://10.0.0.2/cblr/links/Debian-8.7.1-x86_64/dists/jessie/Release -O - | grep -E '^(Suite|Codename)'
choose-mirror[5124]: WARNING **: mirror does not support the specified release (jessie)
```
Running the command directly from TTY2 works:
```
wget -q http://10.0.0.2/cblr/links/Debian-8.7.1-x86_64/dists/jessie/Release -O - | grep -E '^(Suite|Codename)'
Suite: stable
Codename: jessie
```
If I make the same request to an official Debian repository, I get exactly the same answer:
```
wget -q http://httpredir.debian.org/debian/dists/jessie/Release -O - | grep -E '^(Suite|Codename)'
Suite: stable
Codename: jessie
```
Now, if instead of using the cobbler repo, I use the Debian one, by adding these two lines in the "sample.seed":
```
d-i mirror/http/hostname string httpredir.debian.org
d-i mirror/http/directory string /debian
```
It works.
I would guess that it has to do with the debian-installer. But once again, the issue appears only when using the cobbler repo.

Does someone know what comes right after that _wget_?

**Comment by kwizart** [comment]
How have you created the cobbler mirror ? rsync from an official debian mirror or cobbler import from iso ?
The latter will miss the gpg signature for the repository content.
You might need to look at the cobbler httpd log to see any other files the debian installer requested and wasn't present.

**Comment by julenl** [comment]
It's been a while... I think I made it from the ISO file. That could be the reason why the key was missing.
At that time, I just solved the issue by using external repositories.

**Comment by SchoolGuy** [comment]
@julenl So can we close this one then?

**Comment by julenl** [comment]
Well... the version is already quite obsolete anyway, we can close it.
