### ISSUE TITLE
dhcpd entries with interface_type = infiniband

### ISSUE THREAD

**Issue by chuntera** [cobbler/cobbler#1774]
Infiniband hardware address are 20 bytes while ethernet are 8 bytes. If cobbler is configured to use isc dhcpd (module = manage_isc)  then adding infiniband interface hw address will cause an dhcpd error about "hardware address too long".  Solution described below. Using cobber 2.6.11(d/l from epel) with redhat 6.8.

If a 20byte infiniband mac address is added to cobbler system record eg)
>cobbler system edit --name=test1 --interface=ipoib0 --mac=80:00:00:03:fe:80:00:00:00:00:00:00:00:11:75:00:00:78:50:5a --interface-type=infiniband --connected-mode=N --static=1 --ip-address=172.20.10.162 --netmask=255.255.255.0

Then "cobbler "sync" will generate a dhcpd entry such as eg)
>  host generic17 {
>	hardware ethernet 80:00:00:03:fe:80:00:00:00:00:00:00:00:11:75:00:00:78:50:5a;
>        fixed-address 172.20.10.162;
>        option host-name "test1";
>        option subnet-mask 255.255.255.0;
>    }

However this results in an error when restarting dhcpd service:
>Mar 26 23:31:34 cobbler dhcpd: /etc/dhcp/dhcpd.conf line 131: hardware address too long
>Mar 26 23:31:34 cobbler dhcpd:         hardware ethernet 80:00:00:03:fe:80:00:00:00:00:00:00:00:11:75:00:00:78:

The solution according to [infiniband vendor documentation](http://www.mellanox.com/related-docs/prod_software/Mellanox_PXE_User_Guide.pdf) is the use dhcpd "option dhcp-client-identifier". The modified dhcpd entry would be eg)
>    host generic17 {
>	option dhcp-client-identifier = 80:00:00:03:fe:80:00:00:00:00:00:00:00:11:75:00:00:78:50:5a;
>        fixed-address 172.20.10.162;
>        option host-name "test1";
>        option subnet-mask 255.255.255.0;
>   }
This entry does not produce an error when restarting dhcpd.

To resolve this issue, I patched cobbler dhcp template (/etc/cobbler/dhcp.template) and added a test for variable $iface.interface_type eg)
old lines:
`host $iface.name {`
`       hardware ethernet $mac;`

new lines:
`host $iface.name {`
`       #if $iface.interface_type == "infiniband":`
`       option dhcp-client-identifier = $mac;`
`       #else`
`       hardware ethernet $mac;`
`       #end if`

**Comment by jmaas** [comment]
Added to master and release28 branches.
Thanks for contributing!
