### ISSUE TITLE
Cleaning up bad 'cobbler status entries'

### ISSUE THREAD

**Issue by julenl** [cobbler/cobbler#1776]
I mistakenly started a machine on the PXE network, which started to get provisioned without a system name, and it shows a line like this:

    # cobbler status
    ip             |target              |start            |state            
    192.168.0.128  |profile:CentOS-7-x86_64|Wed Mar 15 19:04:39 2017|unknown/stalled  

As it does not have a system associated to it I can't do a `cobbler system remove --name=XXXX`.
Does someone know how could I delete that entry?

**Comment by jmaas** [comment]
You don't have to delete it, it's just a user-friendly summary based on /var/log/cobbler/install.log
