### ISSUE TITLE
New records taking upwards of 60 seconds

### ISSUE THREAD

**Issue by apatt** [cobbler/cobbler#1778]
We have been having a problem with cobbler for a while now where creating of new records can take 60+ seconds.  We have seen this when there are 1000+ records and we enable MAC dupe checking.  When we disable MAC dupe checking, then it will create records quickly with no problem.

Any suggestions?

I am comfortable enough with python to try and diagnose this myself, but I would at least like some pointer as to where in the code base this logic exists to know where to start looking.

We tried to use mongodb as a back end, but that did not help, in fact it made things a little worse.

**Comment by jmaas** [comment]
your patches are merged. tnx again.

hope you can contribute further enhancements in the future!
