### ISSUE TITLE
GUI Documentation needed for filter expressons

### ISSUE THREAD

**Issue by MichaelTiernan** [cobbler/cobbler#1781]
i've been trying (for a while) to find any documentation on how to perform simple logic in filter expressions on the GUI screens. I know I'd seen something once that told how to perform a simple "OR" to filter, for say system names, permitting you to select "MachineA OR MachineZ".

If I'm wrong, then it should say so, preferably on/in the Manual on the GUI section. If it is possible to do this then that too should be documented, even if it is a minor reference for just the basic tools "AND OR NOT", etc.

Thank you.

**Comment by SchoolGuy** [comment]
The current GUI will be removed asap and is not favored anymore. I will close this one because of that reason.
