### ISSUE TITLE
Allow working with desktop ISOs

### ISSUE THREAD

**Issue by Gargravarr2112** [cobbler/cobbler#1784]
I'm a newbie to these kinds of projects, but I'd like to know if it's possible to use Cobbler to deploy desktop OSes. I read that Ubuntu, for example, does not support PXE booting the live CD in #1331, however I've actually got a working PXE boot system setup where I can boot both Ubuntu and Mint unmodified over PXE, graphically. Attached screenshot shows the live CD running in a VM with the installer root mounted over NFS as /cdrom, but as I understand, most distros support booting the installer root over HTTP (e.g. https://wiki.archlinux.org/index.php/PXE#HTTP and https://help.ubuntu.com/community/PXEInstallServer).

If it's not currently possible due to either Ubuntu or Cobbler designs, does anyone know what would need to change for this to work?
![screenshot_disposable_2017-05-05_13 36 05](https://cloud.githubusercontent.com/assets/2163696/25745763/6f8faada-3198-11e7-9ffe-7d6b23913cb3.png)

**Comment by jmaas** [comment]
That because of distros not adding the PXE stuff on the desktop ISO's.
You can use server distro and then add workstation packages.

Cant be fixed in Cobbler.
