### ISSUE TITLE
how to use cobbler with customize ISO?

### ISSUE THREAD

**Issue by axxana** [cobbler/cobbler#1789]
Hi,
We have our customize ubuntu ISO with our patches and customize packages. 
We tried to use cobbler to install our customize ISO (our filesystem.squashfs) BUT its seems that its installing the Ubuntu version from the network instead of my customize ISO.
Can you please guide me how to make cobbler install my customize ISO ?

Those are my configuration:
I am using tftp 
I mounted my customize ISO and import it.
I created distro,profile and system.

-----------------------------------------------------------------------
[root@cobbler ~]# cobbler list
distros:
   Axxana-x86_64

profiles:
   Axxana-x86_64

systems:
   Axxana

repos:
   Axxana-x86_64

images:

mgmtclasses:

packages:

files:

-----------------------------------------------------------------------
[root@cobbler ~]# cobbler check
The following are potential configuration items that you may want to fix:

1 : SELinux is enabled. Please review the following wiki page for details on ensuring cobbler works correctly in your SELinux environment:
    https://github.com/cobbler/cobbler/wiki/Selinux
2 : The default password used by the sample templates for newly installed machines (default_password_crypted in /etc/cobbler/settings) is still set to 'cobbler' and should be changed, try: "openssl passwd -1 -salt 'random-phrase-here' 'your-password-here'" to generate new one

Restart cobblerd and then run 'cobbler sync' to apply changes.
-----------------------------------------------------------------------

[root@cobbler ~]# cobbler profile report
Name                           : Axxana-x86_64
TFTP Boot Files                : {}
Comment                        : 
DHCP Tag                       : default
Distribution                   : Axxana-x86_64
Enable gPXE?                   : 0
Enable PXE Menu?               : 1
Fetchable Files                : {}
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Kickstart                      : /var/lib/cobbler/kickstarts/axxana.seed
Kickstart Metadata             : {}
Management Classes             : []
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Owners                         : ['admin']
Parent Profile                 : 
Internal proxy                 : 
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Repos                          : []
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : 1
Virt Bridge                    : xenbr0
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : 5
Virt Path                      : 
Virt RAM (MB)                  : 512
Virt Type                      : kvm

-----------------------------------------------------------------------
[root@cobbler ~]# cobbler distro report
Name                           : Axxana-x86_64
Architecture                   : x86_64
TFTP Boot Files                : {}
Breed                          : ubuntu
Comment                        : 
Fetchable Files                : {}
Initrd                         : /var/www/cobbler/ks_mirror/Axxana-x86_64/install/netboot/ubuntu-installer/amd64/initrd.gz
Kernel                         : /var/www/cobbler/ks_mirror/Axxana-x86_64/install/netboot/ubuntu-installer/amd64/linux
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Kickstart Metadata             : {'tree': 'http://@@http_server@@/cblr/links/Axxana-x86_64'}
Management Classes             : []
OS Version                     : trusty
Owners                         : ['admin']
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Template Files                 : {}
-----------------------------------------------------------------------

[root@cobbler ~]# cobbler system report
Name                           : Axxana
TFTP Boot Files                : {}
Comment                        : 
Enable gPXE?                   : <<inherit>>
Fetchable Files                : {}
Gateway                        : 
Hostname                       : 
Image                          : 
IPv6 Autoconfiguration         : False
IPv6 Default Device            : 
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Kickstart                      : <<inherit>>
Kickstart Metadata             : {}
LDAP Enabled                   : False
LDAP Management Type           : authconfig
Management Classes             : <<inherit>>
Management Parameters          : <<inherit>>
Monit Enabled                  : False
Name Servers                   : []
Name Servers Search Path       : []
Netboot Enabled                : True
Owners                         : <<inherit>>
Power Management Address       : 
Power Management ID            : 
Power Management Password      : 
Power Management Type          : ipmitool
Power Management Username      : 
Profile                        : Axxana-x86_64
Internal proxy                 : <<inherit>>
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Repos Enabled                  : False
Server Override                : <<inherit>>
Status                         : production
Template Files                 : {}
Virt Auto Boot                 : <<inherit>>
Virt CPUs                      : <<inherit>>
Virt Disk Driver Type          : <<inherit>>
Virt File Size(GB)             : <<inherit>>
Virt Path                      : <<inherit>>
Virt PXE Boot                  : 0
Virt RAM (MB)                  : <<inherit>>
Virt Type                      : <<inherit>>

-----------------------------------------------------------------------

**Comment by jmaas** [comment]
try `cobbler buildiso --standalone`

**Comment by ynixon** [comment]
`cobbler buildiso --standalone --distro=axxana-u-18.04.2-server-1.0-x86_64 --iso=/localmnt/axxana-u-18.04.2-server-1.0.iso --distro=ubuntu
task started: 2019-04-07_184529_buildiso
task started (id=Build Iso, time=Sun Apr  7 18:45:29 2019)
using/creating buildisodir: /var/cache/cobbler/buildiso
building tree for isolinux
copying miscellaneous files
Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'distro ubuntu was not found, aborting'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/utils.py", line 106, in die
    raise CX(msg)

Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'distro ubuntu was not found, aborting'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 82, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 152, in runner
    self.logger
   File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 1027, in build_iso
    iso=iso, profiles=profiles, systems=systems, buildisodir=buildisodir, distro=distro, standalone=standalone, source=source, exclude_dns=exclude_dns, mkisofs_opts=mkisofs_opts
   File "/usr/lib/python2.7/site-packages/cobbler/action_buildiso.py", line 566, in run
    self.generate_standalone_iso(imagesdir,isolinuxdir,distro,source)
   File "/usr/lib/python2.7/site-packages/cobbler/action_buildiso.py", line 419, in generate_standalone_iso
    utils.die(self.logger,"distro %s was not found, aborting" % distname)
   File "/usr/lib/python2.7/site-packages/cobbler/utils.py", line 114, in die
    raise CX(msg)

!!! TASK FAILED !!!
`

**Comment by ynixon** [comment]
cobbler.log:
`Sun Apr  7 18:36:54 2019 - INFO | REMOTE start_task(Build Iso); event_id(2019-04-07_183654_buildiso); user(?)
Sun Apr  7 18:37:07 2019 - ERROR | 
# *** ERROR ***
#
# There is a templating error preventing this file from rendering correctly. 
#
# This is most likely not due to a bug in Cobbler and is something you can fix.
#
# Look at the message below to see what things are causing problems.  
#
# (1) Does the template file reference a $variable that is not defined?
# (2) is there a formatting error in a Cheetah directive?
# (3) Should dollar signs ($) be escaped that are not being escaped?
#
# Try fixing the problem and then investigate to see if this message goes
# away or changes.
#
# 
# unexpected EOF while parsing (<string>, line 1)
#   File "/usr/lib/python2.7/site-packages/cobbler/templar.py", line 208, in render_cheetah
#     data_out = t.respond()
# 
#   File "cheetah_DynamicallyCompiledCheetahTemplate_1554650954_95_35771.py", line 275, in respond
# 
#   File "cheetah_DynamicallyCompiledCheetahTemplate_1554650954_95_35771.py", line 91, in __errorCatcher4
# 
`
