### ISSUE TITLE
Use hostname for PXE

### ISSUE THREAD

**Issue by cncook001** [cobbler/cobbler#179]
Cobbler hard codes IP address in PXE boot settings

/usr/lib/python2.6/site-packages/cobbler/pxegen.py

```
        # FIXME: profiles also need this data!
        # FIXME: the _conf and _parm files are limited to 80 characters in length
        try:
            ipaddress = socket.gethostbyname_ex(blended["http_server"])[2][0]
        except socket.gaierror:
            ipaddress = blended["http_server"]
        kickstart_path = "http://%s/cblr/svc/op/ks/system/%s" % (ipaddress, system.name)
```

Please change to allow hostname instead.

Use case:

Our network team will not allow DHCP on our production Server subnet.  We have to use a VLAN for provisioning (using a different NIC on the cobbler server).

Cobber Server with 2 nics.

cobbler.example.com  (10.10.10.1, 192.168.1.10)

10.10.10.1 is the public address cobbler server uses for its network and internet access.

192.168.1.10 is a private, provisioning only subnet/VLAN.

DNS is running on cobbler.example.com.  It answers for the 192.168.1.x subnet.

New host is connected to the 192.168.1.x VLAN.  PXE boot, DHCP server gives it an IP to use.  New host boots, Cobbler gives new host it's ks file to find, but uses an IP ( the default IP for the box, 10.10.10.1) that will not work.

How it should work:

New host PXE boots, is given a DHCP address, it includes where to find a DNS server (192.168.1.10).

Cobbler provides a location to the new host like cobber.example.com/somdir/ks.cfg, the DNS resolves to the correct IP, host is installed.

(After host is provisioned, the network team changes the VLAN the port uses, the server then starts life on our production network)

Using this setup I can also use the same cobbler server to boot servers using it's public NIC.

**Comment by lanky** [comment]
This is still an issue on 2.6.3, appears to be a design decision. The 
`ipaddress = socket.gethostbyname_ex(blended["http_server"])[2][0]`
line will always return an IP address as that call returns a tuple thus:
( 'FQDN', ['hostname', ...], ['ipaddr',...])

it's not clear to me why this is required to be an IP address?

**Comment by SchoolGuy** [comment]
This was fixed through https://github.com/cobbler/cobbler/pull/2357
