### ISSUE TITLE
RedHat 7 dependency removed

### ISSUE THREAD

**Issue by mega-watt** [cobbler/cobbler#1790]
python-ipaddr has been removed in RHEL 7:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Migration_Planning_Guide/sect-Red_Hat_Enterprise_Linux-Migration_Planning_Guide-Removed_Packages.html

Can the rpm for RHEL 7 be updated to use a supported package or include a supplied RPM in your repository?

**Comment by jmaas** [comment]
Cobbler has a dependency on python-netaddr, not python-ipaddr.
I dont think this will be a problem. Please confirm
