### ISSUE TITLE
Centos 7 host failing to provision

### ISSUE THREAD

**Issue by h1y4** [cobbler/cobbler#1800]
Hi
Every attempt/method of creating a Centos 7 host I have tried has failed with the same error:

[   16.951519] localhost dracut-mount[1120]: Warning: Can't mount root filesystem

I have tried using various kickstart files most recently /var/lib/cobbler/kickstarts/sample.ks but also the one shown here https://www.olindata.com/en/blog/2015/07/cobbler-setup-centos7

I have put a full log here - https://pastebin.com/HnQF32NT

Could you please help me work out what I am doing wrong?
Thanks

**Comment by h1y4** [comment]
adding kernel options = inst.repo=http://192.168.1.80/cblr/ks_mirror/CentOS-7-x86_64/ helps it get further but fails like this http://imgur.com/a/oZIUj

**Comment by h1y4** [comment]
Clients need >2.5G RAM

**Comment by kakalotto** [comment]
ran into the same problem, thanks a lot!
