### ISSUE TITLE
how to install fedroa 25 using cobbler

### ISSUE THREAD

**Issue by Git-Rajkumar** [cobbler/cobbler#1808]
I need to install fedora 25 workstation in 10+ systems,  cobbler document says, 

> In order to import a distribution, you will need a DVD ISO for your distribution. NOTE: You must use a full DVD, and not a "Live CD" ISO. 

Refernece: http://ftp.riken.jp/Linux/fedora/releases/25/Workstation/x86_64/iso/  

But, fedora 25 workstation is not there DVD iso image, so, How can I Install fedora 25 using cobbler.

**Comment by opoplawski** [comment]
There is one under Server - http://ftp.riken.jp/Linux/fedora/releases/25/Server/x86_64/iso/

**Comment by Git-Rajkumar** [comment]
@opoplawski  I know this Fedora 25 Server have DVD iso image, but i need to Fedora25 Workstation not a Server.

**Comment by opoplawski** [comment]
If you are installing via kickstart (which is what cobbler does), the whole product thing becomes pretty meaningless.  Use a workstation kickstart and provide access to the Workstation (or Everything) repo and you'll get a workstation install.
