### ISSUE TITLE
use kickstart deploy esxi6 get error

### ISSUE THREAD

**Issue by xiaoman90651** [cobbler/cobbler#1810]
hello
when i deploy esxi6 useing kickstart get **error:vmaccepteula command was not specified. You must read and accept the VMware ESX End User License Agreement by including the command in the ...**
this is my ks

`vmaccepteula

rootpw ideal1234

install --firstdisk --overwritevmfs

network --bootproto=dhcp

reboot

%pre --interpreter=busybox

var=$(esxcli hardware platform get | grep "Serial N")`

**Comment by ujnzxw** [comment]
Hi, 

Just for your information, there is no same error for ESXi 6.5 installation.
And I don't think your error is related with Cobbler.

BTW, there is a default ks example in ESXi host: /etc/vmware/weasel/ks.cfg

**Comment by jmaas** [comment]
works for others.
not a Cobbler bug.
