### ISSUE TITLE
Linux Booting issue 

### ISSUE THREAD

**Issue by dineshjayavel** [cobbler/cobbler#1817]
dear team,
                I am unable to Linux 7 while start system booting issue .swap does not exist.Kindly find the attached screen shot file.
![image](https://user-images.githubusercontent.com/30677700/28902676-2a4c875a-781e-11e7-8fb1-1d51f134d6cd.png)

**Comment by jmaas** [comment]
Doesn't look like a Cobbler issue.
You might get help on the Cobbler ML.
Github is not for user support issues, sorry
