### ISSUE TITLE
Cobbler Import: repo-file mismatch with source_repo setting

### ISSUE THREAD

**Issue by Alex-Bron** [cobbler/cobbler#1818]
If I do a fresh install of Cobbler (2.8.0 or 2.8.1), and I import a CentOS (6 or 7) DVD with cobbler import, there is a mismatch between the stored repo file in /var/www/cobbler/ks_mirror/config and the file mentioned in the source_repo structure in the json file. What I found is that in the modules/manage_import_signatures.py file (cobbler 2.8.1) on line 588 the config file is defined using the dotrepo variable which will not include a counter when that counter is 0. However on line 590, the source_repo structure is filled with a filename containing the counter regardless of its value. So I end up with a config file Centos-7-x86_64.repo, but a source_repo structure pointing at Centos-7-x86_64-0.repo which doesn't exist.

Proposed fix would be to redefine line 590 to:

repo_url = "http://@@http_server@@/cobbler/ks_mirror/config/%s.repo" % (dotrepo)

**Comment by SchoolGuy** [comment]
The PR #1856 was never ported to `master` but according to @philseeley there is no need. Thus closing this issue as done.
