### ISSUE TITLE
Large changes take too long.

### ISSUE THREAD

**Issue by MichaelTiernan** [cobbler/cobbler#1821]
I've noticed that if i change an active profile, upon saving it, cobbler goes through all systems assigned that profile and performs an update. I've got about 500+ systems and when the common profile is updated, i get a time-out from the system complaining about how long it takes.

Personally, I'd much prefer that the task be dispatched into the background to be done allowing the GUI to continue on for other tasks.

(I'm hoping this isn't a duplicate.)

**Comment by jmaas** [comment]
@MichaelTiernan there are some improvements in master (which will be 3.0) for this.

Please see commit 1a85ea46c1a684995694271f36a237511cf46294

If possible try running in master, possibly in a dev environment. I'm not investing time in 2.8 any longer, that is any other than easy bugfixes. All focus now is on getting 3.0 out asap

**Comment by jmaas** [comment]
Closing this as the situation has improved in 3.x
