### ISSUE TITLE
failed to start Switch Root

### ISSUE THREAD

**Issue by tomboxme** [cobbler/cobbler#1823]
I'm having an issue trying to PXE Centos 7.3 on a few of my machines that's been driving me mad and I just can't seem to figure it out. 

Running cobbler 2.8 and keep getting the error "Failed to start Switch Root". 

> Name                           : Centos7.3
> Architecture                   : x86_64
> TFTP Boot Files                : {}
> Breed                          : redhat
> Comment                        : 
> Fetchable Files                : {}
> Initrd                         : /cobbler_OS/Centos7.3/initrd.img
> Kernel                         : /cobbler_OS/Centos7.3/vmlinuz
> Kernel Options                 : {'ksdevice': '', 'inst.repo': 'http://10.218.50.19/CentOS/7.3/mill_CentOS7.3_200217/'}
> Kernel Options (Post Install)  : {}
> Kickstart Metadata             : {}
> Management Classes             : []
> OS Version                     : rhel7
> Owners                         : ['admin']
> Red Hat Management Key         : <<inherit>>
> Red Hat Management Server      : <<inherit>>
> Template Files                 : {}
> 

It appears to pick up the HDD no problem but I'm somewhat lost as to what to look for next, any help is appreciated. 

![screen shot 2017-08-30 at 11 09 56 am](https://user-images.githubusercontent.com/7917387/29883222-318d0384-8d75-11e7-848e-445db7572928.png)

**Comment by jmaas** [comment]
Try adding more RAM, at least 1.5gig is needed for installing.
Also this is not a Cobbler problem (PXE boot started)
