### ISSUE TITLE
APT Mirror For Cobbler 2.6 Seems Removed

### ISSUE THREAD

**Issue by jwbrown77** [cobbler/cobbler#1825]
I am attempting to download Cobbler 2.6 for Ubuntu Trusty.  This has worked for me until recently (the last time I tried was about a month ago).

I add the repo using:

```sudo add-apt-repository "deb http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/xUbuntu_14.04/ ./"```

I also add the GPG, but get:

```
wget -qO - http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/xUbuntu_14.04/Release.key | sudo apt-key add -
gpg: no valid OpenPGP data found.
```

Turns out the file doesn't exist:

```
curl http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/xUbuntu_14.04/Release.key
...
<body>
<h1>Access forbidden!</h1>
<p>




    You don't have permission to access the requested object.
    It is either read-protected or not readable by the server.
```

Looking manually in this path, I can get all the way to:

http://download.opensuse.org/repositories/home:/

But the libertas-ict:/ directory doesn't exist.

This mirror is advertised on your install guide page:

http://cobbler.github.io/downloads/2.6.x.html

Can you please advise if this mirror has been moved; if it can be restored; or if it's just gone away forever and I need to seek an alternative?

Thanks in advance

**Comment by jwbrown77** [comment]
Not sure what happened, but the libertas-ict:/ subfolder is back.

Inside, there are three release folders:

cobbler24
cobbler26
cobbler28

It appears the 24 and 26 folders are empty, but the 28 has releases.  I'm ok going to 2.8 if that's the only option, but restoring 2.6 would be nice, as I have tested fully against this release.

Thanks,

Jeremy

**Comment by jmaas** [comment]
Those packages were deleted as part of OBS cleanup, not my choice :(
I'm not sure if i can restore those.

2.8 is really no that different from 2.6! the version bump was basically just for deprecating stuff that will not be available in 3.0. Originally i didn't event want to do a 2.8.

**Comment by jwbrown77** [comment]
Hi Jorgen,

Understood.  It's very helpful that even 2.8 is available now.  I have no problem testing this version and I'm sure there won't be many issues, if any, to resolve on my side.

It's just very helpful to have the packages on an APT upstream so that I don't have to compile everything, etc.

I will close this for now and let you know if anything happens with the mirror.  Thanks again.

**Comment by jwbrown77** [comment]
Hi Jorgen,

I just got around to trying this, and unfortunately, even though the deb exists in the aformentioned HTTP path, it seems to be just a skeleton that contains only a changelog:

```
sudo dpkg-query -L cobbler
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/cobbler
/usr/share/doc/cobbler/changelog.Debian.gz
```

Is there any chance you can restore the full packages to this mirror?  To be clear, I am attempting:

http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler28/xUbuntu_14.04/

For what it's worth, I also checked the 16.04 repo and the cobbler deb is the same size in both: 1.7KB (too small)

Thanks in advance

**Comment by jmaas** [comment]
The APT packages were broken due to some changes on OBS.
I was not able to figure out how to get them building again.

Since i have limited time, i choose to focus on Cobbler development and let package creation to downstream. Building RPM's still works from the source tree, If you want the latest Cobbler; Debian/Ubuntu is not the best choice unfortunately.

I get a lot of issues/complaints about the DEB's, but no contributions yet :(
I might have time for packaging again when i get the first 3.0 release out.
I will remove the broken packages!

I'm sorry.
