### ISSUE TITLE
tftp transfer speed is very slow 

### ISSUE THREAD

**Issue by 512868516** [cobbler/cobbler#1826]
tftp transfer speed is very slow ,about 2M-5M.
but rsync/wget is very well。

[root@localhost ~]# curl -o 111 tftp://192.168.1.224/images/Memory-os/initrd0.img
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1  539M    1 5698k    0     0  1368k      0  0:06:43  0:00:04  0:06:39 1369k^C
[root@localhost ~]#

**Comment by jmaas** [comment]
what tftp service are you using?

**Comment by jmaas** [comment]
Also, Cobbler's job is to populate the tftp directory. It doesn't have a role in the actual file transfers, unless you are using tftpd.py. In that case i'd suggest using a 'real' tftp-server.

**Comment by 512868516** [comment]
[root@cobbler-puppet ~]# rpm -qa|grep cobbler
cobbler-2.6.3-1.el6.noarch
[root@cobbler-puppet ~]# cat /etc/redhat-release
CentOS release 6.9 (Final)

when the pxe client tftp get the os initrd0.img , i found the tftp transfer speed is very slow.

![1111](https://user-images.githubusercontent.com/6998824/30303241-227ee0dc-9799-11e7-8627-6feb780d4ad7.png)

**Comment by jmaas** [comment]
you could use `strace` to see what the process is doing, perhaps that will give some clues.
are you using tftp-server (in.tftpd) or the python service?

**Comment by jmaas** [comment]
Also, this is better suited for the mailinglist, you might get more help there.
This issue tracker is for bug reports.

**Comment by 512868516** [comment]
![image](https://user-images.githubusercontent.com/6998824/30311813-9e6d19a4-97c9-11e7-9b61-3cac2fb25283.png)

**Comment by 512868516** [comment]
@jmaas
