### ISSUE TITLE
unable to download cobbler for RHEL7

### ISSUE THREAD

**Issue by meetjitesh** [cobbler/cobbler#1827]
Trying to download cobbler using yum, and getting error, after looking into http url it looks like either URL is no longer working or it moved to different location.
 
URL trying to download is,
 
http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/CentOS_CentOS-7/
 
Thank you,

**Comment by 512868516** [comment]
use epel

**Comment by jmaas** [comment]
Cobbler 2.6  is EOL.
Please try cobbler 2.8.1 from OBS or even better EPEL
