### ISSUE TITLE
Consider dropping support for syslinux and yaboot in favor of grub2

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1828]
grub2 is way more stable / better supported.
also grub2-mkrescue can be used to build images for CD/USB booting on UEFI and BIOS.

**Comment by JohanElmis** [comment]
The Grub2 support that has just been added will only support UEFI systems. (using linuxefi) loaders in the PXE configs.
We probably need to continue support syslinux (but get these upgraded) syslinux (at least on CentOS) has both pxelinux and gpxelinux - where the later supports http transfers as well.
Maybe we should just make sure that we have the latest version - for older non UEFI systems.

**Comment by watologo1** [comment]
grub2 should replace pxelinux as well as yaboot (for ppc/ppc64).
I started on the latter. grub2 can boot everything that syslinux or yaboot can nowadays.

I like this feature and enhance it with dropping yaboot as well if it's ok with you: @jmaas

**Comment by SchoolGuy** [comment]
@watologo1 Jörgen is not active anymore on this project. I personally would like to see to get rid of old code which is not needed. Since you said grub2 can boot anything yaboot and pxelinux can boot there should be no compatibility problems.

**Comment by nodeg** [comment]
GRUB 2 is alreday supported and the default. Syslinux is still needed according to @SchoolGuy and Yaboot will get removed with #2723.
