### ISSUE TITLE
Consider documentaton for api ? Rest API ?

### ISSUE THREAD

**Issue by FlorianneRaven** [cobbler/cobbler#1829]
Hello
I have 2 questions:
 will you consider having a real documentation for the xmlrpc API ?

will you use a new form of API like REST API ?

**Comment by jmaas** [comment]
we'd love to move to REST and improve docs.
time is limited, so it relies also on user contributions.
we have already some feature request issues for these topic, so i'll close this one.

user mailinglist: cobbler-users@groups.google.com

thanks!
