### ISSUE TITLE
master branch is broken - Is that beyond repair ?

### ISSUE THREAD

**Issue by kwizart** [cobbler/cobbler#1833]
After testing the master branch on a clean vm. I've managed to create and install the rpm using bdist_rpm (but not install directly). cobblerd was working, but not cobbler_web.

I think I've saw some changes going back and forth related to cobbler_web. But unfortunately I think the revert wasn't made as appropriate, so for example there are lot of cobbler_web urls but not the related directory installed, and I suspect that the related setup.py files wasn't updated according to the new changes.

The other point is that master as diverged a lot from the production ready branch(2.8). so It looks really difficult to cherry pick a feature developed in dev into stable. And even most feature should (are) development from production branches.

So maybe it would be easier to move master -> deprecated and to start a new dev branch based on current 28 ? Then to progressively merge selected , safe and well tested, commits from the old master.
Then to release a 210 branch in few months ?

At this step this is just a question. For example, many changes in master might  be safe and well tested beyond  cobbler_web. So this is my impression for now and is really a question.

**Comment by jmaas** [comment]
It's true master diverged a lot from 2.x.
It really is not sustainable to support two branches, thats why i only do easy bugfixes on 2.x
No feature backports.

I really like to get 3.0 in a good enough shape to push an alpha release out
Fixing cobbler-web seems mandatory ;)

**Comment by jmaas** [comment]
I now have cobbler-web up and running on el7 with django from epel (1.6).
