### ISSUE TITLE
Bad mailing list links.

### ISSUE THREAD

**Issue by cstackpole** [cobbler/cobbler#1846]
Greetings,
When you go to https://cobbler.github.io/community.html and try to go to the mailing list, it goes to fedora hosted, which is no more. I was going to fix and submit a pull request, but I can't find what the new mailing list should be.

It's an issue for people who need to reach out for help (me! ;-).

Can someone please fix the link? Or remove it.

Thanks!

**Comment by jmaas** [comment]
the mailinglist has just been moved to cobbler-users@googlegroups.com
