### ISSUE TITLE
[Question] cobbler parallelism

### ISSUE THREAD

**Issue by DjangoCalendar** [cobbler/cobbler#1851]
Hi,

I have a question regarding parallel installations.

Let's say I have
1. Created new system called "system-A"
2. Performed cobbler sync so that tftp files are re-created and dhcp reconfigured and restarted
3. Next I created next system called "system-B"
4. Now I powered on system-A in step 1)
5. Can I now trigger cobbler sync and this is not going to break system-A installation on whatever phase is installation of system-A?

NOTE: we are talking here about redhat kickstart installations.

**Comment by JohanElmis** [comment]
I don't think that this is a problem.
We are kicking hundreds of servers every day, and running syncs a few times an hour. (Sync is not needed unless larger changes are performed (We have a separate DHCP though).
The necessary files for the PXE boot and install is created without sync.
We are kicking CentOS setups (no advanced RH management solutions).

**Comment by fr4nk18** [comment]
Hi .. do you work in parallel , building several boxes /vms / at a time ?
I am facing strong issues working in parallel when we build more than 4 almost identical (except mac address / ip  etc) servers cobbler dies without any clue.
Did you faced something similar ? Your cobbler server is a big one ? (we are using a vmware virtual with 1cpu/4gb actually) ...

**Comment by jmaas** [comment]
Deploying systems in parallel should not be a issue, after all configs (dhcp/tftp) have been created it's all up to dhcpd and tftp-server to handle client request. getting the kickstart from http should work with multiple deployments running in parallel.

running cobbler sync in parallel does indeed cause major issues; please dont do that.

perhaps we can move this discussion to cobbler-users@groups.google.com
