### ISSUE TITLE
404 after login (to much stripped url data)

### ISSUE THREAD

**Issue by neonknight** [cobbler/cobbler#1855]
sending/bookmarking a link to 
https://cobblerserver/cobbler_web/snippet/edit/file:/var/lib/cobbler/snippets/mysnippet
after login the link is rewritten to
https://cobblerserver/cobbler_web/edit/file:/var/lib/cobbler/snippets/mysnippet
resulting in error 404

**Comment by SchoolGuy** [comment]
The current webinterface will be removed with Cobbler 3.3.0 and a new webinterface will be added when we have time. Thus removing this because it won't be fixed.
