### ISSUE TITLE
No python3 compatibility: Are there ongoing efforts?

### ISSUE THREAD

**Issue by juliogonzalez** [cobbler/cobbler#1858]
So far I see that the code is not compatible (prints, python2-only modules -both from standard library and third parties-...)

We at SUSE are considering creating a patch to make it compatible since SLE15 will ship python3 only, (python2 will be EoL in around 2 years).

So far I can see that other than adapting the cobbler code, there are three dependencies that must change since are not ported to python3:

* cheetah -> cheetah3
* createrepo -> createrepo_c
* urrlgrabber -> pycurl

There's also a problem with virt-manager, that can only be fixed there (not at cobbler): it depends on python-ipaddr which is not going to be ported (should be replaced with python-ipaddress, that it's also available for python2).

Is anyone currently working on this so we can coordinate?

**Comment by juliogonzalez** [comment]
@kwizart: thank you very much for the feedback.

On our side we have finally decided to adapt cobbler to be used with Python 3.0, and we are willing to collaborate.

We can make the changes for everything with the exception of web and django1 -> django2 support (since we don't use it). Is there anyone on your side that can take care of this?

Also I guess it's best moving this discussion to the cobbler-devel mailing list, but since I see that there is not too much traffic there, I don't know if you prefer GitHub issues or email.

@jmaas, since you are marked as maintainer at AUTHORS.in, what is your opinion about this?

**Comment by jmaas** [comment]
Sorry for late response. I have little time to work on Cobbler. I'd love to see people to step up and implement whatever they think is needed. Having said that:

Python3 support is for now the MOST important issue. We are slowly sliding into ecosystem compatibility issues as we cant keep up.

So, feel free to drive this change! I'd suggest to target the master branch.
Cobbler 3 (master) is already a massive incompatible with Cobbler 2, therefor i don't like to branch into 2.10. 

Lets make 3 the release to have a modern base to further improve upon.

I'll try to be more active, i have made some changes in my personal life to free up some time for Cobbler.

**Comment by timcoote** [comment]
afaict, cobbler stopped working on fedora 27 as the wsgi environment is python3 and `/var/www/cobbler/svc/services.py` fails to `    from cobbler.services import CobblerSvc` [line 40] (which is a python2 package) when trying to pull down the kickstart file for a virt-install (`sudo virt-install --connect=qemu:///system --name=puppet --ram=1536 --vcpus=1 --autostart --vnc --virt-type=kvm --machine=pc --extra-args="ks=http://<redacted IP>/cblr/svc/op/ks/system/puppet ksdevice=link kssendmac lang= text " --location=http://<redacted IP>/cblr/links/f28-x86_64/ --arch=x86_64 --disk=path=/var/lib/libvirt/images//puppet-disk0,size=10,format=raw --network=bridge=vmbridge,mac=<redacted mac> --wait=0 --noautoconsole`).

The disturbing thing to me is that I can see no bug for this in fedora. So, either I've got a unique setup, or usage of cobbler is falling off for fedora. Which is disappointing.

**Comment by brejoc** [comment]
I've opened two follow up issues related to this: #1930 and #1931
Comments and suggestions are very welcome!

**Comment by jmaas** [comment]
The ongoing porting effort has been merged into master.
We love contributions :)
