### ISSUE TITLE
Cobbler Server Permission denied 

### ISSUE THREAD

**Issue by srinijreddy** [cobbler/cobbler#1866]
Forbidden
You don't have permission to access /cobbler_web on this server. 

My cobbler version is : 
**Cobbler 2.8.2**
  

**I have this set up in cobbler_web.conf.**

<IfVersion >= 2.4>
    <Location /cobbler_web>
        Require all granted
    </Location>
    <Location /cobbler_webui_content>
        Require all granted
    </Location>
</IfVersion>

**Here is my entire cobbelr_web.conf file:**

 <IfModule mod_ssl.c>
            SSLRequireSSL
        </IfModule>
        <IfModule mod_nss.c>
            NSSRequireSSL
        </IfModule>
        SetEnv VIRTUALENV
        Options Indexes MultiViews
        AllowOverride None
        Order allow,deny
        Allow from all
        Require all granted
</Directory>

<Directory "/var/www/cobbler_webui_content/">
        <IfModule mod_ssl.c>
            SSLRequireSSL
        </IfModule>
        <IfModule mod_nss.c>
            NSSRequireSSL
        </IfModule>
        Options +Indexes +FollowSymLinks
        AllowOverride None
        Order allow,deny
        Allow from all
         Require all granted
</Directory>

 Use separate process group for wsgi
WSGISocketPrefix /var/run/wsgi
WSGIScriptAlias /cobbler_web /usr/share/cobbler/web/cobbler.wsgi
WSGIDaemonProcess cobbler_web display-name=%{GROUP}
WSGIProcessGroup cobbler_web
WSGIPassAuthorization On

<IfVersion >= 2.4>
    <Location /cobbler_web>
        Require all granted
    </Location>
    <Location /cobbler_webui_content>
        Require all granted
    </Location>
</IfVersion>

But still i get permission denied issue. 403.

**Comment by o1dcat** [comment]
hi:

**Comment by o1dcat** [comment]
i have the same issue,and you need use https:// instead of http://

**Comment by jmaas** [comment]
also make sure mod_ssl or the nss packages are installed.

for user support a mailing list is available at: cobbler-users@groups.google.com

**Comment by Laurel-rao** [comment]
I know the solution that resolved this issue, everybody attention here. 
<h1>Check you url isn't http</h1>
<h1>Because cobbler support https only!</h1>
- It's take a long time to resolve the questions.And it was exhausted me!!!

``` 
    # use this url
    https://192.168.1.110/cobbler_web/
```
