### ISSUE TITLE
Questions about mailinglist and some technical questions

### ISSUE THREAD

**Issue by Cyber1000** [cobbler/cobbler#1868]
First of all, I'm new to cobbler, would like to use it at home-environment and tested a little bit successfully with an docker-cobbler image (https://github.com/ContainerSolutions/docker-cobbler).

As this is no real issue, but some questions, I wanted to post on a maillinglist (as stated here: http://cobbler.github.io/community.html), but it seems that maillinglists on fedorahosted.org are retired since March 1st, 2017. Outdated information?

Nevertheless here my problems:
- For now I use openwrt on my router and some pxe-Files, but the more it grows it's not really nice to manage.
- on the other hand cobbler won't work on openwrt (prerequisites, different architecture, kindof reduced busybox-linux), at least not in an easy way.
- My next idea was to have cobbler on a different server (or in a container on a different server), configure it there if I have changes and only copy/rsync dirs like /var/www/cobbler and /var/lib/tftpboot/ to my router.

My questions: 

1. Will these two directories be sufficient to work on my router? (I don't actually need cobbler-configuration on the router, pxe itself should work)
2. Will I have to manually rsync to my router, or is there already an option in cobbler? I've seen rsync in documentation (http://cobbler.github.io/manuals/2.8.0/3/4/3_-_Managing_rsync.html), but the page is empty. Don't know if this is used for syncing between two cobbler-servers or can be used otherwise.
3. Backing up: I would like to have a very lightweight backup, is this possible? As far as I have seen I would need to backup /etc/cobbler (which is very small) and /var/www/cobbler (which depends on image sizes). Is it really necessary to backup whole /var/www/cobbler, wouldn't it be sufficient to remember the links you downloaded ISOs (fedora, ubuntu, ...) from (at least for home setup)? Is it possible/planned in cobbler to only remember the download links? Are there any other dirs I've forgotten to backup?
4. Does cobbler create pxe-submenues? For example if I have one fedora distro but would like to start it with 3 or 4 different settings, it would be nice to have only one "fedora" entry on the main menu which leads to a submenu with different settings.
5. Any other ideas/suggestions on my planned szenario?

Sorry for this long "issue", but as said can't use mailing list.

Regards and thanks for reading/answering.

**Comment by jmaas** [comment]
the new mailinglist is cobbler-users@groups.google.com

1) yes that should work, you just need dhcp/tftp
2) manually. the manage_rsync stuff is for cobbler master/slave configurations
3) /etc/cobbler & /var/lib/cobbler; /var/www/cobbler will be big; might be better te re-import ISO's after failure
4) not that i know of
5) not really; what you suggested should just work.. a bit weird perhaps ;)

Good luck!
