### ISSUE TITLE
unable to add signatures for SLES15 

### ISSUE THREAD

**Issue by jmalantonio** [cobbler/cobbler#1872]
In the past I manually updated distro_signatures.json file to add new OS's but when I add sles15 I keep getting the following message. 
No signature matched in /var/www/cobbler/ks_mirror/sles15 

I noticed in the release rpm it no longer includes SuSE-release file. Is there a work around or any way I can troubleshoot?? 

   "sles15": {
    "signatures":["suse"],
    "version_file":"(sle|SLE-for-VMware)-release-15-(.*).rpm",
    "version_file_regex":null,
    "kernel_arch":"kernel-(.*)\\.rpm",
    "kernel_arch_regex":null,
    "supported_arches":["i386","i586","x86_64","ppc64"],
    "supported_repo_breeds":["yum"],
    "kernel_file":"linux[64.gz]?",
    "initrd_file":"initrd[64]?",
    "isolinux_ok":false,
    "default_kickstart":"/var/lib/cobbler/kickstarts/sample_autoyast.xml",
    "kernel_options":"install=$tree",
    "kernel_options_post":"",
    "boot_files":[]
   },

[2018-01-16_125037_import.log](https://github.com/cobbler/cobbler/files/1636258/2018-01-16_125037_import.log)

**Comment by murali038** [comment]
are you trying to import the installer iso? if yes, then the release rpm is in x86_64 directory

**Comment by mdiep25** [comment]
change "signatures":["suse"], to "signatures":[""],
