### ISSUE TITLE
Power management issue 

### ISSUE THREAD

**Issue by srinijreddy** [cobbler/cobbler#1875]
Can any one help me in fixing this power management issue :+1: 
 **cobbler system powerstatus --name=cobbler01**
task started: 2018-02-07_134002_power
task started (id=Power management (status), time=Wed Feb  7 13:40:02 2018)
cobbler power configuration is:
      type   : ilo4_ssh
      address: 10.86.86.86
      user   : isa
      id     :
running: /sbin/fence_ilo4_ssh
received on stdout:
received on stderr: Unable to connect/login to fencing device
running: /sbin/fence_ilo4_ssh
received on stdout:
received on stderr: Unable to connect/login to fencing device
running: /sbin/fence_ilo4_ssh
received on stdout:
received on stderr: Unable to connect/login to fencing device
Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'command failed (rc=1), please validate the physical setup and cobbler config'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/utils.py", line 106, in die
    raise CX(msg)
failed to execute power task on tzulkar01
*** TASK COMPLETE ***

Here is my input data:
**cobbler system edit --name=cobbler01 --power-type='ilo4_ssh' --power-address=10.86.86.86 --power-user=root --power-pass='abcd'**

I can manual ssh to " Ilo4_ssh " console :

**Comment by jmaas** [comment]
I dont have the means (infrastructure) to even power management support.
This feature is entirely dependent on user contributions.
Sorry!
