### ISSUE TITLE
Cobbler API documentation

### ISSUE THREAD

**Issue by FlorianneRaven** [cobbler/cobbler#1879]
Hello
The documentation for the cobbler API is gone since a long time.
Can you add the documentation on the website or on the github page ?

Here is a link on webarchive:

https://web.archive.org/web/20120403040919/https://fedorahosted.org/cobbler/wiki/CobblerXmlrpc

**Comment by juaningan** [comment]
You can generate with pydoc cobbler.remote, or pydoc -w cobbler.remote for HTML

**Comment by FlorianneRaven** [comment]
I was thinking with some examples...

**Comment by juaningan** [comment]
You have some examples on remote.py
Actually tests

**Comment by jmaas** [comment]
thanks @dagwieers

**Comment by jmaas** [comment]
documentation is a problem.

there are other issues logged for that, closing this one.

**Comment by dagwieers** [comment]
@jmaas I would suggest to recommend people in those issues to move more documentation (from archive.org) to the Wiki, at least it empowers users to help themselves/others.

(Reformatting is a drag, but at least it can be outsourced to the reporter ;-))

**Comment by jmaas** [comment]
great idea, will do that from now on.

if you have time to contribute, please do :)
