### ISSUE TITLE
cobbler check returns "httpd does not appear to be running and proxying cobbler

### ISSUE THREAD

**Issue by myUserTest01** [cobbler/cobbler#1880]
I have install it over ubuntu 16.4 with following packages

Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02

can be depend because in Apache 2.4 the executable do not called httpd?

**Comment by jmaas** [comment]
no that's not the issue, you might have some missing dependencies to apache

mod_ssl, mod_proxy

try running:
```
$ a2enmod proxy
$ a2enmod proxy_http
$ a2enmod rewrite
```

if that does not help, please post to the mailing list.
