### ISSUE TITLE
xmlrpclib login failed after restarting cobblerd

### ISSUE THREAD

**Issue by Karunamon** [cobbler/cobbler#1883]
Steps:

* On an Ubuntu 16.04 machine, `apt-get install cobbler` (which results in v2.4.1 being installed as reported by `cobbler check`)
* Also install cobbler-web: `apt-get install cobbler-web`
* Start the daemon: `systemctl start cobbler`
* Try using the various `cobbler` command line options, notice they work.
* Restart the daemon: `systemctl restart cobbler`

**All** cobbler commands now return an error: `xmlrpclib.Fault: <Fault 1: "<class 'cobbler.cexceptions.CX'>:'login failed'">` 

A stop and a restart does not solve the problem. However, *rebooting* the machine clears the problem and allows Cobbler to run.. as long as the daemon doesn't ever restart.

This may be related to #1824 - the difference being that I can solidly reproduce this.

First instinct is that this is some kind of systemd-related thing since a reboot clears it up.

**Comment by jmaas** [comment]
would be great if you can find the source of this.
alas, i can't reproduce...

**Comment by jmaas** [comment]
also cobbler 2.4 is way too old for me to bother. Sorry.

let's move this to the support mailinglist: cobbler-users@groups.google.com
