### ISSUE TITLE
New builds have split interface definitions

### ISSUE THREAD

**Issue by sheepnwolfe** [cobbler/cobbler#1884]
First, my apologies if this isn't the right place for this, and I do not know if this is an issue or user error, but I could not find an avenue to get help.  Can someone please tell me where to go for help?  The help page says "The primary mailing list for Cobbler is cobbler@lists.fedorahosted.org", but that has been decommissioned, and I do not know where to go.

The issue:  When I add systems to cobbler, I am required to put an --interface definition, and I do not know what to call the interface.  Our systems are VMware VMs and when I build them manually from dvd, they come up with an ens160 interface that I have noticed.  When I use that for the interface name in cobbler, it builds a system that works, and with an interface called ens160 (per "ip addr"), but when I look into /etc/sysconfig/network-scripts, in addition to the one for "lo", there are two ifcfg files:  ifcfg-ens160, and ifcfg-ens192.   Each of the two files has part of the config for the ens160 interface.  If I merge the two files to make one proper ifcfg-ens160 file and reboot, my ens160 interface is fine.  Does anyone know what might be happening here?  

Again, I apologize if this isn't the proper forum, and would appreciate info on where to get help.  Thank you very much 

Don

[root@dc1rhel7 network-scripts]# ls -l /sys/class/net
total 0
lrwxrwxrwx 1 root root 0 Apr  2 10:20 ens160 -> ../../devices/pci0000:00/0000:00:16.0/0000:0b:00.0/net/ens160
lrwxrwxrwx 1 root root 0 Apr  2 10:20 lo -> ../../devices/virtual/net/lo
[root@dc1rhel7 network-scripts]# ls -l ./ifcfg*
-rw-r--r--. 1 root root 176 Apr  2 10:19 ./ifcfg-ens160
-rw-r--r--. 1 root root 400 Apr  2 10:19 ./ifcfg-ens192
-rw-r--r--. 1 root root 254 Apr  2 10:19 ./ifcfg-lo
[root@dc1rhel7 network-scripts]# cat ./ifcfg-ens160
DEVICE=ens160
ONBOOT=yes
HWADDR=00:50:56:xx:xx:xx
TYPE=Ethernet
BOOTPROTO=none
IPADDR=10.100.xxx.20
NETMASK=255.255.255.0
DNS1=10.nn.xxx.45
DNS2=10.nn.xxx.164

[root@dc1rhel7 network-scripts]# cat ./ifcfg-ens192
# Generated by dracut initrd
NAME="ens192"
DEVICE="ens192"
ONBOOT="yes"
NETBOOT="yes"
UUID="........blah....."
IPV6INIT="yes"
BOOTPROTO="none"
TYPE="Ethernet"
IPADDR="10.100.xxx.yy"
PREFIX="24"
GATEWAY="10.100.xxx.1"
DNS1="10.nn.xxx.45"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_PEERDNS="yes"
IPV6_PEERROUTES="yes"
IPV6_FAILURE_FATAL="no"

**Comment by sheepnwolfe** [comment]
When I do the same thing, but specify the interface in the cobbler system definition as eth0, rather than ens160, I still get the same behavior ni that I get two ifcfg-<interface> files, but when I specify eth0, I get one with ifcg-eth0, and the other ifcfg-ens160, again with part of the interface definition in each.
Don

**Comment by jmaas** [comment]
not sure that i understand, are you trying to add two interfaces with identical names to a system record?
i think the installer creates a cfg file for the second interface as it probably has link?

**Comment by jmaas** [comment]
also let's move this support issue to: cobbler-users@groups.google.com

**Comment by sheepnwolfe** [comment]
Thank you Jorgen,

I posted on cobbler-users@groups.google.com<mailto:cobbler-users@groups.google.com>, and tried to clarify.

Thanks again!

Don Wolfe
Office:  (925) 948-2829
Mobile:  (925) 239-5941
