### ISSUE TITLE
the provided network interface eth0 does not exist!

### ISSUE THREAD

**Issue by blankorange** [cobbler/cobbler#1885]
That always give me the in sign for below:
the following error was....
the following problem occurred on line 27 of the kickstact file:
the provided network interface eth0 does not exist

And I had try many methods to fix it ,but have no benifits
pls help!mang thanks!

this is my config file
cat centos6.7.ks
#platform=x86, AMD64, or Intel EM64T
# System authorization information
auth  --useshadow  --enablemd5
# System bootloader configuration
bootloader --location=mbr --append="biosdevname=0"
# Partition clearing information
clearpart --all --initlabel
#Partition information
part /boot --ondisk=sda --size=500
part pv.01 --fstype="lvmpv" --ondisk=sda --size=19455
volgroup centos --pesize=4096 pv.01
logvol swap  --fstype="swap" --size=1024 --name=swap --vgname=centos
logvol /   --size=10000 --name=root --vgname=centos

# Use text mode install
text
# Firewall configuration
firewall --disabled
# Run the Setup Agent on first boot
firstboot --disable
# System keyboard
keyboard us
# System language
lang en_US
# Use network installation
url --url=$tree
# If any cobbler repo definitions were referenced in the kickstart profile, include them here.
$yum_repo_stanza
# Network information
$SNIPPET('network_config')
#network --bootproto=dhcp   --device=em1
# Reboot after installation
reboot
 
#Root password
rootpw --iscrypted $default_password_crypted
# SELinux configuration
selinux --disabled
# Do not configure the X Window System
skipx
# System timezone
timezone   Asia/Shanghai
# Install OS instead of upgrade
install
# Clear the Master Boot Record
zerombr
  
%packages
@base
@compat-libraries
@debugging
@development
tree
nmap
sysstat
lrzsz
dos2unix
telnet

%pre
$SNIPPET('log_ks_pre')
$SNIPPET('kickstart_start')
$SNIPPET('pre_install_network_config')
# Enable installation monitoring
$SNIPPET('pre_anamon')

%post
%end

**Comment by blankorange** [comment]
The client is DELL R630
network interface em1

**Comment by santosh0705** [comment]
This is happening because you have not set kernel boot options for installation. Set the `--kopts="biosdevname=0"` for the system and it should work. You also have to add the same for `--kopts-post`.

This could be configured in cobbler settings file as well, check for the `kernel_options`.

**Comment by blankorange** [comment]
@santosh0705 thx your advise,
at the last I found that was I use the wrong config file...
the stupid operation...
