### ISSUE TITLE
Cobbler enable Fips mode RHEL build via kickstart

### ISSUE THREAD

**Issue by kwentuaa** [cobbler/cobbler#1886]
I am building my RHEL6 and 7 boxes. i just migrated from RedHat Satellite to Cobbler and i would like a way to enable fips mode on the systems I am building using cobbler any ideas?

**Comment by jmaas** [comment]
See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/sect-security_guide-federal_standards_and_regulations-federal_information_processing_standard

Add all required actions to your kickstart %post section.
Even better, if you want to contribute to Cobbler, add it to a snippet and submit here via a pull request.
