### ISSUE TITLE
SEEKING NEW MAINTAINERS

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1892]
Dear Cobbler community,

I'm no longer able to commit enough time to this project to drive it forward. I have to apologize to you all; i have been in denial for too long now and it's hurting the Cobbler community. 

So, i'm seeking volunteers to take ownership of driving Cobbler development forward by merging pull requests, maintaining the website, distro signatures and occasionally do a release.

Please indicate your interest in this issue, if you have any track record contributing to Cobbler you will get commit access. This is a chance to contribute to an opensource project that still is quite relevant.

Hope to hear from you!

Regards,
Jörgen

**Comment by jaywcarman** [comment]
Jörgen,

While I don't have a track record of contributing here, I am a python developer working on a project that relies on Cobbler. I'd be happy to help out.

Cheers, Jay

**Comment by jaywcarman** [comment]
@jmaas The project is called POWER-Up (https://github.com/open-power-ref-design-toolkit/power-up). Beyond Cobbler's base functionality it interacts with network switches (allowing automated port detection and configuration) and provides some post OS install cluster configuration (via Ansible playbooks).

**Comment by uberlinuxguy** [comment]
@jmaas I've made only a couple of small additions to Cobbler recently, but our organization has actually embraced cobbler as a core for our provisioning system.  I can foresee us making more contributions in the future, one I just thought of last night that I now realize is similar to what @jaywcarman is doing, but would be directly integrated into cobbler. (I will need to look harder at @jaywcarman's project.)  I would happily volunteer as a maintainer because it would directly effect our efforts going forward.

**Comment by FlorianneRaven** [comment]
Hi @jmaas I'm not a python dev, much more an infrastructure engineer and i'm willing to test cobbler or propose new functionalities, maybe I can work on the documentation and website.
We at my enterprise are using cobbler for deployment of RedHat and CentOS

**Comment by SchoolGuy** [comment]
Okay so it is a while now since I took over and I just wanted to let everyone now who looks in here. The request for new maintainers is still present because cobbler is a complex project and there is much to be done to stabilize it after the Py3 port!

**Comment by Neurozone** [comment]
Too late, we have migrate to foreman

**Comment by SchoolGuy** [comment]
Okay nobody explicitly replied for a while again. While this is something I would very much like to see apparently this issue is not helpful for now. Closing this one because of said things.
