### ISSUE TITLE
cobbler profile and disto are getting deleted?

### ISSUE THREAD

**Issue by ac427** [cobbler/cobbler#1895]
Hello, 
I added new cobbler distro with below script. I tried to import Oracle Linux and it failed, so, I manually created disto and profile. 

I was able to successfully add distro and profile and then systems, but now I don't see any profiles or distro when i do `cobbler profile list` or `cobbler distro list` . What is wrong? I don't see anything in logs? 

```
# rpm -qa   | grep cobbler
cobbler-2.8.2-1.el7.x86_64
```
```
#!/bin/bash 

if [ "$1" == '' ] || [  "$2" == '' ]; then
        echo 'FAIL; pass profile  as arg1 and distro name as arg2'
        exit 1
else

	mount  | grep iso9660 | grep "root/tmp"
	if [ $? -ne 0 ];then
		echo make sure to mount the iso to /root/tmp
		exit 1
	else
		mkdir -p /tftpboot/images/$2/ 
		cp /root/tmp/images/pxeboot/* /tftpboot/images/$2/ 
		cobbler distro add --name=$1 --arch=x86_64 --kernel=/tftpboot/images/$2/vmlinuz --initrd=/tftpboot/images/$2/initrd.img
		cobbler profile add --name=$1 --distro=$1
	fi

fi
```

```
$cobbler profile list
$cobbler distro list
$cobbler system list | wc -l
99
```

according to the manual, i got all the required fields 
http://cobbler.github.io/manuals/2.8.0/3/1/1_-_Distros.html

**Comment by ac427** [comment]
it is similar to https://github.com/cobbler/cobbler/issues/1030. getting removed on cobblerd restart 
I will checked 1030 what the fix was

**Comment by SchoolGuy** [comment]
@ac427 Was your issue resolved or do we need to look for an error?

**Comment by ac427** [comment]
I am not sure if the issue was resolved in any new releases. We switched to a different solution as it was a big blocker.

**Comment by SchoolGuy** [comment]
@ac427 I will leave it then open until I got time to check myself if this is still a thing.

**Comment by watologo1** [comment]
Cleaning up. Old issue which seem to be fixed already closing:

> I will checked 1030 what the fix was
