### ISSUE TITLE
select disk to install system

### ISSUE THREAD

**Issue by buxiaomo** [cobbler/cobbler#1897]
I  have two vm want to  install system, one install system on sda, one install system on sdb,cobbler can select disk to install system?

**Comment by fberndl** [comment]
From the ubuntu seed file example:

# Due notably to potential USB sticks, the location of the MBR can not be
# determined safely in general, so this needs to be specified:
#d-i grub-installer/bootdev  string /dev/sda
# To install to the first device (assuming it is not a USB stick):
#d-i grub-installer/bootdev  string default

**Comment by jmaas** [comment]
you can also use a template variable (eg. $disk) and get that in via the profile ksmeta.

also user questions should go to cobbler-users@groups.google.com

thanks!
