### ISSUE TITLE
phantom entries

### ISSUE THREAD

**Issue by AlanMcKay** [cobbler/cobbler#19]
Looks like some phantom entries are kicking around.  I used to have a "debuglaptop" system defined but removed it with "cobbler system remove".   I don't recall how I removed the SF2250 image but I think it was done with cobbler and not by hacking the filesystem somwhere.

[root@solexa-db ~]# cobbler list
distros:

profiles:

systems:

repos:

images:
   SF2250
   SF2250-1
[root@solexa-db ~]# cobbler image remove --name=SF2250
cobbler.cexceptions.CX:'cannot delete an object that does not exist: debuglaptop'
[root@solexa-db ~]#

**Comment by kallisti5** [comment]
AlanMcKay: Oh! Please email me!   kallisti5 :at: unixzen.com
