### ISSUE TITLE
pip install cobbler is broken

### ISSUE THREAD

**Issue by rothgar** [cobbler/cobbler#1901]
Searching for the pip package I find the cobbler library but it fails to install. From what I can tell the file has been removed wherever it was served.

Maybe someone can either fix or remove the package from pip.

**Comment by opoplawski** [comment]
Yeah, that's ancient.  I think it's up to Michael DeHaan to remove as he is listed and the maintainer on PyPI.

**Comment by rothgar** [comment]
Is there a reason it was removed or another one that will replace it?

**Comment by opoplawski** [comment]
I think pip was long ago abandoned as a delivery mechanism.  Your distribution hopefully has a package.

**Comment by rothgar** [comment]
Oh, I think I misunderstood the pip package. I thought the it was just the python library not the full application. I'll go ahead and just install the distribution package to get the python library I'm looking for.
