### ISSUE TITLE
issues with EL7 + UEFI + Cobbler

### ISSUE THREAD

**Issue by cstackpole** [cobbler/cobbler#1904]
Greetings,

I'm having a heck of a time with UEFI and would appreciate some help. I reached out on the [mailing list](https://groups.google.com/forum/#!forum/cobbler-users), but it is just crickets over there and there is no history to sort through.

I finally discovered the problem that I mentioned on the mailing list, I just don't know how to fix it. All my hosts are Scientific Linux 7.5.

Here's the short of it. If I use the cobbler loaders (even a forced upgrade), everything goes horribly wrong.

From the SL7.5 disk I copied BOOTX64.EFI -> /var/lib/cobbler/loaders/grub-el7-bootx64.efi and grubx64.efi -> /var/lib/cobbler/loaders/grubx64.efi (my hacky way to have cobbler sync those files too). I updated my dhcpd.template file to load grub-el7-bootx64.efi.

Now suddenly, I no longer have weird TFTP issues! Hooray!! But I can't get it to load the kickstart to provision! Ugh.

Well lets look. For some reason some of my hosts have files that look like this:
```
$ cat /var/lib/tftpboot/grub/01-3C-FD-FE-B2-5A-A3 
default=0
timeout=0
splashimage=(nd)/splash.xpm.gz
title local
	quit
```

Well, that is EFI...but nothing tells it to kickstart anything at all.

Other files look like this:
```$ cat /var/lib/tftpboot/grub/01-3C-FD-FE-B2-5C-A7 
default=0
timeout=0

title testhost02
    root (nd)
    kernel /images/SL-7.5-x86_64/vmlinuz  ksdevice=link lang=en_US kssendmac text  ks=http://192.168.1.3/cblr/svc/op/ks/system/testhost02
    initrd /images/SL-7.5-x86_64/initrd.img
```
Better. At least that is a grub menu...too bad that it is the WRONG one. 

So I wrote a nastly little script that basically figured out which host each of the Mac address are in cobbler and dumps out a GRUB2 file instead. Also, notice the new name AND LOWERCASE (ugh, that bit me hard...).
```
$ cat /var/lib/tftpboot/grub/grub.cfg-01-3c-fd-fe-b5-9a-a4
set default="1"

function load_video {
  insmod efi_gop
  insmod efi_uga
  insmod video_bochs
  insmod video_cirrus
  insmod all_video
}

load_video
set gfxpayload=keep
insmod gzio
insmod part_gpt
insmod ext2

set timeout=3
### END /etc/grub.d/00_header ###

search --no-floppy --set=root -l 'Scientific-7.5-x86_64'

### BEGIN /etc/grub.d/10_linux ###
menuentry 'Install Scientific 7.5' --class fedora --class gnu-linux --class gnu --class os {
	linuxefi /images/SL-7.5-x86_64/vmlinuz ksdevice=link lang=en_US kssendmac text  ks=http://192.168.1.3/cblr/svc/op/ks/system/testhost01
	initrdefi /images/SL-7.5-x86_64/initrd.img
}
```
HOORAY! <Insert heavenly rejoicing music here!>

My nodes now boot UEFI with cobbler!! After much dancing and rejoicing, I would really like to figure out how I can get cobbler to write out a correct GRUB2 menu instead of whatever it is  that it's doing now (since it isn't doing any one thing consistently with the nodes I have right now).

Can someone please help? Have I hit a bug with cobbler or am I just doing something wrong? I can't find anything in the docs that relates to EUFI or configuring GRUB2.

Thanks!

**Comment by cheese** [comment]
I need grub2 UEFI support too.
Qemu with tianocore ovmf PXE failed to boot with grub legacy, but worked with grub2.

**Comment by brianredbeard** [comment]
FYI, the likely issue with grub2 is around the presentation of boot_loaders as defined in: `config/cobbler/distro_signatures.json`

Apparently only "ppc64" can use grub2 (which is absolutely not the case).  This may provide a starting point.

**Comment by JohanElmis** [comment]
I will start looking at Grub2 support.

**Comment by JohanElmis** [comment]
CentOS 7 and UEFI doesn't require Grub2 - But I have issues with HP Gen10 servers in UEFI-mode that has issues with the normal grub-x86_64.uefi loader.
DHCP config looks like:
```
        if option arch = 00:07 {
            # UEFI Client
	    filename = "grub/grub-x86_64.efi";
	} else {
            # BIOS Client
            filename "pxelinux.0";
        }
```
So either pxelinux or Grub (v1?) is loaded depending on Bios/Legacy or UEFI mode is configured.

**Comment by negregg** [comment]
I was running into this problem today too with my new HPE Gen 10 servers.  I finally found out the issue was cobbler get-loaders is not pulling down the latest UEFI loaders from cobbler.io.  get-loaders is actually pulling down F15 "grub-x86_64.efi" instead of F17.  If you pull down F17 it works just fine. 

md5sum compares:
f24175db5ffb572764c8cb545418bfd3:  grub-x86_64.efi-f17
3484decda055ec4660637ca12500faf7:  grub-x86_64.efi-f15/get-loaders

That said, I think work on a grub2 implementation is still the way to go ... especially with RHEL 8 around the corner.

I hope this helps someone.

**Comment by MRinalducci** [comment]
Hi,

I have a working Grub2 implementation which basically replaces Grub legacy for extended UEFI support.

If this match everybody needs, I can make a PR. Let me know.

Cheers!

**Comment by jmaas** [comment]
Please do so, please target master and note that master is a bit broken
right now due to the python3 porting effort.
Many thanks in advance!!!

**Comment by MRinalducci** [comment]
Thanks for your input. 👍
I think it is a good idea to have the possibility of also using http instead of tftp.
Please comment on PR as suggested.
