### ISSUE TITLE
VMware Esxi 6.7 fails import.

### ISSUE THREAD

**Issue by raypettersen** [cobbler/cobbler#1909]
Hi

VMware ESXi 6.7 fails import due to lack of matching signature. Both regexp fails, and files are missing which were removed when going from 6.5 to 6.7.

It would be very useful getting 6.7 support incorporated in the signatures.

Regards
Raymond

**Comment by raviak** [comment]
I am also running into same issue , was there any solution ? .. by the way 6.5 works fine and the only issue is with ESXi 6.7 and it throws an error "No signature matched "

Thanks
Anantha

**Comment by alexbrinister** [comment]
I added the proper signature and boot configuration in #1914.

**Comment by jmaas** [comment]
Support has been added in master and release28 branches.
Expect an 2.8 release soon!
