### ISSUE TITLE
Management Classes

### ISSUE THREAD

**Issue by jmk32889** [cobbler/cobbler#1910]
Hi,

I'm having a difficult time understanding how Management Classes are supposed to work. The documentation is pretty light, but it says Cobbler can function as a lightweight CMS. How does it do this? I think I gather from the documentation that this takes place outside of the install process, by what mechanism does that happen? Are packages/template files pushed out from the Cobbler server periodically?

Thank you.

**Comment by jmaas** [comment]
Cobbler uses koan for this, included in all releases.

https://github.com/cobbler/koan/blob/master/docs/man/koan.1.pod
