### ISSUE TITLE
fix_cheetah_class test in templar.py is incorrect

### ISSUE THREAD

**Issue by behanna** [cobbler/cobbler#1918]
We installed cobbler 2.8.3 on top of python-cheetah-3.1.0 on Fedora 28, and kept getting these errors when attempting to generate kickstart files:

    Mon Aug  6 11:54:46 2018 - INFO | REMOTE generate_kickstart; user(?)
    Mon Aug  6 11:54:46 2018 - INFO | generate_kickstart
    Mon Aug  6 11:54:46 2018 - ERROR |
    # *** ERROR ***
    #
    # There is a templating error preventing this file from rendering correctly.
    #
    # This is most likely not due to a bug in Cobbler and is something you can fix.
    #
    # Look at the message below to see what things are causing problems.
    #
    # (1) Does the template file reference a $variable that is not defined?
    # (2) is there a formatting error in a Cheetah directive?
    # (3) Should dollar signs ($) be escaped that are not being escaped?
    #
    # Try fixing the problem and then investigate to see if this message goes
    # away or changes.
    #
    #
    # SNIPPET() takes exactly 2 arguments (1 given)
    #   File "/usr/lib/python2.7/site-packages/cobbler/templar.py", line 208, in render_cheetah
    #     try:
    #
    #   File "cheetah_DynamicallyCompiledCheetahTemplate_1533571609_52_76647.py", line 171, in respond
    #
    #   File "cheetah_DynamicallyCompiledCheetahTemplate_1533571609_52_76647.py", line 71, in __errorCatcher1
    #
    #   File "<string>", line 1, in <module>
    #
    
    Mon Aug  6 11:54:46 2018 - INFO | Exception occured: <class 'cobbler.cexceptions.CX'>
    Mon Aug  6 11:54:46 2018 - INFO | Exception value: 'Error templating file, check cobbler.log for more details'
    Mon Aug  6 11:54:46 2018 - INFO | Exception Info:
      File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 1050, in generate_kickstart
        return self.api.generate_kickstart(profile,system)
       File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 678, in generate_kickstart
        return self.kickgen.generate_kickstart_for_system(system)
       File "/usr/lib/python2.7/site-packages/cobbler/kickgen.py", line 244, in generate_kickstart_for_system
        return self.generate_kickstart(profile=p, system=s)
       File "/usr/lib/python2.7/site-packages/cobbler/kickgen.py", line 277, in generate_kickstart
        data = self.templar.render(raw_data, meta, None, obj)
       File "/usr/lib/python2.7/site-packages/cobbler/templar.py", line 116, in render
        if template_type == "cheetah":
       File "/usr/lib/python2.7/site-packages/cobbler/templar.py", line 215, in render_cheetah
        self.logger.error(utils.cheetah_exc(e))``

Digging in, it looked like the code at templar.py, circa line 200, where `partial()` gets applied to supply the `self` parameter, was getting skipped.  I found that setting `fix_cheetah_class` to `True` fixed my problem, but the right way to fix this is to fix the major, minor,release comparison near the top of the file to use a proper tuple comparison, like so:

    diff --git a/cobbler/templar.py b/cobbler/templar.py
    index 40dbf259..32880407 100644
    --- a/cobbler/templar.py
    +++ b/cobbler/templar.py
    @@ -43,7 +43,7 @@ from template_api import Template
     import utils
     
     major, minor, release = Cheetah.Version.split('.')[0:3]
    -fix_cheetah_class = int(major) >= 2 and int(minor) >= 4 and int(release) >= 2
    +fix_cheetah_class = (int(major),int(minor),int(release)) >= (2,4,2)
     
     
     class Templar:

This fixes my problem completely.

**Comment by jmaas** [comment]
fixed with: https://github.com/cobbler/cobbler/pull/1919
