### ISSUE TITLE
"Images" documentation references a non-existent (ferodahosted) wiki page

### ISSUE THREAD

**Issue by mohag** [cobbler/cobbler#1923]
https://cobbler.github.io/manuals/2.8.0/3/1/4_-_Images.html directs users to fedorahosted for Images documentation.

https://fedorahosted.org/cobbler/wiki/AllAboutImages redirects to a page mentioning that Fedorahosted has been retired.

Other pages with similar issues: (Search for fedorahosted on the pages)
https://cobbler.github.io/manuals/2.8.0/4/3/3_-_Func_Integration.html
https://cobbler.github.io/manuals/2.8.0/Appendix/A_-_S390_Support.html

**Comment by jmaas** [comment]
Thanks for reporting. Fixed in Git.
Need to build new website
