### ISSUE TITLE
Importing HPE ESXI 6.7 into cobbler

### ISSUE THREAD

**Issue by Hyper200** [cobbler/cobbler#1926]
Hi All,

I'm trying to import a HPE specific version of ESXI 6.7 Into cobbler for deployment to a few servers. 

This version has specific drivers which we need on the boxes for various reasons.

When importing i get the follow error:
Mon Sep  3 09:40:36 2018 - ERROR | No signature matched in /var/www/cobbler/ks_mirror/HP-ESXI-6.7-Gen9plus
Mon Sep  3 09:40:36 2018 - ERROR | ### TASK FAILED ###

Should i be able to import this without an issue?

Thanks

Joe.

**Comment by jmaas** [comment]
Die you get them from the release28 branch?

Op ma 3 sep. 2018 14:20 schreef Hyper200 <notifications@github.com>:

**Comment by Hyper200** [comment]
@jmaas 

I wasn't sure so i re-downloaded release 28, which definitely gets the same issue.

**Comment by Jhongturney** [comment]
@Hyper200 @jmaas 
Edit the distro_signatures.json file for the new esxi 6.7 entry, line 988 so that "default_autoinstall" is "default_kickstart" and it should work.  I submitted this as a PR already as well.

**Comment by Jhongturney** [comment]
@jmaas Any chance this little fix gets put into a release?  I'm trying to build my own rpm from the release28 branch with an edit to this file included, but OSX is making it hard.  It's very critical for our operations at the moment...

**Comment by Hyper200** [comment]
I can confirm this works @Jhongturney 

Thank you.

**Comment by jmaas** [comment]
Fixes were indeed merged into release28.
A release will follow soon!
