### ISSUE TITLE
debian templates does not work as expected

### ISSUE THREAD

**Issue by LooOOooM** [cobbler/cobbler#1928]
I am trying to install a debian maschine, which works for a basic installation fine. The maschine got two networkcards inside: one for the installation and the other one for the later realase use.

In this particular case I am trying to customize the snippet "post_install_network_config_deb" however every single change (commenting out anything) will result in differnt errors.

In case I uncomment onyl the realy first if statment (2nd line:  "if $getVar("system_name","") != ""') and the belonging closing 'end if' in the last before last line, the installation will stopwith the message:
"log-out: /bin/sh: 93: Syntax error: end of file unexpected (expecting "then")"

Another case is if I uncomment the following block in order to set static routes:
```

        #for $route in $static_routes
            #set routepattern = $re.compile("[0-9/.]+:[0-9.]+")
            #if $routepattern.match($route)
                #set [$network, $router] = $route.split(":")
echo "   up ip route add $network via $router dev $iname || true" >> /etc/network/interfaces
            #else
echo "   # Warning: invalid route: $route" >> /etc/network/interfaces
            #end if
        #end for
```

the installation is also hanging with the followign Error:
log-output: /bin/sh: 18: Syntax error: Bad for loop variable

I am using the latest cobbler 2.8 what am I doing wrong ?

**Comment by jmaas** [comment]
The # isn't a comment, it's how the Cheetah templating stuff works.
http://cheetahtemplate.org/

Other questions should go to the mailinglist @ groups.google.com

Thanks!
