### ISSUE TITLE
Python3: Switch form createrepo to createrepo_c

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#1930]
Since `createrepo` is [not being ported to Python3](http://fedora.portingdb.xyz/pkg/createrepo/), we have to think of an alternative. [createrepo_c](https://github.com/rpm-software-management/createrepo_c) seems to be a good candidate. Has anybody worked with this already?

**Comment by jmaas** [comment]
I have not!

**Comment by jmaas** [comment]
Would be great if you could start working on that.

Right now, i have cobblerd running on python 3.7 (fedora29).
But many, many things are still broken.
I hope to merge to master rather soon so that others can help out :)

**Comment by brejoc** [comment]
@jmaas That would be good, because I've also started working on a Py3 port. Maybe we can join forces here!?

**Comment by brejoc** [comment]
I've checked the man pages and the only thing that differs and is being used by cobbler is `--deltas`. This flag is missing in `createrepo_c`, although `createrepo_c` has a dependency on `deltarpm`. So this won't be exactly a drop in replacement but still shouldn't be that hard.

**Comment by jmaas** [comment]
Go for it by all means :)

I'm not currently using/testing this feature, so i'm not yet in the
position to drive the changes on this topic. Based on your analysis my
guess is that the createrepo_c implementation uses deltas by default.

**Comment by Conan-Kudo** [comment]
@brejoc the `--deltas` switch is missing in SUSE's `createrepo_c` because it was disabled when my package was forked by the OBS people. It is normally supported.

**Comment by Conan-Kudo** [comment]
@brejoc It's not difficult to enable for SUSE either, as I already have the `libdrpm` dependency packaged in my OBS project, it's just not in Factory, which is what is required to enable the code that allows the `--deltas` switch.

**Comment by brejoc** [comment]
@Conan-Kudo We can try to. But wasn't the deadline for adding new pkgs to SLES15SP1 last Friday?

**Comment by Conan-Kudo** [comment]
@brejoc So an update on this: `createrepo_c` in openSUSE Tumbleweed now supports `--deltas`, so it's fully at parity in terms of functionality.

I'm hopeful that @juliogonzalez will be able to get the version in Tumbleweed backported for Leap 15.2. In any case, we can ship a build of `createrepo_c` in the cobbler OBS project that has DeltaRPM support turned on, as the necessary dependency is now present in Leap (libdrpm).

We should also tie this together with migrating the YUM code to exclusively use DNF (#1980).

**Comment by SchoolGuy** [comment]
Okay it seems that the exchange to `createrepo_c` is now done. I will close this for now.
