### ISSUE TITLE
Python3: Alternative for python-urlgrabber

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#1931]
`python-urlgrabber` [won't be ported to Python3](http://fedora.portingdb.xyz/pkg/python-urlgrabber/) and I'm thinking about the alternatives. The Fedora _Python 3 Porting Database_ suggests [`pycurl`](https://pypi.org/project/pycurl/). But there is also [`requests`](https://pypi.org/project/requests/). Do you have any preferences here?

**Comment by jmaas** [comment]
I think requests is the best way forward.

**Comment by jmaas** [comment]
It needs to be portable across distros, requests is readily available on
all platforms

**Comment by brejoc** [comment]
@jmaas I guess this can be closed. Feel free to re-open of you think we should keep it.

**Comment by Conan-Kudo** [comment]
For what it's worth, `urlgrabber` 4.x is Python 3 compatible.
