### ISSUE TITLE
diskless linux provisioning  ramdisk approach though cobbler

### ISSUE THREAD

**Issue by pharthiphan** [cobbler/cobbler#1933]
Hi,

I am looking for a tool to provision Linux distro's such as CentOS, SLES and Ubuntu in disk-less method i.e ramdisk approach.

I have limited hardware x86 where I would need to test my application on different OS Distro's and Version. Installing OS on to disk is time consuming having the slower drives and installing Mellanox Infiniband/ Intel OPA drivers.

is it possible to use cobbler for this purpose or any other tool that you guys can suggest.

**Comment by jmaas** [comment]
I'm not aware of any one doing this. Please try the cobbler mailing list (groups.google.com)
