### ISSUE TITLE
Having issues with Cobbler Import 

### ISSUE THREAD

**Issue by rahulmula** [cobbler/cobbler#1934]
Hi Team..

Could you please help on this ? while adding cobbler import getting below issue.

sudo cobbler import --name=centOS-6.3-x86_64 --path=/mnt

task started: 2018-10-04_025739_import
task started (id=Media import, time=Thu Oct  4 02:57:39 2018)
Found a candidate signature: breed=redhat, version=rhel6
Found a candidate signature: breed=redhat, version=rhel7
Found a candidate signature: breed=redhat, version=fedora20
Found a candidate signature: breed=redhat, version=fedora16
Found a candidate signature: breed=redhat, version=fedora17
Found a candidate signature: breed=redhat, version=fedora18
Found a candidate signature: breed=redhat, version=fedora19
No signature matched in /var/www/cobbler/ks_mirror/centOS-6.3-x86_64
!!! TASK FAILED !!!

Cobbler Version

Cobbler 2.4.1
  source: ?, ?
  build time: Thu Feb 20 09:59:20 2014

Thanks in Advance

**Comment by jmaas** [comment]
Go update to a recent version first please.
2.4 is way too old; you should get latest 2.8.x.
2.4 and 2.6 are not supported.
