### ISSUE TITLE
cobbler 2.8.3 replicate fails, but task completes 

### ISSUE THREAD

**Issue by zdudic** [cobbler/cobbler#1935]
Hi, I just setup two of these servers, have imported one distro and created one profile in "master". Now want to replicate to my 'slave' and it fails without much explanation, here is the output:  

[root@host]# cobbler replicate --master=mymaster --use-ssl
task started: 2018-10-05_152901_replicate
task started (id=Replicate, time=Fri Oct  5 15:29:01 2018)
cobbler_master      = mymaster
distro_patterns     = []
profile_patterns    = []
system_patterns     = []
repo_patterns       = []
image_patterns      = []
mgmtclass_patterns  = []
package_patterns    = []
file_patterns       = []
omit_data           = False
sync_all            = False
use_ssl             = True
XMLRPC endpoint: https://mymaster:/cobbler_api
test ALPHA
test BETA
Querying Both Servers
remote names struct is {'profile': ['OL-R7-U5-x86_64_attended'], 'package': [], 'mgmtclass': [], 'image': [], 'system': [], 'repo': [], 'file': [], 'distro': ['OL-R7-U5-x86_64']}
* Finding Explicit distro Matches
* Finding Explicit profile Matches
* Finding Explicit system Matches
* Finding Explicit repo Matches
* Finding Explicit image Matches
* Finding Explicit mgmtclass Matches
* Finding Explicit package Matches
* Finding Explicit file Matches
* Adding Profiles Required By Systems
* Adding Profiles Required By SubProfiles
* Adding Distros Required By Profiles
* Adding Repos Required By Profiles
* Adding Images Required By Systems
transfer list for distro is []
transfer list for profile is []
transfer list for system is []
transfer list for repo is []
transfer list for image is []
transfer list for mgmtclass is []
transfer list for package is []
transfer list for file is []
*NOT* Removing Objects Not Stored On Master
Rsyncing distros
Rsyncing repos
Rsyncing distro repo configs
running: rsync -avzH mymaster::cobbler-distros/config/ /var/www/cobbler/ks_mirror/config
received on stdout:
received on stderr: rsync: failed to connect to mymaster (IP): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

rsync failed
Rsyncing kickstart templates & snippets
running: rsync -avzH mymaster::cobbler-kickstarts /var/lib/cobbler/kickstarts
received on stdout:
received on stderr: rsync: failed to connect to mymaster (IP): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

rsync failed
running: rsync -avzH mymaster::cobbler-snippets /var/lib/cobbler/snippets
received on stdout:
received on stderr: rsync: failed to connect to mymaster (IP): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

rsync failed
Rsyncing triggers
running: rsync -avzH mymaster::cobbler-triggers /var/lib/cobbler/triggers
received on stdout:
received on stderr: rsync: failed to connect to mymaster (ip): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

rsync failed
Rsyncing scripts
running: rsync -avzH mymaster::cobbler-scripts /var/lib/cobbler/scripts
received on stdout:
received on stderr: rsync: failed to connect to mymaster (ip): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

rsync failed
Removing Objects Not Stored On Local
Updating Objects Newer On Remote
Syncing
running pre-sync triggers
cleaning trees
removing: /tftpboot/pxelinux.cfg/default
removing: /tftpboot/grub/images
removing: /tftpboot/grub/efidefault
removing: /tftpboot/s390x/profile_list
copying bootloaders
copying distros to tftpboot
copying images
generating PXE configuration files
generating PXE menu structure
rendering TFTPD files
generating /etc/xinetd.d/tftp
cleaning link caches
running post-sync triggers
running python triggers from /var/lib/cobbler/triggers/sync/post/*
running python trigger cobbler.modules.sync_post_restart_services
running shell triggers from /var/lib/cobbler/triggers/sync/post/*
running python triggers from /var/lib/cobbler/triggers/change/*
running python trigger cobbler.modules.scm_track
running shell triggers from /var/lib/cobbler/triggers/change/*
Done
*** TASK COMPLETE ***

No other errors. The ssh keys are used and manually running rsync between these servers works.

**Comment by jmaas** [comment]
Did you set up rsyncd ?

**Comment by zdudic** [comment]
Right, I've already realized that was mistake and had filed this issue prematurely, sorry for the noise.
