### ISSUE TITLE
Plans for Cobbler package/support on Ubuntu 18.04 ?

### ISSUE THREAD

**Issue by ghost** [cobbler/cobbler#1941]
Have cobbler on Ubuntu 16.04 and 14.04 and all working fine and can use these to build Ubuntu 18.04 hosts but having to move the Cobbler host itself to 18.04 soon.

A manual make install of Cobbler on Ubuntu 18.04 (master branch due to django fixes) does not currently work due to issues with cobbler sync/iso import. Python producing all sorts of errors.

Plus there is no cobbler package currently in the Ubuntu 18.04 repo

Any plans would be useful

**Comment by JohanElmis** [comment]
Python 3 issue?
What version of Python did you use previously (on your working cobbler-servers).
I think I have seen some tickets about Python3 already - and that it's not compatible. Can you install and run Python 2.7? on 18.04 ?

**Comment by Deanosim** [comment]
1+ to this I would really like to see Cobbler on Ubuntu 18.04

**Comment by law** [comment]
Thirded.

**Comment by watologo1** [comment]
There are and will be quite some changes in 3.0.
Specifically some which affect (distro specific) packaging.
It would be great if someone can help with testing on Ubuntu and help to fix up packaging.
Please stay tuned, there will be some major changes and quite some cleanups in master soon.
It would be great if one of you can push updating and test building on Ubuntu soon.

**Comment by mercury00** [comment]
I will help test anything you need tested.

Python 2 will be deprecated entirely January 1st 2020. Thats in about 7 months or so. Currently I have multiple issues trying to use cobbler to provision ubuntu hosts, and I'm almost entirely ubuntu based (300+ machines).

**Comment by brejoc** [comment]
@mercury00 There was some progress [here](https://github.com/cobbler/cobbler/pull/2055). Maybe you could give it a try and provide some feedback? Thanks!

**Comment by Conan-Kudo** [comment]
I've added Debian/Ubuntu package build support to the spec file we use for all other distributions. When we cut a new release from master, we can make a repository available with builds of the cobbler packages for supported distributions along with any necessary backports to satisfy missing dependencies.

**Comment by Conan-Kudo** [comment]
For the time being, you can try out snapshot builds of cobbler by [following these instructions](https://software.opensuse.org//download.html?project=home%3APharaoh_Atem%3Acobbler-dev&package=cobbler).

**Comment by SchoolGuy** [comment]
18.04 added through @Conan-Kudo's specfile rewrite. This can now be closed. Native support from Ubuntu should be done by the Ubuntu/Debian community. We are of course open to PRs!
