### ISSUE TITLE
Set enable_gpxe to True from profile,  device boot from pxe menu will hang!

### ISSUE THREAD

**Issue by wanghaiqing2015** [cobbler/cobbler#1942]
![small_1111111111111](https://user-images.githubusercontent.com/11815186/47897930-a6dd5900-deae-11e8-9bca-42d72f77b3ee.jpg)

**Comment by wanghaiqing2015** [comment]
Cobbler 2.8.3
OS: Centos7.3-7.4

**Comment by SchoolGuy** [comment]
@wanghaiqing2015 Please add steps to reproduce this error or we have to close it as invalid.
