### ISSUE TITLE
Centos6.10 password does not take effect

### ISSUE THREAD

**Issue by Eddy1210** [cobbler/cobbler#1945]
openssl passwd -1 -salt 'random-phrase-here' 'passwd'

vim /etc/cobbler/settings
```
default_password_crypted: "$1$random-p$65IGuYa9EuVZOGN0RRQ201"
```
vim /var/lib/cobbler/kickstarts/CentOS-6.10-x86_64.cfg
```
rootpw --iscrypted $default_password_crypted
```
but
![image](https://user-images.githubusercontent.com/18549520/48837798-4bbdc880-edc1-11e8-9f44-3906c5082c9e.png)

**Comment by JohanElmis** [comment]
Just an idea, maybe CentOS 6.10 doesn't allow the MD5 hashed passwords - and that invalidates the encrypted password that you supplies.

The default Password algorithm is sha-512, which is a lot more secure than MD5 (and generates a lot longer hashes).
See: https://unix.stackexchange.com/questions/81240/manually-generate-password-for-etc-shadow and https://www.thegeekdiary.com/centos-rhel-how-to-change-password-hashing-algorithm/

**Comment by jmaas** [comment]
Indeed, check the hashing method that is expected:
```authconfig --test | grep hashing```

then create an appropriate salted hash.
