### ISSUE TITLE
Replacing mod_python

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#1948]
Due to the fact that the current status of the `mod_python` apache2 module is "dropped" or at least "not actively maintained" I propose that cobbler moved onwards to a replacement of `mod_python`. On SUSE based distros there is currently no possibility to install `mod_python` without using non-official packages. Also my search on Ubuntu was not successfull.

A candidate which should be considered for replacing it should be `mod_wsgi` in my eyes.

**Comment by opoplawski** [comment]
So, near as I can tell, this was already done long ago, but setup.py was never changed to require mod_wsgi instead?
