### ISSUE TITLE
Profile add doesn't verify the distribution.

### ISSUE THREAD

**Issue by JohanElmis** [cobbler/cobbler#1956]
Cobbler 2.8.4 (and previous 2.8 versions) doesn't validate that the required distribution is set.
I missed the '--' on the --distro= and with no proper error it took me a while to figure this out.

In the code there is a check_if_valid() in item_profile.py that is called with distro is None.
Not seeing the message from a raised CX error, but it looks like it's called.

Can't find my way in the code, so I hope that someone can easily fix this.
Just try it like below.  (skipping parent or distro) - you get no error - but it's failing. 

[root@kickstart cobbler]# cobbler profile add  --name=techops-761 --kopts='audit=1 inst.text inst.ks.sendmac inst.sshd net.ifnames=0 biosdevname=0' --repo='' --kickstart='/var/lib/cobbler/kickstarts/techops-76.ks' --owners='admin' --virt-type=xenpv
[root@kickstart cobbler]# cobbler profile list
   techops-76

# Logfile
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - DEBUG | get_item; ['profile', 'techops-761']
Thu Dec 13 18:33:02 2018 - DEBUG | done with get_item; ['profile', 'techops-761']
Thu Dec 13 18:33:02 2018 - INFO | REMOTE new_item(profile); user(<DIRECT>)
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - INFO | REMOTE modify_item(profile); user(<DIRECT>); object_id(___NEW___profile::WU7ilxWY7m6OcdQVT/PSB0HV1lgJkSjOew==); attribute(owners)
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - INFO | REMOTE modify_item(profile); user(<DIRECT>); object_id(___NEW___profile::WU7ilxWY7m6OcdQVT/PSB0HV1lgJkSjOew==); attribute(kickstart)
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - INFO | REMOTE modify_item(profile); user(<DIRECT>); object_id(___NEW___profile::WU7ilxWY7m6OcdQVT/PSB0HV1lgJkSjOew==); attribute(name)
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - INFO | REMOTE modify_item(profile); user(<DIRECT>); object_id(___NEW___profile::WU7ilxWY7m6OcdQVT/PSB0HV1lgJkSjOew==); attribute(virt_type)
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - INFO | REMOTE modify_item(profile); user(<DIRECT>); object_id(___NEW___profile::WU7ilxWY7m6OcdQVT/PSB0HV1lgJkSjOew==); attribute(repos)
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - INFO | REMOTE modify_item(profile); user(<DIRECT>); object_id(___NEW___profile::WU7ilxWY7m6OcdQVT/PSB0HV1lgJkSjOew==); attribute(kernel_options)
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - INFO | REMOTE modify_item(profile); user(<DIRECT>); object_id(___NEW___profile::WU7ilxWY7m6OcdQVT/PSB0HV1lgJkSjOew==); attribute(in_place)
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - INFO | REMOTE save_item(profile); user(<DIRECT>); object_id(___NEW___profile::WU7ilxWY7m6OcdQVT/PSB0HV1lgJkSjOew==)
Thu Dec 13 18:33:02 2018 - DEBUG | REMOTE CLI Authorized; user(?)
Thu Dec 13 18:33:02 2018 - INFO | add_item(profile); ['techops-761']
Thu Dec 13 18:33:02 2018 - DEBUG | get_items; ['profile']
Thu Dec 13 18:33:02 2018 - DEBUG | done with get_items; ['profile']
Thu Dec 13 18:33:19 2018 - DEBUG | get_items; ['profile']
Thu Dec 13 18:33:19 2018 - DEBUG | done with get_items; ['profile']

**Comment by SchoolGuy** [comment]
So a Profile without a Distro cannot exist currently. We should have tests. If we find this again we will open a bug against the current version again.
