### ISSUE TITLE
OpenSuSE: 'getpwnam(): name not found: apache'

### ISSUE THREAD

**Issue by grisu48** [cobbler/cobbler#1957]
Hi, I'm having problems to get cobbler run in the current OpenSuSE LEAP 15.0. On a fresh and updated install I want to run cobblerd and it quits with the following error

    systemctl status cobblerd
    [...]
    Dec 17 14:31:03 hydrogen cobblerd[3162]: Traceback (most recent call last):
    Dec 17 14:31:03 hydrogen cobblerd[3162]:   File "/usr/bin/cobblerd", line 90, in main
    Dec 17 14:31:03 hydrogen cobblerd[3162]:     app.core(api)
    Dec 17 14:31:03 hydrogen cobblerd[3162]:   File "/usr/lib/python2.7/site-packages/cobbler/cobblerd.py", line 43, in core
    Dec 17 14:31:03 hydrogen cobblerd[3162]:     regen_ss_file()
    Dec 17 14:31:03 hydrogen cobblerd[3162]:   File "/usr/lib/python2.7/site-packages/cobbler/cobblerd.py", line 64, in regen_ss_file
    Dec 17 14:31:03 hydrogen cobblerd[3162]:     os.lchown("/var/lib/cobbler/web.ss", pwd.getpwnam(http_user)[2], -1)
    Dec 17 14:31:03 hydrogen cobblerd[3162]: KeyError: 'getpwnam(): name not found: apache'

I could trace back the issue to the function `utils.check_dist()` in cobblerd.py:62 which results in an empty string being returned. The check returns `dist = platform.linux_distribution()[0].lower().strip()`, and that seems to returns an empty string.
I tested the following in a `python` environment:

    $ python
    Python 2.7.14 (default, Oct 12 2017, 15:50:02) [GCC] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import platform
    >>> dist = platform.linux_distribution()[0].lower().strip()
    >>> dist
    ''

I have added the user `apache` and the daemon started successfully, although this is not an elegant or intended solution. Is there anything known about this issue?

Greetings,
Felix

**Comment by brejoc** [comment]
This is a long standing [issue](https://bugs.python.org/issue1322) with Python. There are plans to remove `platform.linux_distribution()` from Python. One not too bad solution would be to switch to [distro](https://pypi.org/project/distro/). The project seems to be actively maintained and the switch wouldn't cause too much trouble.

**Comment by jmaas** [comment]
This issue has  been fixed in the futurize branch, this will get  merged into master soon.
