### ISSUE TITLE
Wrong OS Version after importing Centos7.6

### ISSUE THREAD

**Issue by wchang** [cobbler/cobbler#1960]
Hi all,
When I'm trying to import centos7.6-x86_64, cobbler gives me wrong "OS Version". I think it should be "rhel7"
My Cobbler version is 2.8.4
Please help me to correct the issue, thanks a lot.

#cobbler distro report --name=centos7-6-x86_64
Name                           : centos7-6-x86_64
Architecture                   : x86_64
TFTP Boot Files                : {}
Breed                          : redhat
Comment                        :
Fetchable Files                : {}
Initrd                         : /var/www/cobbler/ks_mirror/centos7-6-x86_64/images/pxeboot/initrd.img
Kernel                         : /var/www/cobbler/ks_mirror/centos7-6-x86_64/images/pxeboot/vmlinuz
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Kickstart Metadata             : {'tree': 'http://@@http_server@@/cblr/links/centos7-6-x86_64'}
Management Classes             : []
**OS Version                     : rhel6**
Owners                         : ['admin']
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Template Files                 : {}

**Comment by martindka** [comment]
try in cli: 
cobbler profile edit name=centos7-6-x86_64 --os-version rhel7

you can avoid it when you import it:
cobbler import --name=centos7-6-x86_64 --arch=x86_64 --os-version rhel7 --breed redhat --path=/mnt/iso
