### ISSUE TITLE
master branch fails to build rpm

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#1972]
```
changing mode of /export/home/orion/redhat/BUILDROOT/cobbler-2.8.4-5.el7.x86_64/usr/share/cobbler/web
warning: install: Could not change owner: You have insufficient permissions.

changing mode of /var/lib/cobbler/webui_sessions
error: /var/lib/cobbler/webui_sessions: No such file or directory
```
It's not properly adding the buildroot path to the front of /var/lib/cobbler/webui_sessions

**Comment by jmaas** [comment]
futurize has been merged into master (same problem persists though).

**Comment by opoplawski** [comment]
Well, I was hoping someone else would know what to change.  I'm not super familiar with setuptools.

**Comment by opoplawski** [comment]
I believe this broke with c1e83f208cc7c7e5943e004c640539fed1440d70

Re-opening

**Comment by jmaas** [comment]
I can built the RPM on F29 as root.
You are trying this as non-root ??

**Comment by brejoc** [comment]
We are currently building an RPM here. Maybe it's worth to check: https://build.opensuse.org/package/show/home:trenn:cobbler3/cobbler3

**Comment by jmaas** [comment]
@opoplawski i just tried it on f29 with user-level permissions, seems to work for me.

is this still an issue for you?

**Comment by opoplawski** [comment]
So it does seem to work for me on Fedora, but not on EL7 - python 3.4 and setuptools 39.2.0.

**Comment by martindka** [comment]
Cobbler 2.8 with python 3.4? Are you kidding me? It is python 2.7 application.

**Comment by SchoolGuy** [comment]
@opoplawski Is this one stil relevant or can we close this. If not what needs actually to be fixed?

**Comment by opoplawski** [comment]
I think we're good now.

**Comment by hbokh** [comment]
Re-open, please.
This still seems to be an issue in builds I see over the last weeks.
See this Travic CI log from March 2, 2020: https://travis-ci.org/cobbler/cobbler/jobs/657281552#L3123

In the regular Debian builds, I patched it like this:
```diff
# cat debian/patches/fix-webui_sessions-error.patch
Re-added self.root to the webui_session part.

--- a/setup.py
+++ b/setup.py
@@ -331,7 +331,7 @@
             raise Exception("libpath is not absolute.")
         # libpath is hardcoded in the code everywhere
         # therefor cant relocate using self.root
-        path = os.path.join(libpath, 'webui_sessions')
+        path = os.path.join(self.root + libpath, 'webui_sessions')
         try:
             self.change_owner(path, http_user)
         except Exception as e:
```

**Comment by SchoolGuy** [comment]
@hbokh Is this all the time a general solution or just when you build the package via rpm/deb? What happens on a pip install? :thinking:
