### ISSUE TITLE
Permission denied while accessing cobbler_web

### ISSUE THREAD

**Issue by prasuprasobh** [cobbler/cobbler#1973]
Hello All...

I am getting below error message while accessing the cobbler_web.

````
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /cobbler_web
on this server.</p>
</body></html>
[root@testcobbler ~]#
````

Please find the configuration details and let me know your suggestion

````
# more cobbler_web.conf
# This configuration file enables the cobbler web
# interface (django version)

<Directory "/usr/share/cobbler/web/">
        <IfModule mod_ssl.c>
            SSLRequireSSL
        </IfModule>
        <IfModule mod_nss.c>
            NSSRequireSSL
        </IfModule>
        SetEnv VIRTUALENV
        Options Indexes MultiViews
        AllowOverride None
        Order allow,deny
        Allow from all
</Directory>

<Directory "/var/www/cobbler_webui_content/">
        <IfModule mod_ssl.c>
            SSLRequireSSL
        </IfModule>
        <IfModule mod_nss.c>
            NSSRequireSSL
        </IfModule>
        Options +Indexes +FollowSymLinks
        AllowOverride None
        Order allow,deny
        Allow from all
</Directory>

# Use separate process group for wsgi
WSGISocketPrefix /var/run/wsgi
WSGIScriptAlias /cobbler_web /usr/share/cobbler/web/cobbler.wsgi
WSGIDaemonProcess cobbler_web display-name=%{GROUP}
WSGIProcessGroup cobbler_web
WSGIPassAuthorization On

<IfVersion >= 2.4>
    <Location /cobbler_web>
        Require all granted
    </Location>
    <Location /cobbler_webui_content>
        Require all granted
    </Location>
</IfVersion>
````

**Comment by martindka** [comment]
Answered in: https://github.com/cobbler/cobbler/issues/2008

**Comment by Laurel-rao** [comment]
I know the solution that resolved this issue, everybody attention here. 
<h1>Check you url isn't http</h1>
<h1>Because cobbler support https only!</h1>
- It's take a long time to resolve the questions.And it exhaust me!!!

``` 
    # use this url
    https://192.168.1.110/cobbler_web/
```

**Comment by watologo1** [comment]
I am going to close this one.
The description itself is really poor as well.
The reason it does not work may be due to not working SSL (could be tried by removing SSLRequireSSL tags, restart apache and cobbler and try again).
But it can be anything else. A closer look has to be taken. For example apache access and error log file and possibly (if it's not SSL and things start to get through) cobbler may log detailed errors which lead to the general "403 Forbidden" html answer...

**Comment by bomblevijay** [comment]
I have also having same issue .I have checked ssl error log then found error access/usr/share/cobbler/web/cobbler.wsgi failed ssl required"
Please let me know if have any solution on it

**Comment by onunixme** [comment]
Cobbler Web is use only SSL module. Do comments to NSS module line.

<Directory "/usr/share/cobbler/web/">
        <IfModule mod_ssl.c>
            SSLRequireSSL
        </IfModule>
        **#<IfModule mod_nss.c>
        #    NSSRequireSSL
        #</IfModule>**
        SetEnv VIRTUALENV
        Options Indexes MultiViews
        AllowOverride None
        Order allow,deny
        Allow from all
</Directory>

<Directory "/var/www/cobbler_webui_content/">
        <IfModule mod_ssl.c>
            SSLRequireSSL
        </IfModule>
        **#<IfModule mod_nss.c>
        #    NSSRequireSSL
        #</IfModule>**
        Options +Indexes +FollowSymLinks
        AllowOverride None
        Order allow,deny
        Allow from all
</Directory>

**Comment by SchoolGuy** [comment]
This issue is not an error in cobbler directly it is a combination of a currently complicated setup and missing documentation.

**Comment by watologo1** [comment]
Enno is right, you have to setup SSL correctly. I haven't done myself, but for a quick test simply commented out both. These:
        #<IfModule mod_nss.c>
        #    NSSRequireSSL
        #</IfModule>
but also these:
        <IfModule mod_ssl.c>
            SSLRequireSSL
        </IfModule>
(iirc there are at least 2 of these SSLRequireSSL configs).
I could then double check that I do not need the web interface and that I do not need to fiddle with certificates or whatever is needed to setup SSL...
You could do the same for testing/debugging purpose, but you should setup SSL when you decide to switch to production.

I guess we can close this one as well?
@bomblevijay : If you set up SSL successfully, a link to an up-to-date documentation or some quick guide for our docs would be very much appreciated.

**Comment by leconk** [comment]
In our lab we are using the self-generated certs. To get this to work I modified the file /etc/httpd/conf.d/cobbler_web.conf I added the following to the virtualhost config:
<VirtualHost *:443>
    ServerName www.example.com
    SSLEngine on
     SSLCipherSuite PROFILE=SYSTEM
     SSLCertificateFile /etc/pki/tls/certs/localhost.crt
     SSLCertificateKeyFile /etc/pki/tls/private/localhost.key
</VirtualHost>

Then restart the httpd server using "apachectl restart"
The cobbler_web UI is then accessible over https after accepting the self-signed cert in the browser.

**Comment by SchoolGuy** [comment]
The webinterface will be removed with 3.3.0 and thus I will close this issue. A new interface will be created when the Team has time and resources for it.
