### ISSUE TITLE
Merge futurize into master?

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1983]
Shall we go ahead and merge futurize into master?
Yes the tree is not in a great shape yet and lots of stuff is still broken.

But it would ease any development efforts from other parties, and hopefully other people will contribute fixes for issues they run into. Also there's no way back :)

What are your thoughts @brejoc  ?

**Comment by brejoc** [comment]
There is indeed no way back! :smile:

Most of the basic stuff should be working now. We can add/remove distros, profiles and systems. `buildiso` should work and even a `sync` shows no error. But I certainly can't guarantee that everything is there. So we can't say master is stable, but at least it's not completely useless. So if that's okay, we can proceed this merging this to master. :+1:

**Comment by jmaas** [comment]
Done! Also removing the futurize branch.
