### ISSUE TITLE
Landscape failure

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#1988]
While checking the toolchain, I discoverd that it seems to be the case that the landscape setup is brocken. [Landscape](https://landscape.io/github/cobbler/cobbler) The last checks it did failed due to unknow reasons.

**Comment by jmaas** [comment]
Landscape itself is broken, i've given up on it.
I've now integrated codacy... just checking to see if it's nice.
I'm open to any other and better options as long as they are free.
Closing this issue.
