### ISSUE TITLE
pxe_just_once not working as expected in 2.8.4

### ISSUE THREAD

**Issue by paddyoneill** [cobbler/cobbler#2015]
I installed cobbler 2.8.4 on CentOS 7 from EPEL. 

[root@deploy ~]# cobbler --version
Cobbler 2.8.4
  source: ?, ?
  build time: Mon Nov 26 18:51:25 2018

I have created a distro and profile, and added a test system which installs the profile. 

I have set 'pxe_just_once: 1' in /etc/cobbler/settings but after the test system finishes installing it just PXE boots again and gets stuck in an infinite loop of rebooting and installing. From what I have read about this, setting pxe_just_once should cause the system definition to be automatically updated to set  "Netboot Enabled" to false, but this is not happening. 

I have checked the kickstart script and it does have "$SNIPPET('kickstart_done')" at the end.

**Comment by wanghaiqing2015** [comment]
i worked normally.

**Comment by mercury00** [comment]
I'm also encountering this issue. `pxe_just_once` does not take effect, snippet enabled for 'kickstart_done'.

Help.

**Comment by kwizart** [comment]
I don't reproduce with 2.5.0-0.1 currently in epel-testing... (with SELinux Enforced)
That been said, I have anamon issue to write log in the cobbler side (but it's unrelated).

**Comment by mercury00** [comment]
This is actually working for me fine. I don't believe it's a issue with cobbler at all.

**Comment by SchoolGuy** [comment]
Then we close this for now.
