### ISSUE TITLE
XMLRPC responses changed in 3.x

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#2030]
Here is an example for the login:

Cobbler 3.x with Python3:
```xml
<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><base64>…</base64></value>
</param>
</params>
</methodResponse>
```

Cobbler 2.6.6 with Python2:
```xml
<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><string>…</string></value>
</param>
</params>
</methodResponse>
```

Looks like Cobbler is just marshalling Python objects to XML. With Python3 some of the types have changed. And it looks like this is happening in several places. @jmaas, what is you point of view here? Shouldn't Cobbler stick to the "old" API? That would of course be better for people expecting the returned XML structure to be the same.

**Comment by watologo1** [comment]
On Wednesday, February 27, 2019 9:29:58 AM CET Jochen Breuer wrote:
> Here is an example for the login:
> 
> Cobbler 3.x with Python3:
> ```xml
> <?xml version='1.0'?>
> <methodResponse>
> <params>
> <param>
> <value><base64>…</base64></value>
> </param>
> </params>
> </methodResponse>
> ```
> 
> Cobbler 2.6.6 with Python2:
> ```xml
> <?xml version='1.0'?>
> <methodResponse>
> <params>
> <param>
> <value><string>…</string></value>
> </param>
> </params>
> </methodResponse>
> ```
> 
> Looks like Cobbler is just marshalling Python objects to XML. With Python3
> some of the types have changed. And it looks like this is happening in
> several places. @jmaas, what is you point of view here? Shouldn't Cobbler
> stick to the "old" API? That would of course be better for people expecting
> the returned XML structure to be the same.

For the general token object, this got fixed by:
https://github.com/cobbler/cobbler/commit/11cbfe92195d14e6c58902fa4be35a35eecaca41

This should fix what you see?
IMO returning the auth token as string was (and now is again) wrong.
This is binary data and should be sent base64 encoded.

And this is still compatible if the data is enclosed in tags as you showed above:
<base64>…</base64>
and was enclosed in:
<string>…</string>
tags.
Why cannot Java or whatever reads the data interpret the base64 tag and decode the
value?

       Thomas

**Comment by watologo1** [comment]
Hi

Am Mittwoch, 27. Februar 2019, 11:39:43 CET schrieb Thomas Renninger:
> On Wednesday, February 27, 2019 9:29:58 AM CET Jochen Breuer wrote:
> > Here is an example for the login:
> > 
> > Cobbler 3.x with Python3:
> > ```xml
> > <?xml version='1.0'?>
> > <methodResponse>
> > <params>
> > <param>
> > <value><base64>…</base64></value>
> > </param>
> > </params>
> > </methodResponse>
> > ```
> > 
> > Cobbler 2.6.6 with Python2:
> > ```xml
> > <?xml version='1.0'?>
> > <methodResponse>
> > <params>
> > <param>
> > <value><string>…</string></value>
> > </param>
> > </params>
> > </methodResponse>
> > ```
> > 
> > Looks like Cobbler is just marshalling Python objects to XML. With Python3
> > some of the types have changed. And it looks like this is happening in
> > several places. @jmaas, what is you point of view here? Shouldn't Cobbler
> > stick to the "old" API? That would of course be better for people expecting
> > the returned XML structure to be the same.
> 
> For the general token object, this got fixed by:
> https://github.com/cobbler/cobbler/commit/11cbfe92195d14e6c58902fa4be35a35eecaca41
> 
> This should fix what you see?
> IMO returning the auth token as string was (and now is again) wrong.
> This is binary data and should be sent base64 encoded.
> 
> And this is still compatible if the data is enclosed in tags as you showed above:
> <base64>…</base64>
> and was enclosed in:
> <string>…</string>
> tags.
> Why cannot Java or whatever reads the data interpret the base64 tag and decode the
> value?

You do not understand me. Of cause we could do it. But you would change the API.
A script which is working with cobbler 2 is not working anymore with cobbler 3.

After our phone call I now know, that there were really API changes.
So it is about to you + matei to decide what "is right".

-- 
Regards

	Michael Calmer

--------------------------------------------------------------------------
Michael Calmer
SUSE LINUX GmbH, Maxfeldstr. 5, D-90409 Nuernberg
T: +49 (0) 911 74053 0
F: +49 (0) 911 74053575  - e-mail: Michael.Calmer@suse.com
--------------------------------------------------------------------------
SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton,
                     HRB 21284 (AG Nürnberg)

**Comment by brejoc** [comment]
@watologo1: This got a little bit confusing. The last message forwarded was from @mcalmer? :)

**Comment by watologo1** [comment]
On Wednesday, February 27, 2019 1:42:41 PM CET Michael Calmer wrote:
> Hi
> 
...
> 
> After our phone call I now know, that there were really API changes.
> So it is about to you + matei to decide what "is right".

After having understood that, even there are XML tags around the value,
it can be a pain in the ass if the (object) type of values changes.
For Java and probably for other clients as well.

So on longterm the XMLRPC API should define return object types and enforce
them. I have started to integrate this (with the "login" function first):

https://github.com/cobbler/cobbler/pull/2032

Please give it a review/comments.

Next step would be to identify other remote funtion return types.
Maybe we should first check your XMLRPC Java client (e.g. when explictly 
casting to a String we know it is/was a string coming from cobbler in the 
past).
Would be great if Matei can help here a bit from Java client side.
We might then have a reasonable amount of functions being checked.

Additional @returns(xy) checks can be added as required or when identified
when someone uses them.

       Thomas

**Comment by brejoc** [comment]
I think we can close this. This happens way less than we anticipated and some of the changes where done intentionally.
