### ISSUE TITLE
Retry curl http kickstart

### ISSUE THREAD

**Issue by datnt53** [cobbler/cobbler#2041]
I have a problem with network, Network Infra converge too slow so anaconda "curl ks http" with error: "No route to host".
![image](https://user-images.githubusercontent.com/44463004/54732994-99a8d880-4bc9-11e9-87d8-c97f5ab334e3.png)

I want to config option to retry curl or sleep before curl.
Can you help me?

**Comment by kwizart** [comment]
Unfortunately this workaround would have to be implemented in "anaconda" which is the component on your distro that is requesting the kickstart.

You maybe can have a chance with this (depending on your distro version).
https://anaconda-installer.readthedocs.io/en/latest/boot-options.html#inst-waitfornet

On a side note (for having experimented the issue) you should consider to disable the "spanning tree" or similar protocols.

Please consider closing the issue.
