### ISSUE TITLE
setup cobbler for unattended PXE boot using ubuntu 18 iso from local repository

### ISSUE THREAD

**Issue by ynixon** [cobbler/cobbler#2056]
Hi,
Cobbler 2.8.4
OS CentOS Linux release 7.6.1810 (Core)

I am straggling with trying to setup cobbler for unattended PXE boot using ubuntu 18 iso
I tried the following iso: https://github.com/netson/ubuntu-unattended on a vmware - and it worked as CDROM smoothly :)
But I assume I am missing a step on cobbler 
The steps I am using:
mkdir /localmnt
mount -o loop /ubuntu-18.04.2-server-amd64.iso /localmnt/
cobbler import --path=/localmnt/ --name=ubuntu-18.04.2-server-amd64 --breed=ubuntu --arch=x86_64
cp /localmnt/preseed/ubuntu-server-minimal.seed /var/lib/cobbler/kickstarts/ (I also tried netson.seed from the above link)
cobbler profile edit --name=ubuntu-18.04.2-server-x86_64 --kopts=interface=ens32 --kickstart=/var/lib/cobbler/kickstarts/ubuntu-server-minimal.seed --repos=ubuntu-18.04.2-server-x86_64
cobbler sync
I am waiting long time with the message: "Checking the Ubuntu archive mirror. Downloading Release files" - with no progress :(
After a while I am gettinh "Choose a mirror of the ubuntu archive. An error has been detected"
My intention was to use the cobbler as the source of the archives 
also tried that: https://purplepalmdash.github.io/2015/05/22/change-cobbler-profile-for-using-local-repository/
Followed steps of netboot from https://wiki.ubuntu.com/Enterprise/Cobbler

can you tel me what I am missing ?

Thanks
Yossi

[distros, profiles and system](https://gist.github.com/ynixon/188033ea8678c3009b541b82eb045871)

**Comment by kwizart** [comment]
IIRC, the moving the cdrom content to network change the way the ubuntu installer gpg checks the repo signature. (you might have a look on which files are 404 on the cobbler server side).
You might need to disable repo signature verification in the preseed.

Also the cdrom installer might miss some needed files to network boot, so unfortunately it seems easier to grab the netboot images instead.

**Comment by ynixon** [comment]
Thanks

**Comment by holmesb** [comment]
Hi @ynixon   Did you manage to fix this?  If so, how?
