### ISSUE TITLE
losing http_port from some snippets

### ISSUE THREAD

**Issue by wanghaiqing2015** [cobbler/cobbler#2058]
/var/lib/cobbler/snippets/cobbler_register
/var/lib/cobbler/snippets/post_koan_add_reinstall_entry

please check the two files

**Comment by SchoolGuy** [comment]
@wanghaiqing2015 Please be also more specific here what you are referring to. What do you mean with that you are losing the `http_port` for some snippets? What functionality is affected by this? What are the symptoms? Are there steps to reproduce this error?

**Comment by wanghaiqing2015** [comment]
Please check these two files.

/var/lib/cobbler/snippets/cobbler_register
/var/lib/cobbler/snippets/post_koan_add_reinstall_entry

**Comment by SchoolGuy** [comment]
@wanghaiqing2015 I looked at the snippets and there is indeed no port considered. If you would be so kind to create a PR for that because I am currently working on other stuff. If this can wait then I will fix this later when I got time.

**Comment by SchoolGuy** [comment]
Fixed through https://github.com/cobbler/cobbler/pull/2464
