### ISSUE TITLE
Bond mode, type appears twice

### ISSUE THREAD

**Issue by wanghaiqing2015** [cobbler/cobbler#2059]
/etc/sysconfig/network-scripts/ifcfg-bond0

TYPE=Bond
TYPE=Ethernet

please update post_install_network_config file.

**Comment by SchoolGuy** [comment]
@wanghaiqing2015 Please extend your issues more or we cannot help you.

**Comment by wanghaiqing2015** [comment]
oh，have you ever used this function？

**Comment by watologo1** [comment]
@wanghaiqing2015 
Network bonding is  a rather special setup and may not be that easy to reproduce/test.
If you could debug this down a bit further that would be appreciated.
