### ISSUE TITLE
os_release does not recognise Oracle Linux

### ISSUE THREAD

**Issue by ghost** [cobbler/cobbler#2065]
**Version:** 2.8.3
**File:** cobbler/utils.py 
**Function affected:** os_release(), tftpboot_location()

**Expected result:** On import of an iso the right directory should be selected by `tftpboot_location())` and in case of Oracle Linux return "/var/lib/tftpboot".
**Current result:** `tftpboot_location())` return "/tftpboot" due the fact that there iso match for OS known by coobler. 
**Reson:** `os_release()` is missing on `re.match("red ?hat|fedora|centos|scientific|virtuozzo linux", check_dist())` "oracle" as another os related to RHEL family.

**Comment by brejoc** [comment]
This is true for the 2.8 release and in part still for cobbler 3. Oracle Linux is still not detected, but the detection itself has changed a little bit. The more important change is that `tftpboot_location` is now coming from the settings. I'm curious how the `os-release` file of Oracle Linux is looking like. Could you attach one please? Thanks!

**Comment by kwizart** [comment]
cat /etc/os-release
```
NAME="Oracle Linux Server"
VERSION="7.6"
ID="ol"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Oracle Linux Server 7.6"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:6:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.6
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.6
```

**Comment by brejoc** [comment]
Thanks @kwizart! So this is vastly different from Rhel. No wonder this is not working.
