### ISSUE TITLE
Support for RHEL 8

### ISSUE THREAD

**Issue by chris1984** [cobbler/cobbler#2068]
When trying to import a RHEL 8.0 ISO I get the following error:

```bash
$ cobbler import --name=RHEL-8.0 --path=/mnt
task started: 2019-05-23_151944_import
task started (id=Media import, time=Thu May 23 15:19:44 2019)
No signature matched in /var/www/cobbler/ks_mirror/RHEL-8.0
!!! TASK FAILED !!!
```

**Comment by kwizart** [comment]
See also https://github.com/cobbler/cobbler/pull/2071

**Comment by brejoc** [comment]
Looks like we've got this in [master](https://github.com/cobbler/cobbler/pull/1944) and [release28](https://github.com/cobbler/cobbler/pull/2071).

**Comment by brejoc** [comment]
I'm closing this. Please feel free to re-open if you think we still need this issue.
