### ISSUE TITLE
make webtest command exit with Error2

### ISSUE THREAD

**Issue by MohanrajBabu** [cobbler/cobbler#2077]
Hello,

Installing cobbler in an centOS VM using the steps given in the [link](https://cobbler.github.io/manuals/2.8.0/2/3_-_Installing_From_Source.html) .

Expected to install fine, but below error throws on running **make webtest** command.
```
changing mode of /usr/share/cobbler/web
changing mode of //var/lib/cobbler/webui_sessions
make[1]: Leaving directory `/root/cobbler'
make restorestate
make[1]: Entering directory `/root/cobbler'
python setup.py -v restorestate --root /; \
find //var/lib/cobbler/triggers | xargs chmod +x
running restorestate
restoring the current configuration from /tmp/cobbler_settings/devinstall
copying /tmp/cobbler_settings/devinstall/config/ to //var/lib/cobbler/config/
copying /tmp/cobbler_settings/devinstall/cobbler_web.conf to //etc/httpd/conf.d/cobbler_web.conf
copying /tmp/cobbler_settings/devinstall/cobbler.conf to //etc/httpd/conf.d/cobbler.conf
copying /tmp/cobbler_settings/devinstall/modules.conf to //etc/cobbler/modules.conf
copying /tmp/cobbler_settings/devinstall/settings to //etc/cobbler/settings
copying /tmp/cobbler_settings/devinstall/users.conf to //etc/cobbler/users.conf
copying /tmp/cobbler_settings/devinstall/users.digest to //etc/cobbler/users.digest
copying /tmp/cobbler_settings/devinstall/dhcp.template to //etc/cobbler/dhcp.template
copying /tmp/cobbler_settings/devinstall/rsync.template to //etc/cobbler/rsync.template
if [ -n "`getent passwd apache`" ] ; then \
	chown -R apache //var/www/cobbler; \
elif [ -n "`getent passwd wwwrun`" ] ; then \
	chown -R wwwrun //usr/share/cobbler/web/cobbler_web; \
elif [ -n "`getent passwd www-data`"] ; then \
	chown -R www-data //usr/share/cobbler/web/cobbler_web; \
fi
if [ -d //var/www/cobbler ] ; then \
	chmod -R +x //var/www/cobbler/web; \
	chmod -R +x //var/www/cobbler/svc; \
fi
chmod: cannot access ‘//var/www/cobbler/web’: No such file or directory
if [ -d //usr/share/cobbler/web ] ; then \
	chmod -R +x //usr/share/cobbler/web/cobbler_web; \
	chmod -R +x //srv/www/cobbler/svc; \
fi
chmod: cannot access ‘//srv/www/cobbler/svc’: No such file or directory
make[1]: *** [restorestate] Error 1
make[1]: Leaving directory `/root/cobbler'
make: *** [devinstall] Error 2
```

How to address this issue?

Thanks,
Mohan

**Comment by harshbajaj16** [comment]
Hi @MohanrajBabu ,

Earlier i was facing the same problem and found workaround as below.

**Problem 1:**
```
chmod: cannot access ‘//var/www/cobbler/web’: No such file or directory
if [ -d //usr/share/cobbler/web ] ; then \
	chmod -R +x //usr/share/cobbler/web/cobbler_web; \
```
**Workaround:**
1. Go to the directory 'usr/share/cobbler' and you will find 'web' inside it.
2. copy the 'web' from above directory to 'usr/share/cobbler'


**Problem 2:**
```
chmod: cannot access ‘//srv/www/cobbler/svc’: No such file or directory
make[1]: *** [restorestate] Error 1
make[1]: Leaving directory `/root/cobbler'
make: *** [devinstall] Error 2
```
**Workaround:** 

Go to cobbler root directory and open Makefile:
1. vim Makefile 
2. search keyword 'srv'
3. Replace it with 'var' from srv 

After applying both workaround run again 'make webtest' command.


Regards,
Harsh Bajaj

**Comment by SchoolGuy** [comment]
@harshbajaj16 That is not an acceptable solution because this means that cobbler is not correctly installed.

**Comment by SchoolGuy** [comment]
@MohanrajBabu Are you trying to install a 2.8 cobbler or a master version? Maybe you found a bug! What I can say for sure is that the documentation is currently not a reliable source of information because it is outdated and was not updated recently.

**Comment by harshbajaj16** [comment]
Could you please suggest for 2.8 installation if it not solution then how can we install 2.8 version?

**Comment by SchoolGuy** [comment]
@harshbajaj16 I would suggest that you use a version of cobbler out of the repositorys of your distro. Most of the time they include fixes which we are not aware of sometimes because they are specific for their distro.

**Comment by MohanrajBabu** [comment]
Hi @SchoolGuy ,
Caught up with some work, sorry for delayed response.
I am using release28.

**Comment by MohanrajBabu** [comment]
Hi @harshbajaj16 
Caught up with some work, sorry for delayed response.
Your solution worked. 

For problem 1 you meant it right, but there is typo error I think.
**_copy the 'web' from above directory to 'usr/share/cobbler'_**

replaced usr with var, it worked.

Thanks

**Comment by SchoolGuy** [comment]
The linked information was moved to another location for which we should need a new bug. Thus closing this one.
