### ISSUE TITLE
ubuntu import failing on one system works on other

### ISSUE THREAD

**Issue by mnkdstock** [cobbler/cobbler#2093]
System 1: Centos import works, for Ubuntu 16.04 import or 14.04 import it says "signature not found", task failed 
System 2: Centos, Ubuntu 16.04 and Ubuntu 14.04 import works and signature is found every time

I'm running into issues have have Cobbler container running on 2x host systems running same host OS and kernel version. Only difference I see in the log files is in the system where Ubuntu import works, the logs show the type of file that is scanned such as "ASCII text" or "PGP signature" in System that it doesn't work it just seems to say "received on stderr:  /bin/sh: /usr/bin/file: No such file or directory". System 2 seems to give errors for each file scanned

System 1 Logs: 
[ubuntu1404importfails.log](https://github.com/cobbler/cobbler/files/3313328/ubuntu1404importfails.log)

Fri Jun 21 06:24:54 2019 - DEBUG | Found a candidate signature: breed=ubuntu, version=trusty
Fri Jun 21 06:24:54 2019 - INFO | running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/Release
Fri Jun 21 06:24:55 2019 - INFO | received on stdout: 
Fri Jun 21 06:24:55 2019 - DEBUG | received on stderr: /bin/sh: /usr/bin/file: No such file or directory

Fri Jun 21 06:24:55 2019 - INFO | running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/Release.gpg
Fri Jun 21 06:24:55 2019 - INFO | received on stdout: 
Fri Jun 21 06:24:55 2019 - DEBUG | received on stderr: /bin/sh: /usr/bin/file: No such file or directory

Fri Jun 21 06:24:55 2019 - INFO | running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/restricted/binary-amd64/Release
Fri Jun 21 06:24:55 2019 - INFO | received on stdout: 
Fri Jun 21 06:24:55 2019 - DEBUG | received on stderr: /bin/sh: /usr/bin/file: No such file or directory

Fri Jun 21 06:24:55 2019 - INFO | running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/restricted/binary-i386/Release
Fri Jun 21 06:24:56 2019 - INFO | received on stdout: 
Fri Jun 21 06:24:56 2019 - DEBUG | received on stderr: /bin/sh: /usr/bin/file: No such file or directory

Fri Jun 21 06:24:56 2019 - INFO | running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/main/binary-amd64/Release
Fri Jun 21 06:24:56 2019 - INFO | received on stdout: 
Fri Jun 21 06:24:56 2019 - DEBUG | received on stderr: /bin/sh: /usr/bin/file: No such file or directory

Fri Jun 21 06:24:56 2019 - INFO | running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/main/binary-i386/Release
Fri Jun 21 06:24:56 2019 - INFO | received on stdout: 
Fri Jun 21 06:24:56 2019 - DEBUG | received on stderr: /bin/sh: /usr/bin/file: No such file or directory

System 2 Logs:
ubuntuimportworks.logs 
[ubuntuimportworks.log](https://github.com/cobbler/cobbler/files/3313333/ubuntuimportworks.log)

Fri Jun 21 06:00:09 2019 - DEBUG | received on stderr: 
Fri Jun 21 06:00:09 2019 - INFO | running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/Release.gpg
Fri Jun 21 06:00:10 2019 - INFO | received on stdout: /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/Release.gpg: PGP signature

Fri Jun 21 06:00:12 2019 - DEBUG | received on stderr: 
Fri Jun 21 06:00:12 2019 - DEBUG | Found a candidate signature: breed=ubuntu, version=trusty
Fri Jun 21 06:00:12 2019 - INFO | running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/Release
Fri Jun 21 06:00:13 2019 - INFO | received on stdout: /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64/dists/trusty/Release: ASCII text

Fri Jun 21 06:00:13 2019 - DEBUG | received on stderr: 
Fri Jun 21 06:00:13 2019 - DEBUG | Found a matching signature: breed=ubuntu, version=trusty
Fri Jun 21 06:00:13 2019 - INFO | Adding distros from path /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64:
Fri Jun 21 06:00:13 2019 - INFO | creating new distro: ubuntu_14.04-x86_64
Fri Jun 21 06:00:13 2019 - INFO | trying symlink: /var/www/cobbler/ks_mirror/ubuntu_14.04-x86_64 -> /var/www/cobbler/links/ubuntu_14.04-x86_64
Fri Jun 21 06:00:15 2019 - INFO | creating new profile: ubuntu_14.04-x86_64
Fri Jun 21 06:00:15 2019 - INFO | associating repos
Fri Jun 21 06:00:15 2019 - INFO | checking for apt repo(s)
Fri Jun 21 06:00:15 2019 - INFO | adding apt repo for ubuntu_14.04-x86_64
Fri Jun 21 06:00:15 2019 - INFO | Added repos for ubuntu_14.04-x86_64
Fri Jun 21 06:00:17 2019 - INFO | ### TASK COMPLETE ###

System 1 Host OS :
root@pc-004:~/projects/cobbler-container/cobbler-container-main# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@pc-004:~/projects/cobbler-container/cobbler-container-main# 
root@pc-004:~/projects/cobbler-container/cobbler-container-main# uname -r
5.0.0-050000-generic
root@pc-004:~/projects/cobbler-container/cobbler-container-main# 

System 2 Host OS:
root@system2:~/user/cobbler-container-ios# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@system2:~/user/cobbler-container-ios#
root@puppet-1604-1:~/user/cobbler-container-ios# uname -r
5.0.0-050000-generic
root@puppet-1604-1:~/user/cobbler-container-ios#

**Comment by superuser12** [comment]
Issue resolved, system having issue was missing the "/usr/bin/file" package, so had to do "yum install cobbler" in the container. Everything now works as expected.

**Comment by mnkdstock** [comment]
Issue resolved, system having issue was missing the "/usr/bin/file" package, so had to do "yum install cobbler" in the container. Everything now works as expected.
