### ISSUE TITLE
support for httpboot?

### ISSUE THREAD

**Issue by thiller2018** [cobbler/cobbler#2102]
can cobbler be used for http boot as well? Would this need to allow tftpboot location per system (to have pxe and http mixed setup)?

**Comment by SchoolGuy** [comment]
@thiller2018 To my knowledge httpboot is something you need to configure inside the webserver (e.g. apache2). So this would be a feature which would require cobbler to touch your webserver config. A question would be on how to determine the vhost/config to touch.

I played with this at work and it is theoretically possible.

**Comment by thiller2018** [comment]
I'm about to start playing with it at work as well. Isn't it basically the same content that is currently at /srv/tftpboot, which would reside within the apache directories e.g. htdocs/httpboot ?

**Comment by watologo1** [comment]
Yep, I also like to touch/enhance this if needed soon.

**Comment by thiller2018** [comment]
I exposed /srv/tftpboot as /httpboot in httpboot.conf:
Alias /httpboot /srv/tftpboot

<Directory /srv/tftpboot>
        Options Indexes FollowSymLinks
        AllowOverride None
        AuthType None
        Require all granted
</Directory>

Now the only issue is that grub2 cannot load the kernel from /images.
In tftpgen.py:

           if 'http' in distro.kernel and 'http' in distro.initrd:
                kernel_path = distro.kernel
                initrd_path = distro.initrd
            else:
                kernel_path = os.path.join("/images", distro.name, os.path.basename(distro.kernel))
                initrd_path = os.path.join("/images", distro.name, os.path.basename(distro.initrd))

So I could change the kernel and initrd in distro to a web url and it should work, but this will break pxe (which I need for some servers still)

**Comment by SchoolGuy** [comment]
We have enough to clean up. I would say that we do this properly. I will start working on this on Monday...

**Comment by thiller2018** [comment]
I changed my apache config and now it works:
Alias /httpboot /srv/tftpboot/grub
Alias /images /srv/tftpboot/grub/images

<Directory /srv/tftpboot/grub>
        Options Indexes FollowSymLinks
        AllowOverride None
        AuthType None
        Require all granted
</Directory>

**Comment by SchoolGuy** [comment]
@thiller2018 Thanks for pointing this out! I will use that as a staring point as soon when I am starting to work on this. If you have a general solution I would love to see a PR for this!

**Comment by thiller2018** [comment]
with the above it works. The issue was that the grub prefix ends at the server address and doesn't include the directory where grub is located. So /images could not be found. Adding another alias for /images solved this. Not sure where this should be fixed.
Is this a grub / grub.cfg issue?

**Comment by SchoolGuy** [comment]
Well tbh I am not sure. Maybe @watologo1 can help?

**Comment by watologo1** [comment]
@thiller2018 : Nice catch! Can you make Pull Request out of this.
In tftp fs we already do:
images -> ../images
That apache needs extra handling for http boot I was not aware and this look like a sane fix for this.
I wonder where this should go since other apache config was moved to vhost configs, maybe:
/etc/apache2/conf.d/cobbbler.conf
?

**Comment by hbokh** [comment]
👍🏻

**Sidenote / off-topic**
We use a combo of nginx (instead of Apache2) in front of Cobbler 2.x and `lpxelinux.0` (instead of `pxelinux.0`):

*Since version 5.10, a special PXELINUX binary, lpxelinux.0, natively supports HTTP and FTP transfers, greatly increasing load speed and allowing for standard HTTP scripts to present PXELINUX's configuration file. To use HTTP or FTP, use standard URL syntax as filename; use DHCP options to transmit a suitable URL prefix to the client, or use the "pxelinux-options" tool provided in the "utils" directory to program it directly into the lpxelinux.0 file.*
From: https://wiki.syslinux.org/wiki/index.php?title=PXELINUX#HTTP_and_FTP

Our nginx config (behind a load balancer):

```
server {
    listen 10.20.30.40:80 default;
    server_name cobbler.example.int;

    access_log /var/log/nginx/cobbler-int.access.log;
    error_log  /var/log/nginx/cobbler-int.error.log;

    location ~ ^/cblr(?!/svc/)(.*)?$ {
        alias /srv/www/cobbler/$1;
    }

    location ~ ^/cobbler_track/(.*)?$ {
        alias /srv/www/cobbler/$1;
    }

    location /cobbler {
        alias /srv/www/cobbler;
    }

    location /cblr/svc/ {
        include uwsgi_params;
        uwsgi_pass unix:/run/uwsgi/app/cobbler_svc/socket;
    }

    # Facilitate download of kernel and initrd.gz
    # over HTTP instead of slow TFTP
    location /boot/isolinux {
         alias /usr/lib/syslinux/modules/bios;
    }

    location /pxelinux.cfg {
         alias /srv/tftp/pxelinux.cfg;
    }

    location /images {
         alias /srv/www/cobbler/images;
    }

    location ~ ^/cblr(?!/svc/)(.*)?$ {
        alias /srv/www/cobbler/$1;
    }

    location /cobbler_web {
        rewrite ^/cobbler_web/?(.*) /$1 break;
        include uwsgi_params;
        uwsgi_pass unix:/run/uwsgi/app/cobbler_web/socket;
    }

    location /cobbler_webui_content {
        alias /srv/www/cobbler_webui_content;
    }

    location /cobbler_api {
        rewrite ^/cobbler_api/?(.*) /$1 break;
        proxy_pass http://127.0.0.1:25151;
    }

    # redirect requests for / to the Web UI
    rewrite ^/$ https://cobbler.example.com/cobbler_web permanent;
}
```

And `dnsmasq.template` a line like this:

```
pxe-service=x86PC, "Boot PXELinux (=Cobbler controlled)", lpxelinux , $next_server
```

**Comment by SchoolGuy** [comment]
@hbokh Thanks a lot for sharing! Is it possible when you switch to Cobbler 3 that you probably write a guide on cobbler.github.io on how your setup works and how the reader can set it up, as well as what advantages it has?

**Comment by hbokh** [comment]
I think I can, in the long run. First I have to (try to) finish our migration to Cobbler 3.

**Comment by watologo1** [comment]
Am Dienstag, 3. März 2020, 16:59:37 CET schrieb Henk:
> 👍🏻
> 
> **Sidenote / off-topic**
> We use a combo of nginx (instead of Apache2) in front of Cobbler 2.x and
> `lpxelinux.0` (instead of `pxelinux.0`):
 
> *Since version 5.10, a special PXELINUX binary, lpxelinux.0, natively
...
Yet another boot loader...?
I thought grub2 gets or better is _the_ unified boot loader on quite a lot
of architecutres and it certainly can do http requests as well and is much
more powerful.

     Thomas

**Comment by hbokh** [comment]
@watologo1 Grub2 can do exactly the same and more than `pxelinux.0`? I was unaware of that.
As stated: we are still on an ancient Cobbler 2.x installation and had the opportunity 3 years ago to improve on the slow TFTP transfer by adding `lpxelinux.0`.

But then, why isn't this an option in Cobbler 3.1.1?
![bootloaders](https://user-images.githubusercontent.com/519955/75852299-fe197380-5deb-11ea-9062-e098fbc656b3.png)
There are 4 boot loaders, of which only 2 are valid choices: `grub` and `pxelinux`.
Just trying to get my head around this.

**Comment by watologo1** [comment]
On Wednesday, March 4, 2020 7:49:48 AM CET Henk wrote:
> @watologo1 Grub2 can do exactly the same and more than `pxelinux.0`? I was
> unaware of that. As stated: we are still on an ancient Cobbler 2.x
> installation and had the opportunity 3 years ago to improve on the slow
> TFTP transfer by adding `lpxelinux.0`.

I was unaware about ipxe, but from what I see, ipxe has another scope.
This is more a firmware replacement, but cannot boot kernel/initrd native
(please correct me if I am wrong).
This would only be a "legacy x86" (non-UEFI) chainloading boot solution,
where you can tell to chainload the boot loader from local dist or via
san (interesting, not sure whether there is grub2 module for that), etc.
 
> But then, why isn't this an option in Cobbler 3.1.1?
> ![bootloaders](https://user-images.githubusercontent.com/519955/75852299-fe1
> 97380-5deb-11ea-9062-e098fbc656b3.png)
I get:
This XML file does not appear to have any style information associated with 
it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
...

> There are 4 boot loaders, of which
> only 2 are valid choices: `grub` and `pxelinux`. Just trying to get my head
> around this.

grub == grub2
If the question is, why is there no grub2:
grub (verion 1) is outdated for years, so when cobbler (after 3.0) is using
the name grub, then grub2 (grub version 2) is meant.

   Thomas

**Comment by hbokh** [comment]
Right. In my opinion the other options should be dropped if Cobbler 3 states this:

```
<class 'cobbler.cexceptions.CX'>:'Invalid boot loader name: . Supported boot loaders are: grub pxelinux'

```

In different news: I started PXEboot testing in Vagrant (two VirtualBoxen) with Cobbler 3, where the `boot_loader` is a new option compared to Cobbler 2. Having some issues where only Ubuntu 18.04 is added to the `grub/x86_64_menu_items.cfg` but not Debian 10. That is only booting with `pxelinux`.

What is the best spot to discuss this issue? Open a new question?

**Comment by watologo1** [comment]
@thiller2018 : I had a closer look at this. The change in the apache conf you did, seem to be the wrong approach.
IMO, the bootloaders which are synced to /srv/tftpboot/
have to be synced to
/srv/www/cobbler/
or whatever distro specific directory it is.

Please have a look at:
https://github.com/cobbler/cobbler/pull/2303

With the above commit/patch as preparation you can add something like below and sync bootloaders also into www dir. As images are also alread in www dir, this seem to be the better and more secure way to go forward:

--- a/cobbler/actions/sync.py
+++ b/cobbler/actions/sync.py
@@ -98,6 +98,7 @@ class CobblerSync(object):
         # Have the tftpd module handle copying bootloaders,
         # distros, images, and all_system_files
         self.tftpd.sync(self.verbose)
+        self.tftpgen.copy_bootloaders(self.settings.webdir)
         # Copy distros to the webdir
         # Adding in the exception handling to not blow up if files have
         # been moved (or the path references an NFS directory that's no longer

**Comment by thiller2018** [comment]
The disadvantage here is that you have two places with the same programs. It's clearer when it comes to separation I agree.
Why should this be more secure?

**Comment by watologo1** [comment]
Sorry, I did not have much time the last weeks, just reading up the list..
Do not hesitate to send me a private mail if you need a quick answer.

I am not an apache expert. Afaik it is/should run chrooted, this seem not be possible if the data is outside /srv/www? Most files are owned by root anyway, but theoretically this could be adjusted.

Decide yourself which solution you think is better/saver if you find time to send a patch. Currently this is missing at all, it could be adjusted later if more people play with it.
