### ISSUE TITLE
Cobbler 2.8.5 release

### ISSUE THREAD

**Issue by kwizart** [cobbler/cobbler#2109]
I'd like to have cobbler 2.8.5 tagged (but not yet).

last 2.8.4 is more than 6 months old and the django fix to current is awaited for fedora users (and CentOS users that need to deal with pip install for the appropriate version instead of using the current django 1.11 before python2 is deprecated).

I've a minimal patchset I'd like to submit before (few cherry-pick from master or else).
I'd like to also look at the current bugfix to see if any trivial bug can be fixed before.

Anything one would consider relevant for release28 branch ?
Thx

**Comment by SchoolGuy** [comment]
Since most of the fixes we did are Py3 I don't think that we need anything else.

**Comment by brejoc** [comment]
Uh, yeah… picking fixes form master would indeed be very hard. :frowning:

**Comment by mjm455** [comment]
Just be sure to include rhel8 to the json file.

**Comment by kwizart** [comment]
okay, so I'm just missing a tag for 2.8.5 but it's pending some docs update.
As I'm aware, the only doc PR is located at https://github.com/cobbler/cobbler/pull/2117 but I don't think it's relevant to release28 anyway ?
https://github.com/cobbler/cobbler/pull/2111#issuecomment-522578655

**Comment by SchoolGuy** [comment]
@kwizart Well as soon as we have some control over readthedocs (currently access is exclusive to Jörgen) then we can backport the docs improvements.

**Comment by SchoolGuy** [comment]
@kwizart So I now have control over Readthedocs. I would say that if at least two more people approve of my PR then I will merge it into master and backport it on the release28 branch and tag the last version of the 2.x.x series.

**Comment by hbokh** [comment]
So what it the status of this issue? 
I ask because I have 2.8.5 running on `CentOS Linux release 7.7.1908` since Sept. 20th:

```
Jun 07 18:56:22 Installed: cobbler-2.8.4-4.el7.x86_64
Jun 07 18:56:45 Installed: cobbler-web-2.8.4-4.el7.noarch
Sep 20 11:27:49 Updated: cobbler-2.8.5-0.1.el7.x86_64
Sep 20 11:31:16 Updated: cobbler-web-2.8.5-0.1.el7.noarch
Nov 02 13:14:19 Updated: cobbler-2.8.5-0.3.el7.x86_64
Nov 02 13:14:21 Updated: cobbler-web-2.8.5-0.3.el7.noarch
```

There is no tag, but there are RPMs available, which is a bit puzzling.

**Comment by kwizart** [comment]
> @kwizart So I now have control over Readthedocs. I would say that if at least two more people approve of my PR then I will merge it into master and backport it on the release28 branch and tag the last version of the 2.x.x series.

Which PR ?

**Comment by SchoolGuy** [comment]
@kwizart I have merged it already. I will sit down as soon as I can and prepare the release. Expect it by end of this week.

**Comment by darcyllingyan** [comment]
Hi @SchoolGuy,
I also have the same request.
Whether the 2.8.5 has been tagged and when will I get the 2.8.5 tag package in https://github.com/cobbler/cobbler/releases? Thanks.

Thanks
Dacy

**Comment by SchoolGuy** [comment]
Okay. The release28 branch builds and has no pyflakes errors. As far as I can see there has not much changed from 2.8.4. But I will address what has changed in the release. I will tag now and soon we will have 2.8.5 @kwizart

**Comment by SchoolGuy** [comment]
Closed with https://github.com/cobbler/cobbler/releases/tag/v2.8.5
