### ISSUE TITLE
Git provided spec file out-of-date - openSUSE Leap 15.0 not building

### ISSUE THREAD

**Issue by jsaathof** [cobbler/cobbler#2114]
Hi,

I just found your new 3.0 release (I know it's 45 mins old) and I am trying to create a package for OpenSUSE Leap 15.0. I run into an issue that the SPEC file is not up-to-date. First of all the version says 2.9.0. Second the requires for OpenSUSE (>= 1230) has pyhton-Cheetah. This is a package for python 2.7. Since this is a rewrite for python3 I guess that this is not the idea. I haven't checked everything but it is clear to me that the SPEC file is not done.

Jurriaan

**Comment by jsaathof** [comment]
Added these missing modules as well because of errors during the package build.

```
BuildRequires: python3-future
BuildRequires: python3-distro
BuildRequires: python3-coverage
```

**Comment by watologo1** [comment]
The background ist that the .spec file used in the Open Build Service (OBS) where SUSE builds its distributions and whoever else can easily build against them diverged heavily over time.
But as you are the 2nd who complained recently, it is time to cleanup the git repo one.
This is not an easy task as it interferes with other distros where packages/macros/... might be named differently, etc.
It's also time consuming to develop and check as well and while I'd like to have a closer look, I'd like to point you to the spec file used in the OBS for now:
https://build.opensuse.org/package/view_file/systemsmanagement/cobbler/cobbler.spec
Best and quickest solution for you might be to simply use the Leap 15.0 build there. Be aware that my last submitrequest was rejected. The code is nearly on latest 3.0 base, I'll re-submit today.
If you simply need a build you can just add the build repo which falls out from above OBS package:
https://download.opensuse.org/repositories/systemsmanagement/openSUSE_Leap_15.0/systemsmanagement.repo
(you find the link by following Leap 15.0 build) and you can easily add it by adding the repo (ar) specifing the .repo file link above:
zypper ar https://dow....gement.repo

PS: I took the liberty to re-name your issue. I like o keep it open if it's not yet a duplicate. It's common practice that spec files diverge inside the build systems of distros, but it should get some updates indeed. Thanks!

**Comment by thiller2018** [comment]
This should be solved now with my PR being merged.

**Comment by SchoolGuy** [comment]
Since distro packaging is always a bit behind this is okay now. We are trying to update as soon as reasonable and the service file automatically unpacks the specfile without modification. If this is not the case then the package is not built like we desire it and thus this should be a downstream (distro) issue and not upstream (cobbler).
