### ISSUE TITLE
Too many Django settings.py?

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#2119]
While working on the RPM pkg, @dincamihai and I noticed that there are two `settings.py` files from Django. And as far as I can tell, one of them is not used. Can anybody verify that?

**Comment by thiller2018** [comment]
There are two settings.py and both are needed. web/settings.py is for the UI, settings.py for cobbler itself.

**Comment by brejoc** [comment]
@thiller2018 Ah, thanks for the explanation!
