### ISSUE TITLE
cobbler check throws ProtocolError for 127.0.0.1:25151/RPC2: 500 Internal Server Error

### ISSUE THREAD

**Issue by MohanrajBabu** [cobbler/cobbler#2120]
Hi,

OS: Centos7

Installed cobbler using the developer guide: https://cobbler.github.io/manuals/developer/

Used branch release28.

Both command make install and make webtest run without any issue.

When I tried to run cobbler check, I am getting below error.

`cobblerd does not appear to be running/accessible: <ProtocolError for 127.0.0.1:25151/RPC2: 500 Internal Server Error`

netstat -aptun | grep 25151

`tcp        0      0 127.0.0.1:25151         0.0.0.0:*               LISTEN      11656/python 
`

How to fix this issue?

Thanks,
Mohan

**Comment by SchoolGuy** [comment]
@MohanrajBabu Do you see any connection attempts in the log in `/var/log/cobbler/cobbler.log`ß

**Comment by MohanrajBabu** [comment]
Hi @SchoolGuy 

Below is the cobbler.log. 

[root@cob-serv cobbler] tail -f /var/log/cobbler/cobbler.log
Mon Aug 12 11:40:29 2019 - DEBUG | XMLRPC running on 25151
Mon Aug 12 19:50:31 2019 - INFO | 11 breeds and 81 OS versions read from the signature file
Mon Aug 12 19:50:31 2019 - DEBUG | API handle initialized
Mon Aug 12 19:50:31 2019 - DEBUG | XMLRPC running on 25151
Mon Aug 12 19:50:53 2019 - INFO | 11 breeds and 81 OS versions read from the signature file
Mon Aug 12 19:50:53 2019 - DEBUG | API handle initialized
Mon Aug 12 19:50:53 2019 - ERROR | [Errno 98] Address already in use
Tue Aug 13 05:08:10 2019 - INFO | 11 breeds and 92 OS versions read from the signature file
Tue Aug 13 05:08:10 2019 - DEBUG | API handle initialized
Tue Aug 13 05:08:10 2019 - DEBUG | XMLRPC running on 25151

Thanks

**Comment by SchoolGuy** [comment]
@MohanrajBabu It appears to be that your CLI client is not able to connect to the port. Is there maybe a firewall in between the client and the server?

**Comment by MohanrajBabu** [comment]
Checked firewall is fine.

Since working cobbler needed, had to delete the VM, created a new one and its working fine. will update if faced similar issue.

**Comment by SchoolGuy** [comment]
Okay please reopen this issue if you experience it again. For now let's close it.
