### ISSUE TITLE
could not find kernel image: /images/esxi60-x86_64/mboot.c32

### ISSUE THREAD

**Issue by dominick000** [cobbler/cobbler#2121]
HI,Cobbler Teams
    I finish importing an ESXi 6.0 iso(VMware-VMvisor-Installer-201706001-5572656.x86_64) and create a system named "esxi_test" successfully.

import an ESXi iso

    [root@localhost images]# cobbler import --path=/mnt/ --name=esxi60
    task started: 2019-08-13_164009_import
    task started (id=Media import, time=Tue Aug 13 16:40:09 2019)
    Found a candidate signature: breed=vmware, version=esxi65
    running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi60/vmware-esx-base-osl.txt
    received on stdout: /var/www/cobbler/ks_mirror/esxi60/vmware-esx-base-osl.txt: ASCII text, with very long lines, with CRLF line terminators
    received on stderr: 
    Found a candidate signature: breed=vmware, version=esxi51
    running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi60/s.v00
    received on stdout: /var/www/cobbler/ks_mirror/esxi60/s.v00: gzip compressed data, was             "vmvisor-sys.vtar", from Unix, last modified: Thu May 18 08:01:01 2017
    received on stderr: 
    Found a candidate signature: breed=vmware, version=esxi67
    running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi60/vmware-esx-base-osl.txt
    received on stdout: /var/www/cobbler/ks_mirror/esxi60/vmware-esx-base-osl.txt: ASCII text, with very long lines, with CRLF line terminators
    received on stderr: 
    Found a candidate signature: breed=vmware, version=esxi60
    running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi60/s.v00
    received on stdout: /var/www/cobbler/ks_mirror/esxi60/s.v00: gzip compressed data, was     "vmvisor-sys.vtar", from Unix, last modified: Thu May 18 08:01:01 2017
    received on stderr: 
    Found a matching signature: breed=vmware, version=esxi60
    Adding distros from path /var/www/cobbler/ks_mirror/esxi60:
    running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi60/tools.t00
    received on stdout: /var/www/cobbler/ks_mirror/esxi60/tools.t00: gzip compressed data, was "tools-light.tar", from Unix, last modified: Fri May  5 15:44:15 2017
    received on stderr: 
    creating new distro: esxi60-x86_64
    trying symlink: /var/www/cobbler/ks_mirror/esxi60 -> /var/www/cobbler/links/esxi60-x86_64
    creating new profile: esxi60-x86_64
    associating repos
    *** TASK COMPLETE ***

Create a system

    [root@localhost images]# cobbler system add --name=esxi_test --mac=00:50:56:ab:9c:2c --profile=esxi60-x86_64 --ip-address=192.168.1.201 --netmask=255.255.255.0 --gateway=192.168.1.254 --interface=vmnic0 --static=1

However,I always get met with this error when I boot the server

 _boot:_
 _could not find kernel image :/images/esxi60-x86_64/mboot.c32_

I can confirm the file "mboot.c32" is in the correct path

    [root@localhost images]# ll /var/lib/tftpboot/images/esxi60-x86_64/mboot.c32 
    -r-------- 3 root root 86192 May 18  2017 /var/lib/tftpboot/images/esxi60-x86_64/mboot.c32

Can someone help me with this please?
Thanks

**Comment by SchoolGuy** [comment]
@dominick000 Can you see which files the system successfully accessed? Because if no files are requested successfully I guess there is a wrong path somewhere...

**Comment by SchoolGuy** [comment]
Closing this in favor of #2337 which is a general issue for the esxi support for Cobbler.
