### ISSUE TITLE
code comprehension

### ISSUE THREAD

**Issue by as900** [cobbler/cobbler#2123]
Hi there, When I was learning and trying to understand the function "deserialize" in `cobbler/cobbler/modules/serializers/file.py`, I was confused about the description of the its delivered function. My understanding of this code snippet is "load a collection from database". Do I understand that right?

**Comment by SchoolGuy** [comment]
Well if you look at it then you will see that the function calls `deserialize_raw` which loads the collection file from the disk and then returns the read results.

**Comment by SchoolGuy** [comment]
Was your question answered @as900 or do you need further explanations?

**Comment by brejoc** [comment]
I'm closing this. @as900, feel free to re-open this issue if you need more information.
