### ISSUE TITLE
cobbler 2.8.4 install ubuntu preseed "d-i netcfg/choose_interface select eth0" The command has not taken effect

### ISSUE THREAD

**Issue by yogi401** [cobbler/cobbler#2126]
cobbler 2.8.4 install ubuntu14.04 and 16.04 , i use seed file like this：
```
# netcfg will choose an interface that has link if possible. This makes it
# skip displaying a list if there is more than one interface.
# set $myhostname = $getVar('hostname',$getVar('name','cobbler')).replace("_","-")
#d-i netcfg/choose_interface select auto
d-i netcfg/enable boolean true
d-i netcfg/choose_interface select eth0
d-i netcfg/get_hostname string $myhostname
d-i netcfg/get_domain string none
```
but During the installation process, I still need to select the network interface and fill in the nameserver. is there anything wrong that the netcfg command does not take effect?

<img width="644" alt="select_interface" src="https://user-images.githubusercontent.com/1264604/63490369-1f1d1580-c4e7-11e9-8ed3-85cf36861e23.png">
<img width="642" alt="nameserver" src="https://user-images.githubusercontent.com/1264604/63490384-26dcba00-c4e7-11e9-8567-3732bfb95620.png">

**Comment by SchoolGuy** [comment]
Please see this Launchpad bug: https://bugs.launchpad.net/ubuntu/+source/netcfg/+bug/855921

**Comment by yogi401** [comment]
> Please see this Launchpad bug: https://bugs.launchpad.net/ubuntu/+source/netcfg/+bug/855921

thanks, i change "netcfg/choose_interface eth0" into kernel options slove the interface selection problem.
but i still need to fill the  nameserver to contiune the installation process ,how can i skip this step? just like the second screenshot i upload

**Comment by arafatx** [comment]
@yogi401 netcfg/choose_interface=eth0 or netcfg/choose_interface eth0  ? doesn't seem to work here
