### ISSUE TITLE
Write access to docs for Enno

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#2127]
Hey @jmaas, from my point of view it would make sense to give write access for the docs to @SchoolGuy. He is driving most of the changes here at the moment and is backed by @watologo1 and me. Then he could also get the docs ready for a last 2.8.x release and an official 3.0.0. What do you think?

**Comment by jmaas** [comment]
Yes, I know and agree. I have limited access due to vacation. I will take
care of this in the weekend.

Op di 27 aug. 2019 14:43 schreef Jochen Breuer <notifications@github.com>:

**Comment by brejoc** [comment]
Awesome! Thanks, @jmaas. And enjoy your vacation!

**Comment by brejoc** [comment]
I guess this can be closed now!
