### ISSUE TITLE
Wrong `signature` in `distro_signatures.json` for opensuse15.0

### ISSUE THREAD

**Issue by xenlo** [cobbler/cobbler#2132]
Since July, I saw that a signature for opensuse15.0 appears. The issue is that the content looks wrong to me. 

Especially the `"signatures":["suse"]`. Since OpenSuse Leap 15.0 there is no more  `/suse/` directory on the ISO's. The package directory for a certain arch is now directly in the root of the ISO.

The `"supported_arches":["i386","i586","x86_64"]` seems also wrong, with obsolete arch! 

ISO's of openSuse 15.0:
- https://download.opensuse.org/distribution/leap/15.0/iso/openSUSE-Leap-15.0-NET-x86_64.iso?mirrorlist
- https://download.opensuse.org/distribution/leap/15.0/iso/openSUSE-Leap-15.0-DVD-x86_64.iso?mirrorlist
ISO's of openSuse 15.1:
- https://download.opensuse.org/distribution/leap/15.1/iso/openSUSE-Leap-15.1-DVD-x86_64.iso?mirrorlist
- https://download.opensuse.org/distribution/leap/15.1/iso/openSUSE-Leap-15.1-NET-x86_64.iso?mirrorlist

**Comment by SchoolGuy** [comment]
PR merged, so this can be closed.
