### ISSUE TITLE
changes to the cobbler settings via terminal not reflecting in webUI settings.

### ISSUE THREAD

**Issue by MohanrajBabu** [cobbler/cobbler#2135]
Hello,

OS: CentOS7
Cobbler: release28

**Description**:

Changes made to settings file in /etc/cobbler/settings not reflecting in cobbler UI: http://192.168.43.178/cobbler_web/setting/list

**Steps**:
Used nano editor in shell and edit the cobbler settings file to set manage_dhcp:1, next_server:192.168.43.178 , server: 192.168.43.178.

ran `cobbler sync` in shell itself.

open cobbler web UI and clicked Configuration/settings, noticed the changed values are not reflecting in web UI. Its only shows the default value. 

Thanks,
Mohan

**Comment by kwizart** [comment]
One need to use systemctl restart cobblerd for that.
cobbler sync would sync the services that are "managed by" cobbler, not the cobblerd service itself

**Comment by MohanrajBabu** [comment]
yes, It has worked. 
In that case, will it make sense if  we have an option in the UI for restarting cobblerd service.
