### ISSUE TITLE
Launch cobbler web without login screen.

### ISSUE THREAD

**Issue by MohanrajBabu** [cobbler/cobbler#2136]
Hello,

Cobbler: release28
OS: CentOS7

Is it possible to bypass login screen and directly move to cobbler homepage when using http://192.168.43.178/cobbler_web

EDIT: link for passthru authentication broken --> http://cobbler.github.io/manuals/2.8.0/5/2/5_-_Passthru.html. 

please share the correct link if available.

Thanks,
Mohan

**Comment by SchoolGuy** [comment]
I guess you are looking for thiis one: https://cobbler.readthedocs.io/en/latest/cobbler-conf.html#authentication

**Comment by SchoolGuy** [comment]
But you are correct. The docs of the master branch are currently pointing to an empty document: https://cobbler.readthedocs.io/en/latest/user-guide.html#web-user-interface

**Comment by SchoolGuy** [comment]
But indeed the old docs have somehting about it: https://cobbler.readthedocs.io/en/release28/5_web-interface/web_authentication.html#passthru

**Comment by SchoolGuy** [comment]
The webinterface will be removed with 3.3.0 and thus I will close this issue. A new interface will be created when the Team has time and resources for it.
