### ISSUE TITLE
CX: 'serializer: error loading collection distro. Check /etc/cobbler/modules.conf'

### ISSUE THREAD

**Issue by MohanrajBabu** [cobbler/cobbler#2149]
Cobbler : release28 , installed from souce.

Followed this guide: https://cobbler.github.io/manuals/2.8.0/4/12/3_-_MySQL.html in configuring mysql database and /etc/cobbler/modules.conf

restart cobblerd, below error throws.

```
[root@localhost cobbler]# systemctl status cobblerd
● cobblerd.service - LSB: daemon for libvirt virtualization API
   Loaded: loaded (/etc/rc.d/init.d/cobblerd; bad; vendor preset: disabled)
   Active: active (exited) since Wed 2019-08-14 15:53:17 EDT; 1s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2403 ExecStop=/etc/rc.d/init.d/cobblerd stop (code=exited, status=0/SUCCESS)
  Process: 2422 ExecStart=/etc/rc.d/init.d/cobblerd start (code=exited, status=0/SUCCESS)

Aug 14 15:53:17 localhost.localdomain cobblerd[2422]: api = cobbler_api.BootAPI(is_cobblerd=True)
Aug 14 15:53:17 localhost.localdomain cobblerd[2422]: File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 119, in __init__
Aug 14 15:53:17 localhost.localdomain cobblerd[2422]: self.deserialize()
Aug 14 15:53:17 localhost.localdomain cobblerd[2422]: File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 953, in deserialize
Aug 14 15:53:17 localhost.localdomain cobblerd[2422]: return self._config.deserialize()
Aug 14 15:53:17 localhost.localdomain cobblerd[2422]: File "/usr/lib/python2.7/site-packages/cobbler/config.py", line 262, in deserialize
Aug 14 15:53:17 localhost.localdomain cobblerd[2422]: raise CX("serializer: error loading collection %s. Check /etc/cobbler/modules.conf" % item.collection_type())
Aug 14 15:53:17 localhost.localdomain cobblerd[2422]: CX: 'serializer: error loading collection distro. Check /etc/cobbler/modules.conf'
Aug 14 15:53:17 localhost.localdomain cobblerd[2422]: [  OK  ]
Aug 14 15:53:17 localhost.localdomain systemd[1]: Started LSB: daemon for libvirt virtualization API.
```
From issue #1751 , tried below steps.
[root@localhost cobbler]# ln -s /usr/local/lib/python2.7/dist-packages/cobbler /usr/lib/python2.7/dist-packages
[root@localhost cobbler]# systemctl restart cobblerd

Still same error.

How to fix this?

Thanks
Mohan

**Comment by sgh1** [comment]
This ended up being helpful: https://lists.fedorahosted.org/pipermail/cobbler/2011-December/007025.html Just remove the try/catch and say serializer.deserialize(item) instead of if not serializer.deserialize(item): raise"".

Restart and check the log again.

My issue ended up being that I had a kickstart file in the .../cobbler/systems.d directory. I'm not familiar with the code base, but it seems like cobbler was trying to read this is a YAML file, which it is not. I mention this because it seems possible that you could have a minor typo in a config, and you'd end up here.

Maybe these errors shouldn't be squashed with raise"" ?

**Comment by SchoolGuy** [comment]
Well okay. So the Python2 version won't get fixes from me. I would highly advise at least to upgrade to 2.8.5! If somehow possible to Cobbler 3.x.x to be Python 3.

Regarding the specific issue... @MohanrajBabu is this resolved or not?

**Comment by SchoolGuy** [comment]
No response and the mysql backend is removed anyway. Thus closing this one.

**Comment by fnevgeny** [comment]
FWIW, in my case, it was a *directory* present in systems.d that raised the error.
