### ISSUE TITLE
koan-2.0.7.1-6.module_el8.0.0+43+68a81eb1 doesn't recognize CentOS 8.0.1905

### ISSUE THREAD

**Issue by xdroop** [cobbler/cobbler#2162]
(If this is not the correct place for Koan issues, I apologize.)

Installed CentOS 8 via Cobbler using the Base group plus a handful of other convenience packages, then ran `dnf -y update ; dnf -y install koan`.

Koan doesn't recognize CentOS 8.0.1905.

```
[root@centos8-testing ~]# cat /etc/redhat-release
CentOS Linux release 8.0.1905 (Core)
[root@centos8-testing ~]# dnf list koan
Installed Packages
koan.noarch           2.0.7.1-6.module_el8.0.0+43+68a81eb1            @AppStream
[root@centos8-testing ~]# koan --replace-self --server=store03 --profile=CentOS-8
- looking for Cobbler at http://store03/cobbler_api
- reading URL: http://store03/cblr/svc/op/ks/profile/CentOS-8
install_tree: nfs://store03:/export/kickstart/CentOS-8
downloading initrd initrd.img to /boot/initrd.img
url=http://store03/cobbler/images/CentOS-8/initrd.img
- reading URL: http://store03/cobbler/images/CentOS-8/initrd.img
downloading kernel vmlinuz to /boot/vmlinuz
url=http://store03/cobbler/images/CentOS-8/vmlinuz
- reading URL: http://store03/cobbler/images/CentOS-8/vmlinuz
failed to detect local OS version from /etc/redhat-release
```
Details on store03, if it matters:
```
[root@store03 ~]# cat /etc/redhat-release ; rpm -q cobbler
CentOS release 6.10 (Final)
cobbler-2.6.11-1.el6.x86_64
```

**Comment by opoplawski** [comment]
You have installed koan from the base operating system so reporting at bugzilla.redhat.com against the koan component of RHEL8 seems the appropriate thing to do.

If you would like to test the upstream version of koan, you can try https://copr.fedorainfracloud.org/coprs/orion/cobbler/ and make sure the rhn-tools module is disabled as noted.  If you find bugs with that please report to https://github.com/cobbler/koan/issues.  Thanks!
