### ISSUE TITLE
System installation step

### ISSUE THREAD

**Issue by MohanrajBabu** [cobbler/cobbler#2163]
Hello,

This is a question post:

Is it possible in cobbler to check the detailed installation steps of a system

[root@localhost ~]# cobbler system list
   CentOS-Mysqlsys
   CentOS-Sys1

Is it possible to check how the system CentOS-Mysqlsys will be installed via cobbler command.

Thanks,
Mohan

**Comment by opoplawski** [comment]
Questions should go to the mailing list, but you want:

cobbler system getks -n CentOS-Sys1

(get-autoinstall in cobbler 3)
