### ISSUE TITLE
No module named 'ipaddress'

### ISSUE THREAD

**Issue by hightekjonathan** [cobbler/cobbler#2164]
I did a fresh install of the packaged version of Cobbler on Fedora 30 Server edition. The installation succeeded, and starts without issue, however when trying to access the Web GUI, I get an error saying that `No module named 'ipaddress'` could be found in `/usr/share/cobbler/web/cobbler_web/views.py in <module>, line 12`. I tried googling the error, but was unable to find helpful information. Is this a known issue, or is it slated to be fixed in the next release? Or am I just out of luck for right now?

**Comment by opoplawski** [comment]
This is a bug in the Fedora cobbler rpm and should be filed at bugzilla.redhat.com.  For now you can simply do:
```
dnf install python2-ipaddress
```
I've submitted updates to Fedora to address this:
https://bodhi.fedoraproject.org/updates/FEDORA-2019-10dba40629
