### ISSUE TITLE
cobbler installation stuck

### ISSUE THREAD

**Issue by BijoyPrajapati** [cobbler/cobbler#2167]
Hi I have a cobbler for pxe installation. When I try to network installation, it started but it goes stopped installation in the following path and asking lots of question : I tried in a vm with the same kickstart file, but there is no error like this and installation completed. I only have this error in another physical machine. What could be the cause ?

![image](https://user-images.githubusercontent.com/52848005/66916599-2d943300-f039-11e9-9015-d1aedc6daf0a.png)

**Comment by BijoyPrajapati** [comment]
#platform=x86, AMD=64, or Intel EM64T
#version=DEVEL

#Use graphical or text install
text

# Root password
rootpw --iscrypted $6$CtKciQVWEXrlYEKZ$8NYyd0AsIgPj.Afu11OOFa35DR4bfnghW5QHwn.q1
# System authorization information
auth --enableshadow --passalgo=sha512
firewall --disabled
selinux  --disabled

firstboot --disabled

# System language
#lang en_US.UTF-8
lang en_US
# Keyboard layouts
#keyboard --vckeymap=us --xlayouts='us'
keyboard us
# System timezone
timezone Asia/Kolkata
#timezone Asia/Kolkata --isUtc --nontp

url --url=$tree
#Use HTTP installation media
#url --url="http://10.1.20.201/cobbler/ks_mirror/EL7.3-X86_64/"
$yum_repo_stanza

$SNIPPET('network_config')

install
reboot

ignoredisk --only-use=sda

# System bootloader configuration
#bootloader --append=" crashkernel=auto" --location=mbr --boot-drive=sda
#autopart --type=lvm
# Partition clearing information
clearpart --none --initlabel

%pre
$SNIPPET('log_ks_pre')
$SNIPPET('kickstart_start')
$SNIPPET('pre_install_network_config')
#Enable installation monitoring
$SNIPPET('pre_anamon')
$SNIPPET('workstation_partition')
%end

%packages
$SNIPPET('func_install_if_enabled')
$SNIPPET('puppet_install_if_enabled')
$SNIPPET('el7.3_workstation_packages')
%end

%post --nochroot
$SNIPPET('log_ks_post_nochroot')
%end

%post
yum -y remove NetworkManager
$SNIPPET('log_ks_post')
$SNIPPET('clean_yum_config')
$yum_config_stanza
$SNIPPET('post_install_kernel_options')
$SNIPPET('post_install_network_config')
$SNIPPET('set_dhcp_hostname')
$SNIPPET('func_register_if_enabled')
$SNIPPET('el7_puppet_register_if_enabled')
$SNIPPET('download_config_files')
$SNIPPET('koan_environment')
#$SNIPPET('redhat_register')
$SNIPPET('cobbler_register')
$SNIPPET('nvidia-driver')
$SNIPPET('workstation_post')
$SNIPPET('facter_facts_if_puppet_enabled')
$SNIPPET('gdm_bits')
$SNIPPET('post_anamon')
#$SNIPPET('el7_workstation_mate_desktop')
$SNIPPET('kickstart_done')
%end


#%addon com_redhat_kdump --enable --reserve-mb='auto'

#%end

#%anaconda
#pwpolicy root --minlen=6 --minquality=50 --notstrict --nochanges --notempty
#pwpolicy user --minlen=6 --minquality=50 --notstrict --nochanges --notempty
#pwpolicy luks --minlen=6 --minquality=50 --notstrict --nochanges --notempty
#%end

**Comment by SchoolGuy** [comment]
@BijoyPrajapati What cobbler version are you using? What Distro are you trying to install and with what version? Is you VM-Image maybe a minimalized image where you can't configure these options at install time?

**Comment by BijoyPrajapati** [comment]
> @BijoyPrajapati What cobbler version are you using? What Distro are you trying to install and with what version? Is you VM-Image maybe a minimalized image where you can't configure these options at install time?

>@SG @ cobbler version using 2.8.7 , distro using el6.5, el6.8 & el 7. this is not gnome desktop version . The pxe is get stuck when I using any of the "$SNIPPET('el7.3_workstation_packages')". It asks yes or no question for each and every installation. But without this snippest, the installation is going well in any physical system. I tried with other snippests for workstation packages, but not successful.

**Comment by SchoolGuy** [comment]
@BijoyPrajapati A few notes for you:
1. There is no cobbler 2.8.7 if there is on your system I would be very interested what it is looking alike.
2. The snippet `el7.3_workstation_packages` is not known to upstream so I can't say how this modifies your system. This also applies for other `*_workstation_packages`.
3. Also you are heavily using self written snippets so I have no way of knowing how your system is looking.
4. Also for the next time: Don't post the password although it is encrpyted here in the question!

I have decided because your problem is so specific to your environment to close this issue because there would be no point in debugging this I am currently seeing no error related to cobbler here. If you have questions to kickstart files and how to write them properly then there are better places!

**Comment by BijoyPrajapati** [comment]
> @BijoyPrajapati A few notes for you:
> 
> 1. There is no cobbler 2.8.7 if there is on your system I would be very interested what it is looking alike.
> 2. The snippet `el7.3_workstation_packages` is not known to upstream so I can't say how this modifies your system. This also applies for other `*_workstation_packages`.
> 3. Also you are heavily using self written snippets so I have no way of knowing how your system is looking.
> 4. Also for the next time: Don't post the password although it is encrpyted here in the question!
> 
> I have decided because your problem is so specific to your environment to close this issue because there would be no point in debugging this I am currently seeing no error related to cobbler here. If you have questions to kickstart files and how to write them properly then there are better places!
-----------------------------------------------------------------------------------------------------------------------------------
@SchoolGuy Hi, Thanks for your note and read carefully. 
1) I am using cobbler version "cobbler 2.8.2".
2) The installation issue of packages is resolved.
3) The password which I posted, was wrong, but I assure you from next time, I will keep mind your word.
I have now few queries : 
1) I install centos-7.4  in a virtual machine and a physical machine. I found there is no installation problem in VM, but I observed in physical machine that after post installation, it will ask for redhat registration and a user creation (text installation). But there was no such things pop up in VM. is there anyway to continue this registration without any popup? 

2) I m using puppet version 3.8.7 open source. I want to join all client machines in domain 2008R2 via puppet without ldap bind. I can join client systesm to the domain via puppet with ldap bind, but unable to join without ldap bind, it gives error. The attached error for your reference and let me know, if you require any more information.
