### ISSUE TITLE
Manpages build with setuptools integration

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2173]
@rbberger pointed out in https://github.com/cobbler/cobbler/issues/2165#issuecomment-542787275 that Sphinx (which is generating our manpages) is able to do this also inside the setup.py.

Here is a document for this: https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html

**Comment by watologo1** [comment]
python setup.py build_sphinx -b man

indeed creates manpages as needed. I guess this one can be closed. I point Richard to it. Once this shows up in a build file it is obvious.
