### ISSUE TITLE
Cobbler should optionally generate https URLs

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#2181]
### Is your feature request related to a problem?

Currently many places in Cobbler have hardcoded the `http://` protocol. It may be required in some environments to use HTTPS.

### Provide a detailed description of the proposed feature

There are various cases where `http://` may be undesired in favour of `https://`, the include according to the research of  @SchoolGuy the following places:

- Retrieval of auto-installation files (AutoYaST, kickstart & preseed files)
- Repository mirror handling
- Trigger of Cobbler Triggers via HTTP (pre- & post-installation)

### Alternatives you've considered

None

### Additional information

None

**Comment by SchoolGuy** [comment]
We have the following usage of hardcoded `http` generated URLs:

- URL for the kernel options that specify the autoinstallation file location: `cobbler/tftpgen.py`
- Image path for ipxe: `cobbler/tftpgen.py`
- Bootloader path for Windows: `cobbler/tftpgen.py`
- Configuration files in the tftproot: `cobbler/tftpgen.py`
- Kernel Parameters for Network bootable ISOs: `cobbler/actions/buildiso/netboot.py`
- Repository configuration for imported distros: `cobbler/modules/managers/import_signatures.py`
- Autoinstallation files that use a curl call to signal their installation status: `cobbler/auotinstallgen.py`

@meaksh @vzhestkov @agraul @ycedres any idea how to divide that? At the moment I have a single setting for them all which seems not right. However having a single setting for each of the usecase seems also overkill. So what are your ideas of splitting this up? I tend to leave the default definitely to `http`, as the certificates are not easy to setup per default, thus the user impact of introducing this is low. However those who want to use it for security should have a smooth experience and not suffer from undesired side-effects.

**Comment by vzhestkov** [comment]
At least we can reduce the number of additional parameters by splitting where this URLs go, I mean as I can see most of them related to the data passed with `tftp`. Maybe I'm wrong here and the rest indirectly related to tftp also. Maybe it make sense to split out the setting for `tftp` part?

**Comment by SchoolGuy** [comment]
Well you are right, however putting ipxe, windows, installation status and kernel options in the same setting feels wrong. However I agree with you that it seems "logical". So you would group the setting by source code file @vzhestkov?

**Comment by SchoolGuy** [comment]
@brejoc If you remember your plan for this one you are of course invited to leave a comment too! :)

**Comment by vzhestkov** [comment]
In case of windows it also make sense to split it individually. In this case it looks like mostly by the source file with the windows setting as the only exception. But not sure actually if it make sense to split windows out as it related to `tftp` anyway. And in general it looks like in 99.99% all of these settings will stay as `http`.

**Comment by brejoc** [comment]
@SchoolGuy Uff… to be honest, my memories around this are less than vague. Sorry! :(

**Comment by SchoolGuy** [comment]
@agraul @meaksh @ycedres Any idea from your side?

**Comment by ycedres** [comment]
@SchoolGuy To have a better understanding, is the `autoinstall_protocol` option always going to be either `http` or potentially `https` value or is there any other possibility apart from those two?

**Comment by SchoolGuy** [comment]
@ycedres I believe that it indeed will always stay with http or https. At least for the next 5-10 years. Maybe Quic or a yet not existing protocol will rise but that is a future I cannot foresee.

**Comment by SchoolGuy** [comment]
@agraul @ycedres @meaksh Any more comments on this matter?

**Comment by ycedres** [comment]
Really not from my side. I was asking because I thought if it might be feasible to add some "secure connection" flag instead of explicitly specifying http or https protocol. I really don't quite understand why having just one `autoinstall_protocol` option is an overkill as you mentioned.

**Comment by SchoolGuy** [comment]
Well it is not overkill but it might be too little. If we only have one setting, then a user might have more HTTPs then he asked for. The early boot process might not have the CA from the server available.

**Comment by agraul** [comment]
I don't have enough context yet and didn't think hard enough about this question to form an opinion yet. I'm passing on this one for now.

**Comment by SchoolGuy** [comment]
@meaksh Any opinion or other comments?

**Comment by SchoolGuy** [comment]
@meaksh Any opinion or do you want to skip this one?
