### ISSUE TITLE
Cobbler uses deprecated MD5 password hashing, cannot run in FIPS mode

### ISSUE THREAD

**Issue by zagarjr** [cobbler/cobbler#2184]
Trying to run Cobbler under RHEL7 with FIPS-mode enabled... cobbler logins fail due to
md5 password hashes being unsupported in FIPS.

cobbler/modules/authn_configfile.py and cobbler/utils.py are the only places where md5 is mentioned, and python2.7 hashlib supposedly provides sha256() so I tried the trivial replacement of sha256() for md5(), and used "openssl passwd -5" to generate a proper password hash...

unfortunately, my trivial changes did not work...

help?

**Comment by SchoolGuy** [comment]
@zagarjr I will investigate tomorrow. It would help knowing which version of cobbler you are using!

**Comment by SchoolGuy** [comment]
@zagarjr Okay I have now setup a VM as a test environment. I never worked with CentOS or even the FIPS-mode. I will have a look and get back as soon as I got a good solution for you.

@brejoc or @watologo1 do we have something in our current SLES versions? I only found something for SLES 12 SP1.

@mcalmer Is this something a customer could open a ticket for at SUMA?

**Comment by SchoolGuy** [comment]
This is also relevant for 3.0.x releases as nothing has changed in this piece of code.

**Comment by juliogonzalez** [comment]
... and if the option is changed from the default to sha256, something should be done.

For example block the accounts using md5 and ask for a password reset.

**Comment by paususe** [comment]
@SchoolGuy 
Will this impact the FIPS certification?

**Comment by SchoolGuy** [comment]
@paususe Well sadly yes as far as I know. I know what to do but I haven't had the time to work on it.

This can be fixed like stated above if we rework the authentication mechanism of cobbler and use a more modern hash algorithm. I would say including testing the changes I would need half a week to do it.
