### ISSUE TITLE
Support for static routes on CentOS 7

### ISSUE THREAD

**Issue by tesujimath** [cobbler/cobbler#2193]
The provided snippet `pre_install_network_config` does not work with regard to static routes on CentOS 7, which may be defined per-interface.  It attempts to set them up like this:
```
  ip route add $network via $router dev \$IFNAME
```
at line 148 of `pre_install_network_config`.

The work-around to get these working on CentOS 7 (and surely some other distros?) is to replace that command with this:
```
  nmcli connection modify \$IFNAME +ipv4.routes "$network $router"
```

What's the best way to get such a variant into cobbler?  Some setting somewhere that says whether we're using NetworkManager for such things?

**Comment by SchoolGuy** [comment]
Well you can just replace the line with your line. The templates we deliver are suggestions and we hope that they help you in managing your infrastructure but of course the templates are not perfect so you may need to adjust them!

**Comment by tesujimath** [comment]
If you're open to pull requests to improve your templates and snippets, I think the whole community would benefit.

I'm thinking of a ksmeta variable called say NetworkManager, and a conditional on that being True in the snippet.  And some documentation, somewhere.

Are you interested?

**Comment by SchoolGuy** [comment]
Of course! We appreciate documentation as well as improvements to our code/snippets!

**Comment by SchoolGuy** [comment]
The question was answered and no follow ups were raised. Thus closing this one.
