### ISSUE TITLE
EFI support in buildiso

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#2211]
Seems like this was on the agenda once, but was never done: https://github.com/cobbler/cobbler/issues/1756

PXE is starting to go away and therefore we need to be able to boot via EFI.

### The Behaviour you'd like

Be able to create ISOs that can be EFI-booted.

@watologo1, @SchoolGuy: Do you guys now what is needed to make this reality?

**Comment by watologo1** [comment]
I try to talk with Raymund about this and have a closer look at it. Probably not before next year.

**Comment by brejoc** [comment]
@watologo1 Awesome! Thanks a lot!

**Comment by Conan-Kudo** [comment]
As part of #2220, I changed cobbler's buildiso code to use xorrisofs. It may make sense after the fact to change this to use xorriso more fully, since it's the only ISO making tool I know of that everyone has that supports producing EFI-capable ISOs.

I switched livecd-tools/livecd-creator to use xorriso last year for similar reasons: https://github.com/livecd-tools/livecd-tools/commit/686e5b63111ba40319c7a42d0ec966260d43d2a9

**Comment by brejoc** [comment]
Sounds good. Thanks @Conan-Kudo!

**Comment by loreson** [comment]
Do we wan't to support 32bit EFI?

**Comment by Conan-Kudo** [comment]
32-bit UEFI is used in some cases to boot to 64-bit OSes, so probably?

**Comment by SchoolGuy** [comment]
@loreson If it is possible without too much trouble I would also like to see this happening.

**Comment by cpmcmah** [comment]
First post so I'm probably going to blow it, but how close are you all to making this happen? We have to install 800 Dell 7070s that do not support legacy with CentOS6. We cannot figure out UEFI with cobbler. Not much information on the internet. I was going to burn 20 disks to give to my guys. If you have any updates or, better yet, can point me to good information on setting cobbler up for UEFI, that would be awesome. We currently use Cobbler and CentOS6 Dell 7040s for our military folks. Going to 7 soon. Thanks.

**Comment by paususe** [comment]
Are there any news about this?

**Comment by SchoolGuy** [comment]
@paususe Nope we havn't had the time to do this.
