### ISSUE TITLE
what is the replacement URL for https://cobbler.github.io/manuals/ ?

### ISSUE THREAD

**Issue by hunter86bg** [cobbler/cobbler#2212]
Hello,

it seems that https://cobbler.github.io/manuals/ is unavailable for some reason.
As I'm quite new to cobbler, can someone point me to the documentation ?

Thanks in advance.

**Comment by SchoolGuy** [comment]
Yes that is corrected and intended. The manuals are at https://cobbler.readthedocs.io and https://koan.readthedocs.io
