### ISSUE TITLE
Cobblerd doesnt start on boot in Redhat 7.4

### ISSUE THREAD

**Issue by nagaphani23** [cobbler/cobbler#2221]
### Version

````
Cobbler 2.8.1
source: ?, ?
build time: Mon Jun 12 17:09:17 2017
````
Cobbler 2.8.1
### Question

Cobblerd is failing to start with below Exception:-
   CX: 'serializer: error loading collection **image**. Check /etc/cobbler/modules.conf'
Looks its failing while loading the collection **image**.

Cobblerd starts fine when I comment the image filed in '/usr/lib/python2.7/site-packages/cobbler/config.py'.
     
![image](https://user-images.githubusercontent.com/40656342/71380130-91ae1700-25e7-11ea-82a7-7c6e1bf97f58.png)

Can anyone help me in understanding what exactly the image collection looks for so that i can cross verify my config.

**Comment by SchoolGuy** [comment]
@nagaphani23 Please state the version you are running in the format of `cobbler version`. Then we may be able to help you. If your version is too outdated you may need to upgrade before we can help you!

**Comment by nagaphani23** [comment]
Cobbler version:-
Cobbler 2.8.1

**Comment by SchoolGuy** [comment]
@nagaphani23 Okay then please update first. We are preparing the release of 2.8.5 which will be the last supported Python2 release. If the error persists with 2.8.4 (which is the current version for the Python2 branch) then please ping again here.

**Comment by nagaphani23** [comment]
This is the version i am using.
Cobbler 2.8.1
  source: ?, ?
  build time: Mon Jun 12 17:09:17 2017

**Comment by SchoolGuy** [comment]
@nagaphani23 Please update. Since there should be no breaking changes it should be easy and you get quite some fixes for other stuff!

**Comment by SchoolGuy** [comment]
Images do work in general when using current releases. Thus closing this because of too little context.
