### ISSUE TITLE
missing documentation on installing cobbler-web

### ISSUE THREAD

**Issue by shahzebsiddiqui** [cobbler/cobbler#2222]
Section 5 on Web Interface https://cobbler.readthedocs.io/en/release28/web-interface.html 
should have section on installation of cobber web package. There was no reference for it, and I had trouble figuring this out until I asked the community.
There should be a section **5.0 Installing Cobbler Web** that mentions how to install the package.

### Screenshots

![image](https://user-images.githubusercontent.com/12942230/71522279-fee4d500-2891-11ea-9641-c6509ec3aff1.png)

**Comment by SchoolGuy** [comment]
The webinterface will be removed with 3.3.0 and thus I will close this issue. A new interface will be created when the Team has time and resources for it.
