### ISSUE TITLE
Just want to confirm the cobbler doesn't managed DHCP for IPv6

### ISSUE THREAD

**Issue by darcyllingyan** [cobbler/cobbler#2225]
Hi,
Based on #1680 , I just want to confirm the cobbler still doesn't have the managed dhcp for IPv6 and only for IPv4, right?

Thanks

**Comment by watologo1** [comment]
At least for dnsmasq case IPv6 DHCP server configuration writing seem to exists.
Afaik trend is moving to dnsmasq anyway.

cobbler/modules/managers/dnsmasq.py
                ipv6 = interface["ipv6_address"]

                if not mac:
                    # can't write a DHCP entry for this system
                    continue
...
                if ipv6 is not None and ipv6 != "":
                    systxt += ",[%s]" % ipv6
                systxt += "\n"
                dhcp_tag = interface["dhcp_tag"]
                if dhcp_tag == "":
                    dhcp_tag = "default"
...

PS: Let me know when you run into issues. For now I only run dhcp configuration for ISC, but I plan to use dnsmasq pretty soon as well.

**Comment by watologo1** [comment]
Just for the records (@darcyllingyan) this will change soon:
#2511
