### ISSUE TITLE
missing command "setting" from usage

### ISSUE THREAD

**Issue by shahzebsiddiqui** [cobbler/cobbler#2228]
Using cobbler version 2.8.5.

I noticed that the cobbler usage command when running ``cobbler --help`` did not have settings. Clearly this is a command that was missed in the output.

I see this is part of the function `print_help` https://github.com/cobbler/cobbler/blob/d2f327c6119add29364254c078e1a5c3a33a153c/cobbler/cli.py#L717

It may be worth adding this in there. Not sure if there are some other commands that were any other commands missed. 

```
[root@cherrysim ~]# cobbler --version
Cobbler 2.8.5
  source: ?, ?
  build time: Tue Oct 15 01:59:43 2019

[root@cherrysim ~]# cobbler --help
usage
=====
cobbler <distro|profile|system|repo|image|mgmtclass|package|file> ...
        [add|edit|copy|getks*|list|remove|rename|report] [options|--help]
cobbler <aclsetup|buildiso|import|list|replicate|report|reposync|sync|validateks|version|signature|get-loaders|hardlink> [options|--help]

[root@cherrysim ~]# cobbler setting --help
usage
=====
cobbler setting edit
cobbler setting report


```

**Comment by SchoolGuy** [comment]
Okay yes this should be possible to fix. I will prepare a PR until the end of this week.

**Comment by SchoolGuy** [comment]
Fixed through https://github.com/cobbler/cobbler/pull/2464
