### ISSUE TITLE
Add Debian Buster in distro_signatures for 3.0.x

### ISSUE THREAD

**Issue by hbokh** [cobbler/cobbler#2240]
### Version

````
# cobbler version
Cobbler 3.1.1
  source: ?, ?
  build time: Wed Jan 15 13:19:54 2020
````

### Question

Why do the 3.0.x signatures miss Debian Buster?
`wget https://cobbler.github.io/signatures/3.0.x/latest.json`

where the 2.8.x have them?
`wget https://cobbler.github.io/signatures/2.8.x/latest.json`

Please merge with #2082

**Comment by SchoolGuy** [comment]
Well I have to update them in the cobbler.github.io repo. I will try to update them tomorrow.

**Comment by hbokh** [comment]
Some remarks.
For some reason "buster" IS in the signatures when installed from package (3.1.1).
When you run `cobbler signature update`, "buster" is gone. Hence this question.

Reloading the signature always gives an error:

```
# cobbler signature update
task started: 2020-01-19_133933_sigupdate
task started (id=Updating Signatures, time=Sun Jan 19 13:39:33 2020)
running python triggers from /var/lib/cobbler/triggers/task/sigupdate/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/sigupdate/pre/*
shell triggers finished successfully
Successfully got file from https://cobbler.github.io/signatures/3.0.x/latest.json
*** TASK COMPLETE ***

# cobbler signature reload
There was an error loading the signature data in .
Please check the JSON file or run 'cobbler signature update'.
```

**Comment by hbokh** [comment]
Danke schön!
