### ISSUE TITLE
About "template-remote-kickstarts"

### ISSUE THREAD

**Issue by hbokh** [cobbler/cobbler#2246]
### Version

````
Cobbler 3.1.1
  source: ?, ?
  build time: Fri Jan 17 12:33:30 2020
````

### Question

Looking at file https://github.com/cobbler/cobbler/blob/master/config/bash/completion/cobbler#L16-L17
that was updated 28 days ago, it seems that `template-remote-kickstarts` is still an option in Cobbler 3. But it isn't.

On Cobbler 2:
```
# cobbler system add --template-remote-kickstarts
Usage: cobbler [options]

cobbler: error: --template-remote-kickstarts option requires an argument
```

On Cobbler 3:
```
# cobbler system add --template-remote-kickstarts
Usage: cobbler [options]

cobbler: error: no such option: --template-remote-kickstarts
```

Was this option completely removed in Cobbler 3?

**Comment by SchoolGuy** [comment]
A quick search indeed revealed nothing. Either it is hidden deeper or was removed in the past. I will try to have a look on Monday.

**Comment by SchoolGuy** [comment]
This was indeed removed with https://github.com/cobbler/cobbler/commit/83d233e4e876a645a67e35479db7f8b9afd67766

Also from our bash completion this was removed with https://github.com/cobbler/cobbler/commit/eda635ffb86bf81e56fb845070f798e5ea9e441f#diff-1ff61e97e995655681608a9d2952adfc9e45f25e2c3e2a73efbbc1f22e6ee2c6

Thus closing this issue.
