### ISSUE TITLE
passthru authentication is broken 

### ISSUE THREAD

**Issue by teridon** [cobbler/cobbler#2247]
Platform: Centos 7.7.1908
using EPEL packages: 
cobbler-2.8.5-0.3.el7.x86_64 
cobbler-web-2.8.5-0.3.el7.noarch

When using passthru authentication, cobbler reports 
KeyError at /
'REMOTE_USER'

### To Reproduce

1. Change 'modules.conf' to use passthru authentication and authorize all:
```
[authentication]
module = authn_passthru
[authorization]
module = authz_allowall
```
2.  configure Kerberos auth in cobbler_web.conf; something like
```
<Directory "/usr/share/cobbler/web/">
        <IfModule mod_ssl.c>
            SSLRequireSSL
        </IfModule>
        <IfModule mod_nss.c>
            NSSRequireSSL
        </IfModule>
        SetEnv VIRTUALENV
        Options Indexes MultiViews
        AllowOverride None
        <IfVersion <= 2.2>
            Order deny,allow
            Deny from all
        </IfVersion>
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
  AuthType Kerberos
  AuthName " Active Directory Login"
  KrbMethodK5Passwd On
  #Krb5KeyTab /etc/krb5.keytab
  KrbServiceName Any
  KrbMethodNegotiate On
  KrbVerifyKDC Off
  KrbAuthRealms DOMAIN.COM

  <Limit GET POST>
        Require valid-user
    Satisfy any
  </Limit>

</Directory>
```
3.  Restart httpd and cobblerd
4.  Navigate to /cobbler_web

### Expected behavior

If no Kerberos ticket is present, browser should prompt for Kerberos credentials.  After entering credentials, cobbler should present the cobbler home page. 

Instead, I get this error:
```Environment:


Request Method: GET
Request URL: https://gs483-cobbler.mds.nasa.gov/cobbler_web/

Django Version: 1.11.23
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'cobbler_web')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware')



Traceback:

File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/share/cobbler/web/cobbler_web/views.py" in index
  36.    if not test_user_authenticated(request): return login(request,next="/cobbler_web", expired=True)

File "/usr/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/usr/share/cobbler/web/cobbler_web/views.py" in login
  1284.         return accept_remote_user(request, next)

File "/usr/share/cobbler/web/cobbler_web/views.py" in accept_remote_user
  1294.     username = request.META['REMOTE_USER']

Exception Type: KeyError at /
Exception Value: 'REMOTE_USER'
```

Cobbler 2.8.5
  source: ?, ?
  build time: Tue Oct 15 01:59:43 2019

### Additional context

I configured a separate directory for Kerberos auth and it works fine; it's only cobbler that is failing to get the REMOTE_USER key.

I tried adding 'django.contrib.auth.middleware.RemoteUserMiddleware' in settings.py in the MIDDLEWARE section but this did not resolve the issue.   I also tried adding the following to settings.py but this still did not resolve the issue.
```
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.RemoteUserBackend',
)
```

FWIW, passthru/Kerberos auth worked with cobbler 2.6.11

**Comment by opoplawski** [comment]
I can't speak to how 2.6.11 worked, but I think this is pretty much as expected.  I think with passthru the web browser is expected to handle authentication completely.  With our setup (using GSSAPI) only users with valid tickets are allowed in.  You cannot enter a username and password.

**Comment by SchoolGuy** [comment]
Let's add a test for this and see if it works. If not let's fix it.

**Comment by SchoolGuy** [comment]
So I totally missed this one sadly. We have a test for the passthrough auth for a while now. The main Cobbler Server doesn't care about the username and password. It expects to be handed the Shared Secret in the password field.

A quickfix for you is the following replacement in `/usr/share/cobbler/web/cobbler_web/views.py`:

Look for the line `token = remote.login(username, utils.get_shared_secret())`  
And replace it with `token = remote.login('', utils.get_shared_secret())`

But that will only get you one step further. The Docs are saying that Django is doing it very similar to us (see: https://docs.djangoproject.com/en/3.1/howto/auth-remote-user/). Thus I think somewhere we need to find your config error because normally that variable should be present!

**Comment by SchoolGuy** [comment]
P.S.: Before I wrote my answer I googled for an hour. I havn't found any occurrence where this was not set as the basic assumption. Thus if this is not present the login can't succeed. So I believe that Cobbler does in fact handle this correctly, although the Error Message could be displayed better I think. :/

**Comment by SchoolGuy** [comment]
But that Django Monster will be gone soon. Thus don't worry about it.

**Comment by SchoolGuy** [comment]
@teridon Please Please Please try to update to a Cobbler 3 Version. We have a very very very small core contrib team and thus lacking the possibility to support such old versions in most of the times.

**Comment by SchoolGuy** [comment]
I consider this as fixed because there was no response for five days to my direct mention. Since I can't find a Bug in Cobbler I consider it invalid. If someone disagrees, please reopen this issue!
