### ISSUE TITLE
Docker-CI Pipeline does not work

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2252]
### Describe the bug

When you take a look at the CI then you see that this is not working although it is green: https://travis-ci.org/cobbler/cobbler/jobs/642427984#L2161

### To Reproduce

1. Make a PR or Commit
2. Look on the CentOS or Fedora builds
3. Scroll down to the end

### Expected behavior

Either a failing CI or a successful built

### Additional context

Detected by @hbokh 
CC @rbberger

**Comment by hbokh** [comment]
Adding something like `set -eo pipefail` to the scripts in tests can make a difference.

**Comment by hbokh** [comment]
> Adding something like `set -eo pipefail` to the scripts in tests can make a difference.

Yep, it does! See https://travis-ci.org/cobbler/cobbler/builds/642528071
CentOS7 build OK, the rest of the RPM builds all failed.

**Comment by hbokh** [comment]
🎉One to go!
https://travis-ci.org/cobbler/cobbler/builds/642539437

**Comment by hbokh** [comment]
Done! Updated RPM related Dockerfiles to at least compile a working Cobbler package.
All green: https://travis-ci.org/cobbler/cobbler/builds/642746967
Due to the added setting `set -eo pipefail` in `tests/build-and-install-rpms.sh`, builds will exit with a non zero error when things go wrong.

**Note**: CentOS7 depends on package `python36-cheetah` that is currently still in testing for EPEL7. If accepted, it will be in EPEL7 in 2 weeks. Have to adapt `CentOS7.dockerfile` accordingly.

**Comment by SchoolGuy** [comment]
@hbokh See comments in your PR. If you wish to clean it up we leave it open until it is in EPEL 7. Otherwise I will do it for you.

**Comment by hbokh** [comment]
@SchoolGuy If it is okay with you, I will created a new PR to reflect the changes I made.

I don't think it is a good situation leave the CI broken completely for ~ 2 weeks, waiting for an EPEL7 package to arrive! Once the package is there, it is easy to update.
Other possibility is to have the CentOS7 break on purpose for the next coming weeks and it will be fixed automagically.

**Comment by SchoolGuy** [comment]
@hbokh Of course I would very much appreciate that PR (already seen it) and I am for an automagic fix of this because it is "just" the rpms. The application itself is not broken. Yes I don't like having a broken CI but we won't get cheetah in there now so let's reflect that state.

**Comment by SchoolGuy** [comment]
Okay CI currently fails as expected so it works again. Debian builds are a different story so we will close this.
