### ISSUE TITLE
distro_signatures.json for release28

### ISSUE THREAD

**Issue by dansou901** [cobbler/cobbler#2256]
### Version

2.8.x

### Question

Hi @SchoolGuy,
you wanted me to open an issue to remind you about the existing distro_signatures.json for the release28 branch. Will you host it on cobbler.github.io?
Regards,
dansou901

**Comment by dansou901** [comment]
see https://cobbler.github.io/signatures/2.8.x/latest.json

**Comment by dansou901** [comment]
needs to be updated to latest signatures

**Comment by opoplawski** [comment]
Yes, need to get Fedora 31 added there.   And likely Fedora 32 while we're at it.

**Comment by SchoolGuy** [comment]
With https://github.com/cobbler/cobbler.github.io/commit/95c050597b72e195b3b511cc16aadf1007ad88b2 and https://github.com/cobbler/cobbler/commit/3e9acdee44cbf4bcba920b3053abfcc3cee9c7b1 this was fixed.
