### ISSUE TITLE
why pxe boot will prompt to select profile

### ISSUE THREAD

**Issue by pharthiphan** [cobbler/cobbler#2258]
### Describe the bug

PXE boot is prompting to select the profile

using a separate DHCP server

### To Reproduce

1. Add a system to the cobbler
2. Netboot enabled
3. restart server to boot using PXE
4. after acquiring IP it is prompting to select the profile on the blue screen. default is (local)

### Expected behavior

system to boot from the profile set

### Version

2.8.5

**Comment by pharthiphan** [comment]
![image](https://user-images.githubusercontent.com/18302174/73728218-f0bf8980-4758-11ea-8394-3f092ce0247f.png)

**Comment by mercury00** [comment]
Can you verify that the IP it is receiving is the one you've assigned?

Specifically, can you verify that the mac address you entered for that system matches the mac address that it uses to obtain it's DHCP address?

I always get this screen when I PXE boot a system that does not have the correct IP, mac address, or netboot enabled. Note than systems with management interfaces will give both the virtual management interfaces's mac address as well as the ethernet mac address to the dhcp server, but only the ethernet interface is the one booted from, which I usually can only get by booting the system and asking the kernel to display.

**Comment by mercury00** [comment]
If you're using a different dhcp server, you'll need to have cobbler control it somehow in order to add the dhcp entries required to boot the correct kernel. Otherwise this feature won't work.

That's not a bug, it's just how dhcp works.

**Comment by SchoolGuy** [comment]
No response from the reporter and no further participants. Since this is working in Cobbler 3.x.x according to my investigations (and in Cobbler 2.x.x also) I will close this for now.
