### ISSUE TITLE
Are template_files dict or list?

### ISSUE THREAD

**Issue by hbokh** [cobbler/cobbler#2262]
### Version

````
Cobbler 3.1.1
  source: ?, ?
  build time: Sat Feb  8 14:38:00 2020
````

### Question

Please compare this:

`["template_files", {}, 0, "Template Files", True, "File mappings for built-in config management", 0, "list"]`
https://github.com/cobbler/cobbler/blob/master/cobbler/items/distro.py#L55

with 

`["template_files", {}, '<<inherit>>', "Template Files", True, "File mappings for built-in config management", 0, "dict"],`
https://github.com/cobbler/cobbler/blob/master/cobbler/items/profile.py#L61

and

`["template_files", {}, 0, "Template Files", True, "File mappings for built-in configuration management", 0, "dict"],`
https://github.com/cobbler/cobbler/blob/master/cobbler/items/system.py#L74

Which one is correct? Because one should expect `template_files` to be OR **dict** OR **list** everywhere.
Or do `template_files` differ between distro's, profiles and systems?

**NOTE** There is some more I found. Another is `virt_file_size`, which is an "int" for profile, but a "float" in system.
https://github.com/cobbler/cobbler/blob/master/cobbler/items/profile.py#L66
https://github.com/cobbler/cobbler/blob/master/cobbler/items/system.py#L78

**Comment by SchoolGuy** [comment]
In general I would go for the option which is used more often - so in this case a dict - but this is just an assumption. I did not look in the code for writing this. I think it is good that this is documented here and I think it would be good to fix this after we have a stable package build and my tests are merged because then we _may_ see any side effects these subtle changes are generating.

**Comment by SchoolGuy** [comment]
@hbokh Do we have any follow ups or can this be considered done?

**Comment by hbokh** [comment]
Unless I missed something it has not been fixed or being worked on. So it is not done.

In the meantime last week we migrated to Cobbler 3.1.2 at work and so far things seem to behave quite well.

**Comment by SchoolGuy** [comment]
@hbokh That is good to hear. I will then put this on the board as a todo.

**Comment by SchoolGuy** [comment]
According to `item.py +28` we know that the default value of this should be a dict. Thus this is definitly a dict. Let's fix it for the next release!

**Comment by SchoolGuy** [comment]
Fixed through https://github.com/cobbler/cobbler/pull/2464
