### ISSUE TITLE
The createrepo usage issue in cobbler 3.x version

### ISSUE THREAD

**Issue by darcyllingyan** [cobbler/cobbler#2264]
Hi,
After check the installation guide, it said

>  "Since 3.0.0 you will need Python 3. "

But now when install the cobbler 3.x version:
```
rpm -ivh cobbler-3.1.2-1.el7.noarch.rpm
error: Failed dependencies:
        createrepo is needed by cobbler-3.1.2-1.el7.noarch
        dnf-plugins-core is needed by cobbler-3.1.2-1.el7.noarch
```
But createrepo could only be used in python2.x.
So in python3.x, how to use createrepo with cobbler-3.x version? Thanks.

Thanks
Darcy

**Comment by SchoolGuy** [comment]
We are sadly not done with #1930 so this is currently not possible. Cobbler is a big project (feature wise) and we are currently no that many devs. I will keep you however posted if there is progress about this topic.

**Comment by hbokh** [comment]
Just wondering how that RPM package was build / where it was coming from.
Also, this line / package is in vain?
https://github.com/cobbler/cobbler/blob/master/dockerfiles/CentOS7.dockerfile#L45

**Comment by darcyllingyan** [comment]
Hi @SchoolGuy   
Thanks very much for the information, so now if I want to use the createrepo in cobbler 3.x, could I manually install the createrepo_c after install the cobbler 3.x version?

@hbokh,
Thanks very much for the information, I create the 3.x rpm package three days ago with the code from master branch. The rpm package couldn't be created successfylly with cobbler 3.1.1, but seems the master branch is OK.
after I git clone the newest code from master branch, the createrepo is still needed.
```
]# git clone --depth=50 https://github.com/cobbler/cobbler.git cobbler/cobbler
Cloning into 'cobbler/cobbler'...
fatal: unable to access 'https://github.com/cobbler/cobbler.git/': Failed connect to github.com:443; Connection timed out
[root@cnet-per-test master_version]# export http_proxy=http://135.245.48.34:8000
[root@cnet-per-test master_version]# export https_proxy=http://135.245.48.34:8000
[root@cnet-per-test master_version]# git clone --depth=50 https://github.com/cobbler/cobbler.git cobbler/cobbler
Cloning into 'cobbler/cobbler'...
remote: Enumerating objects: 1601, done.
remote: Counting objects: 100% (1601/1601), done.
remote: Compressing objects: 100% (777/777), done.
remote: Total 1601 (delta 895), reused 1275 (delta 778), pack-reused 0
Receiving objects: 100% (1601/1601), 4.73 MiB | 2.01 MiB/s, done.
Resolving deltas: 100% (895/895), done.

]# cat dockerfiles/CentOS7.dockerfile
# vim: ft=dockerfile

FROM centos:7

RUN yum makecache fast && \
    yum install -y epel-release && \
    yum install -y https://repo.ius.io/ius-release-el7.rpm \
                   https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum makecache fast

RUN yum install -y          \
# Dev dependencies
    git                     \
    rsync                   \
    make                    \
    dnf-plugins-core        \
    epel-rpm-macros         \
    openssl                 \
    mod_ssl                 \
    python-sphinx           \
    python36-coverage       \
    python36-devel          \
    python36-distro         \
    python36-future         \
    python36-pyflakes       \
    python36-pycodestyle    \
    python36-setuptools     \
    python36-requests       \
    python36-sphinx         \
    rpm-build

RUN yum install -y          \
# Runtime dependencies
    httpd                   \
    python36-mod_wsgi       \
    python36-pymongo        \
    python36-PyYAML         \
    python36-netaddr        \
    python36-simplejson     \
    python36-tornado        \
    python36-django         \
    python36-dns            \
    python36-ldap3          \
    python36-cheetah        \
    **createrepo              \**
    xorriso                 \
    grub2-efi-ia32-modules  \
    grub2-efi-x64-modules   \
    logrotate               \
    syslinux                \
    systemd-sysv            \
    tftp-server             \
    fence-agents

COPY . /usr/src/cobbler
WORKDIR /usr/src/cobbler

VOLUME /usr/src/cobbler/rpm-build

CMD ["/bin/bash", "-c", "make rpms"]
```

Thanks
Darcy

**Comment by brejoc** [comment]
I'm wondering if we could just switch out the dependencies. :thinking:

**Comment by hbokh** [comment]
> But I'm not sure if I get the syntax right. What exactly is this doing?

If EL7 then install `createrepo`, if not EL7 install `createrepo_c`. Right @Conan-Kudo ?

**Comment by Conan-Kudo** [comment]
That is correct.

**Comment by hbokh** [comment]
Thanks! This should be reflected in the (current) Dockerfiles too:

- https://github.com/cobbler/cobbler/blob/master/dockerfiles/CentOS8.dockerfile#L52
- https://github.com/cobbler/cobbler/blob/master/dockerfiles/Fedora29.dockerfile#L40
- https://github.com/cobbler/cobbler/blob/master/dockerfiles/Fedora30.dockerfile#L40

**Comment by SchoolGuy** [comment]
I would close this now. The dependencies have been switched and CI does not report any errors so far. If there are bugs with these exchanged dependencies then I would say let's open a bug report.

If there is anything regarding this question then I would say just reopen this issue @darcyllingyan !
