### ISSUE TITLE
/var/lib/cobbler/config still used?

### ISSUE THREAD

**Issue by thiller2018** [cobbler/cobbler#2276]
scm_track still tries to also upate config, which is not present in my setup.
Is this a leftover from older versions?

**Comment by SchoolGuy** [comment]
@thiller2018 Yes this should of course be used! There should be a few files and at least a one folder under it.

See for example: https://github.com/cobbler/cobbler/blob/master/setup.py#L576

**Comment by thiller2018** [comment]
This is a file in /var/lib/cobbler and not in /var/lib/cobbler/config,
The directory /var/lib/cobbler/config doesn't exist in my environment.

thiller@cobbler:/var/lib/cobbler> ls
backup  bind_serial  collections  distro_signatures.json  grub_config  loaders  lock  scripts  snippets  templates  triggers  web.ss  webui_sessions

**Comment by SchoolGuy** [comment]
Well according to `setup.py` the distro signatures should be found under `/var/lib/cobbler/config/cobbler/distro_signatures.json. But if that directory is not present then I guess that folder has no meaning.

**Comment by thiller2018** [comment]
distro_signatures.json is in /var/lib/cobbler

**Comment by SchoolGuy** [comment]
@thiller2018 Interesting. Then you are right. I guess we can remove that directory then.

**Comment by SchoolGuy** [comment]
This can be closed due to the already merged PR
