### ISSUE TITLE
Provided httpd cobbler_web.conf is incorrect

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#2286]
### Describe the bug

Commit c304030f54605f2b7e5e27747797cc743c1d6e56 added VirtualHost statements to the apache cobbler_web.conf file.  This does not work on Fedora/RedHat because it does not actually enable and configure SSL in that virtualhost, so you end up with a standard http server on the https port.  I don't know why this was added as the previous version appeared to work fine.

### Version

 3.1.1

**Comment by SchoolGuy** [comment]
This means that this bug/problem was introduced with https://github.com/cobbler/cobbler/pull/2080

Hm webserver configuration works apparently because the CI has a running webserver so the current api tests green. When using https we will need to adjust the cobbler config anyway. So I don't see that as bug here.

What I am now indeed seeing and have not seen is in the past then when SSL is configured the wsgi statements are missing.

**Comment by hbokh** [comment]
FYI It was me who added these lines as a hack in CI:

https://github.com/cobbler/cobbler/blob/master/tests/build-and-install-rpms.sh#L35-L40

**Comment by opoplawski** [comment]
I just ran into this again testing our cobbler 3.1.2 on EL7.  I have to remove the VirtualHost lines to get httpd to start.  Can we please remove them?  @thiller2018 indicates it's to make it easier to run the gui on HTTP, but that's just backwards from a security standpoint.

**Comment by SchoolGuy** [comment]
So the webinterface will be removed with 3.3.0

I won't do this for the (probably) last minor release with that config file available.

**Comment by asimat** [comment]
Will there be a replacement for Web Interface ?

Remove means lots of people will stop using the new versions of cobblers.

**Comment by SchoolGuy** [comment]
@asimat There will be indeed a replacement. This new web-interface will be decoupled to enable people to run Cobbler in a Container and not have a dedicated Server for it. This new web-interface will be written in Angular and be published once the contributor who does the initial work feels comfortable enough to publish it. It will have the same feature for version 1.0 and will be compatible with Cobbler 3.3.0 and onward in the first version.
