### ISSUE TITLE
cobbler system add fails in fresh 3.1.1 install

### ISSUE THREAD

**Issue by krehm** [cobbler/cobbler#2293]
I am running CentOS 8.1, I installed cobbler 3.1.1 from epel-release module cobbler:3.  While trying to create a new system, cobbler immediately fails with:

````
[root@delphi-mgmt /]# cobbler system add --name=bob
Traceback (most recent call last):
  File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 738, in main
    rc = cli.run(sys.argv)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 351, in run
    self.object_command(object_type, object_action)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 421, in object_command
    network_interface_fields, settings, object_action)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 231, in add_options_from_fields
    _add_parser_option_from_field(parser, field, settings)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 202, in _add_parser_option_from_field
    raise Exception("field %s default value (%s) is not listed in choices (%s)" % (name, default, str(choices)))
Exception: field power_type default value (ipmitool) is not listed in choices (['amt_ws', 'apc', 'apc_snmp', 'bladecenter', 'brocade', 'cisco_mds', 'cisco_ucs', 'compute', 'drac5', 'eaton_snmp', 'emerson', 'eps', 'evacuate', 'heuristics_ping', 'hpblade', 'ibmblade', 'idrac', 'ifmib', 'ilo', 'ilo2', 'ilo3', 'ilo3_ssh', 'ilo4', 'ilo4_ssh', 'ilo5', 'ilo5_ssh', 'ilo_moonshot', 'ilo_mp', 'ilo_ssh', 'imm', 'intelmodular', 'ipdu', 'ipmilan', 'kdump', 'mpath', 'redfish', 'rhevm', 'rsa', 'rsb', 'sbd', 'scsi', 'virt', 'vmware_rest', 'vmware_soap', 'wti', 'xvm'])
````

This happens because in `/etc/cobbler/settings` the parameter "power_management_default_type" is set to "ipmitool", but that is not a valid choice from the list above.

I don't use the power management feature in cobbler, so after debugging this I changed "ipmitool" to one of the other values in the list, and the problem goes away.

The default value for `power_management_default_type` in `/etc/cobbler/settings` should be changed to match a valid value.

# cobbler version
Cobbler 3.1.1
  source: ?, ?
  build time: Tue Jan 14 05:07:09 2020

**Comment by watologo1** [comment]
This is fixed by commit:
commit dfec7bdcc796bdec41b862cd9694a3458c57a627 (origin/fix_fence_ipmitool, fix_fence_ipmitool)
Author: Thomas Renninger <trenn@suse.com>
Date:   Thu Feb 13 12:50:21 2020 +0100

    Add fence_ipmitool wrapper script calling fence_impilan with lanplus enabled
