### ISSUE TITLE
missing directory /usr/share/cobbler/web

### ISSUE THREAD

**Issue by mantel** [cobbler/cobbler#2294]
### Describe the bug

If only the main package cobbler is installed, status will print this error:

suma-head-srv:~ # systemctl status cobblerd
● cobblerd.service - Cobbler Helper Daemon
   Loaded: loaded (/usr/lib/systemd/system/cobblerd.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-03-03 09:39:35 CET; 1h 24min ago
  Process: 13568 ExecStartPost=/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi (code=exited, status=1/FAILURE)
 Main PID: 13567 (cobblerd)
    Tasks: 1
   CGroup: /system.slice/cobblerd.service
           └─13567 /usr/bin/python3 -s /usr/bin/cobblerd -F

Mär 03 09:39:35 suma-head-srv systemd[1]: Starting Cobbler Helper Daemon...
Mär 03 09:39:35 suma-head-srv touch[13568]: /usr/bin/touch: cannot touch '/usr/share/cobbler/web/cobbler.wsgi': No such file or directory
Mär 03 09:39:35 suma-head-srv systemd[1]: Started Cobbler Helper Daemon.

Reason is that directory /usr/share/cobbler/web is only in subpackage cobbler-web. Luckily this is just cosmetic as cobblerd is running just fine.

**Comment by SchoolGuy** [comment]
Problem is that this file (https://github.com/cobbler/cobbler/blob/master/config/service/cobblerd.service) is currently assuming that cobbler-web is also installed. This is not always the case and thus cobbler-web needs to adjust this or needs an own service file/systemd unit.

**Comment by SchoolGuy** [comment]
The webinterface will be removed with 3.3.0 and thus I will close this issue. A new interface will be created when the Team has time and resources for it.
