### ISSUE TITLE
install metadata not propagated to legacy field

### ISSUE THREAD

**Issue by bowlerct** [cobbler/cobbler#2311]
### Describe the bug

Setting Automatic Installation Template Metadata does not automatically propagate it to the legacy field `ks_meta` making this data not accessible in the install template var `ks_meta`

### To Reproduce
1. Under a system add data (`loc=bldg1`) to Automatic Installation Template Metadata
1. Create a snippet that uses `ks_meta["loc"]` and add to the systems install template
   ```
   #if "loc" in $ks_meta
   echo Location is $ks_meta["loc"]
   #end if
   ```
1. Click on the system and View Automatic Installation Template
1. See that Location is not present

### Expected behavior
Update the field Automatic Installation Template Metadata and click Save. The data should be immediately accessible in the `ks_meta `variable.

### Workaround
Update the field Automatic Installation Template Metadata and then run `cobbler system report `which updates the `ks_meta` data for all systems

This works because it triggers the method `remote.py::get_items(self, what)` and updates the `ks_meta` var

### Version
Master branch

````
Cobbler 3.1.2
  source: b'25209de', b'Mon Mar 16 09:37:43 2020 +0100'
  build time: Fri Mar 20 23:19:00 2020
````

**Comment by SchoolGuy** [comment]
CC @brejoc
