### ISSUE TITLE
After running cobbler sync i get TASK FAILED

### ISSUE THREAD

**Issue by jayavardhanu** [cobbler/cobbler#2318]
### Version

````paste below
````
### Question

````
cobbler sync
task started: 2020-04-07_204013_sync
task started (id=Sync, time=Tue Apr  7 20:40:13 2020)
running pre-sync triggers
cleaning trees
removing: /var/lib/tftpboot/grub/images
copying bootloaders
Exception occured: <class 'cexceptions.CX'>
Exception value: 'Could not find files matching /usr/lib/syslinux/pxelinux.0'
Exception Info:
  File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 87, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/dist-packages/cobbler/remote.py", line 186, in runner
    return self.remote.api.sync(self.options.get("verbose",False),logger=self.logger)
   File "/usr/lib/python2.7/dist-packages/cobbler/api.py", line 767, in sync
    return sync.run()
   File "/usr/lib/python2.7/dist-packages/cobbler/action_sync.py", line 114, in run
    self.tftpd.sync(self.verbose)
   File "/usr/lib/python2.7/dist-packages/cobbler/modules/manage_in_tftpd.py", line 168, in sync
    self.pxegen.copy_bootloaders()
   File "/usr/lib/python2.7/dist-packages/cobbler/pxegen.py", line 101, in copy_bootloaders
    dst, api=self.api, cache=False, logger=self.logger)
   File "/usr/lib/python2.7/dist-packages/cobbler/utils.py", line 1261, in copyfile_pattern
    raise CX(_("Could not find files matching %s") % pattern)

!!! TASK FAILED !!!
````

**Comment by SchoolGuy** [comment]
@jayavardhanu I took the liberty and tried to improve the formatting of your question. Also I would like to know which version this stacktrace is coming from.

Additionally the question you have would be interesting to know. The error message is clear that cobbler was not able to find the file you configured it should use.

**Comment by jayavardhanu** [comment]
Hello Enno G,
I have attached the screen shots of the errors i got.
Can you please have a look and get back to me.
As i'm new to cobbler and ubuntu and the post installation configurations
are complex. I'm finding it hard to troubleshoot the errors.
 That's the reason i'm reaching out for help.

-Jayavardhan

**Comment by SchoolGuy** [comment]
@jayavardhanu Sadly attachments via E-Mail are not working on Github. You need to upload the picture via the web interface (Drag & Drop should work).

Also if you are using Cobbler on Ubuntu 16.04, I was not able to distinguish the version (https://packages.ubuntu.com/search?keywords=cobbler). According to their repos they only have Cobbler 2.4.1 (which is way to old to help you).

**Comment by jayavardhanu** [comment]
so, using cobbler in ubuntu18.04 will be useful ?

**Comment by SchoolGuy** [comment]
@jayavardhanu Official packages feeds are no longer available on Ubuntu. You need to either grab a release from the OBS or you need the package from sources yourself.

**Comment by BRVN01** [comment]
Hello,
I managed to fix this error, first install pxelinux; to have access to some files. After that, copy these new files to some folders and then run 'cobbler sync', the error must be gone, at least it works for me, I hope I can help.

sudo cp /usr/lib/PXELINUX/pxelinux.0 /usr/lib/syslinux/
sudo cp -v /usr/lib/syslinux/modules/bios/{ldlinux.c32,libcom32.c32,libutil.c32,vesamenu.c32} /var/lib/cobbler/loaders/
sudo cp -v /usr/lib/syslinux/modules/bios/{ldlinux.c32,libcom32.c32,libutil.c32,vesamenu.c32} /var/lib/cobbler/loaders/
sudo cp -v  /usr/lib/syslinux/modules/bios/menu.c32 /usr/lib/syslinux/menu.c32
sudo cp -v  /usr/lib/syslinux/modules/bios/chain.c32 /usr/lib/syslinux/chain.c32
sudo cobbler sync
