### ISSUE TITLE
Coobler2.8x in Ubuntu18.04 unable to update a profile to the Cobbler with the following command

### ISSUE THREAD

**Issue by jayavardhanu** [cobbler/cobbler#2320]
### Version

````paste below
sudo cobbler profile edit --name=ubuntu16.04-x86_64 --kickstart=/var/lib/cobbler/kickstarts/ubuntu16.04.ks
exception on server: 'kickstart not found: None'
````

### Question

<I created a kickstart file for ubuntu16.04 and while trying to update the kickstart file i get an error like kickstart not found>

**Comment by SchoolGuy** [comment]
@jayavardhanu Did you fix it or why did you close this one?

**Comment by jayavardhanu** [comment]
Yes fixed. For Debian based distributions we should use preseed file
instead of kickstart file
