### ISSUE TITLE
Dependency "file" missing for CentOS 8 docker image

### ISSUE THREAD

**Issue by dansou901** [cobbler/cobbler#2334]
### Describe the bug

On CentOS 8 as docker image basis, when trying to import an image with cobbler import, it files with the error "file - command not found". 
### To Reproduce

1. Install latest cobbler rpms in a CentOS 8 docker image and run it with supervisor
2. Try to import a distribution with cobbler import
3. See error "file - command not found" (or similar)

### Expected behavior

Distribution should be successfully imported.

### Version

````
Cobbler 3.1.1
  source: ?, ?
  build time: Tue Jan 14 05:07:09 2020
````

### Additional context

This is due to file not being a default package for the CentOS 8 docker image. If file would be added as a required dependency for the cobbler rpms for CentOS 8, this would be fixed.

**Comment by SchoolGuy** [comment]
I just found out that the `file` package is missing in our specfile. Thus we need to adjust it instead of just the image specific to CentOS 8.
