### ISSUE TITLE
LDAP not working in CentOS 8 docker image

### ISSUE THREAD

**Issue by dansou901** [cobbler/cobbler#2335]
### Describe the bug

When trying to use LDAP authentication (configured in both modules.conf and settings) it fails with "Module not found".

### To Reproduce

1. Install cobbler and cobbler-web in CentOS 8 docker image and run it with supervisor
2. Configure LDAP Server details in /etc/cobbler/settings
3. Configure LDAP authentication in /etc/cobbler/modules.conf
4. Restart Cobbler
5. Try to authenticate in web interface

### Expected behavior

Authentication via LDAP should work as excepted.

### Version

````
Cobbler 3.1.1
  source: ?, ?
  build time: Tue Jan 14 05:07:09 2020
````

### Screenshots
```
2020-04-27T08:25:46 - INFO | Exception occured: <class 'ModuleNotFoundError'>
2020-04-27T08:25:46 - INFO | Exception value: No module named 'ldap'
2020-04-27T08:25:46 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 2245, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 2057, in login
    if self.__validate_user(login_user, login_password):

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1958, in __validate_user
    return self.api.authenticate(input_user, input_password)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 934, in authenticate
    rc = self.authn.authenticate(self, user, password)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/authentication/ldap.py", line 48, in authenticate
    import ldap
```

### Additional context

This is due to python3-ldap3 being the default dependency for ldap authentication. There is package called python3-ldap in AppStream for CentOS 8, when this is installed, LDAP authentication works. So this should be fixed by installing python3-ldap instead  of python3-ldap3.

**Comment by SchoolGuy** [comment]
We can't use a `Suggests` in the specfile because this is not always supported. I think we should instead document this because setting up Cobbler to use LDAP is not something which is done out of the box for you.

@dansou901 Would you agree or do you have a desired better solution in mind?

**Comment by dansou901** [comment]
That would help of course and should be enough. When we ever want to do an official docker image for cobbler (which we should do latest for 4.0.0 in my eyes), we should include the needed package there of course.

**Comment by SchoolGuy** [comment]
Fixed through: https://github.com/cobbler/cobbler/pull/2464
