### ISSUE TITLE
Invalid documentation link

### ISSUE THREAD

**Issue by emergy** [cobbler/cobbler#2341]
### To Reproduce

1. Go to https://cobbler.readthedocs.io/en/latest/cobbler-conf.html#modules-conf
2. Click on https://github.com/cobbler/cobbler/wiki/Dns-management link

### Version
current

**Comment by SchoolGuy** [comment]
Actually all of the Github Wiki Links are dead. *sigh*

Thanks for the reminder though! @emergy

**Comment by SchoolGuy** [comment]
I will complete https://github.com/cobbler/cobbler/pull/2202 and then do this
