### ISSUE TITLE
HTTPBoot not working on all non SUSE systems

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2343]
### Describe the bug

If you try to use HTTPBoot with Cobbler via our configured Apache configuration that will not work, as the directory for files is not under `/srv` but under another path.

### To Reproduce

1. Try to HTTPBoot a client
2. See that the Folder requested is not available on the webserver
### Expected behavior

I would like an out of the box experience for all clients.

### Version

Master

### Additional context

Related to #2295

**Comment by thiller2018** [comment]
what is not working? webroot is set in setup.py and apache_webconfigdir is set in cobbler.spec.
Are not all os versions covered there?

**Comment by SchoolGuy** [comment]
@thiller2018 In your PR (https://github.com/cobbler/cobbler/pull/2295/) there are hardcoded paths in the Apache2 config. This leads to above described errors.

**Comment by thiller2018** [comment]
#2347 added a variable

**Comment by SchoolGuy** [comment]
Fixed through https://github.com/cobbler/cobbler/pull/2347 and https://github.com/cobbler/cobbler/pull/2359
