### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by 4gemenot** [cobbler/cobbler#2345]
Hello Gents,

Good day.

I install the Cobbler application using the EPEL-8-Modular repo.

I'm getting SSL_ERROR_RX_RECORD_TOO_LONG error accessing the cobbler (https://192.168.9.9/cobbler_web

I clear the cache, reset the browser still having the same error issue.

Please any help.

Thanks,

OS : RHEL 8
Kernel version: 4.18.0-193.el8.x86_64

Cobbler version: 
[root@rhel8-test epel-testing-modular]# rpm -qi cobbler
Name        : cobbler
Version     : 3.1.1
Release     : 1.module_el8+8666+47d43720
Architecture: noarch
Install Date: Mon 18 May 2020 11:05:31 PM +03
Group       : Unspecified
Size        : 1981595
License     : GPLv2+
Signature   : RSA/SHA256, Thu 16 Apr 2020 05:05:01 AM +03, Key ID 21ea45ab2f86d6a1
Source RPM  : cobbler-3.1.1-1.module_el8+8666+47d43720.src.rpm
Build Date  : Thu 16 Apr 2020 01:59:22 AM +03
Build Host  : buildvm-25.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://cobbler.github.io/
Bug URL     : https://bugz.fedoraproject.org/cobbler
Summary     : Boot server configurator

Cobbler Web:
[root@rhel8-test epel-testing-modular]# rpm -qi cobbler-web
Name        : cobbler-web
Version     : 3.1.1
Release     : 1.module_el8+8666+47d43720
Architecture: noarch
Install Date: Mon 18 May 2020 11:05:31 PM +03
Group       : Unspecified
Size        : 1412869
License     : GPLv2+
Signature   : RSA/SHA256, Thu 16 Apr 2020 05:05:00 AM +03, Key ID 21ea45ab2f86d6a1
Source RPM  : cobbler-3.1.1-1.module_el8+8666+47d43720.src.rpm
Build Date  : Thu 16 Apr 2020 01:59:22 AM +03
Build Host  : buildvm-25.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://cobbler.github.io/
Bug URL     : https://bugz.fedoraproject.org/cobbler
Summary     : Web interface for Cobbler

**Comment by SchoolGuy** [comment]
Cobbler itself does not handle certificates in any way and is not even aware if an application is talking HTTP or HTTPS to it. So this is definitely a configuration problem.

Here a short stackoverflow post about that topic: https://stackoverflow.com/questions/119336/ssl-error-rx-record-too-long-and-apache-ssl

I could try to help you if you provide us with the webserver config you adjusted for Cobbler.

**Comment by 4gemenot** [comment]
Hi SchoolGuy,

no changes from the webserver config, all defaults. I'm attaching the configuration of the webserver and the cobbler.conf and cobbler_web.conf

Thanks,

[webserver-config.zip](https://github.com/cobbler/cobbler/files/4657677/webserver-config.zip)

**Comment by 4gemenot** [comment]
Hello SchoolGuy,

It resolved this error after replacing the line <VirtualHost *:443> to <VirtualHost mycobbler.test.com:443> from cobbler_web.conf file.

Thanks,

**Comment by SchoolGuy** [comment]
Since I just now saw that this is solved we will close this. If the problem persists, please reopen.
