### ISSUE TITLE
Do we want to depend on pymongo or not?

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#2350]
### Describe the bug

There is a broken attempt to remove the automatically generated dependency on pymongo in the spec file:

https://github.com/cobbler/cobbler/blob/master/cobbler.spec#L113
```
%global __requires_exclude_from ^%{python3_sitelib}/modules/serializer_mongodb.py*$
```
which doesn't work for a number of reasons - mainly because I think the automatic requires operates on the requires.txt file.

Now, the mongodb serializer at this point I'm pretty sure is just a historical artifact.  Do we even want to ship it?  If we do want to ship it and exclude the deps I think we either:
```
%global __requires_exclude pymongo
```
or in %install:
```
sed -i -e /pymongo/d %{buildroot}%{python3_sitelib}/cobbler*.egg-info/requires.txt
```
The latter might be safe depending on how things are imported via distutils (sometimes it complains about missing deps).

**Comment by SchoolGuy** [comment]
So we have the same problem with all serializers except the `file` one. I think either we need to repair them or indeed remove them. I think repairing would be the better call but that will require some effort.

**Comment by SchoolGuy** [comment]
So my vote would be to depend on them.

**Comment by opoplawski** [comment]
Works for me.
