### ISSUE TITLE
(http_)server resolved to IP when generating PXE profiles - why?

### ISSUE THREAD

**Issue by jmozd** [cobbler/cobbler#2356]
### Version

````paste below
````
Cobbler 2.9.0
  source: ?, ?
  build time: Mon Apr 20 12:00:00 2020

RPM identifies as
Name        : cobbler
Version     : 3.0.0+git20190806.32c4bae0
Release     : 7.7.3.19539.3.TEST.1169779

### Question

I have a multi-homed server running cobblerd and am trying to PXE-install SUSE-based systems. Installation takes place in a separate PXE network (no connectivity except for the cobblerd server), installed systems will be configured to access separate production networks during installation.
DNS resolution works for all networks: When looking up "pxeserver.company.com" during PXE installation, it will return the server's IP address in the PXE network. Resolving later from the "live" system, it will return the server's IP on the production network.

I can set "server" to i.e. "pxeserver.company.com", that would make almost every access work during PXE install and after (we're using the $server variable to i.e. define repository access inside the installation profiles) - except for access to the installation profile itself: Cobbler will convert any host name to an IP address when generating the according kernel command line for the PXE configuration file. See tftpgen.py:

```
        # automatic installation file path rewriting (get URLs for local files)
        if autoinstall_path is not None and autoinstall_path != "":

            # FIXME: need to make shorter rewrite rules for these URLs

            try:
                ipaddress = socket.gethostbyname_ex(blended["http_server"])[2][0]
            except socket.gaierror:
                ipaddress = blended["http_server"]
            URL_REGEX = "[a-zA-Z]*://.*"
            local_autoinstall_file = not re.match(URL_REGEX, autoinstall_path)
            if local_autoinstall_file:
                if system is not None:
                    autoinstall_path = "http://%s/cblr/svc/op/autoinstall/system/%s" % (ipaddress, system.name)
                else:
                    autoinstall_path = "http://%s/cblr/svc/op/autoinstall/profile/%s" % (ipaddress, profile.name)
```

But because this happens on the cobbler server (and not on the installed client system), DNS can return a wrong IP address (production network) and loading the autoinstallation profile fails during PXE boot, because that IP address is not reachable from the PXE installation network.

Why was it important to use the IP address here? And if the reasoning still holds, is there a way to replace http_server per system (to cater for different installation environments)? I've not found a way to do so.

**Comment by SchoolGuy** [comment]
I am really intrigued by that 2.9.0 thingy. It was never used upstream. Anyway...

The decision was made before my time but I guess that the reasoning then was that not at all times DNS may be available whilst IP addresses should work as long as network is there. Although you explained your question very good and in extensive length I sadly can't return the favor and give you a more extensive answer then this. I will try to have a look as soon as I have some free time.

**Comment by jmozd** [comment]
Meanwhile I had a look at where "http_server" is set... it's in utils.py:blender():
```
    http_port = results.get("http_port", 80)
    if http_port not in (80, "80"):
        results["http_server"] = "%s:%s" % (results["server"], http_port)
    else:
        results["http_server"] = results["server"]
As it is unconditionally, it is *always* set this way, with no chance of overriding it - at least that's how I read the code. So it seems we cannot override this value by settings files.
```

The origin of this IP address thingy seems to be https://github.com/cobbler/cobbler/commit/588756aa7aefc122310847d007becf3112647944 where (according to the comment) it was introduced to limit the string length for s390 - the DNS name was longer than the IP address. If that remains the only reason for using the IP address, I'd like to prepare a pull request to revert this behavior (but if possible, keep it for systems running on s390 - once I've found out to to properly determine this per system/profile). Or maybe we could skip this fully, as s390 admins might just set the "server" variable to an IP...

**Comment by SchoolGuy** [comment]
@jmozd I think reverting this and leaving whatever variable was set is a good change. If we want to ensure that s390 will always work we could look up what the maximum length is now and create a check for the length and throw an error at the user if it is to long. If we want to be superb we could add a config switch which enabled converting it to an IP address or not.

**Comment by jmozd** [comment]
Done... https://github.com/cobbler/cobbler/pull/2357
I have no idea what S/390 allows for, so I simply made the name2ip-conversion depend on a new config switch, default "0".
The changes were backported to my current cobblerd and tested there.
