### ISSUE TITLE
[Errno 2] No such file or directory while writing system config

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#2362]
### Describe the bug

This happens when changing a distribution with SUSE Manager while Cobbler is writing the system config. The config was existing before, so it should get overwritten.

Permissions look like this: 

```
-rw-r--r-- 1 root root 445 Jun 24 16:13 /srv/tftpboot/grub/system/3d:be:25:b0:64:fd
```

When deleting all files I can see that the file actually gets created correctly, but the error gets thrown nevertheless.

```
Wed Jun 24 16:13:11 2020 - INFO | Exception value: [Errno 2] No such file or directory: '/srv/tftpboot/grub/system/3d:be:25:b0:64:fd'
Wed Jun 24 16:13:11 2020 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 2241, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1063, in save_distro
    return self.save_item("distro", object_id, token, editmode=editmode)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1059, in save_item
    self.api.add_item(what, obj, logger=self.logger)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 437, in add_item
    self.get_items(what).add(ref, check_for_duplicate_names=check_for_duplicate_names, save=save, logger=logger)

  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/collection.py", line 358, in add
    self.lite_sync.add_single_distro(ref.name)

  File "/usr/lib/python3.6/site-packages/cobbler/actions/litesync.py", line 87, in add_single_distro
    self.add_single_profile(k.name, rebuild_menu=False)

  File "/usr/lib/python3.6/site-packages/cobbler/actions/litesync.py", line 128, in add_single_profile
    self.add_single_system(k.name)

  File "/usr/lib/python3.6/site-packages/cobbler/actions/litesync.py", line 155, in add_single_system
    self.tftpd.add_single_system(system)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/in_tftpd.py", line 131, in add_single_system
    self.tftpgen.write_all_system_files(system, menu_items)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 198, in write_all_system_files
    self.write_pxe_file(grub_path, system, profile, distro, working_arch, format="grub")

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 494, in write_pxe_file
    fd = open(filename, "w")
```

### To Reproduce

1. Use SUSE Manager
2. Import Centos
3. Create distro, profiles (I had 100) and systems (also 100)
4. Change distribution in SUSE Manager and wait for error to happen.

### Expected behavior

There should not be an error, since file should be writable.

### Version

````
3.0.0+git20190806.32c4bae0-401.15.18.develHead
````

This is the Cobbler version in SUMA head.

**Comment by SchoolGuy** [comment]
I was with Jochen when this happend. So I can confirm that this is happening.

**Comment by brejoc** [comment]
When slowing Cobbler down a little bit with…
```
            with open(filename, "w") as fd:
                sleep(0.2)
                fd.write(buffer)
```
… it's working. :frowning_face: 
I guess it would also work without the `with`. I was just testing a little bit.

**Comment by SchoolGuy** [comment]
I suspect that Python itself is the problem here: https://docs.python.org/3/library/io.html#reentrancy

I think that since `open()` gives us a buffered object possibly that buffer is invalidated during using it and thus then raising for whatever reason a FileNotFound error. That 0.2 seconds possibly are enough to empty that buffer.

**Comment by brejoc** [comment]
Not sure about that. We are not doing async or threaded stuff here. Also it's not the Runtime error that is described in the docs. But my feeling would also say that it hast to be something in that direction.

**Comment by brejoc** [comment]
A better (and tested) workaround would look like this. But I don't really like it either.

```python
            try:
                with open(filename, "w") as fd:
                    fd.write(buffer)
            except FileNotFoundError as e:
                self.logger.error("Got \"{}\" while trying to write {}".format(e, filename))
                self.logger.error("Trying to write {} again after some delay.".format(filename))
                sleep(1)
                with open(filename, "w") as fd:
                    fd.write(buffer)
```

**Comment by watologo1** [comment]
Ouch..., as a quick workaround for a customer this might be worth it...
Let me have a closer look at this. 
At quick look I found:
cobbler/actions/litesync.py
last line (224):
utils.rmfile(os.path.join(bootloc, "grub", filename.upper()))
The .upper looks wrong.

Concurrancy can happen if (maybe more cases):
cobbler/modules/managers/in_tftpd.py
--netboot-enabled is set 
-- A system is added
-- a sync is happening

But I need more time to look at this.
@brejoc I wonder how difficult it is to reproduce this. And if it's easy to reproduce, how easy it is to set up the test environment for easy reproducing. Maybe I can log on a machine that exposes the issue. Best ping me privately.

**Comment by SchoolGuy** [comment]
@watologo1 It is reproduced in @brejoc 's environment multiple times. What you have to do is:

1. setup a SUMA and 
2. then in the UI create a distro and 
3. a profile for a distro of choice and 
4. then use a testscript to add a lot of fake profiles and systems which are linked to this single distro.
5. Afterwards update in the SUMA UI the distro and
6. see the error happening in the `cobbler.log`.

Note: No sync required the litesync which is triggered automatically is sufficient.
