### ISSUE TITLE
How to use cobbler3.1.2 on centos7?

### ISSUE THREAD

**Issue by wanghaiqing2015** [cobbler/cobbler#2368]
How to use cobbler3.1.2 on centos7?

**Comment by SchoolGuy** [comment]
I guess this is your best guess: https://cobbler.readthedocs.io/en/latest/installation-guide.html

**Comment by WVenus** [comment]
I also want to know how to install, the documentation is a little difficult to understand. If you use cobbler3.0 on centos7, can you share notes with me? Thank you

**Comment by opoplawski** [comment]
You could try my build here: https://copr.fedorainfracloud.org/coprs/orion/cobbler/

**Comment by SchoolGuy** [comment]
@WVenus What parts are hard for you to understand? This is one of the most important documents and it shouldn't be hard to understand in an optimal world.

**Comment by WVenus** [comment]
> @WVenus What parts are hard for you to understand? This is one of the most important documents and it shouldn't be hard to understand in an optimal world.

If there is a command line example, for me, a group who is not familiar with python, get better help. I always get the wrong dependency, which makes the installation more difficult.

**Comment by SchoolGuy** [comment]
Okay I think I can work on that.

**Comment by WVenus** [comment]
> You could try my build here: https://copr.fedorainfracloud.org/coprs/orion/cobbler/
--> 正在处理依赖关系 python36-mod_wsgi，它被软件包 cobbler-3.1.2-1.el7.noarch 需要
---> 软件包 libtommath.x86_64.0.0.42.0-6.el7 将被 安装
--> 解决依赖关系完成
错误：软件包：cobbler-3.1.2-1.el7.noarch (copr:copr.fedorainfracloud.org:orion:cobbler)
          需要：python36-mod_wsgi
 您可以尝试添加 --skip-broken 选项来解决该问题
 您可以尝试执行：rpm -Va --nofiles --nodigest
[root@192 yum.repos.d]# pip3.6 install python36-mod_wsgi -i https://mirrors.aliyun.com/pypi/simple      
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Collecting python36-mod_wsgi
  Could not find a version that satisfies the requirement python36-mod_wsgi (from versions: )
No matching distribution found for python36-mod_wsgi
[root@192 yum.repos.d]# yum -y install python36-mod_wsgi
已加载插件：fastestmirror
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirrors.njupt.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
没有可用软件包 python36-mod_wsgi。
错误：无须任何处理
[root@192 yum.repos.d]# pip3.6 install mod_wsgi -i https://mirrors.aliyun.com/pypi/simple         
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Requirement already satisfied: mod_wsgi in /usr/local/lib64/python3.6/site-packages

**Comment by WVenus** [comment]
> You could try my build here: https://copr.fedorainfracloud.org/coprs/orion/cobbler/
[root@192 yum.repos.d]# pip3.6 install mod_wsgi -i https://mirrors.aliyun.com/pypi/simple         
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Requirement already satisfied: mod_wsgi in /usr/local/lib64/python3.6/site-packages



--> 解决依赖关系完成
错误：软件包：cobbler-3.1.2-1.el7.noarch (copr:copr.fedorainfracloud.org:orion:cobbler)
          需要：python36-mod_wsgi
 您可以尝试添加 --skip-broken 选项来解决该问题
 您可以尝试执行：rpm -Va --nofiles --nodigest
[root@192 yum.repos.d]# pip3.6 install python36-mod_wsgi -i https://mirrors.aliyun.com/pypi/simple      
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Collecting python36-mod_wsgi
  Could not find a version that satisfies the requirement python36-mod_wsgi (from versions: )
No matching distribution found for python36-mod_wsgi
[root@192 yum.repos.d]# yum -y install python36-mod_wsgi
已加载插件：fastestmirror
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirrors.njupt.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
没有可用软件包 python36-mod_wsgi。
错误：无须任何处理

**Comment by WVenus** [comment]
> You could try my build here: https://copr.fedorainfracloud.org/coprs/orion/cobbler/

I used your rpm repository, there was an error that python36-mod_wsgi was missing, and I used pip3.6 install mod_wsgi to have no effect after successful installation

**Comment by wanghaiqing2015** [comment]
yum install -y https://repo.ius.io/ius-release-el7.rpm
yum makecache fast
yum install python36-mod_wsgi -y

**Comment by WVenus** [comment]
> yum install -y https://repo.ius.io/ius-release-el7.rpm
> yum makecache fast
> yum install python36-mod_wsgi -y

Sorry, I tried downloading and it didn't work

**Comment by opoplawski** [comment]
We can't read your mind.  What didn't work?  If I were to guess it's that you haven't configured the ssl cert in /etc/httpd/conf.d/cobbler_web.conf.

**Comment by wanghaiqing2015** [comment]
You can manual download ius-release-el7.rpm.

Then you can run "rpm -ivh ius-release-el7.rpm"
