### ISSUE TITLE
[HELP WANTED]: Cobbler Community

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2369]
This is a follow up to this original issue: #1892

Cobbler is currently from the point of code mainly maintained by me. This means that I, as an apprentice with no real hardware to test this software and very limited time, am fixing most of the bugs, building the website, making announcements, taking care of basic packaging problems and support of course. This is currently somehow possible.

If we are looking where Cobbler is currently as a project I would say I am very happy about what I have achieved and I am forever grateful to all those who have helped me in building the knowledge to do all this, as well as of course those few how are contributing from time to time.

However Cobbler will most likely have the problem that with the current situation it is unlikely that we get new features and most bugs will stay. The plans for the future and the roadmap is there. The time for developing all this is just not there as a single person. I would expect that for a project of this size we would at least need a whole person dedicated on revising all the documentation and checking that all of this is still valid and there are no bigger problems with it. This is just an example, there is of course more needed on just a person reading and correcting/improving docs.

I would consider myself very lucky if we could build together a community which is more active in contributing to the code and thus getting new Features which are brought to you from the Community. Also we could fix more bugs and make Cobbler more enjoyable because there are less problems with it.

If we won't find anyone on the long term which is willing to help in contributing actively to the code, Cobbler will die. I can try to keep it living as long as possible but not forever. I will try to reach out to some mailing lists in the distros where this is packaged to get some feedback how and where Cobbler is still used today.

**Comment by opoplawski** [comment]
@SchoolGuy Thank you for all your work keeping cobbler going, it is greatly appreciated.  cobbler is a central piece of infrastructure at my work - we provision all of our hosts in it, source of DNS/DHCP/802.1X, and ansible inventory.  I also package it for Fedora/EPEL.  As such I will attempt to keep it going as much as possible as well.  That said, like so many people I am stretched thin on multiple projects and at work so I have very little time to dedicate to cobbler.  I will attempt to fix bugs and add enhancements that affect me, but I cannot do more at this time.

**Comment by gpezza2** [comment]
As I am currently working on a fresh installation of cobbler 3.1 from a current installation of 2.8, I am happy to share documentation updates for installing/building cobbler since I am doing that now, and have noticed some issues with it that I have fixed. I just need some guidance on the best way to get that to the project.

**Comment by SchoolGuy** [comment]
@gpezza2 We have a docs folder in this repo. In this folder you can document all standard tasks. The files and captions should be self-explanatory. The code itself is documented in the python files itself and also in rst. If you want to create a longer guide which takes you from zero to datacenter or does describe something which is consistent of multiple steps, I would very much appreciate if we could publish that on our website on cobbler.github.io (which is in a separate repo with markdown).

**Comment by lazzurs** [comment]
I have just had a look at the project after a very long time and glad to see it is still being maintained. I would love to help squish a bunch of the issues and tidy things up. I will submit some small pull requests shortly and I am hoping to help with the Terraform provider too and move it to the Terraform Registry.

**Comment by bowlerct** [comment]
I don't have a lot of time but would like to help with cobbler and more on the UI side. I am familiar with several frontends (php, bootstrap, Ext-JS, jsp) but not angular so I need to read some docs and tutorials on it. I'm looking forward to contributing and keeping the project going.

**Comment by tpw56j** [comment]
I have some time and I could try to solve some of the issues that you think you can assign me.
In addition, I have some experience in using Cobbler for installing Windows, which I have outlined in https://habr.com/ru/post/263883 in Russian. If you find this interesting, then I could translate it into English for the Cobbler community.

**Comment by SchoolGuy** [comment]
@tpw56j We have an open feature request for that. So if you could translate that into English, it would be marvelous! I would love to post that on our blog!

**Comment by tpw56j** [comment]
I am ready to provide this translation into English. The implementation of the Windows installation feature described in the post has many disadvantages. I did it more than 5 years ago and now I would do a lot differently, but it still works for me. I would be very grateful if someone could help make English text in the post more correct. How can I share this post for discussion?

**Comment by SchoolGuy** [comment]
@tpw56j Just open a WIP PR for the website. Did you ever work with Jekyll?

**Comment by dansou901** [comment]
@tpw56j when you're done just ping me in the pull request for grammar / spelling, I can help you with that

**Comment by tpw56j** [comment]
> @dansou901 Thanks! I need one or two more days to complete.

**Comment by dansou901** [comment]
@tpw56j we also want to use cobbler for Windows installations in the future so your implementation would help us to get started, maybe together we'll find other ways of solving this.

**Comment by tpw56j** [comment]
@dansou901 I am very glad that there is interest in this topic and there is someone with whom to discuss these problems. Now I will create a WIP PR and post the trigger code, and I will describe how it works a little later.

**Comment by tpw56j** [comment]
WIP: Trigger to generate Windows boot files #2466

**Comment by dansou901** [comment]
I can't help you with reviewing that PR as I am not a developer and can't speak python, some of the other ones should be able to help you with that. But as soon as you do your PR against the website with the blog post, I'll review that.

**Comment by tpw56j** [comment]
@dansou901 How to create a PR against the website?

**Comment by dansou901** [comment]
You can find in the repo https://github.com/cobbler/cobbler.github.io. It's written in jekyll, which is mostly markdown code, you'll just have to figure out where to add the blog post.

**Comment by dansou901** [comment]
Just add *.md file to the _posts directory, that should be all if I'm not mistaken. You can see the file name syntax in the other posts.

**Comment by SchoolGuy** [comment]
@tpw56j If you need more help we could have a session in Jitsi to do it together. I would really love if we get this into our website!

**Comment by tpw56j** [comment]
I posted a description of working with a trigger as commit in #2466 cobbler/docs/user-guide/windows.rst. I'll try to figure out how to transfer this to a website.

**Comment by SchoolGuy** [comment]
@tpw56j Don't bother. It is worthy of being in the official docs. I will write an annoucement post for you.

**Comment by tpw56j** [comment]
@SchoolGuy It seems to me that official Windows support in Cobbler should be done somewhat differently. But this may require a lot of changes to the Cobbler code. Hacking Microsoft binaries in pxeboot.n12 and bootmgr.exe looks very doubtful (how legal is it?). Though wimboot from iPXE does similar things. I dont know..

**Comment by SchoolGuy** [comment]
@tpw56j I will review carefully and ask a legal guy from my company. It may be that we need to package this extra, as it requires additional dependencies etc. In any way I want your work as part of Cobbler because this is a huge step for us!

**Comment by tpw56j** [comment]
@dansou901 Thanks for the tips on https://github.com/cobbler/cobbler.github.io. I forked and cloned the repo. For a blog, what I wrote at https://github.com/tpw56j/cobbler/blob/master/docs/user-guide/windows.rst doesn't quite fit. There is too much code and little explanation. I'll add some clarification and now I'm looking for a way to hide large sections of code in links so that those who are interested can see them.

**Comment by tpw56j** [comment]
Draft blog post in https://github.com/cobbler/cobbler.github.io WIP PR: Trigger to generate Windows boot files. The formatting is broken, I'll fix it later.

**Comment by dansou901** [comment]
@tpw56j thanks a lot for your work. If I don't get to review it today, I'll certainly do so tomorrow.

**Comment by asimat** [comment]
Happy to do testing and write some documentation / guides. I never digged deep in to cobbler's inner working before, but as I am trying to migrate to v3.2 so have learned a lot due to loads of bugs being present.

I work in windows + linux (CentOS) environment, where DHCP server is Windows 2016/2019 server, and cobbler machine runs PXE deployment and puppet. Can do some testing and write guides to help.

**Comment by SchoolGuy** [comment]
@asimat Greatly appreciated! Feel free to open PRs and Issues for problems you encounter. If you have any questions you may find us on [Gitter](https://gitter.im/cobbler/community) (which can be used via your GH Account or bridged via Matrix).

**Comment by javier-angulo** [comment]
@SchoolGuy thank you for your efforts, very much appreciated. At my company we are happily using cobbler to deploy ESXi and CentOS across 4 datacenter (recently updated from 2.6 to 3.2) . Sadly I am not a python dev and I am involved in other projects, but will try to contribute with minor fixes and testing.

**Comment by SchoolGuy** [comment]
@javier-angulo If you provide good Bug Reports and share guides or write Blog Posts that would also contribute to Cobbler in a awesome way! Everything you can offer I will gladly take!

**Comment by SchoolGuy** [comment]
So an update on this as of now:

- For openSUSE we have stable packaging
- For Redhat based distros we have stable packaging
- Debian and Debian based systems are still missing (upstream), since we don't provide native packaging for them - DEBs are available still through `debbuild`
- We are working on a new Web Interface and other tech-debt is identified and will be worked on.
- Contributions from the outside are beginning to be increased slowly
- Documentation is getting better but is not good so that Cobbler could be considered "easily manageable" when used with the full funcitonallity
- Roadmap is being addressed and progressed
- If everything goes well, I will have a job after my apprenticeship which will allow me to continue working on Cobbler

So although the situation is not fully solved due to people with deep codebase knowledge, the help of @nodeg is and was tremendous! Thus I will close this issue since we are at a much better place now then when I opened this back in July 2020.
