### ISSUE TITLE
There was an error importing ubuntu

### ISSUE THREAD

**Issue by WVenus** [cobbler/cobbler#2370]
```
[root@192 ~]# cobbler import --name=ubuntu-18.04-server --breed=ubuntu --os-version=bionic --path=/mnt  
task started: 2020-07-03_145451_import
task started (id=Media import, time=Fri Jul  3 14:54:51 2020)
Found a candidate signature: breed=ubuntu, version=bionic
running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu-18.04-server/dists/bionic/Release
received on stdout: /var/www/cobbler/ks_mirror/ubuntu-18.04-server/dists/bionic/Release: ASCII text

received on stderr: 
Found a matching signature: breed=ubuntu, version=bionic
Adding distros from path /var/www/cobbler/ks_mirror/ubuntu-18.04-server:
No distros imported, bailing out
!!! TASK FAILED !!!
```

**Comment by brejoc** [comment]
Am Fr., 3. Juli 2020 um 08:57 Uhr schrieb ermao <notifications@github.com>:
>
> [root@192 ~]# cobbler import --name=ubuntu-18.04-server --breed=ubuntu --os-version=bionic --path=/mnt
> task started: 2020-07-03_145451_import
> task started (id=Media import, time=Fri Jul 3 14:54:51 2020)
> Found a candidate signature: breed=ubuntu, version=bionic
> running: /usr/bin/file /var/www/cobbler/ks_mirror/ubuntu-18.04-server/dists/bionic/Release
> received on stdout: /var/www/cobbler/ks_mirror/ubuntu-18.04-server/dists/bionic/Release: ASCII text
>
> received on stderr:
> Found a matching signature: breed=ubuntu, version=bionic
> Adding distros from path /var/www/cobbler/ks_mirror/ubuntu-18.04-server:
> No distros imported, bailing out
> !!! TASK FAILED !!!

Which ISO are you using? The standard server ISO or some netinstall?

Could you please check if the regexes for initrd and kernel are still
valid? https://github.com/cobbler/cobbler/blob/master/config/cobbler/distro_signatures.json#L1224-L1225
You should be able to grep for this in /mnt.

**Comment by WVenus** [comment]
> 您正在使用哪个ISO？标准服务器ISO或一些netinstall？您能否检查initrd和kernel的正则表达式是否仍然有效？https://github.com/cobbler/cobbler/blob/master/config/cobbler/distro_signatures.json#L1224-L1225 您应该可以在/ mnt中对此进行grep。

I am using ubuntu-18.04.4-live-server-amd64.iso.

**Comment by SchoolGuy** [comment]
@WVenus I guess that is the problem. It should work but so far only the full ISOs are expected to work.
