### ISSUE TITLE
start dhcpd service failed

### ISSUE THREAD

**Issue by wanghaiqing2015** [cobbler/cobbler#2371]
```
systemctl start dhcpd 

journalctl -xe

Jul 04 14:40:06 vm100 dhcpd[1736]: Internet Systems Consortium DHCP Server 4.2.5
Jul 04 14:40:06 vm100 dhcpd[1736]: Copyright 2004-2013 Internet Systems Consortium.
Jul 04 14:40:06 vm100 dhcpd[1736]: All rights reserved.
Jul 04 14:40:06 vm100 dhcpd[1736]: For info, please visit https://www.isc.org/software/dhcp/
Jul 04 14:40:06 vm100 dhcpd[1736]: Not searching LDAP since ldap-server, ldap-port and ldap-base-dn were not specified in the config file
Jul 04 14:40:06 vm100 dhcpd[1736]: Wrote 0 leases to leases file.
Jul 04 14:40:06 vm100 dhcpd[1736]: 
Jul 04 14:40:06 vm100 dhcpd[1736]: No subnet declaration for ens33 (192.168.10.100).
Jul 04 14:40:06 vm100 dhcpd[1736]: ** Ignoring requests on ens33.  If this is not what
Jul 04 14:40:06 vm100 dhcpd[1736]:    you want, please write a subnet declaration
Jul 04 14:40:06 vm100 dhcpd[1736]:    in your dhcpd.conf file for the network segment
Jul 04 14:40:06 vm100 dhcpd[1736]:    to which interface ens33 is attached. **
Jul 04 14:40:06 vm100 dhcpd[1736]: 
Jul 04 14:40:06 vm100 dhcpd[1736]: 
Jul 04 14:40:06 vm100 dhcpd[1736]: Not configured to listen on any interfaces!
Jul 04 14:40:06 vm100 dhcpd[1736]: 
Jul 04 14:40:06 vm100 dhcpd[1736]: This version of ISC DHCP is based on the release available
Jul 04 14:40:06 vm100 dhcpd[1736]: on ftp.isc.org.  Features have been added and other changes
Jul 04 14:40:06 vm100 dhcpd[1736]: have been made to the base software release in order to make
Jul 04 14:40:06 vm100 dhcpd[1736]: it work better with this distribution.
Jul 04 14:40:06 vm100 dhcpd[1736]: 
Jul 04 14:40:06 vm100 dhcpd[1736]: Please report for this software via the CentOS Bugs Database:
Jul 04 14:40:06 vm100 dhcpd[1736]:     http://bugs.centos.org/
Jul 04 14:40:06 vm100 dhcpd[1736]: 
Jul 04 14:40:06 vm100 dhcpd[1736]: exiting.
Jul 04 14:40:06 vm100 systemd[1]: dhcpd.service: main process exited, code=exited, status=1/FAILURE
Jul 04 14:40:06 vm100 systemd[1]: Failed to start DHCPv4 Server Daemon.
-- Subject: Unit dhcpd.service has failed
```

```
[root@vm100 ~]# cat /etc/cobbler/dhcp.template 
#import netaddr

ddns-update-style interim;

allow booting;
allow bootp;

ignore client-updates;
set vendorclass = option vendor-class-identifier;

option system-arch code 93 = unsigned integer 16;

subnet 192.168.10.0 netmask 255.255.255.0 {
     option routers             192.168.10.2;
     option domain-name-servers 114.114.114.114;
     option subnet-mask         255.255.255.0;
     range dynamic-bootp        192.168.10.100 192.168.10.254;
     default-lease-time         21600;
     max-lease-time             43200;
     next-server                $next_server;
     class "pxeclients" {
          match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";

          # Legacy
          if option system-arch = 00:00 {
              filename "grub/grub.0";
          }
          # UEFI-32-1
          if option system-arch = 00:06 {
               # Not supported, no 32 bit UEFI grub executable
              filename "unsupported";
          }
          # UEFI-32-2
          if option system-arch = 00:02 {
              # Not supported, no 32 bit UEFI grub executable
              filename "unsupported";
          }
          # UEFI-64-1
          else if option system-arch = 00:07 {
              filename "grub/grubx64.efi";
          }
          # UEFI-64-2
          else if option system-arch = 00:08 {
              filename "grub/grubx64.efi";
          }
          # UEFI-64-3
          else if option system-arch = 00:09 {
              filename "grub/grubx64.efi";
          }
          # armv7   (aka arm 32 bit)
          else if option system-arch = 00:0a {
              filename "grub/armv7.efi";
          }
          # aarch64 (aka arm 64 bit)
          else if option system-arch = 00:0b {
              filename "grub/grubaa64.efi";
          }
          # RiskV 32 bit
          else if option system-arch = 00:25 {
              #ToDo petitboot loader
              filename "unsupported";
          }
          #RiskV 32 bit
          else if option system-arch = 00:27 {
              #ToDo petitboot loader
              filename "unsupported";
          }
          else if option system-arch = 00:0e {
              filename "grub/grub.ppc64le";
          }
          else
          {
              filename "grub/grub.0";
          }
     }
}

#for dhcp_tag in $dhcp_tags.keys():
    ## group could be subnet if your dhcp tags line up with your subnets
    ## or really any valid dhcpd.conf construct ... if you only use the
    ## default dhcp tag in cobbler, the group block can be deleted for a
    ## flat configuration
    # group for Cobbler DHCP tag: $dhcp_tag
    group {
        #for mac in $dhcp_tags[$dhcp_tag].keys():
            #set iface = $dhcp_tags[$dhcp_tag][$mac]
            #set mac_dhcp_format = netaddr.EUI($mac,dialect=netaddr.mac_unix)
            host $iface.name {
                #if $iface.interface_type == "infiniband":
                    option dhcp-client-identifier = $mac;
                #else
                    hardware ethernet $mac_dhcp_format;
                #end if
            #if $iface.ip_address:
                fixed-address $iface.ip_address;
            #end if
            #if $iface.dns_name:
               option host-name "$iface.dns_name";
            #else if $iface.hostname:
                option host-name "$iface.hostname";
            #end if
            #if $iface.netmask:
                option subnet-mask $iface.netmask;
            #end if
            #if $iface.if_gateway:
                option routers $iface.if_gateway;
            #else if $iface.gateway:
                option routers $iface.gateway;
            #end if
            #if "filename" in $iface.keys() and $iface.filename:
                #if $iface.enable_gpxe:
                    if exists user-class and option user-class = "gPXE" {
                        filename "http://$cobbler_server/cblr/svc/op/gpxe/system/$iface.owner";
                    } else if exists user-class and option user-class = "iPXE" {
                        filename "http://$cobbler_server/cblr/svc/op/gpxe/system/$iface.owner";
                    } else {
                        filename "undionly.kpxe";
                    }
                #else
                    filename "$iface.filename";
                #end if
            #end if
            #if $iface.next_server:
                next-server $iface.next_server;
            #end if
            #if $iface.filename:
                filename $filename
            #end if
            #if $iface.name_servers:
                #set $mynameservers = ','.join($iface.name_servers)
                option domain-name-servers 114.114.114.114;
            #end if
        }
    #end for
}
#end for
```

**Comment by wanghaiqing2015** [comment]
[root@vm100 ~]# rpm -qa|grep dhcp
dhcp-libs-4.2.5-79.el7.centos.x86_64
dhcp-4.2.5-79.el7.centos.x86_64
dhcp-common-4.2.5-79.el7.centos.x86_64
 
[root@vm100 ~]# rpm -qa|grep cobbler
cobbler-web-3.1.2-1.el7.noarch
cobbler-3.1.2-1.el7.noarch

**Comment by wanghaiqing2015** [comment]
how to resove this problem？

**Comment by SchoolGuy** [comment]
So far from my phone I see two problems.

1. One subnet is missing
2. You didn't specify on what your dhcp server should bind.

I guess both problems can be fixed through the template but I need to have a look from my home computer.

**Comment by wanghaiqing2015** [comment]
1、There is a subnet：
subnet 192.168.10.0 netmask 255.255.255.0 {
}

2、Only one netword interface：ens33

3、vmware nat mode：
     （1）closed dhcp

**Comment by wanghaiqing2015** [comment]
`# ******************************************************************
# Cobbler managed dhcpd.conf file
#
# generated from cobbler dhcp.conf template ($date)
# Do NOT make changes to /etc/dhcpd.conf. Instead, make your changes
# in /etc/cobbler/dhcp.template, as /etc/dhcpd.conf will be
# overwritten.
#
# ******************************************************************

#import netaddr

ddns-update-style interim;

allow booting;
allow bootp;

ignore client-updates;
set vendorclass = option vendor-class-identifier;

option system-arch code 93 = unsigned integer 16;

subnet 192.168.10.0 netmask 255.255.255.0 {
     option routers             192.168.10.2;
     option domain-name-servers 114.114.114.114;
     option subnet-mask         255.255.255.0;
     range dynamic-bootp        192.168.10.100 192.168.10.254;
     default-lease-time         21600;
     max-lease-time             43200;
     next-server                $next_server;
     class "pxeclients" {
          match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";

          # Legacy
          if option system-arch = 00:00 {
              filename "grub/grub.0";
          }
          # UEFI-32-1
          if option system-arch = 00:06 {
               # Not supported, no 32 bit UEFI grub executable
              filename "unsupported";
          }
          # UEFI-32-2
          if option system-arch = 00:02 {
              # Not supported, no 32 bit UEFI grub executable
              filename "unsupported";
          }
          # UEFI-64-1
          else if option system-arch = 00:07 {
              filename "grub/grubx64.efi";
          }
          # UEFI-64-2
          else if option system-arch = 00:08 {
              filename "grub/grubx64.efi";
          }
          # UEFI-64-3
          else if option system-arch = 00:09 {
              filename "grub/grubx64.efi";
          }
          # armv7   (aka arm 32 bit)
          else if option system-arch = 00:0a {
              filename "grub/armv7.efi";
          }
          # aarch64 (aka arm 64 bit)
          else if option system-arch = 00:0b {
              filename "grub/grubaa64.efi";
          }
          # RiskV 32 bit
          else if option system-arch = 00:25 {
              #ToDo petitboot loader
              filename "unsupported";
          }
          #RiskV 32 bit
          else if option system-arch = 00:27 {
              #ToDo petitboot loader
              filename "unsupported";
          }
          else if option system-arch = 00:0e {
              filename "grub/grub.ppc64le";
          }
          else
          {
              filename "grub/grub.0";
          }
     }
}

#for dhcp_tag in $dhcp_tags.keys():
    ## group could be subnet if your dhcp tags line up with your subnets
    ## or really any valid dhcpd.conf construct ... if you only use the
    ## default dhcp tag in cobbler, the group block can be deleted for a
    ## flat configuration
    # group for Cobbler DHCP tag: $dhcp_tag
    group {
        #for mac in $dhcp_tags[$dhcp_tag].keys():
            #set iface = $dhcp_tags[$dhcp_tag][$mac]
            #set mac_dhcp_format = netaddr.EUI($mac,dialect=netaddr.mac_unix)
            host $iface.name {
                #if $iface.interface_type == "infiniband":
                    option dhcp-client-identifier = $mac;
                #else
                    hardware ethernet $mac_dhcp_format;
                #end if
            #if $iface.ip_address:
                fixed-address $iface.ip_address;
            #end if
            #if $iface.dns_name:
               option host-name "$iface.dns_name";
            #else if $iface.hostname:
                option host-name "$iface.hostname";
            #end if
            #if $iface.netmask:
                option subnet-mask $iface.netmask;
            #end if
            #if $iface.if_gateway:
                option routers $iface.if_gateway;
            #else if $iface.gateway:
                option routers $iface.gateway;
            #end if
            #if "filename" in $iface.keys() and $iface.filename:
                #if $iface.enable_gpxe:
                    if exists user-class and option user-class = "gPXE" {
                        filename "http://$cobbler_server/cblr/svc/op/gpxe/system/$iface.owner";
                    } else if exists user-class and option user-class = "iPXE" {
                        filename "http://$cobbler_server/cblr/svc/op/gpxe/system/$iface.owner";
                    } else {
                        filename "undionly.kpxe";
                    }
                #else
                    filename "$iface.filename";
                #end if
            #end if
            #if $iface.next_server:
                next-server $iface.next_server;
            #end if
            #if $iface.filename:
                filename $filename
            #end if
            #if $iface.name_servers:
                #set $mynameservers = ','.join($iface.name_servers)
                option domain-name-servers 114.114.114.114;
            #end if
        }
    #end for
}
#end for

`

**Comment by wanghaiqing2015** [comment]
`
1111111
`

**Comment by wanghaiqing2015** [comment]
no /etc/dhcp/dhcpd.conf auto generate ? 

but, version 2.8.4 can auto generate it .

**Comment by wanghaiqing2015** [comment]
now, we can run dhcpd and cobblerd services.

but ,run "cobbler check" will report the below error:

[root@vm100 ~]# cobbler check
httpd does not appear to be running and proxying Cobbler, or SELinux is in the way. Original traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 399, in check_setup
    s.ping()
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for 192.168.10.100:8000/cobbler_api: 404 Not Found>
Traceback (most recent call last):
  File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 854, in main
    rc = cli.run(sys.argv)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 420, in run
    self.token = self.remote.login("", self.shared_secret)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for 192.168.10.100:8000/cobbler_api: 404 Not Found>

**Comment by wanghaiqing2015** [comment]
can open the web site.

http://192.168.10.100:8000/

**Comment by wanghaiqing2015** [comment]
[root@vm100 conf.d]# netstat -natp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      874/sshd            
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      972/master          
tcp        0      0 127.0.0.1:25151         0.0.0.0:*               LISTEN      12205/python3       
tcp        0      0 0.0.0.0:873             0.0.0.0:*               LISTEN      1700/rsync          
tcp        0     52 192.168.10.100:22       192.168.10.1:12245      ESTABLISHED 12213/sshd: root@pt 
tcp        0      0 192.168.10.100:22       192.168.10.1:12203      ESTABLISHED 12112/sshd: root@pt 
tcp        0      0 192.168.10.100:42796    58.49.194.241:80        TIME_WAIT   -                   
tcp        0      0 192.168.10.100:22       192.168.10.1:12017      ESTABLISHED 979/sshd: root@pts/ 
tcp        0      0 127.0.0.1:25151         127.0.0.1:52540         TIME_WAIT   -                   
tcp6       0      0 :::10443                :::*                    LISTEN      1699/httpd          
tcp6       0      0 :::22                   :::*                    LISTEN      874/sshd            
tcp6       0      0 ::1:25                  :::*                    LISTEN      972/master          
tcp6       0      0 :::8000                 :::*                    LISTEN      1699/httpd          
tcp6       0      0 :::873                  :::*                    LISTEN      1700/rsync

**Comment by wanghaiqing2015** [comment]
Modifying the http_port is also invalid.

now ， change to 80 port，can “cobbler check&sync” successflly。

**Comment by SchoolGuy** [comment]
Okay so what problems are now left? You sent a lot of code and I am not sure how we can help you.

**Comment by wanghaiqing2015** [comment]
Two problems:
1. /etc/dhcp/dhcpd.conf not generated automatically
2. Change http_port from 80 to 8000, the cobbler_api not found.

**Comment by SchoolGuy** [comment]
Okay so I verified.

1. This is the default behaviour. If this is really not working then we need a bug for that. But since @watologo1 is running and managing a lab dhcp server with Cobbler I doubt that this is not working.
2. This is possible. I can't check now but I will check tomorrow.

**Comment by watologo1** [comment]
@wanghaiqing2015 

> Change http_port from 80 to 8000, the cobbler_api not found.

Is this only from "cobbler check" or do you see real functionality issues? cobbler check is partly outdated and may throw false positive warnings.

> /etc/dhcp/dhcpd.conf not generated automatically

Can you send the generated /etc/dhcpd.conf, please.
Did you specify the interface in the dhcpd call? In SUSE there is:
/etc/sysconfig/dhcpd
DHCPD_INTERFACE="eth0"

which results in (see last param):
ps aux |grep dhcpd
dhcpd    13211  0.0  0.0  60500  5988 ?        Ss   Jul03   0:50 /usr/sbin/dhcpd -4 -cf /etc/dhcpd.conf -pf /var/run/dhcpd.pid -chroot /var/lib/dhcp -lf /db/dhcpd.leases -user dhcpd -group nogroup eth0

You could check dhcpd config without actually starting/re-starting dhcpd by using -t option (and possibly -cf option).

**Comment by wanghaiqing2015** [comment]
1、cobbler sync also this error。
2、I used centos7 OS，no /etc/dhcpd.conf generated。
3、systemctl status dhcpd

[root@vm100 ~]# systemctl status dhcpd
● dhcpd.service - DHCPv4 Server Daemon
   Loaded: loaded (/usr/lib/systemd/system/dhcpd.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2020-07-05 00:03:29 CST; 9min ago
     Docs: man:dhcpd(8)
           man:dhcpd.conf(5)
  Process: 1698 ExecStart=/usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid (code=exited, status=1/FAILURE)
 Main PID: 1698 (code=exited, status=1/FAILURE)

**Comment by wanghaiqing2015** [comment]
`[root@vm100 ~]# cat /etc/dhcp/dhcpd.conf
#
# DHCP Server Configuration file.
#   see /usr/share/doc/dhcp*/dhcpd.conf.example
#   see dhcpd.conf(5) man page
#
`

**Comment by wanghaiqing2015** [comment]
`sh
[root@vm100 ~]# cat /etc/dhcp/dhcpd.conf
#
# DHCP Server Configuration file.
#   see /usr/share/doc/dhcp*/dhcpd.conf.example
#   see dhcpd.conf(5) man page
#
`

**Comment by wanghaiqing2015** [comment]
![QQ截图20200706212615](https://user-images.githubusercontent.com/11815186/86598185-58f7ed00-bfcf-11ea-8633-9032b0781126.png)

**Comment by watologo1** [comment]
/etc/cobbler/settings
manage_dhcp: 1
?
Otherwise you should see error messages in cobbler sync.

**Comment by wanghaiqing2015** [comment]
now，we can generate this dhcpd.conf

**Comment by fwt11** [comment]
> now，we can generate this dhcpd.conf
I encountered the same problem, may I ask how you solved it?
