### ISSUE TITLE
Add repo to profile, report error message.

### ISSUE THREAD

**Issue by wanghaiqing2015** [cobbler/cobbler#2373]
cobbler 3.1.2

create a repo:
![QQ截图20200708173931](https://user-images.githubusercontent.com/11815186/86903516-03901d00-c142-11ea-91bc-560600057a62.png)

add repo to profile
![QQ截图20200708174012](https://user-images.githubusercontent.com/11815186/86903588-20c4eb80-c142-11ea-8d53-0227536f1a84.png)

View Automatic Installation Template
![QQ截图20200708174117](https://user-images.githubusercontent.com/11815186/86903670-3fc37d80-c142-11ea-97d9-0e740f2139b4.png)

/var/log/cobbler/cobbler.log
![QQ截图20200708174155](https://user-images.githubusercontent.com/11815186/86903741-5b2e8880-c142-11ea-972e-ccf1ec3d1dee.png)

**Comment by wanghaiqing2015** [comment]
remove repo from profile
![QQ截图20200708174346](https://user-images.githubusercontent.com/11815186/86903930-9761e900-c142-11ea-82a4-a044e821a072.png)

View Automatic Installation Template
![QQ截图20200708174421](https://user-images.githubusercontent.com/11815186/86904002-aba5e600-c142-11ea-897e-c7736f384750.png)

**Comment by SchoolGuy** [comment]
I had a short look at the code. Yes this bug can be reproduced if a repository has no yum options.

**Comment by SchoolGuy** [comment]
@wanghaiqing2015 Could you please check the PR if this actually fixes your problem?

**Comment by wanghaiqing2015** [comment]
No, there are still failed

**Comment by wanghaiqing2015** [comment]
vi /usr/lib/python3.6/site-packages/cobbler/items/mgmtclass.py
vi /usr/lib/python3.6/site-packages/cobbler/items/repo.py 
vi /usr/lib/python3.6/site-packages/cobbler/items/system.py

 cobbler sync

**Comment by opoplawski** [comment]
Were the repos created with 3.1.2?  How were they created?  I can't reproduce producing a repo without a yumopts being set to {}.  What is the contents of /var/lib/cobbler/collections/repos/allyun-centos7.json?

**Comment by wanghaiqing2015** [comment]
I deleted the old repos and added a new one. The yumopts still null.

![QQ截图20200711120137](https://user-images.githubusercontent.com/11815186/87216027-4afaf100-c36e-11ea-9431-6b4aa09885bd.png)

**Comment by wanghaiqing2015** [comment]
![QQ截图20200711120338](https://user-images.githubusercontent.com/11815186/87216076-b8a71d00-c36e-11ea-9b24-ec3a65b48048.png)
![QQ截图20200711120408](https://user-images.githubusercontent.com/11815186/87216078-ba70e080-c36e-11ea-890c-77fa3c9936e9.png)
![QQ截图20200711120434](https://user-images.githubusercontent.com/11815186/87216079-bb097700-c36e-11ea-8795-e9b87bfa8730.png)

**Comment by wanghaiqing2015** [comment]
cobbler repo add --name=aliyun-centos7  --arch=x86_64 --breed=yum --mirror-locally=Flase --comment=Centos7-64 --mirror=http://mirrors.aliyun.com/centos/7/os/x86_64/

**Comment by wanghaiqing2015** [comment]
If create the repo from web, it can be created successfully.

![QQ截图20200711120736](https://user-images.githubusercontent.com/11815186/87216123-205d6800-c36f-11ea-9774-bff377797e65.png)

**Comment by wanghaiqing2015** [comment]
Suffix error

![QQ截图20200711121131](https://user-images.githubusercontent.com/11815186/87216175-ae395300-c36f-11ea-99a6-5f748a641c48.png)

**Comment by wanghaiqing2015** [comment]
Sorry, I restarted the cobberd service. Now it can be generated normally.

systemctl restart cobblerd

**Comment by wanghaiqing2015** [comment]
There is only one error suffix left.

**Comment by SchoolGuy** [comment]
@wanghaiqing2015 I will create a new Bug for your suffix error as this is a different bug in my eyes.
