### ISSUE TITLE
Repository items have .json suffix

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2376]
### Describe the bug

Found by @wanghaiqing2015

When adding a repo object we are creating a file named `name.json.json` this does not affect the functionallity of Cobbler apparently but it is ugly and confusing.

### To Reproduce

1. Create a repo with the CLI or Web-UI
2. Look at `/var/cobbler/collections/repo/`
3. See error

### Expected behavior

The files should be named `name.json`

### Version

See tag: 3.1.2

**Comment by ghjs** [comment]
I missed mentioning this issue in PR [#2451](https://github.com/cobbler/cobbler/pull/2451).

**Comment by SchoolGuy** [comment]
This was closed via the mentioned PR. Thus closing this.
