### ISSUE TITLE
Fix Cobbler <--> Terraform compatibility #1

### ISSUE THREAD

**Issue by holmesb** [cobbler/cobbler#2381]
Terraform only works if two changes are made.  This issue concerns the first:

> In `cobbler/items/item.py`, this line has to be uncommented:
> 
> ```python
>      def to_dict(self):
>          return utils.to_dict_from_fields(self, self.get_fields())  # <== UNCOMMENTED LINE
> 
>          value = self.get_from_cache(self)
>          if value is None:
>              value = utils.to_dict_from_fields(self, self.get_fields())
>          self.set_cache(self, value)
>          return value
> ```
> If not, you will get:
> `Error: Cobbler Profile: Error Creating: Fault(1): <class 'AttributeError'>:'str' object has no attribute 'copy'`.

This is caused because in utils.py's [`__consolidate` function](https://github.com/cobbler/cobbler/blob/31fa87ddd6f848793870da7dee2b10d3756aa7d4/cobbler/utils.py#L772), we attempt to update the `results` dictionary with an empty value.  The 'str' value referred in the above error is empty because there is no `node_data` for some fields.  Is solved by ignoring empty node_data items ([data_item](https://github.com/cobbler/cobbler/blob/31fa87ddd6f848793870da7dee2b10d3756aa7d4/cobbler/utils.py#L797)).  With this condition, caching can be used and the above line does not need to be uncommented.

> If anyone wants to test / debug this behaviour, we provide pre-compiled binaries here:
> https://github.com/wearespindle/terraform-provider-cobbler/releases/
> 
> Follow the instructions in this PR (link: <https://cobbler--2283.org.readthedocs.build/en/2283/user-guide/terraform-provider.html>) to set things up. Will make a nice (weekend) project for those stuck at home during the current Corona outbreak. 🦠 🤡
> 
> _Originally posted by @hbokh in https://github.com/cobbler/cobbler/pull/2283#issuecomment-598271114_

**Comment by holmesb** [comment]
This has been worked-around by adding an option that [disables caching](https://github.com/cobbler/cobbler/pull/2387).  

Be great if could have a new Cobbler release that is compatible with Terraform @SchoolGuy

**Comment by SchoolGuy** [comment]
@holmesb If we test `libcobblersignatures` and integrate it we can release a new version. Before that I would like to keep the current version.
