### ISSUE TITLE
Packaging: Provide native packages for Debian & Ubuntu

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2393]
### Is your feature request related to a problem?

Currently we only provide packages for Debian and Ubuntu via Debbuild. This is good for test installations or users how know the OBS already and are familiar with it.

### The Behaviour you'd like

`apt install cobbler`

### Alternatives you've considered

Well the OBS is nice and all but in the end we will probably have more users when providing Distro-Native packages. Also we will have a simpler specfile.

### Additional context

Current OBS project in my home: https://build.opensuse.org/project/show/home:SchoolGuy:cobbler

**Comment by SchoolGuy** [comment]
As per the Gitter chat @dansou901 said he is able to start working on this later this year.

**Comment by SchoolGuy** [comment]
@dansou901 Do you think you will be able to progress this? Or shall someone else take over? What is your desire in this regard?

**Comment by dansou901** [comment]
I still want to do this, sadly I didn't find the time yet to do so. But I will have at least one more week of holidays this year, then I'll start on this for sure.

**Comment by SchoolGuy** [comment]
Thanks a billion times! I will try to integrate the openSUSE OBS so you don't have to worry about dependencies and building.

**Comment by dansou901** [comment]
I already did some digging around and try to figure out the best way of doing this. I'm still quite new to debian packaging as I never packaged something as big as cobbler. What I found is that the openstack did debian builds way back until version 2.6.6. So to get the current version into debian, we would need to inherit their responsibility for the cobbler package which should be orphaned by now. At least that's the current state of cobbler in debian.

**Comment by SchoolGuy** [comment]
@dansou901 The way of getting this on the SUSE side is just to ask nicely on the appropriate mailing list. Thus I believe a mail and updating to the latest version is the thing to to. If you somehow see a showstopper, I would be glad to help you...

**Comment by dansou901** [comment]
It's much more complicated on debian, see the following document: https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html. They have a special issue tracking system to ask for including packages on which you have to follow a specific route to have your package added. The package also needs to meet specific requirements. It's all listed in the link above.

**Comment by SchoolGuy** [comment]
Thanks. I will have a look. Maybe we can split the work so it gets easier for both of us!

**Comment by SchoolGuy** [comment]
Since I broke `master` with one of my PRs and I want to ship the new version rather sooner then later, I think I need to reschedule this for 3.4.0. We have DEBs so it is not pressing for now imho.

**Comment by SchoolGuy** [comment]
@dansou901 Do you have an update on this?

**Comment by dansou901** [comment]
I'm sorry for the late answer. Currently, we are discussing internally which tools we want to use in the future to administer our systems. This will take a while. It's a possibility that we will drop the usage of cobbler in favor of something different, but that's not clear yet. As soon as it is, I will have a look at this again.

**Comment by SchoolGuy** [comment]
@dansou901 Thanks a lot! If you decide to replace Cobbler I would love to know which solution won over Cobbler. I would love to make it better for other people, so the community gets bigger in the future.

**Comment by dansou901** [comment]
I will. Right now, we are starting to bootstrap our new configuration management infrastructure, so setting up a new install server will be part of that. As soon as I have more news, I'll check back in here.

**Comment by SchoolGuy** [comment]
@dansou901 Any news on this?

**Comment by dansou901** [comment]
I'm still busy setting up the new environment in our infrastructure, I'll be evaluating options for an install server this or next week.

**Comment by SchoolGuy** [comment]
@dansou901 Don't hesitate to ask for features. I have a strong interest in this contribution and thus I am willing to invest in your company with a feature that you would desire. It is my free time so don't expect wonders but I'll do my best. :)

**Comment by SchoolGuy** [comment]
@dansou901 Don't hesitate to ask for features. I have a strong interest in this contribution and thus I am willing to invest in your company with a feature that you would desire. It is my free time so don't expect wonders but I'll do my best. :)

**Comment by dansou901** [comment]
The main thing missing right now for me is the missing web interface.

**Comment by dansou901** [comment]
Also nice would be a way to provision a machine automatically via cobbler, in a way that cobbler powers on the machine and installs it in one go (maybe that's already possible today)

**Comment by dansou901** [comment]
Sounds good. Do you have an estimate on when the Web interface will be done?

**Comment by SchoolGuy** [comment]
@dansou901 I will sit down tomorrow and create one. The API Client and Fronted both have rudimentary functions but it is definitely not ready.

**Comment by SchoolGuy** [comment]
@dansou901 Any updates? I CC'd you in the project plan I have for the WebUI.

**Comment by SchoolGuy** [comment]
@dansou901 I have something working! The PR is not yet ready but I would really appreciate your comments on the draft if you have time!

**Comment by dansou901** [comment]
Saw what you did, looking good so far. But you said lintian is quite unhappy with the current state, maybe I can help with that. I've got some experience working around lintian problems. Do you have an output of what lintian disapproves of?

**Comment by dansou901** [comment]
Something else, do you have plans already for where to push the finished packages to when they are done?

**Comment by dansou901** [comment]
Also just left a comment for one small thing in the pull request.

**Comment by SchoolGuy** [comment]
@dansou901 So my current knowledge of Debian packaging is limited to the last 5 hours. So I haven't thought about pushing it to Debian & Ubuntu, although I would really love if that is possible. If that is not possible or too much work, I would try to attach the RPMs and DEBs for a release along to the GitHub Release and then additionally building them in my home project in the OBS to be able to provide a repository. However all of that requires time after I got the packaging working in the CI we run here.

Lintian is basically unhappy about the following two rules:

- https://lintian.debian.org/tags/dir-or-file-in-var-www
- https://lintian.debian.org/tags/package-installs-python-pycache-dir

Apart from that I only see warnings that I would ignore for the moment.

**Comment by dansou901** [comment]
Both of them shouldn't be hard to fix. The first one is a design question: Do we want to point to /var/www as DocumentRoot or do we want to change that? How will such a change affect updates / migrations from previous versions? If we do not want to change that, we need to add a lintian override.
The second one should be done as it says: the package shouldn't include the pycache directory but rather create and populate it during postinst. Maybe this should also be changed in the rpm if it is the same behaviour there.
For lintian overrides just add a file called cobbler.lintian-override and populate it with the tag you want to override, in the first case that would be just the string "dir-or-file-in-var-www". Same goes for other warnings you want to ignore.

**Comment by dansou901** [comment]
Apart from building the debs in your OBS home project, I would rather propose to create a ppa at launchpad. That would be the fastest way to get the packages to people. As soon as we have those there, we can still try to figure out how to get them included in the main repositories.

**Comment by SchoolGuy** [comment]
Okay then let's do it exactly like you proposed. It is one place more for me but that isn't a problem. I already have an account at Launchpad.

In regard to the warnings and errors of lintian: I will call it a day for now but I will try to sit down on Sunday to get the things in order. The heat make concentration hard. Especially the document root change needs to be done properly. Doing that cross-distro will be an interesting challenge.

**Comment by dansou901** [comment]
If we do the document root change cross-distro, maybe it's a good idea to point that to one directory for all distros to make it easier. Just as an idea.

**Comment by SchoolGuy** [comment]
That would be indeed cool. I will dig into that. We would save ourselves quite some configuration variables and logic in quite many places...
