### ISSUE TITLE
Unable to import ubuntu-20.04.1 distro "No signature matched"

### ISSUE THREAD

**Issue by pharthiphan** [cobbler/cobbler#2395]
Unable to import ubuntu-20.04.1 distro "No signature matched"

received on stderr:
No signature matched in /var/www/cobbler/ks_mirror/ubuntu-20.04.1-x86_64
!!! TASK FAILED !!!

### To Reproduce

mount -t iso9660 -o loop,ro ubuntu-20.04.1-desktop-amd64.iso /mnt
cobbler import --name=ubuntu-20.04.1 --arch=x86_64 --path=/mnt

### Expected behaviour

Import completed!

### Version

Cobbler 2.8.5

**Comment by SchoolGuy** [comment]
I will try to update the signatures this weekend or next week.

**Comment by SchoolGuy** [comment]
Note: I strongly encourage you to update to Cobbler 3 since Cobbler 2.x.x is EOL since it is Py2!

**Comment by pharthiphan** [comment]
@SchoolGuy Thanks! is there a way I can update the signature on my current version. can you help me with the steps if that is not too complicated?

**Comment by SchoolGuy** [comment]
`cobbler signature update` should be enough if I do everything correctly.

**Comment by SchoolGuy** [comment]
This works both for Cobbler 2 and 3.

**Comment by pharthiphan** [comment]
I mean I tried that but still getting the same error message

`No signature matched in /var/www/cobbler/ks_mirror/ubuntu-20.04.1-x86_64
!!! TASK FAILED !!!
`

**Comment by pharthiphan** [comment]
Ok, will run the command once you have updated the signatures

**Comment by pharthiphan** [comment]
@SchoolGuy How to upgrade cobbler from 2.8.5 to 3.x? can you refer to some link if it exists ?

**Comment by SchoolGuy** [comment]
The linked PRs are the WIP state. I need to test this tomorrow when I have more time.

**Comment by pharthiphan** [comment]
@SchoolGuy 

I tried to upgrade the cobbler version from 2.8.5 to 3.1.2 but unable to import Ubuntu 20.04.1 server. Also, I ran into another issue distro, profile & system are not visible after upgrading! can't we preserve the data while upgrading cobbler to 3.x? 

`# cobbler --version
Cobbler 3.1.2
  source: ?, ?
  build time: Mon Aug 17 08:34:46 2020
`

`Exception value: 'No signature matched in /var/www/cobbler/distro_mirror/ubuntu-20.04.1-server-amd64'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 102, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 309, in runner
    self.logger

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1502, in import_tree
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 186, in run
    raise CX(error_msg)

!!! TASK FAILED !!!
`

**Comment by SchoolGuy** [comment]
@pharthiphan So the problem regarding the signature is the same as under 2.8.5 the data needs to be migrated via the script we provide in our repo. This is not executed automatically.

I was not able to find time at the weekend. Tomorrow although I will have time to do so.

**Comment by pharthiphan** [comment]
@SchoolGuy can you please point me to the script?

**Comment by SchoolGuy** [comment]
https://www.github.com/cobbler/cobbler/tree/master/scripts%2Fmigrate-data-v2-to-v3.py

**Comment by pharthiphan** [comment]
Did I miss something?

`# ./migrate-data-v2-to-v3.py
Processing distros.d:
    Processing CentOS-7-Minimal-1908-x86_64
Processing files.d:
Processing images.d:
Processing mgmtclasses.d:
Processing packages.d:
Processing profiles.d:
    Processing CentOS-7-Minimal-1908-x86_64
Processing repos.d:
Processing systems.d:
    Processing cn01
cp: missing file operand
Try 'cp --help' for more information.
`

**Comment by SchoolGuy** [comment]
I know noone who did a manual migration and I am very sure that (depending on the size of your setup) this is not desired. If you have a very small setup just install Cobbler 3 and start from scratch.

Accounting for all migration steps manually was never done in my eyes...

**Comment by pharthiphan** [comment]
@SchoolGuy thank-you for the explanation but the migration script doesn't seem to be working! Setup is relatively big and it would be hard to start from scratch!

**Comment by SchoolGuy** [comment]
@opoplawski Do I recall correctly that you wrote the script (I am traveling only with my mobile currently thus I can't check)?

@pharthiphan I know at least of one successful migration with this script. I also know of the existance of another script but I need to find it tomorrow...

**Comment by pharthiphan** [comment]
@opoplawski @SchoolGuy replacing subprocess.run with os.system kind of solved the copying issue but cobbler distro/ system list doesn't show up anything

`subprocess.run(["/bin/cp", "-al", "%s/" % old_path, "%s/" % new_path], shell=True)`

`        cmd = " ".join(["cp", "-al", "%s/" % old_path, "%s/" % new_path])
        os.system(cmd)
`

`./migrate-data-v2-to-v3.py
Processing distros.d:
    Processing CentOS-7-Minimal-1908-x86_64
Processing files.d:
Processing images.d:
Processing mgmtclasses.d:
Processing packages.d:
Processing profiles.d:
    Processing CentOS-7-Minimal-1908-x86_64
Processing repos.d:
Processing systems.d:
    Processing cn01
`

**Comment by SchoolGuy** [comment]
@pharthiphan That I don't know without sitting in front of my computer... I see what I can do tomorrow.

**Comment by SchoolGuy** [comment]
I now tested the PRs and will merge them. Afterwards after a `cobbler signature update` the image should be successfully imported.
