### ISSUE TITLE
PAM authentication failure

### ISSUE THREAD

**Issue by fonzinc** [cobbler/cobbler#2400]
### Describe the bug

Enabling authentication.pam module results in TypeError exception and failure to authenticate.

### To Reproduce

1. Change authentication module to "authentication.pam" in modules.com
2. Restart cobbler service
3. Attempt to login via web UI
4. See error in cobbler.log

````
DEBUG | authn_pam: PAM service is login
INFO | Exception occured: <class 'ctypes.ArgumentError'>
INFO | Exception value: argument 1: <class 'TypeError'>: wrong type
INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3477, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3233, in login
    if self.__validate_user(login_user, login_password):

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3113, in __validate_user
    return self.api.authenticate(input_user, input_password)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1599, in authenticate
    rc = self.authn.authenticate(self, user, password)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/authentication/pam.py", line 141, in authenticate
    retval = PAM_START(str(service), str(username), pointer(conv), pointer(handle))

````

### Expected behavior

PAM authentication should succeed.

### Version

````
Cobbler 3.1.2
  source: ?, ?
  build time: Sun May 31 02:32:34 2020
````

**Comment by fonzinc** [comment]
The following patch seems to have fixed the issue for me:
````
--- /usr/lib/python3.6/site-packages/cobbler/modules/authentication/pam.py.orig	2020-08-24 22:12:16.178380466 +0000
+++ /usr/lib/python3.6/site-packages/cobbler/modules/authentication/pam.py	2020-08-24 22:19:34.634209255 +0000
@@ -124,7 +124,7 @@
         p_response[0] = cast(addr, POINTER(PamResponse))
         for i in range(n_messages):
             if messages[i].contents.msg_style == PAM_PROMPT_ECHO_OFF:
-                pw_copy = STRDUP(str(password))
+                pw_copy = STRDUP(password.encode())
                 p_response.contents[i].resp = cast(pw_copy, c_char_p)
                 p_response.contents[i].resp_retcode = 0
         return 0
@@ -138,7 +138,7 @@
 
     handle = PamHandle()
     conv = PamConv(my_conv, 0)
-    retval = PAM_START(service, username, pointer(conv), pointer(handle))
+    retval = PAM_START(service.encode(), username.encode(), pointer(conv), pointer(handle))
 
     if retval != 0:
         # TODO: This is not an authentication error, something
````

**Comment by SchoolGuy** [comment]
@fonzinc Does the module work now to your expectations or is there anything else which is broken in your eyes.

**Comment by fonzinc** [comment]
Yes, PAM authentication seems to work as expected after applying the patch. I have not encountered any additional issues, but I did not conduct a full audit of the module for additional type issues.

I would love to see the patch included. Thanks!

**Comment by SchoolGuy** [comment]
Okay when I have time at the weekend or in the evening I will include it in master. The next release will happen along with the new signatures library (which needs testing before integrating it), thus the next version will need some time until it will get released.

**Comment by opoplawski** [comment]
Looks like this got forgotten about and never applied?

**Comment by SchoolGuy** [comment]
Yes it was forgotten. Damit. I will create a PR now.

**Comment by SchoolGuy** [comment]
@fonzinc I never used PAM but while I read into it and create some testcases so your error can't reappear please be patient. I will try my best.

**Comment by SchoolGuy** [comment]
I wrote to the original author of the PAM Python connector to see if we can get the patch also included in his library and depend on the library (since our source code is just copy & pasted from his sources).

**Comment by SchoolGuy** [comment]
@catlee maybe you are faster to respond directly here...
