### ISSUE TITLE
Functions defined in cheetah_macros unavailable in templates

### ISSUE THREAD

**Issue by glbyers** [cobbler/cobbler#2403]
### Describe the bug

Cheetah macros/functions defined in /etc/cobbler/cheetah_macros are not available for use in templates as documented in extending_cobbler.

### To Reproduce

Define a function in /etc/cobbler/cheetah_macros.

```
#def hello($str)
Hello, $str
#end def
```

Attempt to use it in a template. For example, in the main section of a kickstart template;

```
$hello('Grant')
```

Check the rendered kickstart;
```
# curl -s http://127.0.0.1/cblr/svc/op/autoinstall/system/test-host
# This automatic OS installation file had errors that prevented it from being rendered correctly.
# The cobbler.log should have information relating to this failure.
```

Check cobbler logs;
```
# cannot find 'hello'
#   File "/usr/lib/python3.6/site-packages/cobbler/templar.py", line 212, in render_cheetah
#     data_out = t.respond()
```

### Expected behavior

Rendered output should include the raw string "Hello, Grant"

### Version

````
# cobbler version
Cobbler 3.1.2
  source: ?, ?
  build time: Sun May 31 02:32:34 2020
````

### Screenshots

N/A

### Additional context

N/A

**Comment by SchoolGuy** [comment]
I find that the docs about this are rather vague or missing. Let's fix that for the next release.

**Comment by SchoolGuy** [comment]
I looked through the code and saw that the file is loaded but never actually used. I will dive into it to fix it.
