### ISSUE TITLE
Linting & Dependency tracking

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2422]
### Version

````paste below
git master
````

### Question

Currently we are using Codacy for Linting our Pull Requests and some basic linting in our CI. I now found the following tool: <https://pyup.io/>.

This new tool now checks for Python dependency problems. In my eyes it would be reasonable to enable that for us but I wanted to check with the community first.

My question to the community now is what tools to we want to use for ensure good tools and what to we want to disable?

Codacy enabled is doing a good job currently, with the nitpick that it is not configured and thus sometimes gives false positives (docstring formatting for example).

In the CI (and via `make qa`):

- pyflakes --> Configured
- pycodestyle --> Configured

In Codacy (defaults from the tools are applyed):

- Bandit 1.6.2
- CSSLint 1.0.5
- ESLint 7.10.0
- Hadolint 1.17.5
- JSHint 2.12.0
- JacksonLinter 2.10.2
- Prospector 1.2.0
- PyLint (Python 3) 2.6.0
- RemarkLint 7.0.1
- Stylelint 13.7.2
- shellcheck v0.7.1 

Please discuss!

**Comment by dansou901** [comment]
Good effort! If we follow this road completely, we will need pyup.io additionally to the tools we already use. Is the list you put up in your first post complete on what we have enabled for now? Would it be a good idea to document this in the wiki section of the project? That way, it would be easier to track those things.
Something else: When we ever decide to provide docker containers in the future, we should also scan those with clair or something similar just to be sure.

**Comment by dansou901** [comment]
For Codacy: if there is only configuration that is needed, maybe I can help. I don't know the tool, but I can go through the docs and try to configure it in a way that it works for us. As said before: documentation on what is enabled already will help others to understand what needs to be done.

**Comment by SchoolGuy** [comment]
@dansou901 Yes the first list are the tools enabled in the CI and the second list is what is enabled in Codacy. Codacy basically collects these tools and acts as a CI and renders the results nicely. I enabled Pyup for a testrun and we now have a lot of version pinning PRs open. Also it seems that they depend on requirements files.

**Comment by SchoolGuy** [comment]
Travis currently is not running due to a negative credit balance. I think I will replace that with a Jenkins Instance hosted by myself. That will have the effect that the the tests run slower but I also don't like the fact that they have a "Marketplace" which indicates that they do wish at some point to earn money with it. Gitlab is also a good idea but for that I would need to use my personal credits or we would need a Cobbler Org there. In any case this is more work and I won't think that it is possible to do in the linked PR.

**Comment by dansou901** [comment]
GitLab CI still isn't ready for forks, also see https://gitlab.com/gitlab-org/gitlab/-/issues/5667 and https://gitlab.com/gitlab-org/gitlab/-/issues/281689 on that. Will be fixed sometime in the current year I hope, but can also take more time if we're unlucky, so going with a Jenkins instance wouldn't be bad. Where would you be hosting that?

**Comment by SchoolGuy** [comment]
@dansou901 In my basement. Thus 1000MBit/s down + 50 MBit/s up but that includes also the rest of the server and our home network...

**Comment by dansou901** [comment]
Would it be good to have a backup instance in the background in case yours has problems? I also have a server in my flat with 500 Mbit/s down and 50 Mbit/s up where I can just spin up another container with Jenkins in it.

**Comment by SchoolGuy** [comment]
@dansou901 How do we configure this then? One Container needs to be the master and running the pipeline both times (your and my flat/house) is not a cool thing in my eyes...

**Comment by dansou901** [comment]
No. I just would start up mine in case yours has severe problems you can't solve within one day. Just as an idea.

**Comment by dansou901** [comment]
Ok so we should have identical configurations on our servers and test the manual failover mechanism somehow (easiest would be to just change dns when needed, we should also have the same email address configured for Let's Encrypt on both sides, just to be sure). Should we do a separate repository with the compose configuration in it?

**Comment by SchoolGuy** [comment]
@dansou901 Let me check tomorrow what is possible

**Comment by dansou901** [comment]
and maybe we should continue talking about ci in another issue, this one will be closed by your pull request once merged
