### ISSUE TITLE
Build Cobbler 3.x  from source on CentOS 7 

### ISSUE THREAD

**Issue by Kirandp6** [cobbler/cobbler#2432]
### Version

Yet  to install , 3.x latest 

### Question

As with normal epel repo on CentOS 7, i do not get latest cobbler , i decided to download the sorce code 

did 
git clone https://github.com/cobbler/cobbler.git

cd cobbler
source distro_build_configs.sh

cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

python --version
Python 3.6.9

Error

make install
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    from sphinx.setup_command import BuildDoc
ModuleNotFoundError: No module named 'sphinx'
make: *** [build] Error 1

#######################################

Doc i follow for install & installed as pre-reqisit rpms 

https://cobbler.readthedocs.io/en/latest/installation-guide.html

Thanks

**Comment by dansou901** [comment]
is there a reason that doesn't allow you to use CentOS 8? In CentOS 8 you'll get the latest version from epel.

**Comment by SchoolGuy** [comment]
@Kirandp6 So this definitely works on CentOS7 since we are building every pushed commit in the CI on CentOS7. Thus maybe the docs are not good enough but from a technical side this should work.

The error message you are getting is due to a missing dependency. According to the website of Sphinx (<https://www.sphinx-doc.org/en/master/usage/installation.html>) this should work with `yum install python-sphinx`.

**Comment by Kirandp6** [comment]
@SchoolGuy  , Thanks, i had to do below

yum install *sphinx*  -y

 yum install *coverage*  -y


can i ignore the 2 last lines - errors 

copying svc/services.py -> /var/www/cobbler/svc/
copying cobbler/web/settings.py -> /usr/local/share/cobbler/web/
creating /etc/cobbler/zone_templates
copying templates/zone_templates/foo.example.com -> /etc/cobbler/zone_templates
copying config/cobbler/logging_config.conf -> /etc/cobbler
copying build/sphinx/man/cobbler.1 -> /usr/local/share/man/man1
copying build/sphinx/man/cobbler.conf.5 -> /usr/local/share/man/man5
copying build/sphinx/man/cobblerd.8 -> /usr/local/share/man/man8
running install_egg_info
running egg_info
creating cobbler.egg-info
writing cobbler.egg-info/PKG-INFO
writing dependency_links to cobbler.egg-info/dependency_links.txt
writing requirements to cobbler.egg-info/requires.txt
writing top-level names to cobbler.egg-info/top_level.txt
writing manifest file 'cobbler.egg-info/SOURCES.txt'
reading manifest file 'cobbler.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'AUTHORS'
writing manifest file 'cobbler.egg-info/SOURCES.txt'
Copying cobbler.egg-info to /usr/local/lib/python3.6/site-packages/cobbler-3.2.0-py3.6.egg-info
running install_scripts
copying build/scripts-3.6/cobbler -> /usr/local/bin
copying build/scripts-3.6/cobblerd -> /usr/local/bin
copying build/scripts-3.6/cobbler-ext-nodes -> /usr/local/bin
changing mode of /usr/local/bin/cobbler to 755
changing mode of /usr/local/bin/cobblerd to 755
changing mode of /usr/local/bin/cobbler-ext-nodes to 755
Error in 'chown apache /usr/local/share/cobbler/web': "getpwnam(): name not found: 'wwwrun'"
Error in 'chown apache //var/lib/cobbler/webui_sessions': "getpwnam(): name not found: 'wwwrun'"

**Comment by SchoolGuy** [comment]
@Kirandp6 Yes you can. That effectively means that the directorys `/usr/local/share/cobbler/web` and `/var/lib/cobbler/webui_sessions` are owned by the user you used for building Cobbler. This means that your webserver will maybe have trouble serving some web content but that can easily be fixed with a `chown` of the webserver user of your OS.

**Comment by hbokh** [comment]
I used to build the RPMs on my Mac **using Docker:**
Run this in the Cobbler repo base directory:
`./tests/build-and-install-rpms.sh el7 dockerfiles/CentOS7.dockerfile`

and the RPMs can be found after a successful  build in subdir. `rpm-build`.
These packages in that directory can be copied to a CentOS7 host and installed over there:

- `cobbler-3.2.0-1.el7.noarch.rpm`
- `cobbler-web-3.2.0-1.el7.noarch.rpm`

**Comment by hbokh** [comment]
Tried to build RPMs on my little CentOS7 box. This also works, without using Docker.
Had to install `wheel` for Python3 first: `pip3 install wheel`.
Than ran `make rpms` and subdir. `rpm-build` showed freshly baked RPM files.

I suggest to try this method (create and install packages) instead of `make install` from source.

**Comment by SchoolGuy** [comment]
FYI @Kirandp6: In the end the scripts are also executing `make install`. This target is just safeguarding a lot that could be missing... Thus I would agree with @hbokh that as long as we have such a complex installation process `make rpms` ist the best option. Although technically spoken it is not 100% from source as this makes use of a lot of pre built dependencies via your package manager.

**Comment by hbokh** [comment]
> Error in 'chown apache /usr/local/share/cobbler/web': "getpwnam(): name not found: 'wwwrun'"
> Error in 'chown apache //var/lib/cobbler/webui_sessions': "getpwnam(): name not found: 'wwwrun'"

This is odd!
`wwwrun` for `APACHE_USER` is only used for SUSE, not for CentOS /  Fedora.

Try using `bash -x` instead of `source` before `distro_build_configs.sh`.
Here's my outputm which clearly shows `+ APACHE_USER=apache`:

```shell
# bash -x distro_build_configs.sh
+ export DATAPATH=/usr/share/cobbler
+ DATAPATH=/usr/share/cobbler
+ export DOCPATH=share/man
+ DOCPATH=share/man
+ export ETCPATH=/etc/cobbler
+ ETCPATH=/etc/cobbler
+ export LIBPATH=/var/lib/cobbler
+ LIBPATH=/var/lib/cobbler
+ export LOGPATH=/var/log
+ LOGPATH=/var/log
+ export COMPLETION_PATH=/usr/share/bash-completion/completions
+ COMPLETION_PATH=/usr/share/bash-completion/completions
+ export STATEPATH=/tmp/cobbler_settings/devinstall
+ STATEPATH=/tmp/cobbler_settings/devinstall
+ export HTTPD_SERVICE=apache2.service
+ HTTPD_SERVICE=apache2.service
+ export WEBROOT=/srv/www
+ WEBROOT=/srv/www
+ export WEBCONFIG=/etc/apache2/vhosts.d
+ WEBCONFIG=/etc/apache2/vhosts.d
+ export WEBROOTCONFIG=/etc/apache2
+ WEBROOTCONFIG=/etc/apache2
+ export TFTPROOT=/srv/tftpboot
+ TFTPROOT=/srv/tftpboot
+ export DEFAULTPATH=etc/sysconfig
+ DEFAULTPATH=etc/sysconfig
+ '[' 0 -ge 2 ']'
+ '[' '' = '' ']'
+ '[' -r /etc/os-release ']'
+ source /etc/os-release
++ NAME='CentOS Linux'
++ VERSION='7 (Core)'
++ ID=centos
++ ID_LIKE='rhel fedora'
++ VERSION_ID=7
++ PRETTY_NAME='CentOS Linux 7 (Core)'
++ ANSI_COLOR='0;31'
++ CPE_NAME=cpe:/o:centos:centos:7
++ HOME_URL=https://www.centos.org/
++ BUG_REPORT_URL=https://bugs.centos.org/
++ CENTOS_MANTISBT_PROJECT=CentOS-7
++ CENTOS_MANTISBT_PROJECT_VERSION=7
++ REDHAT_SUPPORT_PRODUCT=centos
++ REDHAT_SUPPORT_PRODUCT_VERSION=7
+ case $ID in
+ DISTRO=FEDORA
+ '[' FEDORA = SUSE ']'
+ '[' FEDORA = UBUNTU ']'
+ '[' FEDORA = FEDORA ']'
+ export APACHE_USER=apache
+ APACHE_USER=apache
+ export APACHE_GROUP=apache
+ APACHE_GROUP=apache
+ export HTTPD_SERVICE=httpd.service
+ HTTPD_SERVICE=httpd.service
+ export WEBROOT=/var/www
+ WEBROOT=/var/www
+ export WEBCONFIG=/etc/httpd/conf.d
+ WEBCONFIG=/etc/httpd/conf.d
+ export WEBROOTCONFIG=/etc/httpd
+ WEBROOTCONFIG=/etc/httpd
+ export TFTPROOT=/var/lib/tftpboot
+ TFTPROOT=/var/lib/tftpboot
```

**Comment by Kirandp6** [comment]
> make rpms

well.. i already did 

make install

make devinstall
...

make[1]: Entering directory `/root/cobbler-source/cobbler'
# Check if we are on Red Hat, SUSE or Debian based distribution
running restorestate
if [ -n "`getent passwd apache`" ] ; then \
        chown -R apache //var/www/cobbler; \
elif [ -n "`getent passwd wwwrun`" ] ; then \
        chown -R wwwrun //usr/share/cobbler/web; \
elif [ -n "`getent passwd www-data`"] ; then \
        chown -R www-data //usr/share/cobbler/web; \
fi
if [ -d //var/www/cobbler ] ; then \
        chmod -R +x //var/www/cobbler/svc; \
fi
if [ -d //usr/share/cobbler/web ] ; then \
        chmod -R +x //usr/share/cobbler/web; \
fi
if [ -d //srv/www/cobbler/svc ]; then \
        chmod -R +x //srv/www/cobbler/svc; \
fi
rm -rf /tmp/cobbler_settings/devinstall
make[1]: Leaving directory `/root/cobbler-source/cobbler'



...

Well still tried in source code 

make rpms ( post wheel install ) , gave error 

make rpms
cleaning: python bytecode
cleaning: build artifacts
cleaning: temp files
checking: pyflakes /bin/pyflakes
cobbler/cli.py:392:90: invalid syntax
            print("cobblerd does not appear to be running/accessible: %s" % repr(e), file=sys.stderr)
                                                                                         ^
cobbler/cobblerd.py:98:24: invalid syntax
        print(msg, file=sys.stderr)
                       ^
cobbler/serializer.py:37:65: invalid syntax
    print("Ctrl-C not allowed during writes. Please wait.", file=sys.stderr)
                                                                ^
cobbler/settings.py:199:28: invalid syntax
    def collection_types() -> str:
                           ^
cobbler/tftpgen.py:621: undefined name 'FileNotFoundError'
bin/cobblerd:33:70: invalid syntax
        print("fork #1 failed: %d (%s)" % (e.errno, e.strerror), file=sys.stderr)
                                                                     ^
make: *** [qa] Error 1



#######################################

per other note, i was doing source code as CentOS 7 does not have latest cobbler in EPEL .. i will try on CentOS 8 as well ... as EPEL way is much better & easy 





There are seems more steps needed to bring it in systemd ..

**Comment by Kirandp6** [comment]
> is there a reason that doesn't allow you to use CentOS 8? In CentOS 8 you'll get the latest version from epel.

well .. centos 8 is not fully baked wrt community ansible roles.. so i was doing centos 7 ... many roles i use today from community do not have centified yet on centos 8

**Comment by Kirandp6** [comment]
> > Error in 'chown apache /usr/local/share/cobbler/web': "getpwnam(): name not found: 'wwwrun'"
> > Error in 'chown apache //var/lib/cobbler/webui_sessions': "getpwnam(): name not found: 'wwwrun'"
> 
> This is odd!
> `wwwrun` for `APACHE_USER` is only used for SUSE, not for CentOS / Fedora.
> 
> Try using `bash -x` instead of `source` before `distro_build_configs.sh`.
> Here's my output on CentOS7, which clearly shows `+ APACHE_USER=apache`:
> 
> ```shell
> # bash -x distro_build_configs.sh
> + export DATAPATH=/usr/share/cobbler
> + DATAPATH=/usr/share/cobbler
> + export DOCPATH=share/man
> + DOCPATH=share/man
> + export ETCPATH=/etc/cobbler
> + ETCPATH=/etc/cobbler
> + export LIBPATH=/var/lib/cobbler
> + LIBPATH=/var/lib/cobbler
> + export LOGPATH=/var/log
> + LOGPATH=/var/log
> + export COMPLETION_PATH=/usr/share/bash-completion/completions
> + COMPLETION_PATH=/usr/share/bash-completion/completions
> + export STATEPATH=/tmp/cobbler_settings/devinstall
> + STATEPATH=/tmp/cobbler_settings/devinstall
> + export HTTPD_SERVICE=apache2.service
> + HTTPD_SERVICE=apache2.service
> + export WEBROOT=/srv/www
> + WEBROOT=/srv/www
> + export WEBCONFIG=/etc/apache2/vhosts.d
> + WEBCONFIG=/etc/apache2/vhosts.d
> + export WEBROOTCONFIG=/etc/apache2
> + WEBROOTCONFIG=/etc/apache2
> + export TFTPROOT=/srv/tftpboot
> + TFTPROOT=/srv/tftpboot
> + export DEFAULTPATH=etc/sysconfig
> + DEFAULTPATH=etc/sysconfig
> + '[' 0 -ge 2 ']'
> + '[' '' = '' ']'
> + '[' -r /etc/os-release ']'
> + source /etc/os-release
> ++ NAME='CentOS Linux'
> ++ VERSION='7 (Core)'
> ++ ID=centos
> ++ ID_LIKE='rhel fedora'
> ++ VERSION_ID=7
> ++ PRETTY_NAME='CentOS Linux 7 (Core)'
> ++ ANSI_COLOR='0;31'
> ++ CPE_NAME=cpe:/o:centos:centos:7
> ++ HOME_URL=https://www.centos.org/
> ++ BUG_REPORT_URL=https://bugs.centos.org/
> ++ CENTOS_MANTISBT_PROJECT=CentOS-7
> ++ CENTOS_MANTISBT_PROJECT_VERSION=7
> ++ REDHAT_SUPPORT_PRODUCT=centos
> ++ REDHAT_SUPPORT_PRODUCT_VERSION=7
> + case $ID in
> + DISTRO=FEDORA
> + '[' FEDORA = SUSE ']'
> + '[' FEDORA = UBUNTU ']'
> + '[' FEDORA = FEDORA ']'
> + export APACHE_USER=apache
> + APACHE_USER=apache            <--- there
> + export APACHE_GROUP=apache
> + APACHE_GROUP=apache
> + export HTTPD_SERVICE=httpd.service
> + HTTPD_SERVICE=httpd.service
> + export WEBROOT=/var/www
> + WEBROOT=/var/www
> + export WEBCONFIG=/etc/httpd/conf.d
> + WEBCONFIG=/etc/httpd/conf.d
> + export WEBROOTCONFIG=/etc/httpd
> + WEBROOTCONFIG=/etc/httpd
> + export TFTPROOT=/var/lib/tftpboot
> + TFTPROOT=/var/lib/tftpboot
> ```

well, i will try later this week with CentOS 8 EPEL ... so i am almost giving up on CentOS 7 source code build tho i am very near build with normal steps & have done them already ... i will keep posted

**Comment by Kirandp6** [comment]
trying the centos 8 EPEL wrt https://github.com/cobbler/cobbler/issues/2437  , so closing this one
