### ISSUE TITLE
Cobbler /etc/cobbler/pxe/*.template

### ISSUE THREAD

**Issue by danishina** [cobbler/cobbler#2436]
### Version

````paste below
````
Cobbler Version: 2.8.4-4

### Question

Stuck at a problem with /etc/cobbler/pxe/*.template files.
I notice it comes with default files but I was wondering if I can add my own templates and use them in profiles, for ex:

Profile:
lrh7v7-x86_64
Templates:
/etc/cobbler/pxe/pxeprofile_my.template
/etc/cobbler/pxe/pxesystem_my.template

Any help will be appreciated.

Regards
-danish

**Comment by SchoolGuy** [comment]
Yes of course you can do that. Only remember to use them then in the appropriate places. It is also possible to modify the existing ones.

**Comment by danishina** [comment]
Hmm in that case Im doing something incorrect.

I created 3 files:
/etc/cobbler/pxe/pxesystem_abc.template
/etc/cobbler/pxe/pxelocal_abc.template
/etc/cobbler/pxe/pxelocal_abc.template

Then I created a new OS profile and under the ‘Management Tab’ leveraging ‘Template files’ I call /etc/cobbler/pxe/pxesystem_abc.template.

When I try to build a system it doesn’t pickup /etc/cobbler/pxe/pxesystem_abc.template instead it picks up /etc/cobbler/pxe/pxesystem.template.
I’ve scanned the distro-profile and system-profile and the ‘Template files’ field is empty.

Please help/guide.

Regards

**Comment by SchoolGuy** [comment]
Okay while I strongly recommend to upgrade Cobbler 3, I will still try to help you.

I took a look at the code we have and discovered that the filename is to my surprise hardcoded. I wasn't aware that we can't override this.  
However this does not stop you from achieving what you want to do! All `.template` files are Cheetah templates, thus you can just put some template code in there and write conditionals in there as much as you like. In the end Cobbler still picks up the same template but it will be what you like to achieve with the separate file.

Sorry for any inconvenience caused through my misinformation. I sadly don't know every line just yet...

The reference for the Cheetah language can be found at: <https://cheetahtemplate.org/>

**Comment by danishina** [comment]
Thank you so much.  I feel better.
Let me poke around on how to modify the .template…
By any chance, do you guys have any reference material for these templates ?

**Comment by SchoolGuy** [comment]
As written in the last line: https://cheetahtemplate.org

**Comment by SchoolGuy** [comment]
So no follow ups there. Thus closing this. Please reopen if more information is required!
