### ISSUE TITLE
logging check fails with SELinux

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#2440]
### Describe the bug

Commits 012bca33af7e0a8f544ee6f4b80ae15176c82590 and 7dafc770b2bf2b035701d66e6083f2f009675e04 attempt to deal with logging in the apache context versus the cobblerd context.  Unfortunately this check:
```
if os.access("/var/log/cobbler/cobbler.log", os.W_OK):
```
is not correct on an SELinux system as the cobblerd_t context does not have write permissions to /var/log/cobbler/cobbler.log, only append.

### To Reproduce

On SELinux enabled system start cobblerd.  Note:
```
audit[1073]: AVC avc:  denied  { write } for  pid=1073 comm="cobblerd" name="cobbler.log" dev="dm-0" ino=663024 scontext=system_u:system_r:cobblerd_t:s0 tcontext=system_u:object_r:cobbler_var_log_t:s0 tclass=file permissive=0
```

At this point since we are already ignoring any exceptions from logging.config.fileConfig(), I propose doing just:
```
# Avoid errors with apache trying to write to log file
# TODO - handle this properly as we currently ignore any errors with cobblerd logging
LOG_FILE = "/var/log/cobbler/cobbler.log"
try:
    logging.config.fileConfig('/etc/cobbler/logging_config.conf')
except Exception:
    pass
```
But we do need to resolve this issue properly.  Though perhaps will just drop out of the splitting of the GUI and backend code in cobbler 3.3?

**Comment by opoplawski** [comment]
@watologo1 can you point me to where any cobbler code running as apache would try to do logging?  i.e. what triggered this issue in the first place?

**Comment by opoplawski** [comment]
> @watologo1 can you point me to where any cobbler code running as apache would try to do logging? i.e. what triggered this issue in the first place?

Never mind - I found it after restarting apache and checking the apache error log.

**Comment by SchoolGuy** [comment]
We merged the PR. Thus closing this one as it will drop out with Cobbler 3.3 possibly anyway.

**Comment by SchoolGuy** [comment]
Please reopen if I did close this too early.
