### ISSUE TITLE
How to get ID of exsiting system in API?

### ISSUE THREAD

**Issue by Alex-Souslik** [cobbler/cobbler#2470]
### Version

````paste below
````
Cobbler 3.2.0
    source: ?, ?
    build time: Sun Nov  1 09:04:03 2020
### Question
I know that when creating a system through the  XMLRPC API the ID is returned, but suppose I want to modify a system I created earlier and I didn't save the ID. how can I get it through the API?

**Comment by SchoolGuy** [comment]
You have in the API the `find_<object_type>()` methods. Via these methods you can easily find any system or item in Cobbler you previously created. Please see for reference: https://cobbler.readthedocs.io/en/latest/code-autodoc/cobbler.html#cobbler.api.CobblerAPI.find_system

**Comment by SchoolGuy** [comment]
If you find that the docs are not extensive enough about this please state so. We are reliant on user feedback in regards to our docs. Many of us developers don't have access to a "demo" or "production" setup which is pure Cobbler. Thus we don't use it except some fake test or dev cases.

**Comment by Alex-Souslik** [comment]
> You have in the API the `find_<object_type>()` methods. Via these methods you can easily find any system or item in Cobbler you previously created. Please see for reference: https://cobbler.readthedocs.io/en/latest/code-autodoc/cobbler.html#cobbler.api.CobblerAPI.find_system

I'm aware but to my knowledge, correct me if I'm wrong, the system object returned from `find_system()` doesn't include the id which is required for `modify_system()` and as such doesn't help me.

**Comment by SchoolGuy** [comment]
For that you have the `get_<object_type>_handle()` - https://cobbler.readthedocs.io/en/latest/code-autodoc/cobbler.html#cobbler.remote.CobblerXMLRPCInterface.get_system_handle

**Comment by Alex-Souslik** [comment]
> For that you have the `get_<object_type>_handle()` - https://cobbler.readthedocs.io/en/latest/code-autodoc/cobbler.html#cobbler.remote.CobblerXMLRPCInterface.get_system_handle
Thank you very much!
