### ISSUE TITLE
Doc not align with command arguments

### ISSUE THREAD

**Issue by xenlo** [cobbler/cobbler#2473]
### Describe the bug

The man pages and the [cobbler doc](https://cobbler.readthedocs.io/en/latest/cobbler.html) are not in line with the `cobbler` command and arguments.

Here is table comparing attributes documented and those accepted by the command `cobbler` to add/edit a profile:
| cmd args | Doc |
| --- | --- |
| --autoinstall | autoinst |
| --autoinstall-meta |  |
| --boot-files |  |
| --comment |  |
| --ctime |  |
| --depth |  |
| --dhcp-tag |  |
| --distro | distro |
| --enable-gpxe |  |
| --enable-menu |  |
| --fetchable-files |  |
| --help |  |
| --in-place |  |
| --kernel-options |  |
| --kernel-options-post |  |
| --mgmt-classes |  |
| --mgmt-parameters |  |
| --mtime |  |
| --name | name |
| --name-servers | name-servers |
| --name-servers-search | name-servers-search |
| --next-server |  |
| --owners |  |
| --parent | parent |
| --proxy |  |
| --redhat-management-key |  |
| --repos | repos |
| --server | server |
| --template-files |  |
| --uid |  |
| --virt-auto-boot |  |
| --virt-bridge | virt-bridge |
| --virt-cpus | virt-cpus |
| --virt-disk-driver |  |
| --virt-file-size | virt-file-size |
| --virt-path | virt-path |
| --virt-ram | virt-ram |
| --virt-type | virt-type |
|  | filename |

### Expected behavior

Obviously that Doc matching command.

### Version

````paste below
cobbler4:~ # cobbler version
Cobbler 3.1.2
  source: ?, ?
  build time: Fri Nov 13 12:00:00 2020
````

**Comment by SchoolGuy** [comment]
@xenlo Since it would be good to have this in the next release. Thus I will wait to make it until we have merged your PR.
