### ISSUE TITLE
cobbler centos7 docker build not working

### ISSUE THREAD

**Issue by teridon** [cobbler/cobbler#2515]
### Describe the bug

Building cobbler via docker on centos7.9.2003 is not working

### To Reproduce

1. git clone cobbler repo
2. git checkout release32
3. sudo ./tests/build-and-install-rpms.sh el7 dockerfiles/CentOS7.dockerfile

Near the end of the build process (step 8 of Dockerfile), I get:

```
[...]
Removing intermediate container ed12d9271df0
Step 8/8 : CMD /bin/bash -c make rpms
 ---> Running in f06b21e49c37
 ---> cda04890ba22
Removing intermediate container f06b21e49c37
Successfully built cda04890ba22
==> Build RPMs ...
[...]
removing build/bdist.linux-x86_64/wheel
creating: release artifacts
mkdir -p rpm-build
cp dist/*.gz rpm-build/
cp: cannot create regular file 'rpm-build/cobbler-3.2.0.tar.gz': Permission denied
```

I'm using the Centos-provided docker, docker-1.13.1-203.git0be3e21.el7.centos.x86_64

**Comment by SchoolGuy** [comment]
@teridon What are your permissions on the host folder you mounted for that build? Because my guess would be that you have a problem there.

**Comment by teridon** [comment]
This appears to be a docker/SELinux issue (I have SElinux in enforcing mode); the test script needs to add ":Z" to the mount:
````
docker run -ti -v "$PWD/rpm-build:/usr/src/cobbler/rpm-build:Z" "$IMAGE"
````
when I added ":Z" as above, the RPMs were built successfully. 

see http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/ 

Unfortunately, while using ":Z" fixes the RPM build, there are other issues caused by SELinux later with the privileged container .  For now I will just build with SELinux in permissive mode.  Ideally one should be able to build cobbler with SELinux in enforcing mode.

**Comment by SchoolGuy** [comment]
@teridon I will relabel this issue as a feature request and adjust accordingly. I have no history eoth SELinux. Thus this will probably not be done before 4.0 because that will be the first actual release where Cobbler will run inside a Container and we will support this use case.

**Comment by SchoolGuy** [comment]
Okay so CentOS 7 is from the table because it has no full Python3 Support (we have missing dependencies). Thus we won't provide packages. We have very little manpower and thankfully Python3 makes our life much easier. However I won't close this but try to fix this on CentOS 8 because I guess we will have the same problem there.

**Comment by SchoolGuy** [comment]
Okay. Update on this one: Since we have dependencies not available for CentOS 7 this won't be supported anymore. BUT I will update for the next release instead the docs on how to make it work without using the RPMs so you guys can continue to use it.

**Comment by SchoolGuy** [comment]
Since there is no further response and I don't plan on supporting CentOS 7 (no full Python 3 stack), I will close this issue. If this is relevant, pls reopen.
