### ISSUE TITLE
Web Interface - Snippet save path is wrong 

### ISSUE THREAD

**Issue by asimat** [cobbler/cobbler#2520]
### Describe the bug

When you try to save a snippet using web interface it saves it to: /var/lib/cobbler/snippets/var/lib/cobbler/snippets/

Instead of /var/lib/cobbler/snippets/

If you list snippets in webinterface it then shows the path and full filename e.g. var/lib/cobbler/snippets/test instead of just test

### To Reproduce

1. Go to: Web interface >> snippets'
2. Click on : Create New Automatic Installation Snippet

### Version

Cobbler 3.2

### Additional context

Other things like creating new template etc work fine.

If you could mention which file is responsible for saving snippets, then I am happy to have look and do a quick fix myself.

---General Feedback---
I know web interface is being dropped - so I would recommend releasing 3.2.1, which covers/fixes all minor bugs. My IT teams will not be able to work without a web interface as its a big time saver, so I don't mind sticking with a working version (3.2/3.2.1) for few months or even a year. As all companies will need UEFI PXE boot - so I would probably need to upgrade them all to cobbler 3.2 or 3.2.1 this year. 
 
I have introduced Cobbler to about 10 post production companies in last 6 years or so, so am a big fan of using cobbler. I am finding too many bugs in 3.2 (Took me 1 week+ to get v3.2 to usable level, but still finding more small bugs). Lost too much sleep on this !

**Comment by SchoolGuy** [comment]
@asimat I regret that you experience so many bugs but Cobbler was dead for a long time and I am trying to revive it. I am getting rid of more and more tech-debt. The Web Interface with Django (which will be droped with 3.3.0) has shaped Cobbler in a way that I can't introduce anything new or refactor things. This is one reason why I decided to decouple the Web UI your fixes will definitely get into 3.2.1 and I am willing to accept fixes for the old WebUI after 3.3.0 (meaning they go directly to the release32 branch and we will release 3.2.X). But the active work which will be carried out will go in the direction of 4.0.0 which will have full Container support. My plan is to release version 1.0 for the new WebUI on par with 3.3.0 to have a guaranteed feature loss transition. Many thanks however for contributing and raising the Bugs!

**Comment by asimat** [comment]
Good plan. Looking forward to the new versions.

Can you give me a hint which file has the snipper save path ?

**Comment by SchoolGuy** [comment]
@asimat Grep the code for `autoinstall_snippets_dir`. This gives you an entry point for this problem most probably.

**Comment by javier-angulo** [comment]
I believe this was fixed on #2485 
I can reproduce the error on 3.2.0 (but not in master).

**Comment by SchoolGuy** [comment]
@javier-angulo Okay then let's close this.
