### ISSUE TITLE
Deleting a system (or any object) may not persist across cobbler restarts

### ISSUE THREAD

**Issue by krehm** [cobbler/cobbler#2529]
Problem is seen in 

```
Cobbler 3.1.2
  source: ?, ?
  build time: Sun May 31 02:32:34 2020
```

This bug was actually fixed via commit 63d8312bac0bc4a1567d7e511beddfa89f4e1562 in December 2020.  File modules/serializers/file.py functions serialize_item() and serialize_delete() were appending the string ".json" to the filename twice.    Rather than trying to delete file "object.json", serialize_delete() would try to delete "object.json.json" which didn't exist, and so the code did nothing.  After a cobbler restart, the "object.json" file would be seen and the object re-appeared in cobbler.   In this case the object was created before the last cobbler upgrade, so it has the "object.json" filename format, it didn't have the ".json.json" suffix.  Objects created after the last cobbler upgrade all have the ".json.json" suffix, there is no "object.json" file.

The duplication was removed, but this leaves existing sites with a mess in their collections subdirectories.  Depending upon when they created objects relative to when they last upgraded cobbler, they can have files with name "object.json", "object.json.json", or both files can exist simultaneously.

Seems like there should be some code added to detect this situation, and rename the "object.json.json" files back to their appropriate "object.json" names.

**Comment by SchoolGuy** [comment]
Okay I agree that we need code to fix that automatically. Or at least document this more extensively.

**Comment by SchoolGuy** [comment]
Related PR is https://github.com/cobbler/cobbler/pull/2451

**Comment by SchoolGuy** [comment]
@krehm If you update to 3.2.0, does that error persist? Or is that something you can't do?
