### ISSUE TITLE
Can't build CentOS8 docker image - lack of dependencies

### ISSUE THREAD

**Issue by TerranMan** [cobbler/cobbler#2553]
### Describe the bug

Error:
Problem: conflicting requests
-nothing provides python3.6.dist(contextlib2) >= 0.5.5 needed by python3-schema-0.7.3.-1.el8.noarch

Solution:
Added RUN rpm -Uvh https://ftp.lysator.liu.se/pub/opensuse/tumbleweed/repo/oss/noarch/python36-contextlib2-0.6.0-2.3.noarch.rpm
(for x86-64)
![err](https://user-images.githubusercontent.com/6996410/109127074-0c7c4000-775f-11eb-9dfb-008fc7bd9218.jpg)

**Comment by SchoolGuy** [comment]
Thanks for opening an issue explicitly. We are already aware of it and are working on it.

**Comment by opoplawski** [comment]
contextlib2 is now in EPEL testing - please provide karma here: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-65e082736e

**Comment by dansou901** [comment]
According to your link @opoplawski contextlibs2 is now in stable, can you confirm that? If yes, it should be possible to build a new centos 8 image of cobbler now, correct?

**Comment by SchoolGuy** [comment]
@dansou901 Latest build on `master` has not yet received that from an hour ago.

**Comment by SchoolGuy** [comment]
As of https://github.com/cobbler/cobbler/runs/2033887369 we are successful again. Thanks a lot @opoplawski ! This is great news! And even on point for the new release I will be shipping later in the evening!
