### ISSUE TITLE
CI will fail on master due to missing automatic version increase

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2566]
### Describe the bug

Currently we are having a hardcoded version in `setup.py` this needs to change to make versioning more dynamic to the CI.

### To Reproduce

1. Look at `setup.py` and our Github workflow.

### Expected behavior

The CI pushes with every new `master` commit a new version to the Test PyPi.

### Version

````paste below
master
````

**Comment by nodeg** [comment]
@SchoolGuy and I decided that we will use nightly builds as used in [Tensorflow](https://github.com/tensorflow/tensorflow/blob/master/.github/workflows/update-nightly.yml).
