### ISSUE TITLE
[feat] Move from the deprecated optparse to argparse (CLI)

### ISSUE THREAD

**Issue by nodeg** [cobbler/cobbler#2574]
### Is your feature request related to a problem?

According to the [documentation](https://docs.python.org/3/library/optparse.html), `optparse` is deprecated since Python 3.2. According to [PEP 594](https://www.python.org/dev/peps/pep-0594), however, it will not be removed in the near future since it is so widely used. Nevertheless to make Cobbler more future proof, we should switch to [argparse](https://docs.python.org/3/library/argparse.html).

There is already a [document](https://docs.python.org/3/library/argparse.html#upgrading-optparse-code) which describes the transition from `optparse` to `argparse`.

The following files have to be edited afaik but this has to be confirmed and tested afterwards. I think especially the test cases for the CLI have to be adjusted, as well.

```
cobbler/cli.py
contrib/api-examples/create_snippet.py
contrib/api-examples/demo_connect.py
contrib/api-examples/read_snippet.py
contrib/api-examples/remove_snippet.py
tests/cli/cobbler_cli_direct_test.py
tests/cli/cobbler_cli_object_test.py
```

When #2747 is merged, the following is already taken care of.
```
bin/cobblerd
```

Furthermore we need to look into Cobbler `builtiso` when not supplying any parameter. See https://github.com/cobbler/cobbler/pull/2985

**Comment by michiboo** [comment]
Hi can I help on this issue?

**Comment by SchoolGuy** [comment]
@michiboo Yes of course! Feel free to open a Pull Request! After a short review, we will merge it as soon as reasonable!

**Comment by nodeg** [comment]
@michiboo Any progress on this?

**Comment by michiboo** [comment]
Hi I have been working on it~ but still not finished !

**Comment by nodeg** [comment]
Nice. Thank you for the quick update! If you have any question, do not hesitate to ask.

**Comment by SchoolGuy** [comment]
I will close this issue as we will move to our new golang based CLI for 3.4.0. Thus this work is redundant.
