### ISSUE TITLE
Remove leftover validateks code

### ISSUE THREAD

**Issue by nodeg** [cobbler/cobbler#2579]
`cobbler validateks` was removed in 2009 with https://github.com/cobbler/cobbler/commit/4a18e37b26381b6c85f657f8a3356d4115c2538b. 

We still have some leftovers in our code which can safely be removed.

```
$ grep -rin "validateks" .     
./config/bash/completion/cobbler:12:    TYPE="distro profile system repo image mgmtclass package file aclsetup buildiso import list replicate report reposync sync validateks version signature hardlink"
./docs/user-guide.rst:275:To check for potential errors in kickstarts, prior to installation, use ``cobbler validateks``. This function will check
./docs/user-guide.rst:277:may be some false positives. It should be noted that ``cobbler validateks`` runs on the rendered kickstart output, not
```

**Comment by SchoolGuy** [comment]
This was fixed through pushing to `main` directly by accident. Thus this was fixed via [30fb320](https://github.com/cobbler/cobbler/commit/30fb320c996a87aa418901921eabd7a271a4c6d7).
