### ISSUE TITLE
[Branding] Add a more distinctive GitHub avatar

### ISSUE THREAD

**Issue by hbokh** [cobbler/cobbler#2604]
In my personal opinion the default Cobbler avatar could (should) be replaced with something more distinctive 
 / distinguishing than the randomly chosen GitHub avatar. This will give a more professional look.

As an example have a look at https://registry.terraform.io/providers/cobbler/cobbler/latest

![Screenshot 2021-03-24 at 08 43 20](https://user-images.githubusercontent.com/519955/112273071-3735b780-8c7d-11eb-9e7f-fc4f13a000a6.png)

I think this looks "ugly" and could be easily improved.

In some ways even a temporary image of a regular emoji like the shoe [👞 ] would do better than what is presented at the moment.
Here's a larger shoe image that could be used instead:

![shoe](https://user-images.githubusercontent.com/519955/112273863-20dc2b80-8c7e-11eb-8efe-0b452f045be3.png)

**Comment by nodeg** [comment]
Thanks for opening this up, @hbokh. @SchoolGuy and I discussed this a couple of weeks ago and he mentioned that there is already someone who is working on a new logo. But I am not sure who it is and where it is developed. @SchoolGuy do you have more information?

**Comment by SchoolGuy** [comment]
I have an appointment with a friend of mine who will maybe help us to design a new logo. Let's see where this goes. I will report back tomorrow.

**Comment by SchoolGuy** [comment]
@hbokh @nodeg I have talked to my friend and she will prepare some things. When she is ready she will post some drafts here. We can then discuss with her all further steps in that regard. It will take a few days however since she is not a wizard. :)

**Comment by mandutzsenta** [comment]
Hello there :)

I made some logo design prototypes. As you might notice they differ... a lot! That's because first we wanted to have a serious logo somehow displaying the use of the tool. The second idea was to have something unique that is recognizable and also contains a pun (cobbler as in the dish). 
Please let me know which one you like best or what changes I should make.

Idea 1:
Version 1:

![logo2](https://user-images.githubusercontent.com/73784108/112753368-a2fa8600-8fd7-11eb-9695-7ae26e4ad459.png)

Version 2:

![logo3](https://user-images.githubusercontent.com/73784108/112753370-a3931c80-8fd7-11eb-83e7-910b204dee92.png)

Idea 2:
Version 1:

![logo4](https://user-images.githubusercontent.com/73784108/112753371-a3931c80-8fd7-11eb-8516-b20f783d42a1.png)

Version 2:

![logo5](https://user-images.githubusercontent.com/73784108/112753366-a261ef80-8fd7-11eb-8429-febe69b69fb9.png)

**Comment by SchoolGuy** [comment]
So I would vote for idea 2, version 1 since this can be used as an icon and is easily recognizable. But I will leave it up to the community to decide which way we do want to go.

**Comment by dansou901** [comment]
I do like idea 2, version 1 as well. But I have a suggestion: is it possible to have the top of the "cobbler" a bit less flat and more bumpy? Or is that too much?

**Comment by hbokh** [comment]
👍🏻
Personally I prefer idea 1, because I fail to see what a pie / cake has to do with Cobbler. 😇
Looks like the one with the tools fits best in a square icon spacing.

**Comment by nodeg** [comment]
My favourite is idea 2, version 1, too since it looks really cute and delicious. Like @hbokh I did not know that a Cobbler is also something to eat, so now that I know that, I feel reassured about my decision according to instinct / my gut.

**Comment by Conan-Kudo** [comment]
I like idea 2, version 1 as well. 😉

**Comment by SchoolGuy** [comment]
So as an intermediate summary:

- Idea 1 (unspecified version): @hbokh 
- Idea 2 - version 1: @Conan-Kudo @nodeg @dansou901 @SchoolGuy 

I think I'll let the vote go on a little while in case someone comes around. The issue is pinned so everyone should see it.

**Comment by hbokh** [comment]
Let me quote a co-worker of me:
_I wouldn't associate Cobbler with being "a piece of cake"._
😇

**Comment by SchoolGuy** [comment]
@hbokh That quote makes me even more want to use the cake because it should be one day...

P.S.: Not the right issue but could you possibly interview him and collect his pain points in a GH Discussion please? I would really like to make it easier...

**Comment by hbokh** [comment]
> P.S.: Not the right issue but could you possibly interview him and collect his pain points in a GH Discussion please? I would really like to make it easier...

I consider it as a tongue-in-cheek kind of joke. No need for an inquisition. 🕵🏻‍♂️

**Comment by hbokh** [comment]
FYI @mandutzsenta the cake is not going to fit as an avatar with the current (rectangle) dimensions:

![Screenshot 2021-04-03 at 13 07 32](https://user-images.githubusercontent.com/519955/113476734-982f6d80-947d-11eb-9bee-69590f17c375.png)

**Comment by nodeg** [comment]
Furthermore we need a dark version for dark themes.

**Comment by SchoolGuy** [comment]
Since we did not get more votes in the last days I consider the final results this:

>     * Idea 1 (unspecified version): @hbokh
>     * Idea 2 - version 1: @Conan-Kudo @nodeg @dansou901 @SchoolGuy

**Comment by SchoolGuy** [comment]
Just a quick update. I am working on my final papers and exams of my apprenticeship. On the 5th of May this will be done. I have a lot in the queue but after that I will continue to work on this. It is not forgotten!

**Comment by SchoolGuy** [comment]
Just a quick update. I am working on my final papers and exams of my apprenticeship. On the 5th of May this will be done. I have a lot in the queue but after that I will continue to work on this. It is not forgotten!

**Comment by SchoolGuy** [comment]
This is done as of now. PR https://github.com/cobbler/cobbler.github.io/pull/165 will work on implementing this on our website.
