### ISSUE TITLE
Cannot toggle iPXE support via cobbler CLI tool

### ISSUE THREAD

**Issue by heroin-moose** [cobbler/cobbler#2674]
### Describe the bug

It's not possible to toggle iPXE support, the API responds with a type check error:

```
# cobbler profile edit --name foobar --enable-ipxe 1
exception on server: enable_ipxe needs to be of type bool
```

### Steps to reproduce

1. Build fresh RPMs from master
2. Create a distro
3. Create a profile for that distro
4. Run `cobbler profile edit`

### Expected behavior

The given command should not fail.

### Cobbler version

````paste below
# cobbler version
Cobbler 3.2.1
  source: ?, ?
  build time: Mon Jun 21 17:54:49 2021
````

### Operating system

CentOS 8.

### Cobbler log

````paste below
[Thread-5] 2021-06-22T08:44:16 - INFO | Exception occurred: <class 'TypeError'>
[Thread-5] 2021-06-22T08:44:16 - INFO | Exception value: enable_ipxe needs to be of type bool
[Thread-5] 2021-06-22T08:44:16 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3505, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1938, in xapi_object_edit
    self.modify_item(object_type, handle, key, value, token)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1696, in modify_item
    setattr(obj, attribute, arg)

  File "/usr/lib/python3.6/site-packages/cobbler/items/profile.py", line 285, in enable_ipxe
    raise TypeError("enable_ipxe needs to be of type bool")
````

**Comment by SchoolGuy** [comment]
The problem is that the value on the CLI is always a str. Currently we need to convert it with the `utils` method. Sadly we can't do that in the CLI since we can't distinguish that there. Thus we need to do it in the model. This is affecting all boolean attributes.
