### ISSUE TITLE
New systems have two identical interfaces

### ISSUE THREAD

**Issue by heroin-moose** [cobbler/cobbler#2681]
### Describe the bug

Running `cobbler system add --name new --profile foobar --mac 11:22:33:44:55:66`
creates a system with two identical interfaces:

```
$ cobbler system add --name new --profile foobar --mac 11:22:33:44:55:66
$ cobbler system report --name new | grep -E '^(Interface =====|MAC Address)'
Interface =====                : default
MAC Address                    : 11:22:33:44:55:66
Interface =====                : None
MAC Address                    : 11:22:33:44:55:66
```

### Steps to reproduce

1. Create a new system via `cobbler system add`

### Expected behavior

There should be only one interface instead of two.

### Cobbler version

````paste below
Cobbler 3.2.1
  source: ?, ?
  build time: Tue Jun 22 15:41:34 2021
````

### Operating system

CentOS 8.

### Cobbler log

````paste below
[Thread-154] 2021-06-22T21:37:57 - INFO | REMOTE get_settings; user(?)
[Thread-155] 2021-06-22T21:37:57 - INFO | REMOTE get_item(system,new); user(?)
[Thread-155] 2021-06-22T21:37:57 - DEBUG | get_item; ['system', 'new']
[Thread-155] 2021-06-22T21:37:57 - DEBUG | done with get_item; ['system', 'new']
[Thread-159] 2021-06-22T21:39:49 - INFO | REMOTE version; user(?)
````

**Comment by SchoolGuy** [comment]
This can in my eyes not happen but since it does anyway, I believe that this is happening somewhere in `xapi_object_edit` in the Lines 1950 and 1966. I will try to debug.

**Comment by heroin-moose** [comment]
Fixed in master, closing?
