### ISSUE TITLE
[feat] Trigger /etc/dhcpd.conf update when changing iPXE attribute

### ISSUE THREAD

**Issue by heroin-moose** [cobbler/cobbler#2689]
### Describe the bug

Without manual `cobbler sync` toggling iPXE attribute does not trigger /etc/dhcpd.conf update.

### Steps to reproduce

1. Create a distro, a profile and a system with "pxe" bootloader
2. Run `cobbler system edit --name test --netboot-enabled 1 --enable-ipxe 1`
3. Check /etc/dhcpd.conf
4. Run `cobbler sync`
5. Check /etc/dhcpd.conf again

### Expected behavior

Each time the attribute is changed /etc/dhcpd.conf should be modified accordingly.

### Cobbler version

````paste below
Cobbler 3.2.1
  source: ?, ?
  build time: Wed Jun 23 12:53:14 2021
````

### Operating system

CentOS 8.

### Cobbler log

Nothing relevant.

**Comment by SchoolGuy** [comment]
This we can achieve through adding logic to:

https://github.com/cobbler/cobbler/blob/bb089ad80021ff765fb02dc08933b1fb54ac540f/cobbler/items/profile.py#L277-L287

and

https://github.com/cobbler/cobbler/blob/bb089ad80021ff765fb02dc08933b1fb54ac540f/cobbler/items/system.py#L1253-L1261

**Comment by SchoolGuy** [comment]
I know how and where to fix this. I will implement this tomorrow at work.

**Comment by nodeg** [comment]
This is no regression but a feature request. Changing the label.

**Comment by SchoolGuy** [comment]
Okay I found additional problem related to this topic. Will investigate. They are related to writing the `dhcpd.conf` file.

**Comment by SchoolGuy** [comment]
And I found more bugs. We are using in the dhcp and dns managers still the old notation. I will port and test that along with the (not yet existing) PR because otherwise the functionality is unusable.

**Comment by SchoolGuy** [comment]
Okay so my initial approach of using the properties does not work since there are cases where the items are not present on the server side and thus a direct update in the property is not possible. I will instead try to modify the `add()` method in the collection because it is triggered every time an item is modified in theory.

**Comment by SchoolGuy** [comment]
Okay... In case we start dhcpd for the first time we run into trouble because `/var/state/dhcp/dhcpd.leases` may not exist.

**Comment by SchoolGuy** [comment]
The problem with the leases file is specific to the environment. Thus this is solved via our development docker container. Since `cobbler sync` is now working, we can start debugging this.
