### ISSUE TITLE
Add indicators for grub distro level menus

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2693]
### Is your feature request related to a problem?

This issue is related to https://github.com/cobbler/cobbler/pull/2217

Currently Grub does not indicate that the menu structure contains submenus. Thus we desire that because not everyone knows that we are using submenus now.

### Provide a detailed description of the proposed feature

An indicator in the menu which shows that this is not a boot entry.

### Alternatives you've considered

- Letting users discover that for themselves: Well not user friendly
- Reverting the change: Not good as well since this can cause a lot of overhead in the boot menu.

### Additional information

Internal Bug for SUSE Employees: https://github.com/SUSE/spacewalk/issues/15241

**Comment by SchoolGuy** [comment]
This was refactored with https://github.com/cobbler/cobbler/pull/2575 so sadly the easy way we had then doesn't work. I will investigate deeper.

**Comment by SchoolGuy** [comment]
This feature request was raised against Cobbler version 3.1.2 since that is was SUMA uses atm. Since the refactoring by @tpw56j was done, I need to reproduce that on `master` now.

@tpw56j do you have an idea how to add an indicator. I saw your code and was wondering where the most top level menu is generated for all loaders? In `make_pxe_menu` maybe but I am not sure right now.

**Comment by SchoolGuy** [comment]
As written in #2684 I found that the children list has invalid entries and thus i need to dive deeper there first.

**Comment by tpw56j** [comment]
@SchoolGuy I will try to remember how the menu is formed, and maybe I will have ideas.

**Comment by SchoolGuy** [comment]
@tpw56j If not, I will dive into the code deep myself, please just give me ping in any of both cases. :)

**Comment by tpw56j** [comment]
@SchoolGuy I'm very busy right now and will only be able to do this at the end of the week.:(

**Comment by SchoolGuy** [comment]
@tpw56j That is totally fine. Don't feel bad about it. If you look at the end of the week and update if you took a look or not that is enough. If it is closed by then you just know that I now understand your code... ;)

**Comment by tpw56j** [comment]
@SchoolGuy Maybe this problem can be solved by changing the submenu templates?

For example by adding the '>' symbol  in front of $menu_name to `cobbler/templates/boot_loader_conf/grub_submenu.template`:
submenu '>$menu_name' --class gnu-linux --class gnu --class os {
$menu_items
}

**Comment by heroin-moose** [comment]
Currently I cannot find any grub menus at all in master. There is an iPXE menu (ipxe/default.ipxe), a PXELINUX menu (pxeconfig.cfg/default), but there is no Grub menu at all. Only per-system records.

**Comment by SchoolGuy** [comment]
@tpw56j Thanks for the suggestion. I will try to apply and check it tomorrow!
