### ISSUE TITLE
Almalinux 8.4: `cobblerd` not starting

### ISSUE THREAD

**Issue by ds-04** [cobbler/cobbler#2749]
### Describe the bug

A fix is needed to api.py to allow cobblerd to start on Almalinux 8.4

Temporary hack to make server work (line98 of api.py):

`old: self.dist, self.os_version = utils.os_release()`

`new: self.dist, self.os_version = 'centos', 8.4`

### Steps to reproduce

1. Install cobbler on Almalinux 8.4
2. Try to start cobblerd

### Expected behavior

cobblerd should start

### Cobbler version

````
cobbler.noarch                                                      3.2.0-2.module_el8+10474+71f42bad
````

### Operating system

AlmaLinux release 8.4 (Electric Cheetah)

**Comment by nodeg** [comment]
In master this is already fixed and I successfully imported Alma Linux in a VM. See

https://github.com/cobbler/cobbler/blob/9c454558bb1bb0da29a3af5580ec28ded83a8574/cobbler/utils.py#L964-L965

https://github.com/cobbler/cobbler/blob/9c454558bb1bb0da29a3af5580ec28ded83a8574/cobbler/utils.py#L978-L1003

**Comment by ds-04** [comment]
From journalctl (with 3.2.0 version of api.py and uitls.py), can't see anything relevant in cobbler.log

> Aug 11 08:38:56 cobblerd[26836]: Traceback (most recent call last):
> Aug 11 08:38:56 cobblerd[26836]:   File "/usr/bin/cobblerd", line 75, in main
> Aug 11 08:38:56 cobblerd[26836]:     api = cobbler_api.CobblerAPI(is_cobblerd=True)
> Aug 11 08:38:56 cobblerd[26836]:   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 98, in __init__
> Aug 11 08:38:56 cobblerd[26836]:     self.dist, self.os_version = utils.os_release()
> Aug 11 08:38:56 cobblerd[26836]: TypeError: 'NoneType' object is not iterable

**Comment by ds-04** [comment]
thanks for clarity I'm using this install method on Almalinux 8.4

`dnf -y install epel-release`
`dnf -y module enable cobbler`
`dnf -y install cobbler`

_cobbler-web_ also installed using dnf option --_allowerasing_ (for python-django)

**Comment by zparihar** [comment]
Hey folks, 

I've setup AlmaLinux 8.4 and trying to install Cobbler and get Cobbler working.  I've followed the suggestions above, however, when running a 'cobbler sync' i'm running into the following problem:

> $  cobbler sync
> task started: 2021-08-31_202342_sync
> task started (id=Sync, time=Tue Aug 31 20:23:42 2021)
> running python triggers from /var/lib/cobbler/triggers/task/sync/pre/*
> running shell triggers from /var/lib/cobbler/triggers/task/sync/pre/*
> shell triggers finished successfully
> Exception occured: <class 'TypeError'>
> Exception value: 'NoneType' object is not iterable
> Exception Info:
>   File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 98, in run
>     rc = self._run(self)
> 
>   File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 227, in runner
>     self.remote.api.sync(self.options.get("verbose", False), logger=self.logger)
> 
>   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1314, in sync
>     sync = self.get_sync(verbose=verbose, logger=logger)
> 
>   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1343, in get_sync
>     ).get_manager(self._collection_mgr, logger)
> 
>   File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/isc.py", line 268, in get_manager
>     return IscManager(collection_mgr, logger)
> 
>   File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/isc.py", line 69, in __init__
>     self.settings_file = utils.dhcpconf_location(self.api)
> 
>   File "/usr/lib/python3.6/site-packages/cobbler/utils.py", line 2441, in dhcpconf_location
>     """
> 
> !!! TASK FAILED !!!

I installed Cobbler the same as the method above by @ds-04 :

> dnf -y install epel-release
> dnf -y module enable cobbler
> dnf -y install cobbler


I saw @nodeg comment about the files: 
- cobbler/cobbler/utils.py

>  redhat_list = ("red hat", "redhat", "scientific linux", "fedora", "centos", "virtuozzo", "almalinux", 
>                 "rocky linux", "oracle linux server")

 

and

 def os_release(): 
     """ 
     Get the os version of the linux distro. If the get_family() method succeeds then the result is normalized. 
  

>      :return: The os-name and os version. 
>      """ 
>      family = get_family() 
>      distro_name = distro.name().lower() 
>      distro_version = distro.version() 
>      if family == "redhat": 
>          if "fedora" in distro_name: 
>              make = "fedora" 
>          elif "centos" in distro_name: 
>              make = "centos" 
>          elif "almalinux" in distro_name: 
>              make = "centos" 
>          elif "rocky linux" in distro_name: 
>              make = "centos" 
>          elif "virtuozzo" in distro_name: 
>              make = "virtuozzo" 
>          elif "oracle linux server" in distro_name: 
>              make = "centos" 
>          else: 
>              make = "redhat" 
>          return make, float(distro_version) 


I also took @ds-04  suggestions for modifying /usr/lib/python3.6/site-packages/cobbler/api.py

> old: self.dist, self.os_version = utils.os_release()
> to
> new: self.dist, self.os_version = 'centos', 8.4

CobblerD starts, just 'cobbler sync' is returning the error stated above (Exception value: 'NoneType' object is not iterable) 

> $ cat /etc/redhat-release 
> AlmaLinux release 8.4 (Electric Cheetah)
> $ rpm -qa | grep cobbler
> cobbler-3.2.0-2.module_el8+10474+71f42bad.noarch

Help would be greatly appreciated!

**Comment by ds-04** [comment]
Did you install the dependencies needed by cobbler? It might just be that. 

I use an ansible role to do so.

**Comment by zparihar** [comment]
Just to let everyone know, I resolved the problem.

I actually left 'api.py' in its default state, and implemented the following change in 'utils.py'

```
def get_family():
    """
    Get family of running operating system.

    Family is the base Linux distribution of a Linux distribution, with a set of common parents.

    :return: May be "redhat", "debian" or "suse" currently. If none of these are detected then just the distro name is
             returned.
    :rtype: str
    """
    # TODO: Refactor that this is purely reliant on the distro module or obsolete it.
    #redhat_list = ("red hat", "redhat", "scientific linux", "fedora", "centos", "virtuozzo")
    redhat_list = ("red hat", "redhat", "scientific linux", "fedora", "centos", "virtuozzo", "almalinux",
                   "rocky linux", "oracle linux server")


    distro_name = distro.name().lower()
    for item in redhat_list:
        if item in distro_name:
            return "redhat"
    if "debian" in distro_name or "ubuntu" in distro_name:
        return "debian"
    if "suse" in distro.like():
        return "suse"
    return distro_name


def os_release():
    """
    Get the os version of the linux distro. If the get_family() method succeeds then the result is normalized.

    :return: The os-name and os version.
    """
    family = get_family()
    distro_name = distro.name().lower()
    distro_version = distro.version()
    if family == "redhat":
        if "fedora" in distro_name:
            make = "fedora"
        elif "centos" in distro_name:
            make = "centos"
        elif "almalinux" in distro_name:
            make = "centos"
        elif "rocky linux" in distro_name:
            make = "centos"
        elif "virtuozzo" in distro_name:
            make = "virtuozzo"
        elif "oracle linux server" in distro_name:
            make = "centos"
        else:
            make = "redhat"
        return make, float(distro_version)

    elif family == "debian":
        if "debian" in distro_name:
            return "debian", float(distro_version)
        elif "ubuntu" in distro_name:
            return "ubuntu", float(distro_version)

    elif family == "suse":
        make = "suse"
        if "suse" not in distro.like():
            make = "unknown"
        return make, float(distro_version)
```

I think its safe to say we can close this ticket.

Cheers,

Zubin.

**Comment by SchoolGuy** [comment]
@zparihar Could you sent a PR for this so we can incorporate it in `master`? If we get it in before the 20th, then it will make it to the next release.

**Comment by ds-04** [comment]
@SchoolGuy see @nodeg comments above (11th August). It's just that the EPEL RPM Alma pulls down for 3.2.0 needs this hack/fix to get running on Alma.

**Comment by SchoolGuy** [comment]
Okay then I will close this issue. Thanks everyone for helping out!
