### ISSUE TITLE
Null setting for proxy_url_ext is not allowed by reposync.

### ISSUE THREAD

**Issue by mwaldron104** [cobbler/cobbler#2754]
### Describe the bug

We don't need to use a proxy server to mirror repos, so our setting for proxy_url_ext is "". After upgrading to cobbler 3.2.1, we get an error when running reposync,  
```
Error parsing config: Error parsing "proxy = ''": URL must be http, ftp, https, socks4, socks4a, socks5 or socks5h not "" 
```

### Steps to reproduce

1. cobbler reposync
2.
3.

### Cobbler version

```Cobbler 3.2.1
  source: ?, ?
  build time: Wed Jun 23 20:49:28 2021
````

### Cobbler log

````2021-08-16T11:23:13 - DEBUG | REMOTE CLI Authorized; user(?)
2021-08-16T11:23:13 - INFO | REMOTE start_task(Reposync); event_id(2021-08-16_112313_reposync); user(?)
2021-08-16T11:23:14 - INFO | reposync; ['turbovnc']

````

**Comment by mwaldron104** [comment]
Sorry, description got lost somehow.
After updating to cobbler 3.2.1, cobbler reposync returns an error:
Error parsing config: Error parsing "proxy = ''": URL must be http, ftp, https, socks4, socks4a, socks5 or socks5h not ""

Our environment doesn't use a proxy server to be able to mirror repos, so we've never had to set the proxy_url_ext setting.

**Comment by nodeg** [comment]
I edited your post to include the description. What operating system do you use? How did you install Cobbler? You can provide those missing information in your first post by editing it.

**Comment by mwaldron104** [comment]
Was using OS RHEL 7.9 and compiled Cobbler rpms from the 3.2.1 source. I have since switched to RHEL 8.4 and installed the cobbler 3.2.0 rpms available in the EPEL repo, and the problem has gone away. So I'll close this issue.

Thanks.

**Comment by SchoolGuy** [comment]
If this is present in 3.2.1 but not in 3.2.0 it is active and we need to fix it.

**Comment by opoplawski** [comment]
I can't reproduce this with recent 3.2 branch.
