### ISSUE TITLE
Wrong bind config for Debian

### ISSUE THREAD

**Issue by nodeg** [cobbler/cobbler#2765]
### Describe the bug

We use the wrong bind path in our settings.py:

```python
def autodetect_bind_chroot():
    """
    Autodetect bind chroot configuration
    """
    bind_config_filename = None
    if os.path.exists("/etc/sysconfig/named"):
        # RHEL/Fedora
        bind_config_filename = "/etc/sysconfig/named"
    else:
        # Debian
        bind_config_files = glob.glob("/etc/default/bind*")
        for filename in bind_config_files:
            if os.path.exists(filename):
                bind_config_filename = filename
    # Parse the config file if available
    if bind_config_filename:
        parse_bind_config(bind_config_filename)

```
The correct path according to the Debian wiki is `/etc/bind/`. Thanks @agraul!
Furthermore we should us the OS detection instead of checking if certain files exist.

### Expected behavior

The correct path should be used.

### Cobbler version

Git master.

### Additional information

https://wiki.debian.org/Bind9#Configuration

**Comment by SchoolGuy** [comment]
This is a candidate for our pre-build shellscript because we can once at buildtime define the location and don't execute the check on every restart of Cobbler. After all the code currently in place is just thought for a reasonable default.
