### ISSUE TITLE
pxe_just_once no longer working with 3.2.1

### ISSUE THREAD

**Issue by lucap22** [cobbler/cobbler#2783]
### Describe the bug

I have upgraded cobbler from 3.2.0 to 3.2.1 and pxe_just_once option no longer working, after the installation completes successfully the "Netboot Enabled" is still set to "True", I have correcty migrate settings file to new file format with .yaml extension.
After some checks i found the issue in the autoinstall_done snippet where the pxe_just_once check are done with "true" lowercase while $pxe_just_once variable contains the string "True" with T in Uppercase.
I have applyed a workaround below reported.

```
cobbler system report  --name=xxx  | grep -i Netboo
Netboot Enabled                : True
```

```
/etc/cobbler/settings.yaml
pxe_just_once: true
```

```
cobbler system dumpvars --name=xxx
pxe_just_once: True
```

Workaround used:
```
/var/lib/cobbler/snippets/autoinstall_done
    #if $pxe_just_once in [ "1", "true", "yes", "y" ]    --> 
    #if $pxe_just_once in [ "1", "true", "yes", "y", "True" ]
```

### Cobbler version
`Cobbler 3.2.1`

### Operating system
`CentOS Linux release 8.4.2105`

### Other
There are other checks done in this way that maybe it is worth checking:

```
./autoinstall_snippets/autoinstall_done:    #if $pxe_just_once in [ "1", "true", "yes", "y" ]
./autoinstall_snippets/autoinstall_done:    #if $run_install_triggers in [ "1", "true", "yes", "y" ]
./autoinstall_snippets/autoinstall_done:    #if $run_install_triggers in [ "1", "true", "yes", "y" ]
./autoinstall_snippets/autoinstall_start:    #if $run_install_triggers in [ "1", "true", "yes", "y" ]
./autoinstall_snippets/autoinstall_start:    #if $run_install_triggers in [ "1", "true", "yes", "y" ]

```

**Comment by SchoolGuy** [comment]
@lucap22 Thanks for the report. Could you try if the following works too please?

```
#if $pxe_just_once
```

The reason I am asking is because this is a boolean and normally this should not be a `str` anymore. So be careful that the negative case is also working. In Python non empty strings are being evaluated as `True`, so `"False"` would also be `True` (mind the quotation marks I added to mark it as a `str`).

**Comment by lucap22** [comment]
Sure, let me try.

**Comment by lucap22** [comment]
Yes, it works

**Comment by SchoolGuy** [comment]
I'll fix it today and open a PR and look through all other snippets as well.

**Comment by SchoolGuy** [comment]
@lucap22 I created a PR and tried to fix as much as possible. Please leave a comment in the PR if it works or not if you have time to test this again.
