### ISSUE TITLE
[CI] Building Tumbleweed RPMs fails

### ISSUE THREAD

**Issue by nodeg** [cobbler/cobbler#2811]
### Describe the bug

We need to look into the following issue when building the Tumbleweed RPMs in the CI:
```bash
Step 4/11 : RUN zypper dup -y
 ---> Running in 61a6eaabd809
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
The command '/bin/sh -c zypper dup -y' returned a non-zero code: 139
```
I saw this error in 3 pull request.

**Comment by SchoolGuy** [comment]
So I can't reproduce this locally. Thus I need to spam #2810 until I find a solution for the problem...

**Comment by SchoolGuy** [comment]
Okay we can't do anything until https://bugzilla.suse.com/show_bug.cgi?id=1190670 is solved. Kudos to @vogtinator for finding it for me.

**Comment by nodeg** [comment]
Ok. So another glibc 2.34 issue.

**Comment by SchoolGuy** [comment]
Example of the failure: https://github.com/cobbler/cobbler/pull/2810/checks?check_run_id=3742282637#step:3:164

**Comment by SchoolGuy** [comment]
This is fixed in the meantime. Thus we can close it.
