### ISSUE TITLE
"make debs" can't find sphinx, but sphinx is installed with pip

### ISSUE THREAD

**Issue by jringoot** [cobbler/cobbler#2863]
### Describe the bug

"make debs" can't find sphinx, but sphinx is installed with pip

### Steps to reproduce

1.
**make debs**

> cleaning: python bytecode
> cleaning: build artifacts
> cleaning: temp files
> checking: pyflakes /opt/cobbler/cobbler/bin/pyflakes
> checking: pycodestyle
> creating: AUTHORS
> creating: sdist
> Traceback (most recent call last):
>   File "setup.py", line 18, in <module>
>     from sphinx.setup_command import BuildDoc
> ModuleNotFoundError: No module named 'sphinx'
> make: *** [Makefile:86: sdist] Error 1

2.
3.

### Expected behavior

Make debs just generates the debs

### Cobbler version

V3.3.0

````paste below
````
Cobbler is not yet installed

### Operating system

Ubuntu 20.04.3 LTS

### Cobbler log

````paste below
````
no such file, cobbler is not yet installed
### Additional information

sphynx is installed
**python -m pip install --upgrade sphinx**

> Requirement already satisfied: sphinx in /opt/cobbler/cobbler/lib/python3.8/site-packages (4.3.1)
> Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.1.5)
> Requirement already satisfied: sphinxcontrib-qthelp in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.0.3)
> Requirement already satisfied: docutils<0.18,>=0.14 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (0.17.1)
> Requirement already satisfied: imagesize in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.3.0)
> Requirement already satisfied: sphinxcontrib-applehelp in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.0.2)
> Requirement already satisfied: requests>=2.5.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.26.0)
> Requirement already satisfied: Jinja2>=2.3 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (3.0.3)
> Requirement already satisfied: sphinxcontrib-devhelp in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.0.2)
> Requirement already satisfied: snowballstemmer>=1.1 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.2.0)
> Requirement already satisfied: babel>=1.3 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.9.1)
> Requirement already satisfied: sphinxcontrib-jsmath in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.0.1)
> Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.0.0)
> Requirement already satisfied: Pygments>=2.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.10.0)
> Requirement already satisfied: alabaster<0.8,>=0.7 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (0.7.12)
> Requirement already satisfied: setuptools in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (44.0.0)
> Requirement already satisfied: packaging in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (21.3)
> Requirement already satisfied: pytz>=2015.7 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from babel>=1.3->sphinx) (2021.3)
> Requirement already satisfied: MarkupSafe>=2.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from Jinja2>=2.3->sphinx) (2.0.1)
> Requirement already satisfied: idna<4,>=2.5 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (3.3)
> Requirement already satisfied: certifi>=2017.4.17 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (2021.10.8)
> Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (2.0.9)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (1.26.7)
> Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from packaging->sphinx) (3.0.6)

**Comment by parkour99** [comment]
I came accross the similar error: No module named 'sphinx', when i install cobbler by pip3 install cobbler-3.3.0.tar.gz
,then **i fix this by command**: 
```
pip3 --no-cache-dir install sphinx coverage simplejson
```

**Comment by jringoot** [comment]
> I came accross the similar error: **No module named 'sphinx'**, when i install cobbler by pip3 install cobbler-3.3.0.tar.gz ,then **i fix this by command**:
> 
> ```
> pip3 --no-cache-dir install sphinx coverage simplejson
> ```

Thanks for looking into it, but it's still not working for me:

> 

> pip3 --no-cache-dir install sphinx coverage simplejson
> Requirement already satisfied: sphinx in /opt/cobbler/cobbler/lib/python3.8/site-packages (4.3.2)
> Requirement already satisfied: coverage in /opt/cobbler/cobbler/lib/python3.8/site-packages (6.2)
> Requirement already satisfied: simplejson in /opt/cobbler/cobbler/lib/python3.8/site-packages (3.17.6)
> Requirement already satisfied: setuptools in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (44.0.0)
> Requirement already satisfied: babel>=1.3 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.9.1)
> Requirement already satisfied: sphinxcontrib-qthelp in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.0.3)
> Requirement already satisfied: sphinxcontrib-jsmath in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.0.1)
> Requirement already satisfied: Jinja2>=2.3 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (3.0.3)
> Requirement already satisfied: docutils<0.18,>=0.14 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (0.17.1)
> Requirement already satisfied: snowballstemmer>=1.1 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.2.0)
> Requirement already satisfied: sphinxcontrib-applehelp in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.0.2)
> Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.0.0)
> Requirement already satisfied: Pygments>=2.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.10.0)
> Requirement already satisfied: alabaster<0.8,>=0.7 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (0.7.12)
> Requirement already satisfied: requests>=2.5.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (2.26.0)
> Requirement already satisfied: packaging in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (21.3)
> Requirement already satisfied: imagesize in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.3.0)
> Requirement already satisfied: sphinxcontrib-devhelp in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.0.2)
> Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from sphinx) (1.1.5)
> Requirement already satisfied: pytz>=2015.7 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from babel>=1.3->sphinx) (2021.3)
> Requirement already satisfied: MarkupSafe>=2.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from Jinja2>=2.3->sphinx) (2.0.1)
> Requirement already satisfied: idna<4,>=2.5 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (3.3)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (1.26.7)
> Requirement already satisfied: certifi>=2017.4.17 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (2021.10.8)
> Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (2.0.9)
> Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/cobbler/cobbler/lib/python3.8/site-packages (from packaging->sphinx) (3.0.6)
> (cobbler) root@easy-install-me:/opt/cobbler-3.3.0# make debs
> cleaning: python bytecode
> cleaning: build artifacts
> cleaning: temp files
> checking: pyflakes /opt/cobbler/cobbler/bin/pyflakes
> checking: pycodestyle
> creating: AUTHORS
> creating: sdist
> Traceback (most recent call last):
>   File "setup.py", line 18, in <module>
>     from sphinx.setup_command import BuildDoc
> ModuleNotFoundError: No module named 'sphinx'
> make: *** [Makefile:86: sdist] Error 1
>

**Comment by jringoot** [comment]
Sphinx is imho correctly installed with BuildDoc, otherwise this import would give an ImportError

```
>>> from sphinx.setup_command import BuildDoc
>>> 

```

**Comment by jringoot** [comment]
Got a lot further with "apt-get install python3-sphinx"

**Comment by holmesb** [comment]
> Got a lot further with "apt-get install python3-sphinx" Still issue with debbuild:
> 
> > /bin/bash: debbuild: command not found
> > make: *** [Makefile:169: debs] Error 127
> > (cobbler) root@easy-install-me:/opt/cobbler-3.3.0#

That's another issue: #2874.  This one can probably be closed

**Comment by SchoolGuy** [comment]
Yeah this one is invalid since I building inside a venv is not supported by our makefile so far.

**Comment by jringoot** [comment]
> Yeah this one is invalid since I building inside a venv is not supported by our makefile so far.

ok, thanks for follow up, it was pip that suggested to use a virtual environment with a message like "this package is besides a pip package also available in your distribution, if you want to install the more recent pip package you are strongly suggested to do this in a virtual environment to avoid messing up your local package system"
That's why I tried this in a venv: having the more recent version of sphynx without messing up the apt system.
