### ISSUE TITLE
dnsmasq write_configs error

### ISSUE THREAD

**Issue by parkour99** [cobbler/cobbler#2866]
### Describe the bug

when cobbler have some systems data,  then I run **cobbler sync**,  I will get error:  **'Archs' object has no attribute 'lower'**

### Steps to reproduce

1.
2.
3.

### Cobbler version

cobbler --version
Cobbler 3.3.0

I install cobbler release 3.3.0 from source code

### Operating system

centos7.4

### Cobbler log

cobbler sync error log
````
writing template files for bootstrap-x86_64
mkdir: /var/lib/tftpboot/pxelinux.cfg
mkdir: /var/lib/tftpboot/ipxe
rendering DHCP files
Exception occurred: <class 'AttributeError'>
Exception value: 'Archs' object has no attribute 'lower'
Exception Info:
!!! TASK FAILED !!!
()[root@roller /]# tailf /var/log/cobbler/cobbler.log 
  File "/usr/local/lib/python3.6/site-packages/cobbler/actions/sync.py", line 160, in run
    self.write_dhcp()

  File "/usr/local/lib/python3.6/site-packages/cobbler/actions/sync.py", line 240, in write_dhcp
    self.dhcp.write_configs()

  File "/usr/local/lib/python3.6/site-packages/cobbler/modules/managers/dnsmasq.py", line 106, in write_configs
    systxt = "dhcp-host=net:" + distro.arch.lower() + "," + mac

[2021-12-17_164434_sync] 2021-12-17T16:44:38 - ERROR | ### TASK FAILED ###
````

### Additional information
we can see error from log, the **distro.arch is a enum.Archs**,
so there's no lower method in it, so we can replace it by **distro.arch.value**,
i have fixed it in my cluster

**Comment by SchoolGuy** [comment]
This has been fixed with 4738c0468e3f895966416ff39322a5df727f92be
