### ISSUE TITLE
Current & Max memory setting missing for virtualized hosts

### ISSUE THREAD

**Issue by AndreasDavour** [cobbler/cobbler#288]
When installing a virtualized host in kvm, the only setting available in cobbler, Virt RAM, is only the maximum memory available to a guest. libvirt/kvm allow a current memory usage setting as well but that one is not possible to configure in cobbler. 

Impact: If I need to provision virtual machines with dynamically adjusted memory, I need to set the max in cobbler and then use another too to adjust it and then reboot the vm. This take the provisioning of virtual machines only half way.

**Comment by jmaas** [comment]
Copied to cobbler/koan repo.
