### ISSUE TITLE
restarting cobblerd fills disk with backup settings.yaml files

### ISSUE THREAD

**Issue by olafhering** [cobbler/cobbler#2881]
Every `systemctl restart cobblerd` will write another copy of settings.yaml, see `ls /etc/cobbler/settings*.yaml`.
Over time it will lead to `ENOSPC` for no good reason.

There is no way to avoid this.

Even this fails:
````
echo 'some_setting: non_standard_value' > I_own_this_instance.yaml
cobblerd --no-daemonize --config  I_own_this_instance.yaml --disable-automigration
````

**Comment by SchoolGuy** [comment]
So the `--disable-automigration` should be fixed as of https://github.com/cobbler/cobbler/pull/2871

However I agree that saving all backup YAMLs is maybe not needed. What is your desired behavior @olafhering ?

I would propose we only keep the last 10? That should be enough in my eyes. I would like to avoid adding a setting which regulates how much backups we keep since the file will become optional in the future.

**Comment by olafhering** [comment]
The required outcome is: either overwrite the settings file, or leave it as it is.

Everyone has a backup in case a restore is actually needed.

**Comment by SchoolGuy** [comment]
@olafhering That is an assumption in my eyes. It could be that you don't expect Cobbler to touch the file and you then don't have a backup of that file. The file is indeed overwritten if you have the automigration enabled. So you just would completely disable the backup of settings files?

**Comment by olafhering** [comment]
I think this code path did not work well either, will double check. Otherwise I would have used it already.

**Comment by olafhering** [comment]
Lets focus in this issue on getting rid of the versioned backup files. Other issues, like `--disable-automigration` not being recognized should be discussed elsewhere.

**Comment by SchoolGuy** [comment]
@olafhering If you just want to get rid of versioned backup files that is easy. But I still don't agree with the reason for it. Not all people have a perfect backup solution or btrfs snapshots.

For me a compromise would be limiting the number of backups we store.

If you insist we need to add a flag which disables this functionality.

**Comment by olafhering** [comment]
Dealing with just N config files would just add more complicate code, instead of removing unhelpful code.
As I said, a backup exists. If not, this will not be cobblers fault.

**Comment by SchoolGuy** [comment]
@agraul @meaksh @vzhestkov What are your opinions on this? My opinion is stated above already.

**Comment by vzhestkov** [comment]
I think the issue could be solved with putting `ExecStartPre` in the cobbler service file with setting it to the script wiping old files. How many files it should keep could be specified in `/etc/sysconfig/...`. The shell script should be very simple to implement.

**Comment by SchoolGuy** [comment]
@meaksh @agraul What are your opinions on this? We should fix this before next Friday in my opinion.

**Comment by agraul** [comment]
I agree with @olafhering's point in not keeping any backups, provided it is documented that the user-provided config file can be overridden. Is it really needed to invest in a "keep N backups" infrastructure? Personally, I think we can do without.

**Comment by SchoolGuy** [comment]
@meaksh @agraul @tiltingpenguin & myself had a discussion about this topic.

We decided to remove the auto-migration on daemon startup and move that functionality to `cobbler-settings` so the user has control over when he wants to execute that. That means however that after a version upgrade Cobbler might not automatically start up anymore.

**Comment by SchoolGuy** [comment]
Okay everything that is left for this ticket is: Flip the default in `api.py` and then we need the docs.
