### ISSUE TITLE
getpwnam(): name not found: 'apache'

### ISSUE THREAD

**Issue by kk678** [cobbler/cobbler#2932]
### Describe the bug

error when compile on centos8.2

### Steps to reproduce
```
[root@os cobbler]# cat /etc/redhat-release 
CentOS Linux release 8.2.2004 (Core) 
[root@os cobbler]# uname -a
Linux os.com 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

1. checkout code e36be05e3792c28b114fb9e3855a3aa90387e6be
    git clone https://github.com/cobbler/cobbler.git
2. make install
3. Error in 'chown apache /usr/local/share/cobbler/web': "getpwnam(): name not found: 'apache'"
   Error in 'chown apache //var/lib/cobbler/webui_sessions': "getpwnam(): name not found: 'apache'"

### Cobbler version

````paste below
````

### Operating system
 centos8.2

### Cobbler log

````paste below
````

**Comment by SchoolGuy** [comment]
So interestingly enough these are leftovers from the webinterface. Thanks for this find. I mean it should still succeed but I will remove the lines in a "cleanup" PR I am doing atm anyway.
