### ISSUE TITLE
Bug: exception on server: '_DnsmasqManager' object has no attribute 'write_dns_files'

### ISSUE THREAD

**Issue by kmahyyg** [cobbler/cobbler#2984]
All things are done strictly followed RTD. Running on Debian 11.

Context linked with Issue #2968 , It is really exhausted to experience such a large number of bugs in few days...

```
root@debian11:~# cobbler system remove --name=debnetinstTest
<ALREADY REMOVED BEFORE I PROCEED>
root@debian11:~# cobbler system add --name=debnetinstTest --profile=debian11-d-i-x86_64
exception on server: '_DnsmasqManager' object has no attribute 'write_dns_files'
root@debian11:~# cobbler version
Cobbler 3.3.2
  source: 9044aa99, Fri Mar 11 09:59:35 2022 +0100
  build time: Mon Mar 21 12:51:50 2022
```

Seems another bug... even I upgraded the version and then `make devinstall` then reboot

**Comment by SchoolGuy** [comment]
@kmahyyg It is not related. It may seem similar but has a totally different cause. I created a PR for `main`. Feel free to confirm if the patch fixes the mentioned issue.
