### ISSUE TITLE
typo error of manage_dhcp_v1

### ISSUE THREAD

**Issue by pkqsun** [cobbler/cobbler#2999]
### Steps to reproduce

1. install cobbler 3.3.2 via source code, using make install cmd
2. check the configuration file of: `/etc/cobbler/settings.yaml`
3. `Missing keys: 'manage_dhcp_v4', 'manage_dhcp_v6', they all named manage_dhcp_v1`

### Expected behavior

```
manage_dhcp: false
manage_dhcp_v1: false
manage_dhcp_v1: false 
```
====>
```
manage_dhcp: false
manage_dhcp_v4: false
manage_dhcp_v6: false
```

### Cobbler version

````
Cobbler 3.3.2
  source: ?, ?
  build time: Tue Mar 22 13:26:53 2022

````

### Operating system
```
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
```

### Cobbler log

````
$ /usr/bin/python3 /usr/local/bin/cobblerd -F
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cobbler/api.py", line 147, in __generate_settings
    normalized_settings = settings.validate_settings(yaml_dict)
  File "/usr/local/lib/python3.6/site-packages/cobbler/settings/__init__.py", line 280, in validate_settings
    return migrations.normalize(settings_content)
  File "/usr/local/lib/python3.6/site-packages/cobbler/settings/migrations/__init__.py", line 291, in normalize
    return VERSION_LIST[version].normalize(settings)
  File "/usr/local/lib/python3.6/site-packages/cobbler/settings/migrations/V3_3_2.py", line 36, in normalize
    return schema.validate(settings)
  File "/usr/local/lib/python3.6/site-packages/schema.py", line 420, in validate
    raise SchemaMissingKeyError(message, e.format(data) if e else None)
schema.SchemaMissingKeyError: Missing keys: 'manage_dhcp_v4', 'manage_dhcp_v6'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/cobblerd", line 92, in main
    execute_settings_automigration=options.automigration)
  File "/usr/local/lib/python3.6/site-packages/cobbler/api.py", line 91, in __init__
    execute_settings_automigration)
  File "/usr/local/lib/python3.6/site-packages/cobbler/api.py", line 150, in __generate_settings
    from error
ValueError: Settings are invalid and auto-migration is disabled. Please correct this manually!

````

### Additional information

From Doc page, it also need update the description:
````Set to true to enable DHCP IPv6 address configuration generation ````
for https://cobbler.readthedocs.io/en/latest/cobbler-conf.html#manage-dhcp-v4

**Comment by SchoolGuy** [comment]
@pkqsun I have no idea how `manage_dhcp_v1` is in your settings file. I checked the logs and we don't have the string `v1` in the source code. So can you maybe explain where that came from?

**Comment by pkqsun** [comment]
Yes, that's strange, The grep cmd shows nothing for manage_dhcp_v1.
But I installed cobbler 3.3.2 in 2 labs form source code and it is the same.

**Comment by SchoolGuy** [comment]
@pkqsun Can you give me more detailed steps to reproduce this behaviour maybe? Because I don't have an idea how to debug this atm.

**Comment by pkqsun** [comment]
@SchoolGuy  BYW, do you know how to install cobbler 3.3.2 using dnf/yum ?
```
[CentOS 8](https://src.fedoraproject.org/rpms/cobbler):
        dnf install epel-release
        dnf module enable cobbler
        dnf install cobbler
```
could only install cobbler 3.2.2 in my trial.
I could not find the correct repo contains 3.3.2, such as  http://mirrors.mit.edu/epel/8/Modular/x86_64/Packages/c/ is 3.2.2.

**Comment by SchoolGuy** [comment]
@pkqsun The maintainer in EPEL did decided to not upgrade to 3.3.x or even newer because I am not able to finish the web interface atm. This is sad but yeah I don't have enough resources with this.
