### ISSUE TITLE
No file ../rpm-build/cobbler-web*rpm after "make rpms"

### ISSUE THREAD

**Issue by denis-54** [cobbler/cobbler#3006]
### Describe the bug

No file ../rpm-build/cobbler-web*rpm after "make rpms"

### Steps to reproduce

1. git clone https://github.com/cobbler/cobbler.git
2. cd cobbler
3. nstalled all the necessary packages, the package list is the same as specified in the Rocky_Linux_8.dockerfile file
4. make rpms:
```
<skip>
Wrote: /home/user1/cobbler-3.4.0/cobbler/rpm-build/cobbler-3.4.0-1.el8.src.rpm
Wrote: /home/user1/cobbler-3.4.0/cobbler/rpm-build/cobbler-3.4.0-1.el8.noarch.rpm
Wrote: /home/user1/cobbler-3.4.0/cobbler/rpm-build/cobbler-tests-3.4.0-1.el8.noarch.rpm
Runing (%clean): /bin/bash -e /var/tmp/rpm-tmp.q4NpLP
+ umask 022
+ cd /home/user1/cobbler-3.4.0/cobbler/rpm-build
+ cd cobbler-3.4.0
+ /usr/bin/rm -rf /home/user1/cobbler-3.4.0/cobbler/rpm-build/BUILDROOT/cobbler-3.4.0-1.el8.x86_64
+ exit 0
```

### Expected behavior

Wrote: /home/user1/cobbler-3.4.0/cobbler/rpm-build/cobbler-3.4.0-1.el8.src.rpm
Wrote: /home/user1/cobbler-3.4.0/cobbler/rpm-build/cobbler-3.4.0-1.el8.noarch.rpm
Wrote: /home/user1/cobbler-3.4.0/cobbler/rpm-build/cobbler-tests-3.4.0-1.el8.noarch.rpm
Wrote: /home/user1/cobbler-3.4.0/cobbler/rpm-build/cobbler-web.el8.noarch.rpm

### Cobbler version

````paste below
3.3.2
3.4.0
````

### Operating system
Rocky Linux release 8.5 (Green Obsidian)

### Cobbler log

````paste below
````

### Additional information
The situation is similar if I use docker to get rpm packages.

**Comment by SchoolGuy** [comment]
In the Changelog we clearly stated on GitHub that we removed the webinterface a while ago. The new webinterface was not possible to be completed because of the lack of resources. Work is actively going on as time permits. There is not an ETA at the moment for a first alpha release.
