### ISSUE TITLE
dnf module enable cobbler not working on rocky

### ISSUE THREAD

**Issue by Shubhangi-dell** [cobbler/cobbler#3062]
### Describe the bug
Our software has been using **dnf module enable cobbler** on rocky for the past several versions and today suddenly it showed the below version. 
We were using Cobbler version 3.2.2 on rocky 8.0.
![image](https://user-images.githubusercontent.com/72869337/164043046-d07c1e7d-4818-469e-bfad-9b4c058be50f.png)
Because of this, our software will have a huge impact as shown in the link: https://github.com/dellhpc/omnia/issues/1039

As of now, we have updated it to dnf module enable cobbler:3. **Please don't delete the cobbler 3.2.2.-11 rpm packages from the repo as this will have a huge impact on our release.** 
Also, we can't use a new version immediately as it will require a whole new round of testing and validations. 

### Steps to reproduce

1. Run dnf module enable cobbler on rocky 8.0
2. It will fail

### Expected behavior
It should run as previously or should automatically take up the version that is the latest and supported by the OS.

### Cobbler version
3,2,2

### Operating system
Rocky 8.0

**Comment by SchoolGuy** [comment]
@opoplawski This is your area. I have no control on that sadly and can't provide help.

**Comment by Shubhangi-dell** [comment]
@opoplawski Can you please shed some light on this issue?

**Comment by opoplawski** [comment]
The cobbler:3 stream will stay with 3.2.X.  That's why I introduced the 3.3 stream.  I suppose I should look into making the 3 stream the default.  I'll see what I can do.

**Comment by opoplawski** [comment]
Well, looks like default streams are not a thing in EPEL8.  Don't worry, 3.2 is sticking around.
