### ISSUE TITLE
[replicate] The "next_server_v4" attribute of the "profile" is wrong after replicating

### ISSUE THREAD

**Issue by wy-z** [cobbler/cobbler#3085]
### Describe the bug

The "next_server_v4" attribute of the "profile" is wrong after replicating.

### Steps to reproduce

1. Master node: 10.0.0.1
2. Standby node: 10.0.0.2 
3. Create profile 'A' on the master node, the 'next_server_v4' attribute of profile 'A' will be forcibly set to '10.0.0.1'
4. Do replicate on the standby node, the 'next_server_v4' attribute of profile 'A' is still '10.0.0.1'

### Expected behavior

The 'next_server_v4' attribute of profile 'A' on the standby node should be '10.0.0.2' or empty.

### Cobbler version

````
Cobbler 3.3.2
  source: ?, ?
  build time: Fri Apr 15 07:36:29 2022
````

### Operating system

```
Rocky Linux release 8.4 (Green Obsidian)
```

### Additional information

https://github.com/cobbler/cobbler/blob/main/cobbler/items/profile.py#L55
The 'next_server_v4/v6' attribute of profile will be forcibly set to `api.settings().next_server_v4`.

Previously, the default value of 'next_server_v4/v6' was empty and was changed in https://github.com/cobbler/cobbler/commit/1d630454a2f62c59da84055136c6701c80014cb2.

**Comment by SchoolGuy** [comment]
@wy-z Do you have set the [`convert_server_to_ip`](https://cobbler.readthedocs.io/en/latest/cobbler-conf.html#convert-server-to-ip) to `False`. That may improve the behaviour in other similar situations.

For this specific use-case: Yeah this is a bug in 3.2.2 I agree. Is this fixed for you with a version which has the commit you linked? Or what do you think should be the correct behaviour?

**Comment by wy-z** [comment]
> @wy-z Do you have set the [`convert_server_to_ip`](https://cobbler.readthedocs.io/en/latest/cobbler-conf.html#convert-server-to-ip) to `False`. That may improve the behaviour in other similar situations.
> 
> For this specific use-case: Yeah this is a bug in 3.2.2 I agree. Is this fixed for you with a version which has the commit you linked? Or what do you think should be the correct behaviour?

Hi @SchoolGuy , thank you very much for your reply.
My temporary solution is setting A to empty by default so that I can use the global `next_server_v4/v6`.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/4213483/166422990-040e8d4c-cf2c-4f03-aa55-afd296dc17a8.png">

I think it is feasible to set `next_server_v4/v6` to empty by default, and you only need to set `next_server_v4/v6` specifically if you want to override the global configuration.

**Comment by SchoolGuy** [comment]
Well this is what `<<inherit>>` does if you upgrade to a newer version. Setting it empty would mean that it should be really empty if you upgrade to the next (not yet published) release.

**Comment by wy-z** [comment]
> Well this is what `<<inherit>>` does if you upgrade to a newer version. Setting it empty would mean that it should be really empty if you upgrade to the next (not yet published) release.

Agree that, it also makes sense to set it to `<<inherit>>`, as in the following code
```py
self._next_server_v4 = enums.VALUE_INHERITED
...
@property
def next_server_v4(self) -> str:
    if self._next_server_v4 == enums.VALUE_INHERITED:
        return self.api.settings().next_server_v4
    return self._next_server_v4
```

**Comment by SchoolGuy** [comment]
So this issue can be closed or is there something to fix from your perspective? Do we need backward compatible replicate code in some fashion?

**Comment by wy-z** [comment]
> So this issue can be closed or is there something to fix from your perspective? Do we need backward compatible replicate code in some fashion?

I'm sorry for my carelessness.
After reading [blender function](https://github.com/cobbler/cobbler/blob/e90abcac58ea7472d80d4574bd492b799bb8d58e/cobbler/utils.py#L669), I realized that `Profile.next_server_v4/v6` can also be set to `<<inherit>>`.

How about setting `Profile._next_server_v4/v6` to `<<inherit>>` by default? So that `Profile` can work properly after replicating.

**Comment by SchoolGuy** [comment]
@wy-z But this is the case at the moment on `main` as you showed before in the snippet you copied. So then all should be good starting with the next release.

**Comment by wy-z** [comment]
> @wy-z But this is the case at the moment on `main` as you showed before in the snippet you copied. So then all should be good starting with the next release.

https://github.com/cobbler/cobbler/blob/main/cobbler/items/profile.py#L55
<img width="764" alt="image" src="https://user-images.githubusercontent.com/4213483/166450443-ec2c6ba4-18cc-4505-8597-e66fb324eaf9.png">
The default value of `next_server_v4/v6` is `api.settings().next_server_v4/v6` on the main branch~
I am sorry that my misrepresentation led to your misunderstanding.

**Comment by SchoolGuy** [comment]
Ahhh correct. Okay that is easily fixable afaik. You want to do a PR or should I do one once I have time?

**Comment by wy-z** [comment]
https://github.com/cobbler/cobbler/pull/3086

> Ahhh correct. Okay that is easily fixable afaik. You want to do a PR or should I do one once I have time?
