### ISSUE TITLE
grubx86.efi vs grubx64.efi (DHCPv4 -> EFI does not work)

### ISSUE THREAD

**Issue by eikef** [cobbler/cobbler#3092]
### Either settings.yaml and dhcp6.template are wrong, or dhcp.template, documentation, and tests are wrong

In dhcp.template, cobbler currently references `grubx64.efi` for x86_64 EFI boots, while dhcp6.template references `grubx86.efi` (for the same function). `cobbler mkloaders` generates grubx86.efi based on `settings.yaml` -> `bootloader_formats` -> `x86_64_efi` -> `binary_name` being set to `grubx86.efi`.

This results in the current dhcp.template being unable to use the EFI bootloaders since the filename is wrong.

A quick fix would be to `s/grubx64.efi/grubx86.efi/` in `dhcp.template`, although I would argue the correct way to solve it would be to rename the `binary_name` to grubx64.efi in `settings.yaml`, the `grubx86.efi` in `dhcp6.template` to `grubx64.efi`, and doing whatever needs to be done in `cobbler/settings/migrations` (in which files also reference `grubx86.efi`). This would be in line with other tests and documentation within cobbler (including `mkloaders_test.py`, `cobbler.rst`, `grub.rst`, `system-tests/listings/*/*/*/index`, and generally grubx64.efi being named that way on many Linux distribution EFI directories.

### Steps to reproduce

1. Use ISC DHCP v4 to attempt to boot via PXE on an EFI system
2. Failure due to grubx64.efi not being present on tftp

### Expected behavior

The default templates for DHCP to work out of the box with `cobbler mkloaders`-provided bootloaders

### Cobbler version

````paste below
cobbler version
Cobbler 3.3.3
  source: b4df3716, Mon Apr 25 13:19:08 2022 +0200
  build time: Fri May  6 13:25:13 2022
````

### Operating system

AlmaLinux 8.5

**Comment by SchoolGuy** [comment]
Okay so I believe as argued by the reporter that we actually want `grubx64.efi` as a name in all places.
