### ISSUE TITLE
cobbler repo add / edit --priority=1 does not work on Cobbler 3.3.2

### ISSUE THREAD

**Issue by zparihar** [cobbler/cobbler#3140]
### Describe the bug

Hey SchoolGuy,

Long time no speak.
I found a bug with "cobbler repo add" and "cobbler repo edit" related to setting the YUM/DNF priority:
It's complaining that "exception on server: Repository priority must be of type int."

### Steps to reproduce

When I run:

`cobbler repo add --name=almalinux86-x86_64-base --mirror=http://mirror.myaccess.ca/8.6/BaseOS/x86_64/os/ --breed=yum --keep-updated=True --mirror-locally=True --arch=x86_64 --priority=1`

I get the error message:

`exception on server: Repository priority must be of type int.`

and when I run: 

`cobbler repo edit --name almalinux84-x86_64-base --priority=1`

I get the error message:

`exception on server: Repository priority must be of type int.`

### Expected behavior

The expected behaviour is that it should not produce an error

### Cobbler version
I'm running:
- Cobbler 3.3 via: "dnf -y module enable cobbler:3.3 && dnf -y install cobbler"
    -> rpm -qa | grep -i cobbler -----> cobbler-3.3.2-2.module_el8+14420+e999864d.noarch

    
    
Do you already have a fix for this?

### Operating system

- AlmaLinux 8.6

### Cobbler log

```
[Thread-468] 2022-06-05T19:18:14 - DEBUG | REMOTE CLI Authorized; user(?)
[Thread-468] 2022-06-05T19:18:14 - DEBUG | REMOTE CLI Authorized; user(?)
[Thread-468] 2022-06-05T19:18:14 - DEBUG | REMOTE CLI Authorized; user(?)
[Thread-468] 2022-06-05T19:18:14 - INFO | Exception occurred: <class 'TypeError'>
[Thread-468] 2022-06-05T19:18:14 - INFO | Exception value: Repository priority must be of type int.
[Thread-468] 2022-06-05T19:18:14 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3640, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 2025, in xapi_object_edit
    self.modify_item(object_type, handle, key, value, token)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1752, in modify_item
    setattr(obj, attribute, arg)

  File "/usr/lib/python3.6/site-packages/cobbler/items/repo.py", line 291, in priority
    raise TypeError("Repository priority must be of type int.")

```

**Comment by SchoolGuy** [comment]
@zparihar Thanks for the report. I have found the error already. Sadly it is not fixed in 3.3.3 but I will create a PR against the `main` branch.

**Comment by zparihar** [comment]
@SchoolGuy 

Hey SchoolGuy!  Thanks so much!  
If you do resolve this and have some time to post the changes, I'd like to replace the appropriate file / code and try it.

Cheers!

**Comment by SchoolGuy** [comment]
@zparihar A patch can be found here: https://github.com/cobbler/cobbler/pull/3141/commits/6cc1a348beedfd58899205fefa2558bd8b33df7f

However sadly that won't apply as it is part of a refactoring that I made in that PR. Thus you would have to backport it yourself. If you need a backport for 3.3.x urgently I can try but I can't promise anything.
