### ISSUE TITLE
Use entrypoint scripts instead of custom written ones

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#3144]
### Is your feature request related to a problem?

At the moment we write, maintain and package our own entrypoint scripts for Cobbler. Admittedly this is not much work but I see no reason to do that.

### Provide a detailed description of the proposed feature

I would like to utilize https://setuptools.pypa.io/en/latest/userguide/entry_point.html to ship the entrypoints for Cobbler.

### Alternatives you've considered

None

### Additional information

None

**Comment by SchoolGuy** [comment]
Okay we have a small hickup. Debian 10 seems to package `mod_wsgi` in a different way which leads to the fact that setuptools seems to not recognize the installed package. Thus we need to find a solution for this. I can think of two things:

- Remove `mod_wsgi` from the requirements list
- Let this stay open until June 2024 - https://wiki.debian.org/LTS
- Ignore that Debian 10 is broken? - Not an option imho

Did I overlook something? @cobbler/suse-reviewers

**Comment by tiltingpenguin** [comment]
I looked into this a bit and a cli in golang would probably solve this problem as well

**Comment by SchoolGuy** [comment]
Since @tiltingpenguin summarized the issue state pretty good, I will close this one in favor of working on the golang CLI.
