### ISSUE TITLE
HTTPboot not documented

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#3153]
### Is your feature request related to a problem?

We added HTTPboot support in https://github.com/cobbler/cobbler/issues/2102 ages ago. However we havn't documented how to set it up and how it works. Let's change that.

### Provide a detailed description of the proposed feature

A step-by-step explanation on how to enable HTTPboot and how it works.

### Alternatives you've considered

None

### Additional information

CC @ishackigozi

**Comment by ishackigozi** [comment]
@SchoolGuy I hope you are well, any idea when you can assist with this documentation?
Thank you.

**Comment by SchoolGuy** [comment]
@ishackigozi Well what I would do is using libvirt to create a Cobbler playground and then try to figure out how to use it. Afterwards I would document this and then refine it while I perform the documented steps by myself. If you are interested, you are more then welcome to do this!

**Comment by SchoolGuy** [comment]
A colleague of mine gave me this documentation that he created during a customer setup. 

[httpboot.txt](https://github.com/cobbler/cobbler/files/10147488/httpboot.txt)
