### ISSUE TITLE
mkloaders fails to create .efi files

### ISSUE THREAD

**Issue by jfchoquette** [cobbler/cobbler#3158]
### Describe the bug

After updating to Cobbler 3.3.2, the mkloaders command fails to generate efi boot loaders. Cobbler is now asking for a memdisk, which we did not need prior to updating. After providing a path to the syslinux memdisk, cobbler will fail to generate the loaders anyways.

### Steps to reproduce

1. In `/etc/cobbler/settings.yaml`, set the `syslinux_memdisk_folder` and `syslinux_pxelinux_folder` to their defaults (`@@memdisk_folder@@` and `@@pxelinux_folder@@` respectively)
2. `systemctl restart cobblerd`
3. Run `cobbler mkloaders` (cobbler will request valid syslinux folders)
4. Back in `/etc/cobbler/settings.yaml`, set the `syslinux_memdisk_folder` and `syslinux_pxelinux_folder` to `/usr/share/syslinux`
5. `systemctl restart cobblerd`
6. Run `cobbler mkloaders` (the task will no longer fail, but the boot loaders are not generated)

### Expected behavior

An error free response and correctly generated boot loaders.
### Cobbler version

![Cobbler Version](https://user-images.githubusercontent.com/106405445/173414837-17ed7df2-fe02-4d79-8061-9bfc514376a3.png)

### Operating system

NAME="openSUSE Tumbleweed"
VERSION="20220331"

### Cobbler log

![Cobbler memdisk does not exist](https://user-images.githubusercontent.com/106405445/173416499-e465096a-d8d4-4670-ad6b-9355942ad348.png)
![Cobbler skipping grub creation](https://user-images.githubusercontent.com/106405445/173416776-ddda8174-db43-4147-93d4-5294c4ddff5c.png)

### Screenshots

![Cobbler empty efi](https://user-images.githubusercontent.com/106405445/173416829-8adc1d2d-26b3-4e81-8813-013b3f451eb3.png)

**Comment by SchoolGuy** [comment]
@jfchoquette Setting the settings you mentioned to any `@@name@@` variable should never work because the settings file is the source of truth for those settings. So I would expect this to happen. The defaults in the `settings.yaml` should work for you on openSUSE Tumbleweed as this is what we use for our CI also.

The memdisk is required since Cobbler 3.3.1 and was added in #2851. So there should definitely be no for 3.3.2 in this regard.

**Comment by jfchoquette** [comment]
Okay thank you for the help. I was able to find the correct modules and successfully build the bootloader. Looks like it was not a bug after all, so I'm going to close this. Thanks again for helping me identify the problem.
