### ISSUE TITLE
Ever slower adding of nodes, huge slow down since 3.2.x

### ISSUE THREAD

**Issue by bill-broadley** [cobbler/cobbler#3169]
### Describe the bug

I built 3.3.3 and 3.4.0 branches from git.  I noticed that cobbler sync, launching cobblerd, and even things like minor edits to a profile to set a template get ever slower.  On a 3.2.x system I have a cobbler sync takes 3-5 seconds, with 3.3.3 or 3.4.0 it's more like 15-20 minutes.

From what I can tell the more systems I add the more repetitions I get of:
```
[Thread-1406] 2022-07-05T17:19:41 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-1406] 2022-07-05T17:19:41 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-1406] 2022-07-05T17:19:41 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-1406] 2022-07-05T17:19:41 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-1406] 2022-07-05T17:19:41 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-1406] 2022-07-05T17:19:41 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-1406] 2022-07-05T17:19:41 - INFO | grab_tree found 3 children (including settings) of this object
```

Even running really simple stuff like:
```
cobbler system add --name=admin10 --mac=3c:ec:ef:71:db:70 --netboot=true --profile=rocky86-x86_64 --dns-name=admin10.swtestcluster.example.com --ip-address=192.168.3.32 --hostname=admin10.swtestcluster.example.com --netmask=255.255.0.0 --gateway=192.168.1.2
```

Runs at 77 per minute, when I have no system, but then down to 28 per minute when I have 300 nodes added.  It keeps slowing and I was hoping to have 500 nodes and 500 IPMI interfaces in the database.  With 1000 nodes even launching cobblerd takes 90 seconds, when I strace cobblerd it looks like it's blocking on reading a ton of random numbers.  Maybe a 50-100 numbers per host or something?

Building the cobbler database isn't that bad, but waiting 15-20 minutes for a cobbler sync does make any changes pretty painful.  Am I doing something wrong?

### Steps to reproduce

1. git clone (3.4.0 is default now, but 3.3.3 branch seems to behave the same way
2. `rm -rf /var/lib/python3.6/cobbler*`
3. `cd cobbler; make install`
4. download Rocky-8.6-x86_64-minimal.iso
5. `mkdir /mnt/dvd1; mount -o loop Rocky-8.6-x86_64-minimal.iso /mnt/dvd1`
6. `cobbler import --path=/mnt/dvd1 --name=rocky86`
7. add 1000 nodes along the lines of
    `cobbler system add --name=admin10 --mac=3c:ec:ef:71:db:70 --netboot=true --profile=rocky86-x86_64 --dns-name=admin10.swtestcluster.example.com --ip-address=192.168.3.32 --hostname=admin10.swtestcluster.example.com --netmask=255.255.0.0 --gateway=192.168.1.2`
8. time cobbler sync
9. watch 1000s of lines of "grab_tree found 4 children (including settings) of this object"
10. wait a few minutes for 400 nodes, but 15+ minutes for 1000 nodes.
11. Wait 90 seconds or so for cobblerd to launch
12. Wait for minutes for a `cobbler profile edit --autoinstall=`
13. Wait for an entire minute for a single `cobbler system add`

### Expected behavior

I was expecting cobbler system add and cobbler sync to run in a few seconds.  3.2.x can sync 1000 nodes in 5 seconds.  Cobblerd should start in a few seconds, and minor profile edits should run in a few seconds.

### Cobbler version

```
[root@nas-1-1 cobbler]# cobbler version
Cobbler 3.3.3
  source: 5c498dbf, Thu Jun 2 18:01:33 2022 +0200
  build time: Tue Jul  5 23:13:40 2022
```

### Operating system

Rocky 8.6 (a RHEL/CentOS variant)

### Cobbler log

Here's a snipped, for adding 1000 nodes it's something like 400,000 lines:
```
[Thread-4923] 2022-07-05T17:35:47 - DEBUG | REMOTE CLI Authorized; user(?)
[Thread-4923] 2022-07-05T17:35:47 - INFO | add_item(system); ['mc1-35']
[Thread-4923] 2022-07-05T17:35:47 - DEBUG | running python triggers from /var/lib/cobbler/triggers/add/system/pre/*
[Thread-4923] 2022-07-05T17:35:47 - DEBUG | running shell triggers from /var/lib/cobbler/triggers/add/system/pre/*
[Thread-4923] 2022-07-05T17:35:47 - DEBUG | shell triggers finished successfully
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 3 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 4 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 4 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 4 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | generating: /var/lib/tftpboot/pxelinux.cfg/01-3c-ec-ef-70-61-cb
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 4 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 4 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | grab_tree found 4 children (including settings) of this object
[Thread-4923] 2022-07-05T17:35:47 - INFO | generating: /var/lib/tftpboot/grub/system/3c:ec:ef:70:61:cb
[Thread-4923] 2022-07-05T17:35:47 - INFO | Writing template files for mc1-35
```

**Comment by SchoolGuy** [comment]
@bill-broadley If you would do that, that would be a massive help! If you can't do it, I will do it as part of my work for the next SUSE Manager version 4.4 probably but it is not yet set in stone.

**Comment by watologo1** [comment]
@bill-broadley Can you try:
https://github.com/cobbler/cobbler/pull/3180
please.
I wanted to do this more proper (at least one of the 2 commits), but this is intrusive and I do not see that this can happen any time soon.

**Comment by SchoolGuy** [comment]
One of the last commits to `main` (85d4877108fc04308b5d422af40dc311a948938d) just reintroduced caching. With the merge of #3363 this should get better even more.

Do you have the capacity to verify if the performance has increased in a level that you would expect @bill-broadley after the merge of the mentioned PR? Independant if that is in your capacity or not, could you please communicate your expectations in #3341?

**Comment by SchoolGuy** [comment]
@bill-broadley Any update from your side? Recently there were tests conducted that showed that adding 5000 systems takes roughly 100 minutes. Which is arguably not the best time but the mechanism and time when changes are performed did change.
