### ISSUE TITLE
Static Routes field in gui can break the setting silently

### ISSUE THREAD

**Issue by AndreasDavour** [cobbler/cobbler#320]
I have a long list of nets and their routes, and I pasted in them in the web gui. But, I had cut them from a document with quotes, like this "net:route net:route" and I happened to include the quotes.

As I pressed SAVE I  realized that it might not work, but when I then went back and looked at it, the list looked quite ok, without the quotes. 

When I installed the machine the routes where broken and it was only when I ran "cobbler system report --name=FOO" that it became clear that the Static Route list was not individual nets and routes, quoted and comma separated, but a long list within quotes.

So, the GUI accepted wrong input and did not complain, nor did it split the string up into the constituent strings and comma separated them. 

Considering https://github.com/cobbler/cobbler/issues/291 did not fix the problem on the slave after the replication master had been fixed, this is a most aggravating behaviour.

**Comment by jmaas** [comment]
Coped to cobbler/cobbler-web
