### ISSUE TITLE
cobbler status fails when log files are gzipped

### ISSUE THREAD

**Issue by PunisherHD92** [cobbler/cobbler#3247]
### Describe the bug

After some time of running, the log file /var/log/cobbler/install.log gets rotated by logrotate.
Logrotate creates gzipped files, e.g. 'install.log-20220830.gz'

Then "cobbler status" fails with the following error:
````
### ERROR ###
Unexpected remote error, check the server side logs for further info
<class 'TypeError'>:a bytes-like object is required, not 'str'
````

### Steps to reproduce

1. cd /var/log/cobbler 
2. rm -f install.log*.gz
3. cp install.log install.log-20220830
4. cobbler status => works OK
5. gzip install.log-20220830
6. cobbler status => fails

### Expected behavior

Cobbler status should not fail when install.log files are gzipped.

### Cobbler version

Cobbler version 3.2.2 (from EPEL repository)

````paste below
Cobbler 3.2.2
  source: ?, ?
  build time: Wed Mar  2 01:17:52 2022
````

### Operating system

Linux RHEL 8.6

### Cobbler log

````paste below
2022-08-31T20:57:17 - INFO | Exception occurred: <class 'TypeError'>
2022-08-31T20:57:17 - INFO | Exception value: a bytes-like object is required, not 'str'
2022-08-31T20:57:17 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3448, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3025, in get_status
    return self.api.status(mode=mode, logger=self.logger)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1373, in status
    return statusifier.run()

  File "/usr/lib/python3.6/site-packages/cobbler/actions/status.py", line 199, in run
    self.scan_logfiles()

  File "/usr/lib/python3.6/site-packages/cobbler/actions/status.py", line 86, in scan_logfiles
    for line in data.split("\n"):
````

### Additional information

Python 3.6.8
It looks like data read from gzip.open() need to be decoded first.
Proposed patch below:
[cobbler-3.2.2-log_gzip_decode.txt](https://github.com/cobbler/cobbler/files/9465048/cobbler-3.2.2-log_gzip_decode.txt)

**Comment by SchoolGuy** [comment]
@PunisherHD92 Thanks for your proposed patch. What we can instead is specify that the file should be opend in text-mode. We are already using `gzip.open()`, thus we can make your patch even smaller then it already is. Thanks for the amazingly understandable bug report!

**Comment by PunisherHD92** [comment]
Hello, thanks for replying.
You are correct about the gzip.open option.
Here is another proposed patch.
[cobbler-3.2.2-log_gzip_decode_2.txt](https://github.com/cobbler/cobbler/files/9467659/cobbler-3.2.2-log_gzip_decode_2.txt)

**Comment by SchoolGuy** [comment]
Good. I have come up with the same thing. However I am writing the missing tests atm. I will open a PR once I am finished with that.
