### ISSUE TITLE
Build issue: add support for Rocky Linux distribution

### ISSUE THREAD

**Issue by PunisherHD92** [cobbler/cobbler#3248]
### Describe the bug

When building Cobbler 3.2.2 from sources on a Rocky Linux machine, the "distro_build_configs.sh" does not detect the distribution correctly.
FYI: Rocky Linux 8 is a clone of RHEL 8 distribution

### Steps to reproduce

1. Build and install Cobbler on Rocky 8 distribution
2. Directories that are created on target system are incorrect (e.g. '/etc/apache2' instead of '/etc/httpd')

### Expected behavior

The installer should install Cobbler on Rocky Linux in the same way as on RHEL

### Cobbler version

````paste below
Cobbler 3.2.2
````

### Operating system

Rocky Linux 8.6

### Cobbler log

````paste below
N/A
````

### Additional information

Proposed patch to fix the Rocky Linux distribution detection.
[cobbler-3.2.2-rocky.txt](https://github.com/cobbler/cobbler/files/9467701/cobbler-3.2.2-rocky.txt)

**Comment by SchoolGuy** [comment]
@PunisherHD92 Feel free to open a PR. For me 3.2.x is out of maintenance, I only care about `main` and the current release series since my time is too limited to do more.
