### ISSUE TITLE
tftpgen performance issue

### ISSUE THREAD

**Issue by tpw56j** [cobbler/cobbler#3259]
### Describe the bug

With a large number of profiles, editing one profile takes too long and exceeds the timeout.

### Steps to reproduce

1. `# cobbler menu list | wc -l`
32
2. `# cobbler profile list | wc -l`
189
3. `# cobbler profile edit --enable-menu=true --menu=Linux --name=Fedora-latest-x86_64`

### Expected behavior

The command should have completed successfully.
### Cobbler version

````paste below
3.3.3
````
### Operating system

Fedora release 36 (Thirty Six)
### Cobbler log

````paste below
Traceback (most recent call last):
..
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 192.168.100.60:80/cobbler_api: 502 Proxy Error>
````
httpd error_log:
````paste below
[Sun Sep 25 11:08:21.676744 2022] [proxy_http:error] [pid 10792:tid 10950] (70007)The timeout specified has expired: [client 192.168.100.60:36800] AH01102: error reading status line from remote server 127.0.0.1:25151
[Sun Sep 25 11:08:21.676848 2022] [proxy:error] [pid 10792:tid 10950] [client 192.168.100.60:36800] AH00898: Error reading from remote server returned by /cobbler_api
````

### Additional information

At first I thought that the problem is that we read templates from disk many times to generate menus and this takes a lot of time. I tried to fix it:
```diff
+++ tftpgen.py	2022-09-25 11:30:06.348040812 +0300
@@ -53,6 +53,9 @@
         self.menus = api.menus()
         self.templar = templar.Templar(self.api)
         self.bootloc = self.settings.tftpboot_location
+        self.menu_template = {}
+        self.submenu_template = {}
+        self.item_template = {}
@@ -313,23 +316,25 @@
 
         # Write the PXE menu:
         if 'pxe' in menu_items:
-            loader_metadata["menu_items"] = menu_items['pxe']
-            loader_metadata["menu_labels"] = {}
+            loader_metadata["menu_items"] = menu_items.get("pxe", "")
+            loader_metadata["menu_labels"] = menu_labels.get("pxe", "")
             outfile = os.path.join(self.bootloc, "pxelinux.cfg", "default")
-            template_src = open(os.path.join(self.settings.boot_loader_conf_template_dir, "pxe_menu.template"))
-            template_data = template_src.read()
-            boot_menu['pxe'] = self.templar.render(template_data, loader_metadata, outfile)
-            template_src.close()
+            if "pxe" not in self.menu_template:
+                template_src = open(os.path.join(self.settings.boot_loader_conf_template_dir, "pxe_menu.template"))
+                self.menu_template["pxe"] = template_src.read()
+                template_src.close()
+            boot_menu['pxe'] = self.templar.render(self.menu_template["pxe"], loader_metadata, outfile)
 
         # Write the iPXE menu:
         if 'ipxe' in menu_items:
-            loader_metadata["menu_items"] = menu_items['ipxe']
-            loader_metadata["menu_labels"] = menu_labels['ipxe']
+            loader_metadata["menu_items"] = menu_items.get("ipxe", "")
+            loader_metadata["menu_labels"] = menu_labels.get("ipxe", "")
             outfile = os.path.join(self.bootloc, "ipxe", "default.ipxe")
-            template_src = open(os.path.join(self.settings.boot_loader_conf_template_dir, "ipxe_menu.template"))
-            template_data = template_src.read()
-            boot_menu['ipxe'] = self.templar.render(template_data, loader_metadata, outfile)
-            template_src.close()
+            if "ipxe" not in self.menu_template:
+                template_src = open(os.path.join(self.settings.boot_loader_conf_template_dir, "ipxe_menu.template"))
+                self.menu_template["ipxe"] = template_src.read()
+                template_src.close()
+            boot_menu['ipxe'] = self.templar.render(self.menu_template["ipxe"], loader_metadata, outfile)
 
         # Write the grub menu:
         for arch in enums.Archs:
@@ -507,31 +537,40 @@
                   utils.get_supported_system_boot_loaders().
         """
         metadata = {}
         for boot_loader in boot_loaders:
-            template = os.path.join(self.settings.boot_loader_conf_template_dir, "%s_submenu.template" % boot_loader)
-            if os.path.exists(template):
-                with open(template) as template_fh:
-                    template_data[boot_loader] = template_fh.read()
-                if menu:
-                    parent_menu = menu.parent
-                    metadata["menu_name"] = menu.name
-                    metadata["menu_label"] = \
-                        menu.display_name if menu.display_name and menu.display_name != "" else menu.name
-                    if parent_menu:
-                        metadata["parent_menu_name"] = parent_menu.name
-                        if parent_menu.display_name and parent_menu.display_name != "":
-                            metadata["parent_menu_label"] = parent_menu.display_name
-                        else:
-                            metadata["parent_menu_label"] = parent_menu.name
-                    else:
-                        metadata["parent_menu_name"] = "Cobbler"
-                        metadata["parent menu_label"] = "Cobbler"
-            else:
-                self.logger.warning("Template for building a submenu not found for bootloader \"%s\"! Submenu "
-                                    "structure thus missing for this bootloader.", boot_loader)
+            if boot_loader not in self.submenu_template:
+                template = os.path.join(
+                    self.settings.boot_loader_conf_template_dir,
+                    "%s_submenu.template" % boot_loader,
+                )
+                if os.path.exists(template):
+                    with open(template) as template_fh:
+                        self.submenu_template[boot_loader] = template_fh.read()
+                else:
+                    self.logger.warning(
+                        'Template for building a submenu not found for bootloader "%s"! Submenu '
+                        "structure thus missing for this bootloader.",
+                        boot_loader,
+                    )
 
         self.get_submenus(menu, metadata, arch)
         nested_menu_items = metadata["menu_items"]
````
````diff
-            if menu and boot_loader in template_data:
+            if menu and boot_loader in self.submenu_template:
                 metadata["menu_items"] = menu_items[boot_loader]
                 if boot_loader in menu_labels:
                     metadata["menu_labels"] = menu_labels[boot_loader]
-                menu_items[boot_loader] = self.templar.render(template_data[boot_loader], metadata, None)
+                menu_items[boot_loader] = self.templar.render(
+                    self.submenu_template[boot_loader], metadata, None
+                )
                 if boot_loader == "ipxe":
-                    menu_items[boot_loader] += '\n'
+                    menu_items[boot_loader] += "\n"
         metadata["menu_items"] = menu_items
         metadata["menu_labels"] = menu_labels
         return metadata
````
````diff
@@ -675,9 +724,12 @@
 
         # get the template
         if metadata["kernel_path"] is not None:
-            template_fh = open(template)
-            template_data = template_fh.read()
-            template_fh.close()
+            if format not in self.item_template:
+                template = os.path.join(self.settings.boot_loader_conf_template_dir, format + ".template")
+                template_fh = open(template)
+                self.item_template[format] = template_fh.read()
+                template_fh.close()
+            template_data = self.item_template[format]
         else:
             # this is something we can't PXE boot
             template_data = "\n"
````
But the result remained the same, profile edit also threw a timeout error. So I profiled `make_pxe_menu` and got this result:
```
>>> p.sort_stats(SortKey.CUMULATIVE).print_stats(20)
Sun Sep 25 11:08:59 2022    cobbler.stats0

         80609211 function calls (79331248 primitive calls) in 96.577 seconds

   Ordered by: cumulative time
   List reduced from 1225 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       12    0.000    0.000   96.560    8.047 tftpgen.py:362(get_menu_items)
   396/12    0.009    0.000   96.560    8.047 tftpgen.py:541(get_menu_level)
   396/12    0.006    0.000   96.541    8.045 tftpgen.py:372(get_submenus)
      396    0.019    0.000   96.271    0.243 tftpgen.py:424(get_profiles_menu)
      834    0.194    0.000   95.445    0.114 tftpgen.py:643(write_pxe_file)
     2502    0.706    0.000   92.864    0.037 utils.py:635(blender)
   164472   38.724    0.000   79.292    0.000 item.py:897(to_dict)
      834    0.031    0.000   64.191    0.077 tftpgen.py:760(build_kernel)
      834    0.041    0.000   30.014    0.036 tftpgen.py:840(build_kernel_options)
2812488/1917395    9.166    0.000   22.154    0.000 copy.py:128(deepcopy)
410292/137598    1.364    0.000    8.466    0.000 api.py:980(find_items)
    11880    1.635    0.000    8.377    0.001 utils.py:780(__consolidate)
   137598    0.530    0.000    7.910    0.000 api.py:1034(__find_by_name)
 26851769    7.732    0.000    7.742    0.000 {built-in method builtins.isinstance}
   272694    1.463    0.000    6.156    0.000 api.py:1015(__find_with_collection)
  7213140    5.868    0.000    5.868    0.000 {method 'lower' of 'str' objects}
  1918790    4.797    0.000    5.820    0.000 copy.py:243(_keep_alive)
 15141433    5.120    0.000    5.120    0.000 {method 'startswith' of 'str' objects}
   940187    2.413    0.000    4.368    0.000 copy.py:227(_deepcopy_dict)
   978603    1.744    0.000    3.706    0.000 copy.py:201(_deepcopy_list)
```
I see here that the problem is not directly related to the tftpgen.py code:
1. 12(!) `get_menu_items` calls were made to change one profile
2. most of the code execution time was in `utils.py:635(blender)`

So far I haven't found a simple solution to this problem.

**Comment by SchoolGuy** [comment]
Yes I am aware. The clean solution is to separate the generation more to not have unneeded regeneration of config files that stay the same. However the detection mechanism of this is very hard (how do you actually know that nothing has changed). If you look at the most time consuming thing that is actually `item.py:to_dict`. However I have no clue how to reduce the time of that method sadly. Also we have a significant overhead here with `isinstance` but the point of me adding this all around is to prevent that data is being invalid and the silently corrupting data. Sooo I guess I need to finally get my open PRs in and then focus on performance as soon as I can. (Which was the plan anayway)

**Comment by tpw56j** [comment]
@SchoolGuy I think we can start by trying to reduce the number of `make_pxe_menu` calls per profile edit. 96÷12=8s - I would be happy)

**Comment by SchoolGuy** [comment]
@tpw56j Okay. Feel free to suggest things. As said, I need to free my plate before putting more on there.

**Comment by tpw56j** [comment]
@SchoolGuy  Thanks! I will try to study the code and suggest a PR.

**Comment by SchoolGuy** [comment]
@tpw56j Any progress on this front? I am brainstorming about this as well in the context of #2804 and have gotten nowhere atm.

**Comment by tpw56j** [comment]
@SchoolGuy Unfortunately, I haven't had time to do this yet. Maybe later I will have some ideas.

**Comment by SchoolGuy** [comment]
@tpw56j No worries. Thanks for the update.

**Comment by tpw56j** [comment]
@SchoolGuy I had time to look into this problem and this is what I found:
- there is a significant positive effect of template caching.
- I only discovered it now because the OS was rebooted

Replacing the code with a new one with a restart of `cobblerd` and `httpd` does not change the execution time:
```bash
# systemctl stop cobblerd
# systemctl stop httpd

# cp tftpgen.py.new tftpgen.py

# systemctl start httpd
# systemctl start cobblerd

# time cobbler profile edit --name=Fedora-latest-x86_64 --menu=Linux
..
TimeoutError: [Errno 110] Connection timed out

real	2m11,088s
user	0m0,189s
sys	0m0,007s
```
But if you restart the OS, then the improvement becomes noticeable:
```bash
# time cobbler profile edit --name=Fedora-latest-x86_64 --menu=Linux

real	0m42,453s
user	0m0,180s
sys	0m0,011s
```
I did this several times and every time I got the same results. Why it was necessary to restart the OS in order for the code to start working faster, I could not explain, and this remains a mystery to me.

**Comment by tpw56j** [comment]
@SchoolGuy My suggestions:
1. Since item.py:to_dict is too slow and there are no ways to speed it up, it is possible to cache the  item's dict representation in the object itself. Any change to the object invalidates the cache. And the next time you call `to_dict`, the cache is rebuilt.
2. It seems to me that at cobbler startup it is enough to scan the contents of directories with items without reading and parsing the items themselves. And reading and parsing should be done according to the principle of a lazy cache as needed.

For the cache to work, you need metadata to describe the state of each items:
- free - if the item has not yet been read from disk
- clean - if the item has not been changed since the last read/write from/to disk
- dirty - if the item has been changed or new created
- deleted - if you want the persistence layer to remove the item

It is also possible to keep track of the state of each item field in the same metadata.

**Comment by SchoolGuy** [comment]
@tpw56j If I might summarize to understand your last two comments:

- Promoting templates to first-level objects and keeping them in memory is useful (well you said cache templates but instead I would try to promote them for easier management).
- Lazy loading items on a per-need basis - Open question for me is how do we validate at startup that everything is valid?
- Add a caching layer that adds to the performance gains of the two methods above

If I understand this right we could track these three approaches separately and also implement them separately.

**Comment by tpw56j** [comment]
@SchoolGuy I'm sorry, I didn't think about the validity check at the start of cobbler. There are of course ways to get around this, but it seems to me that these workarounds will lead to unjustified complication.

There are 2 ideas left:
- templates caching
- caching the results of item.py:to_dict in Item

**Comment by SchoolGuy** [comment]
@tpw56j Okay perfect. I would try to promote templates then to a first-level object. That is essentially the same but I believe in the code we can gain benefits from this.

Caching `item.py` is more complicated because the last implementation was so bugged I removed it. However I am open to a proper implementation that is well-tested.

**Comment by tpw56j** [comment]
@SchoolGuy Or maybe just cache boot menu templates locally in TFTPGen? It seems to me that this is easier than promoting templates to first-level object.

**Comment by SchoolGuy** [comment]
@tpw56j Well yes but I am a fan of doing things properly. Also what we could do if templates are a first-level object, we can abstract the source of them better. This is for containerization a good point imho. Also we can cache them centrally like all other items.

**Comment by tpw56j** [comment]
@SchoolGuy Okay, that would indeed be more properly.
