### ISSUE TITLE
Impossible to use proxy settings in cobbler config for "signature update"

### ISSUE THREAD

**Issue by Creris** [cobbler/cobbler#3270]
### Describe the bug

It is impossible to use a proxy when attempting to run `cobbler signature update`(and potentially other commands that might interact with the proxy setting `proxy_url_ext` from the cobbler config) because of a conflict of the config schema and the way that the code uses the proxy variable.

### Steps to reproduce

1. set `proxy_url_ext` variable to a valid proxy string(for instance "http://127.0.0.1:3128")
2. run `cobbler signature update`

### Expected behavior

The command should successfully run without throwing an exception from within the requests library.

### Cobbler version

````paste below
Cobbler 3.4.0
  source: ?, ?
  build time: Wed Oct 19 09:35:00 2022
````

Please note that this is a custom build from a git commit f6bc81367d49a0b1f76b3af64af4ef0d496166ec.

### Operating system

Ubuntu 22.04

### Cobbler log

````paste below
Nov 15 16:20:14 my_server.local cobblerd[7068]: INFO | start_task(sigupdate); event_id(2022-11-15_162014_Updating Signatures_e917e570bf834ba08dc2fb35039a2cad)
Nov 15 16:20:14 my_server.local cobblerd[7068]: INFO | Exception occurred: <class 'AttributeError'>
Nov 15 16:20:14 my_server.local cobblerd[7068]: INFO | Exception value: 'str' object has no attribute 'get'
Nov 15 16:20:14 my_server.local cobblerd[7068]: INFO | Exception Info:
Nov 15 16:20:14 my_server.local cobblerd[7068]:   File "/usr/lib/python3/dist-packages/cobbler/api.py", line 1563, in signature_update
Nov 15 16:20:14 my_server.local cobblerd[7068]:     sigjson = dlmgr.urlread(url)
Nov 15 16:20:14 my_server.local cobblerd[7068]:   File "/usr/lib/python3/dist-packages/cobbler/download_manager.py", line 40, in urlread
Nov 15 16:20:14 my_server.local cobblerd[7068]:     return requests.get(url, proxies=proxies, cert=cert)
Nov 15 16:20:14 my_server.local cobblerd[7068]:   File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
Nov 15 16:20:14 my_server.local cobblerd[7068]:     return request('get', url, params=params, **kwargs)
Nov 15 16:20:14 my_server.local cobblerd[7068]:   File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
Nov 15 16:20:14 my_server.local cobblerd[7068]:     return session.request(method=method, url=url, **kwargs)
Nov 15 16:20:14 my_server.local cobblerd[7068]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 532, in request
Nov 15 16:20:14 my_server.local cobblerd[7068]:     settings = self.merge_environment_settings(
Nov 15 16:20:14 my_server.local cobblerd[7068]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 710, in merge_environment_settings
Nov 15 16:20:14 my_server.local cobblerd[7068]:     no_proxy = proxies.get('no_proxy') if proxies is not None else None
Nov 15 16:20:14 my_server.local cobblerd[7068]: INFO | ### TASK COMPLETE ###
````

### Additional information

This issue stems from the fact that the config schema requires the `proxy_url_ext` field to be a string, and then it is loaded without any other processing inside the `DownloadManager` class from the loaded YAML config.
This value is then passed into requests as-is(a string, as per requirement of the schema) since the instance of `DownloadManager` in "api.py" does not use the `proxies` parameter.
Requests since at least version 1.0.4(oldest documentation that they host on their page) requires that the `proxies` parameter be a dictionary, but the `self.proxies` is a string so requests just raises an exception from within its internals when trying to call `.get` on the passed string.

We tried to set the `proxy_url_ext` variable to a format that would be loaded into proper structure but the schema defined for the config file will then raise an exception stating that the field must be a string.

**Comment by SchoolGuy** [comment]
@Creris Do you know which version of requests introduced this change?

**Comment by Creris** [comment]
The first version that supports the proxies parameter of requests is 0.5.0, I checked the source code real quick and the docstring says that the proxies parameter has to be a dictionary. The closest earlier version of requests is 0.4.1 whose source I also peaked at and the docstring for the request function does not support proxies at all.

From this I deduce that requests has never supported any other format of `proxies` parameter than a dictionary with `{ protocol: address }`.
This is even stated in a comment inside the download_manager.py file: https://github.com/cobbler/cobbler/blob/main/cobbler/download_manager.py#L24 , the only problem is that the field that is loaded right after that must be a string based on the schema validation.

**Comment by SchoolGuy** [comment]
Okay. Thanks for the information. If it is possible I would love if a PR is opened by the community by this. I personally won't be able to fix this in the coming weeks.

**Comment by Creris** [comment]
I can try to make a PR that fixes at least this issue, Ive seen the proxy config field used in some tests and one other class so changing the schema sounds like a bad idea.

**Comment by taleintervenor** [comment]
Is there any progress on this bug? Or how can we disable the proxy_url_ext option?
It seems the cobbler signature update can't work at all.

**Comment by SchoolGuy** [comment]
@taleintervenor Feel free to open a PR for this. Atm there are bugs and problems in the core feature that have more priority than this bug. The active manpower of this project is not so high that we can just squash these kinds of bugs in a matter of days or weeks sadly. I will happily review a PR and support the opening contributor in any way I can.

**Comment by opoplawski** [comment]
Closing this as duplicate
