### ISSUE TITLE
ESXi guest unable to boot using efi

### ISSUE THREAD

**Issue by ApertureDevelopment** [cobbler/cobbler#3272]
### Describe the bug

It seems that my VMware ESXi guests are unable to boot using efi PXE. When trying to boot using Legacy PXE everything works as expected. I have already figured out that the templated filename option inside the dhcp file did not match the actual loader filename. After fixing that I get a step further, but it still does not want to boot.

### Steps to reproduce

1. Setup cobbler
2. Start the ESXi guest

### Expected behavior

The ESXi guest should boot from PXE and present the RockyLinux install options.

### Cobbler version

````
Cobbler 3.3.3
  source: ?, ?
  build time: Tue Jun 14 00:00:00 2022
````

### Operating system

RedHat Enterprise Linux 9.1 (Plow) - x86_64

### Cobbler log

[smalllog.log](https://github.com/cobbler/cobbler/files/10032634/smalllog.log)

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/16450982/202486359-765f1e7b-6f34-4d65-9870-dc9b329f2972.png)

**Comment by SchoolGuy** [comment]
So since the bootloaders was successfully downloaded I am bit puzzled. Normally GRUB would then throw an error if a configuration file (like `grub.cfg`) was incorrect from a syntax perspective. However here all we have is "unsuccessful". That is not much to go with.

Is it a great effort for you to try a recent Fedora or Rocky Linux as a Cobbler host?

**Comment by javier-angulo** [comment]
ESXi does not support grub, and (sadly) you cannot chainload the ESXi efi bootloader with grub. Which is what cobbler is trying to do from the image. @SchoolGuy I was also puzzled for a long time until I could confirm that grub was not supported. You need to provide via TFTP the esxi own efi bootloader (on the ESXi installation iso, file `efi/boot/bootx64.efi`, and must be renamed as `mboot.efi`). Then, the bootloader will try to download `boot.cfg` from the same location as `mboot.efi`.

@ApertureDevelopment cobbler does not support installing ESXi with UEFI boot until version 3.4 (which has not been released yet). Here are the instructions (for version 3.4): https://cobbler.readthedocs.io/en/latest/user-guide/esxi.html

As you mentioned you had been able to PXE boot the ESXI via BIOS, I am curious about the version of `pxelinux.0` you are using. VMware docs explicitly instruct to use version from `syslinux 3.86` . It still worked on rhel7's `syslinux 4.x`, but with `syslinux 6.x` (which is rhel9 version), I could not make it work to pxeboot ESXi.

**Comment by ApertureDevelopment** [comment]
> ESXi does not support grub, and (sadly) you cannot chainload the ESXi efi bootloader with grub. Which is what cobbler is trying to do from the image. @SchoolGuy I was also puzzled for a long time until I could confirm that grub was not supported. You need to provide via TFTP the esxi own efi bootloader (on the ESXi installation iso, file `efi/boot/bootx64.efi`, and must be renamed as `mboot.efi`). Then, the bootloader will try to download `boot.cfg` from the same location as `mboot.efi`.
> 
> @ApertureDevelopment cobbler does not support installing ESXi with UEFI boot until version 3.4 (which has not been released yet). Here are the instructions (for version 3.4): https://cobbler.readthedocs.io/en/latest/user-guide/esxi.html
> 
> As you mentioned you had been able to PXE boot the ESXI via BIOS, I am curious about the version of `pxelinux.0` you are using. VMware docs explicitly instruct to use version from `syslinux 3.86` . It still worked on rhel7's `syslinux 4.x`, but with `syslinux 6.x` (which is rhel9 version), I could not make it work to pxeboot ESXi.

Sorry, but I think you misunderstood my issue. I am not trying to install ESXi using PXE, I am trying to install ESXi guests ( Virtual Machines ) using PXE. WHile ESXi may not support being installed using grub, it certainly does support grub inside their VMs/guests.

**Comment by ApertureDevelopment** [comment]
> So since the bootloaders was successfully downloaded I am bit puzzled. Normally GRUB would then throw an error if a configuration file (like `grub.cfg`) was incorrect from a syntax perspective. However here all we have is "unsuccessful". That is not much to go with.
> 
> Is it a great effort for you to try a recent Fedora or Rocky Linux as a Cobbler host?

I can do that. I am actually setting up Fedora and Rocky guests for this right now

**Comment by javier-angulo** [comment]
> Sorry, but I think you misunderstood my issue. I am not trying to install ESXi using PXE, I am trying to install ESXi guests ( Virtual Machines ) using PXE. WHile ESXi may not support being installed using grub, it certainly does support grub inside their VMs/guests.

Ooops sorry for noise!

**Comment by ApertureDevelopment** [comment]
> > Sorry, but I think you misunderstood my issue. I am not trying to install ESXi using PXE, I am trying to install ESXi guests ( Virtual Machines ) using PXE. WHile ESXi may not support being installed using grub, it certainly does support grub inside their VMs/guests.
> 
> Ooops sorry for noise!

No worries



> > So since the bootloaders was successfully downloaded I am bit puzzled. Normally GRUB would then throw an error if a configuration file (like `grub.cfg`) was incorrect from a syntax perspective. However here all we have is "unsuccessful". That is not much to go with.
> > Is it a great effort for you to try a recent Fedora or Rocky Linux as a Cobbler host?
> 
> I can do that. I am actually setting up Fedora and Rocky guests for this right now

Okay, I am still in the process of doing this, but I did some experimenting. I have just added a physical NIC to the vSwitch cobbler is connected to and tried to use UEFI PXE using a physical device. And voilà, it works. So I am assuming this is either a bug in the grub binaries from RHEL, or this is actually a bug in the ESXi EFI implementation. I am gonna try again using fedora and keep you updated

**Comment by ApertureDevelopment** [comment]
Okay, so this actually seems to be a bug in ESXi itself. I am gonna close this and open an issue at VMware
