### ISSUE TITLE
Systems cannot access kickstart files <server>/cblr/svc/op/autoinstall/system/<FQDN>

### ISSUE THREAD

**Issue by ckotte** [cobbler/cobbler#3287]
### Describe the bug

Sorry. Maybe I have overlooked something. I followed the installation procedure, but I cannot find what should be listening on port 8000.

Port 8000 is configured in cobbler.conf in /etc/httpd/conf.d.

### Steps to reproduce

1.git clone https://github.com/cobbler/cobbler.git
2.make rpms
3.rpm -Uvh rpm-build/cobbler-3.4.0-1.el8.noarch.rpm
4. systemctl start cobblerd
5. systemctl start httpd

### Expected behavior

Kickstart file can be accessed in the browser

### Cobbler version

````
# cobbler version
Cobbler 3.4.0
  source: 8db6b958, Sun Nov 20 17:47:56 2022 +0100
  build time: Fri Nov 25 12:55:33 2022
````

### Operating system

RHEL 8.6

### Cobbler log

None

### Screenshots

<img width="866" alt="image" src="https://user-images.githubusercontent.com/8488565/205074855-9eb77277-f82d-46b4-8861-1ba81d178ed5.png">

### Additional information

None

**Comment by SchoolGuy** [comment]
This may be due to the recent change we did with Gunicorn. It seems the documentation was not updated.

**Comment by ckotte** [comment]
Do I understand it right? I can use Gunicorn, Apache, NGINX or whatever I want as a web server hosting the API everything else?

Do I have to change the makefile to use another web server? I would like to use NGINX instead of Apache.

**Comment by SchoolGuy** [comment]
Nope the setup is now:

- CobblerAPI --> opens a port itself
- CobblerSvc --> Hosted by Gunicorn

Apache just acts as a proxy for Gunicorn and the CobblerAPI.

**Comment by ckotte** [comment]
Cobbler listens on port 25151, but nothing listens on port 8000:

```
# netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      2550541/httpd
tcp        0      0 127.0.0.1:25151         0.0.0.0:*               LISTEN      2202429/python3
tcp        0      0 0.0.0.0:47391           0.0.0.0:*               LISTEN      33714/rpc.statd
tcp        0      0 0.0.0.0:59999           0.0.0.0:*               LISTEN      32108/linux_agent_e
tcp        0      0 0.0.0.0:50051           0.0.0.0:*               LISTEN      32108/linux_agent_e
tcp        0      0 0.0.0.0:33221           0.0.0.0:*               LISTEN      47232/pmd
tcp        0      0 127.0.0.1:199           0.0.0.0:*               LISTEN      37137/snmpd
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2550541/httpd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      33986/sshd
```

**Comment by SchoolGuy** [comment]
Yes exactly.

**Comment by ckotte** [comment]
Would be nice if you could help me fixing this. We want to upgrade 300+ systems, distributed around the world, from CentOS7 (cobbler 2.8.x) to RHEL8.6 (Cobbler 3.x.x). I need a UI with basic functionality, but 3.2.2 doesn't work for me (import distro, etc. pp.). That's why I want to use main of cobbler (hopefully 3.4.0 gets released soon) and cobbler-web (Angular UI).

**Comment by SchoolGuy** [comment]
@ckotte So in this case I recommend going through https://cobbler.github.io/blog/2022/11/15/roadmap-update.html any help is appreciated. Especially experts in golang and/or in Angular would be a huge help. If you require I can try to consult a bit in my free time with video calls but at the moment it is mainly me driving the new features, thus if I get sick/family interruptions/... it will take longer.

**Comment by ckotte** [comment]
@SchoolGuy I will check if I can get someone to help with Angular or golang. Let me try the UI first.

**Comment by ckotte** [comment]
I could fix this issue. I only need a systemd service for gunicorn and I need to modify httpd config

/usr/lib/systemd/system/gunicorn.service
```
[Unit]
Description=Cobbler Gunicorn Daemon
After=syslog.target network.target
Wants=cobblerd.service

[Service]
ExecStart=/usr/bin/gunicorn cobbler.services:application
PrivateTmp=yes
KillMode=process

[Install]
WantedBy=multi-user.target
```

/etc/httpd/conf.d/cobbler.conf
```
<VirtualHost *:80>

    #AliasMatch ^/cblr(?!/svc/)(.*)?$ "/var/www/cobbler$1"
    AliasMatch ^/cobbler_track(.*)?$ "/var/www/cobbler$1"
    Alias /cobbler /var/www/cobbler

    Alias /httpboot /var/lib/tftpboot/grub
    Alias /images /var/lib/tftpboot/grub/images

    ProxyPass /cblr/svc/ http://localhost:8000/

   ...
```

I will check how to deploy this via setup.py and create a pull request.

**Comment by SchoolGuy** [comment]
@ckotte Please remember that it is not functional atm.

**Comment by SchoolGuy** [comment]
@ckotte Remeber that the UI is atm more of a rough skeleton and it will not display anything as the connecting pieces are a WIP.

**Comment by ckotte** [comment]
@SchoolGuy Understand. I will try to get some help if we have someone with golang/Angular skills in the company.

**Comment by SchoolGuy** [comment]
@ckotte I will do a bigger documentation overhaul and include this change. I would welcome your opinion once the PR is open.
