### ISSUE TITLE
Anamon cannot send logs to cobbler server

### ISSUE THREAD

**Issue by ckotte** [cobbler/cobbler#3324]
### Describe the bug

Anamon cannot send logs to cobbler server. Invalid data type is logged in cobbler.log on the cobbler server.

### Steps to reproduce

1. Switch `anamon_enabled: true`
2.Download anamon script to /tmp
3. Create /tmp/anaconda.log with some content
4. Execute script with: `/tmp/anamon --name "FQDN" --server "SERVER" --port "80" --debug`
5. Error logged in cobbler.log. See below.

### Expected behavior

Logs appear in `/var/log/cobbler/anamon/<system>/`

### Cobbler version

````
Cobbler 3.2.2
  source: ?, ?
  build time: Fri Aug 26 01:42:52 2022
````

```
Cobbler 3.4.0
  source: 8db6b958, Sun Nov 20 17:47:56 2022 +0100
  build time: Fri Nov 25 12:55:33 2022
```

### Operating system

RHEL8
cobbler-3.2.2-13.module_el8+15284+5d084733.noarch in EPEL repo 
OR 
main (November 25th)

### Cobbler log

````
2022-12-06T18:33:36 - WARNING | upload_log_data - One of the parameters handed over had an invalid type!
````

### Screenshots

n/a

### Additional information

n/a

**Comment by SchoolGuy** [comment]
During working on this issue I realized that we are missing documentation about Anamon. I will add this to the linked PRs.
