### ISSUE TITLE
PXE Response when NetBoot=false

### ISSUE THREAD

**Issue by btsherid** [cobbler/cobbler#3331]
Hi,

Our Cobbler system doesn't seem to be working the way I would expect.

When NetBoot=true, the host get a PXE response and installs an OS. This is working fine.

When NetBoot=false, the host does not get a PXE response (No DHCP offers were received). The PXE boot eventually times out, the host falls back to the second boot option of hard disk and it then boots to the OS. This works, but the host would boot faster if Cobbler sent a PXE response. Other bare metall installer software I have used does this, so I'm wondering if Cobbler is supposed to and if so, how can I fix this?

Since most of our servers are UEFI boot, I had to do a fair amount of tinkering with the TFTP installation to get Cobbler to work and actually install an OS, so something may be missing or need to be tweaked in my installation.

Thank You,
Brendan Sheridan

**Comment by btsherid** [comment]
I was able to fix this by adding pxelinux.0 into /var/lib/cobbler/loaders/CentOS7-x86-64/.

CentOS7-x86-64 is the profile name. Before, the only two files in that directory were grubx64.efi and shimx64.efi.

**Comment by SchoolGuy** [comment]
Hi! Could you please tell me which version of Cobbler you are using? Depending on it there should be either a script called `mkgrub.sh`, a command called  `cobbler mkgrub` or `cobbler mkloaders` (current version). These should automate the task you just performed manually.

**Comment by btsherid** [comment]
Hi,

I'm running Cobbler 3.2.2. 

I found <code>/usr/share/cobbler/bin/mkgrub.sh</code>. Both <code>cobbler mkgrub</code> and <code>cobbler mkloaders</code> returned No such command.

**Comment by SchoolGuy** [comment]
Yeah so `mkgrub.sh` is already part of 3.2.2. Thus I would advice you to use it in the long-term every time your OS got an update from one of the bootloaders.

See here: https://github.com/cobbler/cobbler/blob/v3.2.2/scripts/mkgrub.sh

**Comment by btsherid** [comment]
Thanks. <code>mkgrub.sh</code> looks like it worked. I was able to remove my CentOS7-x86-64 folder. 

It might be helpful if <code>mkgrub.sh</code> is added to the documentation somewhere.
