### ISSUE TITLE
XML-RPC: Boolean values cannot be set with `modify_setting`

### ISSUE THREAD

**Issue by xuezhixin** [cobbler/cobbler#3336]
### Describe the bug

```
[root@localhost cobbler]# cobbler sync --dhcp
task started: 2023-02-02_051336_Sync_f09f71089bbe47bc8299204141feebf2
task started (id=Sync, time=Thu Feb  2 05:13:36 2023)
start_task(sync); event_id(2023-02-02_051336_Sync_f09f71089bbe47bc8299204141feebf2)
"manage_dhcp" not set. Skipping DHCP sync.
*** TASK COMPLETE ***

[root@localhost cobbler]# cobbler setting edit --name=manage_dhcp --value=true
Changing the setting failed
```

The configuration file was not changed.

`settings.yaml`:

```yaml
manage_dhcp: false
manage_dhcp_v4: false
```

### Expected behavior

The configuration file can be written normally

### Cobbler version

_v3.4.0_

### Operating system

```
[root@localhost dhcp]# cat /etc/os-release 
NAME="Fedora Linux"
VERSION="37 (Server Edition)"
ID=fedora
VERSION_ID=37
```
### Cobbler log

```
INFO | REMOTE create_task(Sync); event_id(2023-02-02_051425_Sync_cc59548baaf74238851c757a040bd3a7); user(?)
INFO | start_task(sync); event_id(2023-02-02_051425_Sync_cc59548baaf74238851c757a040bd3a7)
INFO | "manage_dhcp" not set. Skipping DHCP sync.
INFO | ### TASK COMPLETE ###
```

### Screenshots

None

**Comment by SchoolGuy** [comment]
@xuezhixin So I looked into your bug again.

The error message you are seeing is from the CLI directly. The error message appears if the return code from the XML-RPC is not `0`. Thus the reason for this must be in the log file. The log entries in the issue report only show the `cobbler sync`. The relevant lines can be found probably directly during the time you execute the command. However the reasons for this can range from a disabled `allow_dynamic_settings` setting to a real bug.

Please extend your bug report with the required information or it will be hard for me to help you. The PR you opened has no real change and is in fact IMHO not providing the changes that you need to fix this bug - if it is one.

**Comment by xuezhixin** [comment]
```
[root@localhost cobbler]# grep allow_dynamic_settings /etc/cobbler/settings.yaml 
allow_dynamic_settings: true
[root@localhost cobbler]# cobbler setting edit --name=manage_dhcp --value=true
Changing the setting failed
```

```
print("_______",getattr(self.api.settings(), setting_name))
print("_______",isinstance(getattr(self.api.settings(), setting_name), int))
_______ False
_______ True
```
Thank you for your attention. This was recorded during my self-test, **allow_dynamic_settings=true**. If you need, I will provide the corresponding error log later.In addition, I submitted pytest and set **allow_dynamic_settings=true**.

**Comment by SchoolGuy** [comment]
@xuezhixin So seeing the debugging you did tells me the following things:

1. The setting that is present inside `setting_name` is `False`.
2. Due to the implementation details of booleans in Python it is of course also a valid integer.

I looked at the code again and found the bug myself now I believe. Hopefully, with the output of the following prompt, you understand too what needs to be done:

```
(venv) enno@dell-workhorse:~/Sources/git/cobbler> python3
Python 3.10.9 (main, Dec 08 2022, 14:49:06) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> isinstance(False, int)
True
>>> isinstance(0, int)
True
>>> isinstance(False, int)
True
>>> isinstance(False, bool)
True
>>> isinstance(0, bool)
False
```

If I am not mistaken we actually want to do the following:

```patch
diff --git a/cobbler/remote.py b/cobbler/remote.py
index ffc0fad41..85e705c12 100644
--- a/cobbler/remote.py
+++ b/cobbler/remote.py
@@ -2038,10 +2038,10 @@ class CobblerXMLRPCInterface:
         try:
             if isinstance(getattr(self.api.settings(), setting_name), str):
                 value = str(value)
-            elif isinstance(getattr(self.api.settings(), setting_name), int):
-                value = int(value)
             elif isinstance(getattr(self.api.settings(), setting_name), bool):
                 value = self.api.input_boolean(value)
+            elif isinstance(getattr(self.api.settings(), setting_name), int):
+                value = int(value)
             elif isinstance(getattr(self.api.settings(), setting_name), float):
                 value = float(value)
             elif isinstance(getattr(self.api.settings(), setting_name), list):
```

Feel free to use this inside your patch but remember to submit also a test that shows that my guesswork (because I haven't verified if I am right) is actually correct.

**Comment by xuezhixin** [comment]
Yes, I will modify and resubmit.
