### ISSUE TITLE
IPs not being set on VLAN interfaces 

### ISSUE THREAD

**Issue by btsherid** [cobbler/cobbler#3340]
### Describe the bug

Hi,

I have a host where I would like to bond two physical ports and then have two VLAN interfaces off of that bond. The setup would look like this:

em3 em4   
   bond1 - No IP
   bond1.452   - IP address in VLAN 452
   bond1.1851 - IP address in VLAN 1851

Cobbler supports this setup and creates the correct interfaces on the, but does not set the IP addresses in the ifcfg files for bond1.452 and bond1.1851, even though the addresses show in cobbler system report. The end result is the host has ifcfg files for em3, em4, bond1, bond1.452, and bond1.1851 but none of the files have IPADDR or NETMASK lines in them.

### Steps to reproduce

1. Create host interfaces in cobbler:
    a. cobbler system edit --name <<name>> --interface=bond1 --interface-type=bond --bonding-opts="mode=4 miimon=100" --static=1
    b. cobbler system edit --name <<name>> --interface=bond1.452 --interface-type=bond_slave --interface-master=bond1 --ip-address <<VLAN 452 IP>> --netmask=255.255.254.0 --static=1 --dns-name <<name>>-pvt
    c. cobbler system edit --name << name >> --interface=bond1.1851 --interface-type=bond_slave --interface-master=bond1 --ip-address <<VLAN 1851 IP>> --netmask=255.255.254.0 --static=1 --dns-name <<name>>-pvt2
    d. cobbler system edit --name <<name>> --interface em3 --mac-address <<MAC>> --interface-master=bond1 --interface-type=bond_slave --management=true
    e. cobbler system edit --name <<name>> --interface em4 --mac-address <<MAC>> --interface-master=bond1 --interface-type=bond_slave --management=true
2. Verify with cobbler system report
3. Build node with Cobbler 
4. Check /etc/sysconfig/network-scripts/ifcfg-bond1.452 and /etc/sysconfig/network-scripts/ifcfg-bond1.1851 to see that no IPs have been configured.

### Expected behavior

I expect IP addresses to be set in the ifcfg files when the node is built.

### Cobbler version

Cobbler 3.2.2
  source: ?, ?
  build time: Fri Aug 26 01:42:52 2022

### Operating system

Cobbler is installed on Rocky Linux 8.6. All of the nodes get built with CentOS 7.9

### Additional information

cobbler system report --name r610-aba-3-3
Name                           : r610-aba-3-3
Automatic Installation Template : <<inherit>>
Automatic Installation Template Metadata : {}
TFTP Boot Files                : {}
Boot loader                    : <<inherit>>
Comment                        :
Enable gPXE?                   : <<inherit>>
Fetchable Files                : {}
DHCP Filename Override         : <<inherit>>
Gateway                        :
Hostname                       : r610-aba-3-3.local
Image                          :
IPv6 Autoconfiguration         : False
IPv6 Default Device            :
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : <<inherit>>
Management Parameters          : <<inherit>>
Name Servers                   : ['172.27.230.205']
Name Servers Search Path       : ['local', 'bioinf.unc.edu']
Netboot Enabled                : False
Next Server Override           : <<inherit>>
Owners                         : <<inherit>>
Power Management Address       :
Power Management ID            :
Power Identity File            :
Power Management Options       :
Power Management Password      :
Power Management Type          : ipmilan
Power Management Username      :
Profile                        : CentOS7-x86_64
Internal Proxy                 : <<inherit>>
Redhat Management Key          : <<inherit>>
Repos Enabled                  : False
Serial Baud Rate               :
Serial Device #                :
Server Override                : <<inherit>>
Status                         : production
Template Files                 : {}
Virt Auto Boot                 : <<inherit>>
Virt CPUs                      : <<inherit>>
Virt Disk Driver Type          : <<inherit>>
Virt File Size(GB)             : <<inherit>>
Virt Path                      : <<inherit>>
Virt PXE Boot                  : 0
Virt RAM (MB)                  : <<inherit>>
Virt Type                      : <<inherit>>
Interface =====                : bond0
Bonding Opts                   : mode=4 miimon=100
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       : r610-aba-3-3.local
Per-Interface Gateway          : 172.27.230.205
Master Interface               :
Interface Type                 : bond
IP Address                     : 172.27.231.227
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    :
Management Interface           : False
MTU                            : 9000
Subnet Mask                    : 255.255.254.0
Static                         : True
Static Routes                  : []
Virt Bridge                    :
Interface =====                : bond1
Bonding Opts                   : mode=4 miimon=100
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       :
Per-Interface Gateway          :
Master Interface               :
Interface Type                 : bond
IP Address                     :
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    :
Management Interface           : False
MTU                            :
Subnet Mask                    :
Static                         : False
Static Routes                  : []
Virt Bridge                    :
Interface =====                : bond1.452
Bonding Opts                   :
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       : r610-aba-3-3-pvt
Per-Interface Gateway          :
Master Interface               : bond1
Interface Type                 : bond_slave
IP Address                     : 172.27.143.227
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    :
Management Interface           : False
MTU                            :
Subnet Mask                    : 255.255.254.0
Static                         : True
Static Routes                  : []
Virt Bridge                    :
Interface =====                : bond1.1851
Bonding Opts                   :
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       : r610-aba-3-3-pvt2
Per-Interface Gateway          :
Master Interface               : bond1
Interface Type                 : bond_slave
IP Address                     : 172.27.40.227
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    :
Management Interface           : False
MTU                            :
Subnet Mask                    : 255.255.254.0
Static                         : True
Static Routes                  : []
Virt Bridge                    :
Interface =====                : em1
Bonding Opts                   :
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       :
Per-Interface Gateway          :
Master Interface               : bond0
Interface Type                 : bond_slave
IP Address                     :
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    : 00:22:19:69:8c:a7
Management Interface           : True
MTU                            :
Subnet Mask                    :
Static                         : False
Static Routes                  : []
Virt Bridge                    :
Interface =====                : em2
Bonding Opts                   :
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       :
Per-Interface Gateway          :
Master Interface               : bond0
Interface Type                 : bond_slave
IP Address                     :
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    : 00:22:19:69:8c:a9
Management Interface           : False
MTU                            :
Subnet Mask                    :
Static                         : False
Static Routes                  : []
Virt Bridge                    :
Interface =====                : em3
Bonding Opts                   :
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       :
Per-Interface Gateway          :
Master Interface               : bond1
Interface Type                 : bond_slave
IP Address                     :
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    : 00:22:19:69:8c:ab
Management Interface           : False
MTU                            :
Subnet Mask                    :
Static                         : False
Static Routes                  : []
Virt Bridge                    :
Interface =====                : em4
Bonding Opts                   :
Bridge Opts                    :
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       :
DNS Name                       :
Per-Interface Gateway          :
Master Interface               : bond1
Interface Type                 : bond_slave
IP Address                     :
IPv6 Address                   :
IPv6 Default Gateway           :
IPv6 MTU                       :
IPv6 Prefix                    :
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    : 00:22:19:69:8c:ad
Management Interface           : False
MTU                            :
Subnet Mask                    :
Static                         : False
Static Routes                  : []
Virt Bridge                    :

[root@r610-aba-3-3 ~]# cat /etc/sysconfig/network-scripts/ifcfg-bond1.452
DEVICE=bond1.452
ONBOOT=yes
SLAVE=yes
MASTER=bond1
HOTPLUG=no
TYPE=VLan
BOOTPROTO=none
VLAN=yes
VLAN_ID=452
PHYSDEV=bond1

[root@r610-aba-3-3 ~]# cat /etc/sysconfig/network-scripts/ifcfg-bond1.1851
DEVICE=bond1.1851
ONBOOT=yes
SLAVE=yes
MASTER=bond1
HOTPLUG=no
TYPE=VLan
BOOTPROTO=none
VLAN=yes
VLAN_ID=1851

[root@r610-aba-3-3 ~]# cat /etc/sysconfig/network-scripts/ifcfg-bond1
DEVICE=bond1
ONBOOT=yes
TYPE=Bond
BONDING_MASTER=yes
BONDING_OPTS="mode=4 miimon=100"
BOOTPROTO=dhcp
PEERDNS=no
DNS1=172.27.230.205

PHYSDEV=bond1

**Comment by btsherid** [comment]
I figured this out. I needed to remove interface-type and interface-master from my command:

INCORRECT: cobbler system edit --name <> --interface=bond1.452 --interface-type=bond_slave --interface-master=bond1 --ip-address <<VLAN 452 IP>> --netmask=255.255.254.0 --static=1 --dns-name <>-pvt

CORRECT: cobbler system edit --name <> --interface=bond1.452 --ip-address <<VLAN 452 IP>> --netmask=255.255.254.0 --static=1 --dns-name <>-pvt

**Comment by SchoolGuy** [comment]
@btsherid Do you believe the documentation should be improved or is lacking a piece of certain information? Or did this just take time since it is a more complicated setup?
