### ISSUE TITLE
Perfomance testsuite

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#3341]
### Is your feature request related to a problem?

As a user  
I want that Cobbler is performant enough  
so that I can use it without taking artificial breaks.

### Provide a detailed description of the proposed feature

To monitor our application's performance, we want to utilize [pytest-benchmark](https://github.com/ionelmc/pytest-benchmark). The suite should act as a gatekeeper for the performance of our application.

The measurement point of the performance will be the Python API. If a specific component is identified to eat up a non-acceptable amount of time during runtime it will receive its own set of performance tests if not directly exposed by the API.

Parameterized functions can use the following trick found in an issue of the pytest-benchmark project: https://github.com/ionelmc/pytest-benchmark/issues/48#issuecomment-207887664

To fail the performance tests we can use the following trick found in an issue of the pytest-benchmark project: https://github.com/ionelmc/pytest-benchmark/issues/178#issuecomment-675989711

Documentation for `pytest-benchmark`: <https://pytest-benchmark.readthedocs.io/en/latest/index.html>

### Baseline performance I would expect

The numbers named here shall be put up for discussion and are not final at the point of issue creation.

- `cobbler item add`: Adding an object in the application and persisting it in the datastore, as well as generating related files.
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler item edit`: Editing an arbitrary property of the item and persisting it in the datastore, as well generating related files.
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler item remove`: Removing an object in the application and persisting it in the datastore, as well as removing related files.
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler item rename`: Renaming all references in memory and on disk that are related to the item.
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler item copy`: Copying the item to the new name and generated all related files.
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler reposync`: Executing a reposync for all present repositories in Cobbler.
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler import`
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler check`: Checking for common problems in the instance and reporting those with possible desired mitigations.
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler hardlink`: Hardlinking all files that Cobbler is able to de-duplicate to save disk space.
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler mkloaders`: Number of installed bootloaders (each architecture counts as its own loader).
  - Single: <30 sec
  - 5: <1 min
  - 20: <5 min
- `cobbler replicate`
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler report`
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler status`
  - Single: <5 sec
  - 10k: TBD
  - 100k: TBD
- `cobbler sync`
  - Single: <5 sec
  - 10k: <10 min
  - 100k: <1 h

### Alternatives you've considered

None.

### Additional information

Context #3259

CC @tpw56j

**Comment by tpw56j** [comment]
It seems to me that we cannot easily set thresholds for a certain number of operations on abstract `Items`. The execution time of the operation depends on the `Item` type and topology of the relationships of these elements. Even in an ordinary tree structure, we can get a non-linear increase in execution time depending on the height of the tree, and in the case of the `Cobbler`, we are dealing with a more complex data structure - an object graph.

Therefore, I suggest using more test parameters:
- `n` - number of elements of non-hierarchical types (everything except profiles and menus)
- `m` - the number of elements of hierarchical types at the 1st level (profiles and menus).
- `l` - the height of the tree of hierarchical types
- `c` - the number of children of each element of hierarchical types

Test conditions:
- all elements must be interconnected.
- functions that modify objects (add, edit, copy, rename, etc.) are performed on each element, the total execution time is measured for each type separately
- other operations are performed on the set of elements as a whole

Next, we can apply the approach described in the https://pytest-benchmark.readthedocs.io/en/stable/comparing.html to compare the performance of commits. For example using `--benchmark-compare-fail=min:5%`.

Unfortunately, OBS restrictions do not allow the use of any realistic set of `Items`.
For example in https://github.com/cobbler/cobbler/pull/3301:
- `n` = 2
- `m` = 2
- `l` = 3
- `c` = 1

**Comment by SchoolGuy** [comment]
With #3301 we will gain the first version of this new testsuite. However, it doesn't define hard limits on what we expect from the application.

**Comment by SchoolGuy** [comment]
So @tpw56j made some very good observations in regards to the general performance of our application in https://github.com/cobbler/cobbler/pull/3634#issuecomment-1986765464.

I would like to pick up this discussion in here in regard to this topic.

**Comment by tpw56j** [comment]
Tests from #3578 showed a similar result for me. In this case, it seems that processor power matters more than the type of storage device (SSD/HDD).

laptop: System76 Darter Pro, CPU i7-10510U, Samsung SSD 970 EVO Plus, btrfs single
```
$ time ./read.py
500000

real	0m25,124s
user	0m16,685s
sys	0m7,358s

$ time ./read.py
500000

real	0m17,820s
user	0m14,144s
sys	0m3,579s

$ time ./read2.py
500000

real	0m28,939s
user	0m23,848s
sys	0m4,430s

$ time ./read2.py
500000

real	0m29,297s
user	0m23,862s
sys	0m5,011s
```

desktop: CPU i7-9700, HDD 2 x ST12000NM0007-2A, btrfs raid1
```
$ time ./read.py
500000

real	0m12,340s
user	0m10,493s
sys	0m1,818s

$ time ./read.py
500000

real	0m12,213s
user	0m10,320s
sys	0m1,866s

$ time ./read2.py
500000

real	0m20,684s
user	0m18,492s
sys	0m2,141s

$ time ./read2.py
500000

real	0m20,455s
user	0m18,380s
sys	0m2,024s
```

**Comment by tpw56j** [comment]
@SchoolGuy I was wrong in assuming that most of the time is spent deserializing JSON. Taking a closer look at the code and taking new measurements, it seems to me that most of the time is spent on `collection.from_list()`. `cache_enabled` and `lazy_start` mitigate the problem a little but do not completely solve it.  I don't consider `lazy_start=true` a solution because it only postpones the problem until a later time.

Here are the results of my new measurements.

`cobbler/modules/serializers/sqlite.py`
```python
    def deserialize(
        self, collection: "Collection[ITEM]", topological: bool = True
    ) -> None:
        """
        Load a collection from disk.

        :param collection: The Cobbler collection to know the type of the item.
        :param topological: Sort collection based on each items' depth attribute in the list of collection items. This
                            ensures properly ordered object loading from disk with objects having parent/child
                            relationships, i.e. profiles/subprofiles.  See cobbler/items/item.py
        """
        t1 = time.time()
        self.__connect()
        datastruct = self.deserialize_raw(collection.collection_types())
        t2 = time.time()
        if topological and isinstance(datastruct, list):  # type: ignore
            datastruct.sort(key=lambda x: x.get("depth", 1))  # type: ignore
        t3 = time.time()
        if isinstance(datastruct, dict):
            # This is currently the corner case for the settings type.
            collection.from_dict(datastruct)  # type: ignore
        elif isinstance(datastruct, list):  # type: ignore
            collection.from_list(datastruct)  # type: ignore
        t4 = time.time()
        self.logger.info(f"{collection.collection_types()}: {len(datastruct)} - t4={t4 -t1}, t3={t3-t1}, t2={t2-t1}")
```

cache_enabled: false
lazy_start: false
systems: 1000 - t4=80.99749708175659, t3=0.027951955795288086, t2=0.02795124053955078

cache_enabled: true
lazy_start: false
systems: 1000 - t4=3.9756412506103516, t3=0.025963544845581055, t2=0.02596282958984375

cache_enabled: false
lazy_start: true
systems: 1000 - t4=0.058976173400878906, t3=0.0007021427154541016, t2=0.000701904296875

cache_enabled: true
lazy_start: true
systems: 1000 - t4=0.06196141242980957, t3=0.0006997585296630859, t2=0.0006995201110839844

**Comment by tpw56j** [comment]
@SchoolGuy There is another way to speed up the search. We can cache `item.find_match()` results. When deserializing 1000 systems, `item.find_match()` is called 999000 times and the cache could greatly speed up the deserialization.
The cache implementation for `item.find_match()` is quite simple - about 30 lines of code - but there is a problem with the cache data structure. I planned to implement it as:
`cached_find: Set[Optional[Dict[str, Any]]] = {}` where `Dict[str, Any]` is the search parameter passed to the `item.find_match()`.

But as it turns out, this doesn't work:
```
Error while loading a collection: unhashable type: 'dict'. Skipping collection system!
```
Maybe you know of a way to efficiently convert a Dict into a more  suitable object inside `Item.Cache` without changing the type of the `kwargs`parameter in `item.find_match()`?

Profiling results `collection.from_list()`:
```
         17342541 function calls (17100541 primitive calls) in 9.308 seconds

   Ordered by: cumulative time
   List reduced from 221 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1000    0.012    0.000    9.298    0.009 /usr/lib/python3.12/site-packages/cobbler/cobbler_collections/systems.py:34(factory_produce)
     1000    0.013    0.000    9.286    0.009 /usr/lib/python3.12/site-packages/cobbler/items/system.py:1062(__init__)
     1000    0.062    0.000    9.164    0.009 /usr/lib/python3.12/site-packages/cobbler/items/item.py:1137(from_dict)
185000/127000    0.214    0.000    8.763    0.000 /usr/lib/python3.12/site-packages/cobbler/items/item.py:362(__setattr__)
78000/55000    0.061    0.000    8.719    0.000 {built-in method builtins.setattr}
     1000    0.008    0.000    8.378    0.008 /usr/lib/python3.12/site-packages/cobbler/items/system.py:1173(interfaces)
     1000    0.018    0.000    8.363    0.008 /usr/lib/python3.12/site-packages/cobbler/items/system.py:332(from_dict)
     2000    0.007    0.000    8.224    0.004 /usr/lib/python3.12/site-packages/cobbler/api.py:1362(find_system)
     3000    0.813    0.000    8.222    0.003 /usr/lib/python3.12/site-packages/cobbler/cobbler_collections/collection.py:183(find)
   999000    1.652    0.000    7.028    0.000 /usr/lib/python3.12/site-packages/cobbler/items/item.py:1007(find_match)
     1000    0.003    0.000    4.259    0.004 /usr/lib/python3.12/site-packages/cobbler/items/system.py:548(ip_address)
     1000    0.004    0.000    3.999    0.004 /usr/lib/python3.12/site-packages/cobbler/items/system.py:583(mac_address)
   999000    1.922    0.000    3.423    0.000 /usr/lib/python3.12/site-packages/cobbler/items/item.py:1028(find_match_single_key)
   999000    0.855    0.000    1.498    0.000 /usr/lib/python3.12/site-packages/cobbler/items/item.py:1170(to_dict)
   999000    0.778    0.000    1.310    0.000 /usr/lib/python3.12/site-packages/cobbler/items/item.py:198(__find_compare)
  2140921    0.450    0.000    0.450    0.000 {method 'lower' of 'str' objects}
  2004997    0.396    0.000    0.396    0.000 {method 'items' of 'dict' objects}
162996/4996    0.170    0.000    0.343    0.000 /usr/lib64/python3.12/copy.py:118(deepcopy)
  2001000    0.327    0.000    0.327    0.000 /usr/lib/python3.12/site-packages/cobbler/items/item.py:1340(inmemory)
4999/1999    0.051    0.000    0.317    0.000 /usr/lib64/python3.12/copy.py:217(_deepcopy_dict)
```

**Comment by SchoolGuy** [comment]
@tpw56j Well 90% of the time the dict passed to `find_match` is a single key. That would cover at least our startup problem and most simple CLI searches for simple things. So then we just cache that instead?

**Comment by tpw56j** [comment]
@SchoolGuy If we find a faster algorithm for searching by item properties, then we can simply disable the cache. In the meantime, it seems to me that cache is the easiest way to speed up the start of a cobbler.

**Comment by SchoolGuy** [comment]
@tpw56j Well the algorithm itself is linear as it is only a single for loop. The part that takes time is the `to_dict()`. See the attached flamechart (1 distro, 1 profile, 500 systems).

![output](https://github.com/cobbler/cobbler/assets/15035141/bbb6880f-b40c-4e50-8c9d-dab8d3102452)

**Comment by tpw56j** [comment]
The call to `to_dict()` is in the first line of `find_match`.
And in my case, all calls to `to_dict()` come from `find_match`. And when retrieving a result from the cache, the `to_dict()` call will not happen at all.
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   999000    1.652    0.000    7.028    0.000 /usr/lib/python3.12/site-packages/cobbler/items/item.py:1007(find_match)
   999000    0.855    0.000    1.498    0.000 /usr/lib/python3.12/site-packages/cobbler/items/item.py:1170(to_dict)
```

**Comment by tpw56j** [comment]
@SchoolGuy The idea with a cache for `find_match` turned out to be unsuccessful. We end up with a huge, useless cache of negative search results for every item.

Maybe remove the `to_dict` call from `find_match` and replace the use of dict with getattr/hasattr?

**Comment by SchoolGuy** [comment]
So my thoughts are the following (not coded yet):

When we search for a specific item we need from every item the primary key (name atm) and the key plus value converted to str. Since `to_dict()` atm searches through raw data we can also do `getattr(f"_{key}")` in combination with a `hasattr`. Then we convert this value to str like `to_dict` does for us and compare the values.

The tricky part is how to correctly search through interfaces as this is a subobject of a given System. I would think that this can be done through refactoring `__is_interface_field` from `remote.py` to `utils.py`.

To my surprise, it seems that `find_match` doesn't work since it only returns the match for the last key in the dictionary. `res` is overwritten and not xored with the previous result. We will need a test for that in the future as well.

**Comment by tpw56j** [comment]
@ Yes, these are the same 1000 systems.

**Comment by SchoolGuy** [comment]
That would mean the indexes reduce 9 seconds to 1 second. This is a factor of 9. This is in my eyes plentiful to proceed.

**Comment by tpw56j** [comment]
@SchoolGuy The algorithm is nonlinear, so I expect that the gain will be greater on larger data sets.

There's still a lot to do in #3671 . Add index updates when updating/deleting items, add to the settings the ability to specify properties that will be indexed, etc.

**Comment by SchoolGuy** [comment]
@tpw56j I am fully aware and the testing will also be non-trivial but I fully believe that is the way forward until we remove the JSON database and only use relational databases for storing database records.
