### ISSUE TITLE
Cannot rename Items with uppercase characters

### ISSUE THREAD

**Issue by tpw56j** [cobbler/cobbler#3350]
### Describe the bug

1. Cobbler allows object names containing uppercase characters, but it is not possible to rename such objects. The renamed object is lost and cannot be recovered.
2. When renaming Items, no lock is set on manipulations with the collection, which can lead to unpredictable behavior.

### Steps to reproduce

1. cobbler menu add --name=Test
2. cobbler menu rename --name=Test --newname=test1
````
exception on server: 'Test'

# cobbler menu list
### ERROR ###
Unexpected remote error, check the server side logs for further info
<class 'AttributeError'>:'NoneType' object has no attribute 'name'
````
3. systemctl restart cobblerd
````
# cobbler menu report --name=Test
No menu found: Test
# cobbler menu report --name=test1
No menu found: test1
````
### Expected behavior

The renaming should happen without errors.

### Cobbler version

````paste below
Cobbler 3.3.3
  source: ?, ?
  build time: Wed Jul 20 00:00:00 2022
````
### Operating system

Fedora 37

### Cobbler log

````paste below
File "/usr/lib/python3.11/site-packages/cobbler/remote.py", line 2151, in xapi_object_edit
self.rename_item(object_type, handle, attributes["newname"], token)
File "/usr/lib/python3.11/site-packages/cobbler/remote.py", line 1657, in rename_item
self.api.rename_item(what, obj, newname)
File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 843, in rename_item
self.get_items(what).rename(ref, newname)
File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 262, in rename
self.listing.pop(oldname)
````

**Comment by SchoolGuy** [comment]
Since we called `.lower()` on all items, having items with uppercase letters didn't make much sense. Since the documentation doesn't say that items with uppercase letters are prohibited, I decided to follow the `RE_OBJECT_NAME` regex and remove the regression that we only allow lowercase items.

https://github.com/cobbler/cobbler/blob/8db6b9589cb508d7d61ace67a5e87ffc2bccfc55/cobbler/items/item.py#L25

**Comment by tpw56j** [comment]
@SchoolGuy The problem is local in `collection.rename` when manipulating the `collection.listing`. There is a difference between the keys in `collection.listing` and the names in `item.name`. And the problem is not with the names, but with the keys. Therefore, I do not see the need to change anything in other parts of the code.

**Comment by tpw56j** [comment]
@SchoolGuy I can change the object,  but I cannot have 2 objects named `Test` and `test` at the same time. It seems to me that your idea with `uid` instead of names in the names of json files, from which the change of keys in `collection.listing` from `lower(name)` to `uid` will follow, will solve this problem.
