### ISSUE TITLE
[docs] `get_*_handle()` methods are missing required parameter

### ISSUE THREAD

**Issue by nodeg** [cobbler/cobbler#3356]
### Describe the bug

The docstrings for some of the methods are not up to date. For example
https://github.com/cobbler/cobbler/blob/cbdfeb3e38c3212c1785887f13f0b68e1f8bbd86/cobbler/remote.py#L1333-L1340
does need the a `token` as required positional argument but the docstrings do not mention it.
### Steps to reproduce

1. Use e.g. `get_profile_handle(profile_name)` without specifying a token
2. See the error I mentioned below in the logs

### Expected behavior

The docstrings should be up to date and mention that those methods always need a token.

### Cobbler version

````bash
cobbler-srv:~ # cobbler version
Cobbler 3.3.3
  source: ?, ?
  build time: Thu Jan  5 12:00:00 2023
````

### Operating system

SLES 15 SP4

### Cobbler log

````bash
[Thread-320] 2023-02-21T11:36:37 - INFO | REMOTE version; user(?)                                                                                                             
[Thread-358] 2023-02-21T11:52:37 - INFO | authenticate; ['testing', True]                                                                                                     
[Thread-360] 2023-02-21T11:52:37 - INFO | Exception occurred: <class 'TypeError'>                                                                                             
[Thread-360] 2023-02-21T11:52:37 - INFO | Exception value: get_profile_handle() missing 1 required positional argument: 'token'                                               
[Thread-360] 2023-02-21T11:52:37 - INFO | Exception Info:                                                                                                                     
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3753, in _dispatch                                                                                          
    return method_handle(*params)
```

**Comment by SchoolGuy** [comment]
All `get_*_handle()`  have in their docstrings mentioned that they need a `token`. I will close this as completed. Please reopen if needed.

https://github.com/cobbler/cobbler/blob/d3230d5c550b837db4d08d5f193505d8256304f1/cobbler/remote.py#L1240-L1345
