### ISSUE TITLE
Delay reading collections during startup

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#3360]
### Is your feature request related to a problem?

As a Cobbler administrator
I want to have a quicker startup of Cobbler
so that I can restart the daemon with less downtime.

### Provide a detailed description of the proposed feature

Currently, in bigger environments, the startup of Cobbler is too slow. Since we can optimize the startup procedure only so much it is reasonable to have a delayed initialization of the database that temporarily causes Cobbler to not have its full dataset available.

### Alternatives you've considered

None

### Additional information

Splitout of #3301

**Comment by SchoolGuy** [comment]
The current implementation in #3363 requires us to call an XML-RPC method during daemon startup. This feels wrong.

The alternative that @tpw56j proposed is creating two new triggers that are available to be executed during startup and shutdown.

We also have a problem at the moment (partly linked to #3148) which is that the XML-RPC API is not just an XML-RPC API but also provides functionallity that is exclusively available there. The thing that is of concern for this issue is that we cannot start background tasks with the current structure of the API. This prevents us from moving the task of lazy-loading from `remote.py` to `api.py`. Linked to this is the problem that we skip the built-in authentication because we don't have a token during daemon startup yet. However, if we load the authentication module is loaded we are at a point where we could server request thus signalling to API consumers that we are ready to server requests already (which is not the case because we didn't load the data yet).

**Comment by tpw56j** [comment]
The background task of loading all objects in the implementation https://github.com/cobbler/cobbler/pull/3363 plays an auxiliary role and can be executed at any time later after the creation of the `CobblerAPI` object. You can even refuse to run this task altogether. In this case, there will be a delay when the object is first accessed.

**Comment by SchoolGuy** [comment]
@tpw56j This is your initial work. I would give you the final word.

My opinion is that the penalty for not loading all objects during idle times is very low since probably people just spam a `cobbler sync` which would force most items to be present anyway.

**Comment by tpw56j** [comment]
It also seems to me that it is possible to opt out of forcing objects to be loaded during idle time, at least until such time as there is a satisfactory way to run such a task. Those who need lazy loading have a huge number of objects, but most likely the active set of objects is much smaller. And in the case of `cobbler sync`, the additional time for reading objects will be relatively small.

**Comment by tpw56j** [comment]
It seems to me that the last word would be good to give to those who use a huge set of objects. In my practice, I didn’t have such a set that I needed delayed loading, I was interested in the task itself.

**Comment by tpw56j** [comment]
Alternative: if for some reason it is necessary to have all objects in memory, then we can assign this responsibility to the user, giving the opportunity to start this background job on his own with a command (or via API) something like `cobbler load`.
I do not really like the idea, I bring it only for the sake of completeness of alternatives.

**Comment by SchoolGuy** [comment]
After giving this some thought I have come to the following conclusion: We will not implement the background task in the linked PR. The issue is considered done after the PR is merged.

The reasoning behind that is the following: We have the issues #1283 & #3148. Both issues together state that we should move much of the logic in `remote.py` (thus including starting and managing background tasks) to the `api.py` module. Doing this in the linked PR looks out-of-scope. Since we cannot generate a representative number of users with big systems sadly, there is also no way to know the impact of my decision at this point in time. The worst-case scenario for this is acceptable because it is a one-time penalty which is not a problem for a long-running process like `cobblerd`.
