### ISSUE TITLE
Problem with pxelinux configs

### ISSUE THREAD

**Issue by user050126** [cobbler/cobbler#3370]
Hi,

I encountered a problem with configs generated in pxelinux.cfg folder, specifically the line below:

        append initrd=/images/debian11-x86_64/initrd.gz  auto-install/enable=true priority=criticalnetcfg/choose_interface=auto url=http://1.1.1.1/cblr/svc/op/autoinstall/system/mydebian hostname=test domain=mydomain.com suite=bullseye

There appears to be an extra space between `initrd.gz` and `auto-install` and no space between `priority=critical` and `netcfg`. I traced the issue to file lib/python3/dist-packages/cobbler/tftpgen.py, specifically line:

        f"{append_line} auto-install/enable=true priority=critical"

If we delete the space between `}` and `auto`, followed by inserting space between `critical` and `"`:

        f"{append_line}auto-install/enable=true priority=critical "

 the config is generated as it should:

        append initrd=/images/debian11-x86_64/initrd.gz auto-install/enable=true priority=critical netcfg/choose_interface=auto url=http://1.1.1.1/cblr/svc/op/autoinstall/system/mydebian hostname=test domain=mydomain.com suite=bullseye

### Steps to reproduce

1. Add system to cobbler with netboot enabled
2. Observe contents of /srv/tftpd/pxelinux.cfg/

### Cobbler version

````paste below
Cobbler 3.4.0                                                                                                         
  source: fb1a2d97, Tue Feb 14 18:52:39 2023 +0100                                                                    
  build time: Wed Sep 21 07:30:00 2022
````

### Operating system

````paste below
Debian 11.5
````

Thanks,
B

**Comment by SchoolGuy** [comment]
Thanks for filing this bug. If you have found the bug, is it possible for you to also submit the PR?

**Comment by user050126** [comment]
PR submitted :)

**Comment by SchoolGuy** [comment]
Thanks a lot. Saw it already. :)

**Comment by SchoolGuy** [comment]
@user050126 Any update on my question? I would love to have your PR!

**Comment by SchoolGuy** [comment]
@user050126 Okay no problem. I will then merge the PR. Tests can be added at a later point as well.
