### ISSUE TITLE
Prevent login to cobbler_web via users.conf

### ISSUE THREAD

**Issue by tjwiley** [cobbler/cobbler#338]
Using authn_ldap and either authz_configfile or authz_ownership, there doesn't appear to be a way to prevent login to the UI using users.conf.  I have only 2 users in users.conf & those users can login & have full access.  Any user not in users.conf can still login, they just won't be able to make any changes.  There should be a way to configure it so that any user not in users.conf will be denied access to the UI entirely.

**Comment by SchoolGuy** [comment]
The UI will be completly removed with 3.3.0 and thus I will close this one.
