### ISSUE TITLE
cobbler import fails on esxi70u3

### ISSUE THREAD

**Issue by gthota2342** [cobbler/cobbler#3401]
### Cobbler import fails with esxi70u3

cobbler import --name=esxi70u3iv5 --path=/mnt --arch=x86_64
task started: 2023-04-04_102826_import
task started (id=Media import, time=Tue Apr  4 10:28:26 2023)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
import_tree; ['/mnt', 'esxi70u3iv5', None, None, None]
importing from a network location, running rsync to fetch the files first
running: rsync -a  '/mnt/' /var/www/cobbler/distro_mirror/esxi70u3iv5-x86_64 --progress
received on stdout: sending incremental file list
received on stderr:
Exception occurred: <class 'AttributeError'>
Exception value: 'NoneType' object has no attribute 'get_import_manager'
Exception Info:
!!! TASK FAILED !!!
root@******~# ls -la /var/log/cobbler/
anamon/      cobbler.log  kicklog/     syslog/      tasks/
root@******:~# tail -f /var/log/cobbler/cobbler.log
  File "/usr/local/lib/python3.7/dist-packages/cobbler/remote.py", line 99, in run
    rc = self._run(self)

  File "/usr/local/lib/python3.7/dist-packages/cobbler/remote.py", line 313, in runner
    self.options.get("os_version", None),

  File "/usr/local/lib/python3.7/dist-packages/cobbler/api.py", line 1757, in import_tree
    import_module = self.get_module_by_name("managers.import_signatures") \

[2023-04-04_102826_import] 2023-04-04T10:28:28 - ERROR | ### TASK FAILED ###

**Comment by gthota2342** [comment]
I checked the issue https://github.com/cobbler/cobbler/issues/2544 created for similar issue but it does not work

**Comment by SchoolGuy** [comment]
@gthota2342 You didn't use the Bug report template. If you can open a propper issue I can try to help you but with the content provided, there is nothing I can do. We developed the template for a reason.

**Comment by gthota2342** [comment]
root@******:~# cobbler --version
Cobbler 3.3.3
  source: ?, ?
  build time: Wed Mar 15 10:52:42 2023
root@******:~# python3 --version
Python 3.7.3

**Comment by gthota2342** [comment]
Sure, I can do that
