### ISSUE TITLE
Failing to import windows iso

### ISSUE THREAD

**Issue by ricortiz** [cobbler/cobbler#3404]
### Describe the bug

The code fails to detect the correct file type for the install.wim file. In my case for windows server 2019.

The function call `magic.detect_from_filename(filename)` [here](https://github.com/cobbler/cobbler/blob/fdf13fc953215cec071a797e9b04aaf886cdec1b/cobbler/modules/managers/import_signatures.py#L115) returns a filetype with `ftype.mime_type == application/octet-stream`
but the code expects a `ftype.mime_type = application/x-ms-wim`. Since this ftype is returned by python-magic

The actual error:
```
...
Could not detect the filetype and read the content of file "/var/www/cobbler/distro_mirror/windows2019-x86_64/sources/install.wim". Returning nothing.
No signature matched in /var/www/cobbler/distro_mirror/windows2019-x86_64
...
```
### Steps to reproduce

1. cobbler import --name=windows2019 --path=/mnt/windows2019

### Expected/Correct behavior 

```
received on stdout: sending incremental file list
running: /usr/bin/wiminfo /var/www/cobbler/distro_mirror/windows2019-x86_64/sources/install.wim
received on stdout: WIM Information:
running: /usr/bin/wiminfo /var/www/cobbler/distro_mirror/windows2019-x86_64/sources/install.wim
received on stdout: WIM Information:
running: /usr/bin/wiminfo /var/www/cobbler/distro_mirror/windows2019-x86_64/sources/install.wim
received on stdout: WIM Information:
running: /usr/bin/wiminfo /var/www/cobbler/distro_mirror/windows2019-x86_64/sources/install.wim
received on stdout: WIM Information:
running: /usr/bin/wiminfo /var/www/cobbler/distro_mirror/windows2019-x86_64/sources/install.wim
received on stdout: WIM Information:
running: /usr/bin/wiminfo /var/www/cobbler/distro_mirror/windows2019-x86_64/sources/install.wim
received on stdout: WIM Information:
running: /usr/bin/wiminfo /var/www/cobbler/distro_mirror/windows2019-x86_64/sources/install.wim
received on stdout: WIM Information:
Adding distros from path /var/www/cobbler/distro_mirror/windows2019-x86_64:
running: ['/usr/bin/wimexport', '/var/www/cobbler/distro_mirror/windows2019-x86_64/sources/boot.wim', '1', '/var/www/cobbler/distro_mirror/windows2019-x86_64/boot/winpe.wim', '--boot']
received on stdout: Using LZX compression with 24 threads
running: ['/usr/bin/wimdir', '/var/www/cobbler/distro_mirror/windows2019-x86_64/boot/winpe.wim', '1']
received on stdout: /
running: ['/usr/bin/wimextract', '/var/www/cobbler/distro_mirror/windows2019-x86_64/sources/boot.wim', '1', '/Windows/Boot/PXE/pxeboot.n12', '/Windows/Boot/PXE/bootmgr.exe', '/Windows/System32/config/SOFTWARE', '--dest-dir=/var/www/cobbler/distro_mirror/windows2019-x86_64/boot', '--no-acls', '--no-attributes']
received on stdout: 
running: ['/usr/bin/wimupdate', '/var/www/cobbler/distro_mirror/windows2019-x86_64/boot/winpe.wim', '--command=add /var/www/cobbler/distro_mirror/windows2019-x86_64/boot/SOFTWARE /Windows/System32/config/SOFTWARE']
received on stdout: Scanning "/var/www/cobbler/distro_mirror/windows2019-x86_64/boot/SOFTWARE" (loading as WIM path: "/Windows/System32/config/SOFTWARE")...
running: /usr/bin/wiminfo /var/www/cobbler/distro_mirror/windows2019-x86_64/sources/install.wim
received on stdout: WIM Information:
new_distro; {}
trying symlink: /var/www/cobbler/distro_mirror/windows2019-x86_64 -> /var/www/cobbler/links/windows2019-x86_64
copying: /var/lib/cobbler/misc/anamon -> /var/www/cobbler/misc
copying: /var/lib/cobbler/misc/anamon.init -> /var/www/cobbler/misc
trying hardlink /var/www/cobbler/distro_mirror/windows2019-x86_64/boot/pxeboot.n12 -> /var/www/cobbler/images/windows2019-x86_64/pxeboot.n12
trying hardlink /var/www/cobbler/distro_mirror/windows2019-x86_64/boot/boot.sdi -> /var/www/cobbler/images/windows2019-x86_64/boot.sdi
trying to create cache file /var/lib/tftpboot/images/.link_cache/04ba28dc32fb2a567b728b86e05a18f73c401066
copying: /var/www/cobbler/distro_mirror/windows2019-x86_64/boot/pxeboot.n12 -> /var/lib/tftpboot/images/.link_cache/04ba28dc32fb2a567b728b86e05a18f73c401066
trying to create cache file /var/lib/tftpboot/images/.link_cache/bb025cedca07887916c4b7e5fa7a641ed3e30c14
copying: /var/www/cobbler/distro_mirror/windows2019-x86_64/boot/boot.sdi -> /var/lib/tftpboot/images/.link_cache/bb025cedca07887916c4b7e5fa7a641ed3e30c14
processing boot_files for distro: windows2019-x86_64
skipping symlink, destination (/var/www/cobbler/links/windows2019-x86_64) exists
Writing template files for windows2019-x86_64
new_profile; {}
copying: /var/lib/cobbler/misc/anamon -> /var/www/cobbler/misc
copying: /var/lib/cobbler/misc/anamon.init -> /var/www/cobbler/misc
Writing template files for windows2019-x86_64
sync_systems
associating repos
*** TASK COMPLETE ***
```

### Cobbler version

```
[root@fef585076eae python]# cobbler --version
Cobbler 3.4.0
  source: 711515c3, Fri Mar 31 14:09:55 2023 +0200
  build time: Sun Apr  2 18:16:55 2023
```

### Operating system

RHEL/Rocky Linux 8

### Additional information

I was able to fix it in my case by changing the code to accept what python-magic is returning but a more robust logic is probably preferable.

```
115c115
<         if ftype.mime_type == "application/x-ms-wim":
---
>         if ftype.mime_type == "application/octet-stream":
```

**Comment by SchoolGuy** [comment]
@tpw56j This is your area of expertise. Would you be able to help out please?

**Comment by tpw56j** [comment]
@ricortiz 
`python-magic` is in dependencies of the rpm package.
https://github.com/cobbler/cobbler/blob/fdf13fc953215cec071a797e9b04aaf886cdec1b/cobbler.spec#L58
Maybe `cobbler` wasn't installed from an rpm package?

**Comment by SchoolGuy** [comment]
Ah it could also be that if it is not being installed by the RPM package that the wrong Python magic is used. There are the native Python Magic bindings and the external project we are using.

**Comment by ricortiz** [comment]
@tpw56j I am installing cobbler from main and all its dependencies, I should probably mention that I am building a docker image and running cobbler in a container.

I am also installing the python3-magic RPM but it seems like Roky is installing this version:
```
[root@fef585076eae managers]# dnf list python3-magic
Last metadata expiration check: 0:00:43 ago on Thu Apr  6 20:37:16 2023.
Installed Packages
python3-magic.noarch                                                                                                   5.33-21.el8                                                                                                    @baseos
```
What version of python-magic does cobbler depend on?
I'd like to match it and test it again.

thanks!

**Comment by ricortiz** [comment]
actually, I am using a modified version of this docker file:

https://github.com/cobbler/cobbler/blob/main/docker/rpms/Rocky_Linux_8/Rocky_Linux_8.dockerfile

**Comment by tpw56j** [comment]
Cobbler depends on `python3-magic`, but `python3-magic` depends on `file-libs`.

Rocky 8 uses `file-libs-5.33-21.el8.x86_64` which does not support the WIM format:
```bash
[root@rocky8 /]# file -i /mnt/sources/boot.wim
/mnt/sources/boot.wim: application/octet-stream; charset=binary
```

WIM format support appeared in Rocky 9 (file-libs-5.39-10.el9.x86_64):
```bash
[root@rocky9 ~]# file -i /mnt/sources/boot.wim 
/mnt/sources/boot.wim: application/x-ms-wim; charset=binary

[root@rocky9 ~]# cat /usr/share/misc/magic
..
# Windows Imaging (WIM) Image
# Update: Joerg Jenderek at Mar 2019
# URL: https://en.wikipedia.org/wiki/Windows_Imaging_Format
# Reference: https://download.microsoft.com/download/f/e/f/
# fefdc36e-392d-4678-9e4e-771ffa2692ab/Windows%20Imaging%20File%20Format.rtf
# Note: verified by like `7z t boot.wim` `wiminfo install.esd --header`
0       string          MSWIM\000\000\000
>0      use             wim-archive
# https://wimlib.net/man1/wimoptimize.html
0       string          WLPWM\000\000\000
>0      use             wim-archive
0       name            wim-archive
# _WIMHEADER_V1_PACKED ImageTag[8]
>0      string          x                       Windows imaging
!:mime  application/x-ms-wim
# TO avoid in file version 5.36 error like
# Magdir/windows, 760: Warning: Current entry does not yet have a description
# file: could not find any valid magic files! (No error)
```

**Comment by SchoolGuy** [comment]
@tpw56j That should be mentioned in the Docs. That is an important point I believe...

**Comment by tpw56j** [comment]
@SchoolGuy Yes, we can mention it in the documentation, but I don't see a satisfactory solution for the supported distributions yet (Rocky 8 and maybe some others).

**Comment by SchoolGuy** [comment]
@tpw56j Me neither. This is out of our reach. Documenting it is the only way I see being realistic.

**Comment by tpw56j** [comment]
@SchoolGuy Okay, then I'll create a PR.

**Comment by SchoolGuy** [comment]
@tpw56j Thanks a lot!

**Comment by ricortiz** [comment]
Thanks, @tpw56j and @SchoolGuy. 

I think get what you are saying but to be clear, this is a bug in the current version of Cobbler that affects currently supported distributions, and the solution for the moment is to use a more recent distro with support for `file-libs-5.33-21.el8.x86_64`? 

I presume that if I install Cobbler using the generated RPM I will see this issue on Rocky 8?

This also affects Leap-15.4 since it packages `python3-magic-5.32` (and `file 5.32`).

**Comment by SchoolGuy** [comment]
@ricortiz This is not a bug in Cobbler. The problem here are just outdated dependencies. There is nothing Cobbler can do. And yes the error will be present on any Cobbler RPM because the problem is with `file-magic`. In fact it isn't even a problem with `file-magic`, it is just that the older versions don't have that feature.

I mean for sure Cobbler can improve in these areas but before we reach that point of "perfection" in our code, there are a lot of other things to do...

**Comment by tpw56j** [comment]
Full support for the WIM format was introduced in `file 5.37`: https://github.com/file/file/commit/13ba1a3639f7a40f3bffbabf2737cbdde314faf4

**Comment by ricortiz** [comment]
Okay, fair enough. 
Thanks for your help. Dropping this...

**Comment by SchoolGuy** [comment]
There is a PR that will document the issue. Thus reopening.
