### ISSUE TITLE
PXE Boot menu never includes profiles

### ISSUE THREAD

**Issue by woder** [cobbler/cobbler#3410]
### Describe the bug

When attempting to use Grub and UEFI, the PXE menu presented for a host with no system record is always blank. The only available option is to use "local" boot. 

### Steps to reproduce

1. Install the latest main branch version of cobbler (as of 17/04/2023)
2. Configure "server:" settings
3. Import a distro
4. Restart cobblerd and run cobbler sync
5. Observe that the files under tftpboot/grub are blank. (files like x86_64_menu_items.cfg)

### Expected behavior

Cobbler generates PXE menu entries for each profile, split up by architecture. In the previous example, I would expect "x86_64_menu_items.cfg" to include an entry for the profile I setup.

### Cobbler version

````
Cobbler 3.4.0
         source: ?, ?
         build time: Thu Apr 13 20:01:39 2023
````

### Operating system
Rocky 8

### Cobbler log

N/A

### Screenshots

N/A

### Additional information

It would appear that this problem is caused by an oversight in the profile module. When we go to generate PXE menu entries, we call `api.find_profile()` which eventually leads to the following section in item:
````
def find_match_single_key(
        self, data: Dict[str, Any], key: str, value: Any, no_errors: bool = False
    ) -> bool:
        """
        Look if the data matches or not. This is an alternative for ``find_match()``.
        :param data: The data to search through.
        :param key: The key to look for int the item.
        :param value: The value for the key.
        :param no_errors: How strict this matching is.
        :return: Whether the data matches or not.
        """
        # special case for systems
        key_found_already = False
        if "interfaces" in data:
            if key in [
                "cnames",
                "connected_mode",
                "if_gateway",
                "ipv6_default_gateway",
                "ipv6_mtu",
                "ipv6_prefix",
                "ipv6_secondaries",
                "ipv6_static_routes",
                "management",
                "mtu",
                "static",
                "mac_address",
                "ip_address",
                "ipv6_address",
                "netmask",
                "virt_bridge",
                "dhcp_tag",
                "dns_name",
                "static_routes",
                "interface_type",
                "interface_master",
                "bonding_opts",
                "bridge_opts",
                "interface",
            ]:
                key_found_already = True
                for (name, interface) in list(data["interfaces"].items()):
                    if value == name:
                        return True
                    if value is not None and key in interface:
                        if self.__find_compare(interface[key], value):
                            return True

        if key not in data:
            if not key_found_already:
                if not no_errors:
                    # FIXME: removed for 2.0 code, shouldn't cause any problems to not have an exception here?
                    # raise CX("searching for field that does not exist: %s" % key)
                    return False
            else:
                if value is not None:  # FIXME: new?
                    return False

        if value is None:
            return True
        return self.__find_compare(value, data[key])
````
Note the FIXME which once would have thrown an exception if a key we were expecting to find was not found. The issue is that as the `api.find_profile()` call includes a filter based on the profile field `arch`, the find code expects to find that field on the profile and does not. This appears to be related to the fact that `arch` is a derived property which actually comes from the parent of a profile, the distro. 

I have not fully investigated, but it is certainly possible that more problems of this nature exist within Cobbler, especially since there is no warning that a key we expected to filter on was not found on the object.

**Comment by SchoolGuy** [comment]
The same problem would appear in the Cobbler item `Image`. Thanks for the very well-written bug report and the corresponding Pull Request!
