### ISSUE TITLE
Changes needed to accomodate Sphinx 7.x

### ISSUE THREAD

**Issue by cinnion** [cobbler/cobbler#3455]
### Describe the bug

If Sphinx 7.x is installed, during builds, the build fails with an error such as the following:

````(venv) [cinnion@wing-1 cobbler]$ make webtest
rm -rf //usr/share/cobbler
make savestate
Traceback (most recent call last):
  File "/home/cinnion/git.github/cobbler/setup.py", line 17, in <module>
    from sphinx.setup_command import BuildDoc
ModuleNotFoundError: No module named 'sphinx.setup_command'
make[1]: *** [Makefile:137: savestate] Error 1
make: *** [Makefile:132: devinstall] Error 2
````

The problem is caused by the removal of setup_command from Sphinx 7.x as a part of the removal of support for Setuptools.

### Steps to reproduce

1. Install/upgrade to Sphinx 7.x
2. Attempt to build (e.g. `make webtest`)
3.

### Expected behavior

The build should have proceeded without an error.

### Cobbler version

````
Cobbler 3.3.3
  source: fcabb2b7, Wed Jun 21 08:53:01 2023 +0200
  build time: Wed Jun 21 23:57:10 2023
````

### Operating system

Rocky Linux release 9.2 (Blue Onyx)

### Cobbler log

````paste below
````

### Additional information

The build works fine up to Sphinx 6.2.1.

**Comment by SchoolGuy** [comment]
This issue is a backport of https://github.com/cobbler/cobbler/pull/3434

**Comment by SchoolGuy** [comment]
This is already done as of the 4th of August
