### ISSUE TITLE
Buildiso requires mounting ESP, incompatible with container case

### ISSUE THREAD

**Issue by avshiliaev** [cobbler/cobbler#3457]
### Is your feature request related to a problem?

As a developer  
I want the `buildiso` action to be executed without the underlying mounting of an ESP  
so that I can use it inside a container without giving it extra capabilities. 

### Provide a detailed description of the proposed feature

Calling `cobbler buildiso` is generally impossible inside a container. 
It boils down to the `mount -o loop <efi>` failing with `Could not mount...` as part of the `buildiso` action. I assume we cannot just execute mount inside a container without running it as `--privileged` and/or giving it certain capabilities, like `SYS_ADMIN`. 

In general we call `mount` to copy grub into an ESP as part of the `buildiso`. It's possible however to avoid it by using [mtools](https://www.gnu.org/software/mtools/). With mtools we can interact with a FAT32 partition (which ESP is) without the need to mount it. 

### Alternatives you've considered

Alternatively it's possible to give a container certain capabilities so we can `mount` inside it. However it makes it incompatible with many container use cases. 

### Additional information

General info
https://www.gnu.org/software/mtools/

Similar case by archiso
https://gitlab.archlinux.org/archlinux/archiso/-/merge_requests/72

**Comment by SchoolGuy** [comment]
Thanks for raising this and opening a PR for it!

**Comment by mbussolotto** [comment]
Please keep this issue open. PR https://github.com/cobbler/cobbler/pull/3458 is still missing and we're facing issue in unit test https://github.com/cobbler/cobbler/actions/runs/5644318832/job/15287866026?pr=3458 . Any idea for fixing it is welcome :)

**Comment by SchoolGuy** [comment]
That was the automation. Of course we want to keep this open.
