### ISSUE TITLE
Cobbler doesn't restart dhcpd6 daemon

### ISSUE THREAD

**Issue by Algirdas-Z** [cobbler/cobbler#3463]
### Describe the bug

Cobbler doesn't restart dhcpd daemon for ipv6

### Steps to reproduce

1. Enable IPV6 support in cobbler settings.conf
2. Do `cobbler sync`
3. Only ipv4 version of daemon is restarted

### Cobbler version

````paste below
3.4.0
````

### Operating system
Rocky 8.6

### Cobbler log

````paste below
````

### Additional information

````
Had not time to chase this issue, adding this issue for the record, will have a look if none will solve this sooner.

**Comment by SchoolGuy** [comment]
As much as I would like to finish up 3.4.0 finally, this bug is important enough to be included in 3.4.0.
