### ISSUE TITLE
icon should be a boot

### ISSUE THREAD

**Issue by mpdehaan** [cobbler/cobbler#3478]
This is just a friendly heads up that cobbler is a reference to the profession of shoe ... or **boot** making, not the upside down pie.  

The original icon idea was, I think a little cartoon boot with googley eyes, though this sketch has been lost to time.

Just wanted to make you aware in case you weren't aware you were mixing metaphors :)

I may be referring to the project that shows up in GitHub being a cheese shop thing, in which case it's not pie.  I'll see myself out :)

**Comment by mswilson** [comment]
just linking to #2604
