### ISSUE TITLE
cobbler is not installable in Ubuntu 22.04.3

### ISSUE THREAD

**Issue by coldbloodx** [cobbler/cobbler#3486]
### Describe the bug

cobbler is not installable in Ubuntu 22.04.3

I saw a ticket is logged here:
https://github.com/cobbler/cobbler/issues/3413, and PR has been merged.

so my question is:
a. when could the fix take effect?
b. when could I install cobbler via 'apt install'?

### Steps to reproduce

1.  update apt source:
```
root@usandbox:~# apt update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 https://artifacts.elastic.co/packages/7.x/apt stable InRelease
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [802 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-security/main Translation-en [169 kB]
Fetched 1200 kB in 10s (125 kB/s)
```
2. search cobbler, the command gives no output.
```
root@usandbox:~# apt-cache search cobbler
root@usandbox:~#
```

3. try install
```
root@usandbox:~# apt install cobbler
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package cobbler
```

### Cobbler version

````paste below
````

### Operating system

root@usandbox:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

### Cobbler log
N/A

````paste below
````

### Additional information

here is my source.list file:
```
root@usandbox:~# cat /etc/apt/sources.list
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://archive.ubuntu.com/ubuntu jammy main restricted
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu jammy universe
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy universe
deb http://archive.ubuntu.com/ubuntu jammy-updates universe
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://archive.ubuntu.com/ubuntu jammy multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy multiverse
deb http://archive.ubuntu.com/ubuntu jammy-updates multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu jammy-security main restricted
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy-security main restricted
deb http://archive.ubuntu.com/ubuntu jammy-security universe
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy-security universe
deb http://archive.ubuntu.com/ubuntu jammy-security multiverse
# deb-src http://cn.archive.ubuntu.com/ubuntu jammy-security multiverse
```

**Comment by SchoolGuy** [comment]
@coldbloodx With the provided repositories it is working as designed. Currently, there is no downstream maintainer that submits our code to the Debian and Ubuntu codestreams. As such you will need to use the official community repositories (that changed this week).

**Comment by coldbloodx** [comment]
@SchoolGuy can you point me the official community repositories, and installation document.

thanks in advance.

**Comment by SchoolGuy** [comment]
@coldbloodx The official community repository is located at: https://build.opensuse.org/project/show/systemsmanagement:cobbler

This project has Subprojects that are created for each release series. I am in the process of filling those repositories up so there are easier usable. :)

**Comment by zjf199249** [comment]
Compile and Install Cobbler 3.3 on Ubuntu error:

root@kwai:/opt# cobbler check
httpd does not appear to be running and proxying Cobbler, or SELinux is in the way. Original traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cobbler/cli.py", line 2119, in check_setup
    xmlrpc_server.ping()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 404 Not Found>

**Comment by NileshChandekar** [comment]
https://github.com/cobbler/cobbler/discussions/3573

**Comment by helloxjade** [comment]
I encountered the same issue and managed to resolve it using the following steps. 

sudo vim  /etc/apache2/sites-available/000-default.conf

`
 ServerName {your hostip} 
 ProxyPass /cobbler_api http://127.0.0.1:25151/cobbler_api
 ProxyPassReverse /cobbler_api http://127.0.0.1:25151/cobbler_api
`
sudo vim /etc/apache2/conf-available/cobbler.conf
`
<VirtualHost *:80>
    ServerName {your ip}  # 替换为您的服务器 IP 地址或域名

    DocumentRoot /var/www/html
    ProxyPass /cobbler_api http://127.0.0.1/cobbler_api
    ProxyPassReverse /cobbler_api http://127.0.0.1/cobbler_api
    ProxyPass /cobbler_web http://127.0.0.1/cobbler_web
    ProxyPassReverse /cobbler_web http://127.0.0.1/cobbler_web
</VirtualHost>
`



@

> Compile and Install Cobbler 3.3 on Ubuntu error:
> 
> ```
> root@kwai:/opt# cobbler check
> httpd does not appear to be running and proxying Cobbler, or SELinux is in the way. Original traceback:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/cobbler/cli.py", line 2119, in check_setup
>     xmlrpc_server.ping()
>   File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
>     return self.__send(self.__name, args)
>   File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
>     response = self.__transport.request(
>   File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib/python3.10/xmlrpc/client.py", line 1196, in single_request
>     raise ProtocolError(
> xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 404 Not Found>
> ```

**Comment by zjf199249** [comment]
> **我遇到了同样的问题，并设法使用以下步骤解决了它。**
> 
> sudo vim /etc/apache2/sites-available/000-default.conf
> 
> ```
>  ServerName {your hostip} 
>  ProxyPass /cobbler_api http://127.0.0.1:25151/cobbler_api
>  ProxyPassReverse /cobbler_api http://127.0.0.1:25151/cobbler_api
> ```
> 
> sudo vim /etc/apache2/conf-available/cobbler.conf
> 
> ```
> <VirtualHost *:80>
>     ServerName {your ip}  # 替换为您的服务器 IP 地址或域名
>     DocumentRoot /var/www/html
>     ProxyPass /cobbler_api http://127.0.0.1/cobbler_api
>     ProxyPassReverse /cobbler_api http://127.0.0.1/cobbler_api
>     ProxyPass /cobbler_web http://127.0.0.1/cobbler_web
>     ProxyPassReverse /cobbler_web http://127.0.0.1/cobbler_web
> </VirtualHost>
> ```
> 
> @
> 
> > 在 Ubuntu 上编译和安装 Cobbler 3.3 错误：
> > ```
> > root@kwai:/opt# cobbler check
> > httpd does not appear to be running and proxying Cobbler, or SELinux is in the way. Original traceback:
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.10/dist-packages/cobbler/cli.py", line 2119, in check_setup
> >     xmlrpc_server.ping()
> >   File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
> >     return self.__send(self.__name, args)
> >   File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
> >     response = self.__transport.request(
> >   File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
> >     return self.single_request(host, handler, request_body, verbose)
> >   File "/usr/lib/python3.10/xmlrpc/client.py", line 1196, in single_request
> >     raise ProtocolError(
> > xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 404 Not Found>
> > ```

Are you using Cobbler 3.3.6 or 3.3.3

**Comment by SchoolGuy** [comment]
Installing Cobbler on top of Ubuntu 22.04 is possible for a good while now. As such I will close this bug.
