### ISSUE TITLE
add support os AstraLinux and Alt linux

### ISSUE THREAD

**Issue by oditynet** [cobbler/cobbler#3491]
Hi. Will can  you adding support os as: Alt linux (https://www.altlinux.org/Releases/Download) and Astra linux (https://download.astralinux.ru/astra/stable/orel/iso/)

**Comment by SchoolGuy** [comment]
@tiltingpenguin could you maybe take this in the coming days?

**Comment by tiltingpenguin** [comment]
@oditynet ALT Linux doesn't seem to be a derivative of any of the breeds that we already have in cobbler (like debian, ubuntu, redhat, suse, etc) so we can't easily add support for it. Maybe you could contribute the information we need for supporting it though. Basically we need the parameters specified [here](https://github.com/cobbler/libcobblersignatures/blob/main/libcobblersignatures/data/v2/schema.json). We don't have any descriptions yet but you can have a look [here](https://github.com/cobbler/libcobblersignatures/blob/main/libcobblersignatures/data/v2/distro_signatures.json) for examples

**Comment by oditynet** [comment]
Thanks
