### ISSUE TITLE
Cobbler 3.3.3-1.el9 "url --url=$tree" Kickstart/Autoinstall file problem and workaround

### ISSUE THREAD

**Issue by zparihar** [cobbler/cobbler#3493]
### Describe the bug

Hey Folks and @SchoolGuy , I hope you're doing well.  Thanks for all that you're doing with Cobbler.
I've migrated from Cobbler 2.8.5 on CentOS 7.9 to Cobbler 3.3.3-1.el9 on AlmalLinux 9.2

Cobbler 2.8.5. was super stable.
Cobbler 3.3.3 has a number of issues and I'll start filing some bugs

(What I'd like to do is publish a modern Cobbler Tutorial Series)

BUG:

I have a Kickstart file (both for AlmaLinux 8 and AlmaLinux 9) with the following line: 
`url --url=$tree`

However, the variable '$tree' never gets its value substituted as a result, the PXE installation fails with the following message:

dracut-initqueue: Warning: Invalid value for 'inst.repo': $tree

![image](https://github.com/cobbler/cobbler/assets/684506/075c9104-73bc-4e3b-b637-2d71aa3e7c3b)

As a result, it  cannot find the RPM tree to do a Kickstart installation

I found out that it wasn't substituting the variable by running the 'get-autoinstall' script:
`cobbler profile get-autoinstall --name $ProfileName`

**The workaround is to change the value for 'url --url=$xyz**

I changed:
url --url=$tree

to

url --url=http://$IP_ADDRESS_OF_COBBLER_SERVER/cblr/links/$DISTRO_NAME_IN_COBBLER

### Steps to reproduce

1. Download the Distro:

mkdir /distros
cd /distros
wget http://mirror.myaccess.ca/8.8/isos/x86_64/AlmaLinux-8.8-x86_64-dvd.iso
mount -o loop /distros/AlmaLinux-8.8-x86_64-dvd.iso /mnt
cobbler import --path=/mnt --name=almalinux88-x86_64
umount /mnt
rm AlmaLinux-8.8-x86_64-dvd.iso

2. Do all your /etc/cobbler/* configurations
3. Create the Kickstart / Autoinstall file: /var/lib/cobbler/templates/almalinux8-cobbler-install.ks 

```
# Sample kickstart file for current EL, Fedora based distributions.

#platform=x86, AMD64, or Intel EM64T
# System authorization information
authselect  --useshadow  --enablemd5
# System bootloader configuration
bootloader --location=mbr
# Partition clearing information
clearpart --all --initlabel
# Use text mode install
text
# Firewall configuration
firewall --enabled
# Run the Setup Agent on first boot
firstboot --disable
# System keyboard
keyboard us
# System language
lang en_US
# Use network installation
url --url=$tree
# If any cobbler repo definitions were referenced in the kickstart profile, include them here.
$yum_repo_stanza
# Network information
$SNIPPET('network_config')
# Reboot after installation
reboot

#Root password
rootpw --iscrypted $default_password_crypted
# SELinux configuration
selinux --disabled
# Do not configure the X Window System
skipx
# System timezone
timezone  America/Vancouver --isUtc
# Clear the Master Boot Record
zerombr
# Allow anaconda to partition the system as needed
autopart

%pre
$SNIPPET('log_ks_pre')
$SNIPPET('autoinstall_start')
$SNIPPET('pre_install_network_config')
# Enable installation monitoring
$SNIPPET('pre_anamon')
%end


%packages
@^minimal-environment
kexec-tools
%end


%post --nochroot
$SNIPPET('log_ks_post_nochroot')
%end

%post
$SNIPPET('log_ks_post')
# Start yum configuration
$yum_config_stanza
# End yum configuration
$SNIPPET('post_install_kernel_options')
$SNIPPET('post_install_network_config')
$SNIPPET('download_config_files')
$SNIPPET('koan_environment')
$SNIPPET('redhat_register')
$SNIPPET('cobbler_register')
# Enable post-install boot notification
$SNIPPET('post_anamon')
# Start final steps
$SNIPPET('autoinstall_done')
# End final steps
%end
```

4. Create a Cobbler Profile for the AlmaLinux 8 distor and this kickstart file:

cobbler profile add --name=almalinux8-cobbler-install --distro=almalinux88-x86_64 --autoinstall=almalinux8-cobbler-install.ks

5. run 'cobbler sync'
6. Create a VM and start to PXE boot off the profil e

At this point, you will see this error.

### Expected behavior

It should kickstart AlmaLinux 8

### Cobbler version

````cobbler version
Cobbler 3.3.3
  source: ?, ?
  build time: Tue Jun 14 00:00:00 2022

````

### Operating system

cat /etc/almalinux-release 
AlmaLinux release 9.2 (Turquoise Kodkod)

### Cobbler log

The logs was massive so I searched for the string 'tree' and maybe this is whats relevant (?): 

````
[{'code': 'VFFSL(SL,"tree",True)',
  'exc_val': NotFound("cannot find 'tree'"),
  'lineCol': (23, 12),
  'rawCode': '$tree',
  'time': 'Thu Oct 26 14:53:02 2023'}]


````

### Additional information

**RESOLUTION / workaround is to change the value for 'url --url=$xyz**

I changed:
`url --url=$tree
`
to

`url --url=http://$IP_ADDRESS_OF_COBBLER_SERVER/cblr/links/$DISTRO_NAME_IN_COBBLER`

**Comment by zparihar** [comment]
Related to

https://github.com/cobbler/cobbler/issues/3417

**Comment by SchoolGuy** [comment]
I will close this as a duplicate. Thanks for submitting a workaround and such a well-written bug report!

**Comment by zparihar** [comment]
Thanks @SchoolGuy 

I was thinking about publishing a Bash script in a Post Sync Trigger to update the Kickstartart Auto install file.

Where should I publish that?

**Comment by SchoolGuy** [comment]
@zparihar If it is for the problem you are mentioning in this issue, just attach it to the original issue (#3417). I am currently working on fixing this and doing a backport.
