### ISSUE TITLE
SPEC file in git produces uninstallable RPM on RHEL/Rocky 9

### ISSUE THREAD

**Issue by cinnion** [cobbler/cobbler#3655]
### Describe the bug

The SPEC file found in the repository produces a RPM file which cannot be used on RHEL 9 or Rocky Linux 9. There is no longer any package which provides fence-agents, either as a real package or the metapackage it was. The result is as follows:

````
[root@host rpm-build]# dnf install cobbler-3.3.4-1.el9.noarch.rpm 
Last metadata expiration check: 1:59:17 ago on Sat 09 Mar 2024 01:32:17 PM EST.
Error: 
 Problem: conflicting requests
  - nothing provides fence-agents needed by cobbler-3.3.4-1.el9.noarch from @commandline
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
````

Inspecting the differences between the SPEC file used for the RPM in the EPEL 9 repository  and what is in git reveals that what is in git has no resemblance to what is in git. This should be resolved so that the same file is found in both places.

### Steps to reproduce

1. Build the RPMs from git by doing `make rpms`
2. Attempt to install the rpm using dnf using the command `dnf install  cobbler-3.3.4-1.el9.noarch.rpm`

### Expected behavior

The RPM should install, along with its missing dependencies.

### Cobbler version

````
[root@pell rpm-build]# cobbler version
Cobbler 3.3.4
  source: ?, ?
  build time: Mon Feb 26 00:00:00 2024
````
(from the EPEL RPM)

### Operating system

Verified on the following:
Red Hat Enterprise Linux release 9.2 (Plow)
Red Hat Enterprise Linux release 9.3 (Plow)
Rocky Linux release 9.3 (Blue Onyx)

### Cobbler log

````paste below
````

**Comment by opoplawski** [comment]
Some notes:

- Cobbler and Fedora/EPEL are completely different projects with different requirements and so it is likely that the spec files will be different.  Cobbler upstream may want to support many different RPM based distros.  That said, cobbler's spec file should produce usable RPMs where supported.
- It looks like `cobbler check` explicitly looks for `/usr/bin/fence_ilo` which is provided by the `fence-agents-ilo2` package on Fedora Rawhide.
- In Fedora `fence-agents` is provided by `fence-agents-all` which brings in all of the fence-agents sub-packages.
- `get_power_types()` looks for all of the installed `/usr/bin/fence_*` binaries, and `validate_power_type()` will complain if the power type is not installed and suggest installing `fence-agents` if none are.
- RHEL9 only ships a few fence agents and not the fence-agents-all package.  EPEL ships a few more, but not a fence-agents-all package as well.
- I don't know how other distros package the fence agents.

So, what to do?  I think it's futile to refer to package names in the cobbler code - they can change too much.  I think the cobbler messages should be changed to something like:

- `validate_power_types()`: `Excecutable fence_TYPE was not found.  Installed power management types are: ...  Other power management types may be available, check your distribution repositories.`
- `cobbler check`: Check for all fence_* - report as available power types.  If none found `Warning: no fencing tools were found and are required to use the (optional) power management features. install the desired fence_* executables from your distribution repositories.`

As for the spec file file, we dropped the `Requires: fence-agents` a long time ago in the Fedora package.  I`m not sure a `Suggests` is particularly warranted either, except perhaps on some very commonly used and universally available agents.

**Comment by SchoolGuy** [comment]
I agree with most of what @opoplawski said, sadly I would like to note that `fence-agents` is one of those packages that if not available the whole power management makes no sense. Also, the validation that we perform will cause Cobbler to not function if a package is for example removed during an update.

Moving the Power Management into a plugin doesn't make much sense in my eyes as without power management the PXE workflow is - in an automated manner - impossible. If needed by the community I can link the fence-agents that openSUSE/SLES ships and build them for RHEL/Rocky as well but they won't be maintained very well as I can't do all the things.

**Comment by opoplawski** [comment]
cobbler definitely shouldn't be shipping the fence agents.  In EPEL we can work on having cobbler pull in the fence agents that are available.

**Comment by SchoolGuy** [comment]
@cinnion I do agree that this bug is unfortunate for you but as long as you don't do any power operations this shouldn't have an effect on your Cobbler instance.

**Comment by cinnion** [comment]
Sorry it has been so long since I replied to this. Job hunting is more than a full-time job!. And right now, I am racking up some python development time related to cobbler to show off to a potential employer.

The problem is, even if you do not plan on using the power operations, the package in epel is still 3.3.4, built back on Feb 26, and while trying to build the RPMs works, when you go to install the RPM, you get the following:

```
[root@host rpm-build]# rpm -Uvh cobbler-3.3.6-1.el9.noarch.rpm
error: Failed dependencies:
        fence-agents is needed by cobbler-3.3.6-1.el9.noarch
```

Why am I wanting the RPM instead of doing a make?  I want to keep my builds separate from my admin machine, and I also like the fact that a `rpm -q -a` tells me the version and other info.

Regarding the `fence-agents-all` and `fence-agents-ilo` packages which @opoplawski  mentioned in his "Some notes" comment  on Mar 9, RHEL 9 moved those over to the High Availability repository. You can read about it [here](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/considerations_in_adopting_rhel_9/assembly_changes-to-packages_considerations-in-adopting-rhel-9#moved-packages_assembly_changes-to-packages). For Rocky, this means enabling the `highavailability` repository, and for RHEL 9 itself, it is the `rhel-9-for-x86_64-highavailability-rpms` repository.  Sounds like we might need to document the need for enabling these repos someplace and put a conditional in the spec file to require these to packages.

Thoughts? Shall I put up a pull request to make those two packages the requirement when we are talking RHEL 9?

**Comment by SchoolGuy** [comment]
Well from a Cobbler upstream side all should be good except that we are missing the documentation that on those distros one should enable those repositories.

Downstream the issue is that Cobbler is not part of RHEL/Rocky 9 and as such Cobbler is not being kept in mind when moving packages. I am not an expert but long term the only option is here to get Cobbler into RHEL to make them remember that Cobbler needs this. How they arrange their packages then I have no clue.

Of course, they can just play the ball back to us and tell us to structure Cobbler in a way that the power operations are an optional add-on. However, I don't see this happening as unattended installations are impossible without power management functionality.

**Comment by cinnion** [comment]
Of course, the funny thing is, Cobbler originated with RHEL, and that they would benefit greatly from it, since it makes facilitating kickstart installs so much easier.  As for their packages, I do have a bit of a window into that particular ball of string, but with a delay. I use Rocky for most of my machines, but I also have a personal RHEL developer subscription (it's free, thankfully), and currently have two VMs running honest-to-goodness RHEL9 (installed using kickstart, but manually created and served KS file, sadly).

So, should I go ahead and push a commit which makes the changes to the spec file?

(Now, back to trying to run my new cobbler server on Rocky 9 to replace my old cobbler 2 server running on CentOS 7, so that I can debug what is wrong with my configuration script, which I extracted using a tool I wrote. More on the dev mailing list.)

**Comment by SchoolGuy** [comment]
@cinnion Sadly the changes to the spec files don't really help.

If we were to implement this we would need to make conditional imports, change API responses and make the CLI commands unavailable. All of this is not done yet (the concept of optional CLI commands) and as such I would not like to go ahead with this change. It is not worth the effort to isolate a core feature of the application. 

Instead we just need to document that users need to enable the corresponding repositories before attempting to install Cobbler.

**Comment by cinnion** [comment]
Without the spec file changes, the enabling of the repositories does no
good, because the package name changes, and the install fails. I will go
ahead anyways to push the commit to my copy of the github repo, submit a
pull request and let you see and judge for yourself.

**Comment by cinnion** [comment]
OK... I just created the pull request, and in doing the write up, did some more checking. Not only did `fence-agents` get renamed, but it obviously got split into multiple packages, with `fence-agents-all` being a  meta package which supplies nothing.  I am attaching the output of `rpm -qR` and `rpm -q --filesbypkg` for both of those packages so that you can see for yourself.

And in this case, Red Hat's changes made sense, since this sort of package is really intended for clusters (hence the new repo), and it makes sense to only install what you want/need if doing it manually, while cobbler could technically use any fence, depending on how the systems are configured.
[fence-agents-all.txt](https://github.com/user-attachments/files/17477653/fence-agents-all.txt)
[fence-agents.txt](https://github.com/user-attachments/files/17477654/fence-agents.txt)
