### ISSUE TITLE
Lazy start is useless when there are a large number of systems

### ISSUE THREAD

**Issue by tpw56j** [cobbler/cobbler#3676]
### Describe the bug

Lazy start postpones the slow start problem until the first use of the system. When the system is loaded into memory, all items of the collection are searched and they are also recursively loaded into memory. With a large number of systems, the first command takes a very long time to execute.

### Steps to reproduce

1. lazy_start: true
2. systemctl start cobblerd
3. cobbler system add/edit ..

### Expected behavior

It is necessary to speed up the execution of the first command after the start.

### Cobbler version

````paste below
````

### Cobbler log

````paste below
Cobbler 3.4.0
````

**Comment by SchoolGuy** [comment]
So together with the work on the collection indexes this would mean that during startup we don't require a search anymore that force-loads all items which means in turn that the lazy-loading actually does what we intend it to do. Very good observation from you!
