### ISSUE TITLE
Cobbler not compatible with setuptools 70+

### ISSUE THREAD

**Issue by abravalheri** [cobbler/cobbler#3692]
https://github.com/cobbler/cobbler/blob/d944986a3ac9da519782013e0e4d15a849061695/setup.py#L21

This is the warning currently in place
https://github.com/pypa/setuptools/blob/v69.5.1/setuptools/dep_util.py#L5-L16.

**Comment by mshurutov** [comment]
setiprools-70.0.0 not have a dep_util:
```
Traceback (most recent call last):
  File "/tmp/portage/app-admin/cobbler-3.3.4/work/cobbler-3.3.4/setup.py", line 13, in <module>
    from setuptools import dep_util
ImportError: cannot import name 'dep_util' from 'setuptools' (/usr/lib/python3.12/site-packages/setuptools/__init__.py)
```
