### ISSUE TITLE
Collection indexes

### ISSUE THREAD

**Issue by tpw56j** [cobbler/cobbler#3720]
### Is your feature request related to a problem?

The feature request concerns the performance problem of working with a large number of objects.

As a user of Cobbler  
I want to speed up add/modify/delete operations on items in large collections  
so that I can avoid long waits when using the cobbler.

### Provide a detailed description of the proposed feature

The slowdowns are largely due to lengthy searches for elements in large collections. Collection indexes from PR #3671 solve only one particular problem and do not affect cases of searching by foreign key attributes when:
1. Cache invalidation when an object changes
2. building a PXE menu
2. Recursive removal of objects

Therefore, we need a more general approach to building collection indexes with the ability to disable them and specify properties in the settings.

### Alternatives you've considered

Database indexes would be a better solution to this problem.

### Additional information

None

**Comment by tpw56j** [comment]
@SchoolGuy In my case there are no systems involved, but there are many profiles and menu objects. Slowdowns occur when cache is invalidated in the "cobbler edit" command and when searching for `profile.parent`, `menu.parent` and `profile.menu` in `make_pxe_menu`.

**Comment by SchoolGuy** [comment]
Lets not fully give up on this idea just yet. I'll focus on work for now but I'll keep the ideas and work in the back of my head. The idea itself is completely valid.

**Comment by tpw56j** [comment]
@SchoolGuy Yes, I agree. A bad implementation doesn't mean the original idea was wrong.
