### ISSUE TITLE
DHCP/DNS managers iterate through all systems for a single system addition/removal

### ISSUE THREAD

**Issue by m-czernek** [cobbler/cobbler#3728]
### Describe the bug

When users use Cobbler as a DNS/DHCP manager, they can use one of the manager classes [0]. Currently, the manager classes do not implement adding a single system. Therefore, every time we add a single system, the manager classes iterate through every system managed by Cobbler, and re-render the configuration files.

When we remove a system, currently, managers rely on triggering a sync action that again regenerates all configs, which means iterating through all systems in memory (and since one system was removed from memory, it will effectively remove the system config from the DNS/DHCP config files).

This is not ideal for environments that have large number of systems managed by Cobbler, where adding one system can start to take minutes.

Though Cobbler has been focusing on improving performance of finding systems and iterating through systems, Cobbler should also be able to add/remove a single DNS/DHCP system without iterating through all other systems. 

That said, if a manager class doesn't implement functions to add/remove a single system, the original behavior should be preserved so as not to break backwards compatibility. 

[0] https://github.com/cobbler/cobbler/tree/main/cobbler/modules/managers

**Comment by SchoolGuy** [comment]
@m-czernek As the managers are an internal API I have no issue breaking that as long as we don't break the public one we have in `api.py`.

When looking at both the `ManagerModule`in `main and `release33` I do feel that the available methods are not quite right. The layout of that module was created with the current implementation of `sync.py` in mind. In the past, I have looked at a similar issue already in #3348. My time was too thin to implement my thoughts.

Please also consider while fixing this issue the fact that we will need a [cobbler-tftp](https://github.com/cobbler/cobbler-tftp) no-op module in the near future.
