### ISSUE TITLE
CNAMEs not properly rendered in 3.3(.4) on Redhat 9

### ISSUE THREAD

**Issue by fallsjo** [cobbler/cobbler#3812]
### Describe the bug

While migrating Cobbler from an ancient RHEL7 system running v2.8.5 to v3.3.4 on RHEL9; there seems to be a bug in how CNAMEs are rendered when the zone files are processed.

After some tracking I do believe it is due to how the Python array operators are handled and when forward porting to a newer versions of Python, this piece of code was overlooked, this was probably never caught since it is protected in a try-except block and just silently passed.

### Steps to reproduce

1. create systems with CNAMEs
2. run cobbler sync
3. inspect the rendered zone (fwd-)file

### Expected behavior

The $cname_record should be expanded with the related CNAMEs from the system definitions.

### Cobbler version

````
# cobbler version
Cobbler 3.3.4
  source: ?, ?
  build time: Mon Feb 26 00:00:00 2024
````

### Operating system

Redhat EL 9.4
Python 3.9.18

### Cobbler log

````
N/A
````

### Additional information

The solution is to replace line 482 in modules/managers/bind.py https://github.com/cobbler/cobbler/blob/release33/cobbler/modules/managers/bind.py#L482
````
                    if interface.get("dns_name", "") != "":
````
with
````
                    if interface.dns_name != "":
````

**Comment by SchoolGuy** [comment]
I'll include this in 3.3.7 since the bugfix is already mentioned in the issue description.

**Comment by SchoolGuy** [comment]
My manual test to reproduce this is the following:

```
cobbler-settings modify --key=manage_dns --value=True
cobbler-settings modify --key=manage_forward_zones --value="test.org"
cobbler-settings modify --key="manage_reverse_zones" --value="10.10.0"
supervisorctl restart cobblerd
touch /root/kernel /root/initrd /root/testfile
cobbler distro add --name=test --kernel=/root/kernel --initrd=/root/initrd
cobbler profile add --name=testprof --distro=test
cobbler system add --name=testsys --profile=testprof --interface="default" --ip-address=10.10.0.5 --hostname="myhost.example.org" --cnames="cname1.example.org cname2.example.org" --mac-address="aa:bb:cc:dd:ee:ff" --dns-name="myhost.example.org"
```

**Comment by SchoolGuy** [comment]
After applying the bugfix locally, I was able to generate cname records successfully.
