### ISSUE TITLE
Add support for remote scm repo

### ISSUE THREAD

**Issue by beefsalad** [cobbler/cobbler#427]
First a disclaimer.  I R nub (to git/python/cobbler..)

I have the need to track changes in a 'centralized' git repo (gitlab in this case.)  I appended the required changes to my /var/lib/cobbler/.git/config. 

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[user]
        name = Cobbler
        email = cobbler@bs.hostname.com
[remote "origin"]
        url = git@bs.hostname.com:Cobbler1/cobbler.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master

After verifying I was able to do the push manually, I twiddled a profile and fired off a cobbler sync.

running python trigger cobbler.modules.scm_track
running: git add --all config
received on stdout:
received on stderr:
running: git add --all kickstarts
received on stdout:
received on stderr:
running: git add --all snippets
received on stdout:
received on stderr:
running: git commit -m 'API update' --author 'cobbler <root@localhost.localdomain>'
received on stdout: # On branch master
# Your branch is ahead of 'origin/master' by 1 commit.
#
nothing to commit (working directory clean)

received on stderr:
running shell triggers from /var/lib/cobbler/triggers/change/*
*** TASK COMPLETE ***

So it was apparent that it was doing a commit, but not pushing.  I looked in /usr/lib/python2.6/site-packages/cobbler/modules/scm_track.py and found the following lines related to git.

       rc = utils.subprocess_call(logger,"git add --all config",shell=True)
       rc = utils.subprocess_call(logger,"git add --all kickstarts",shell=True)
       rc = utils.subprocess_call(logger,"git add --all snippets",shell=True)
       rc = utils.subprocess_call(logger,"git commit -m 'API update' --author 'cobbler <root@localhost.localdomain>'",shell=True)

the first idea I had was to add an additional line post-commit...
       rc = utils.subprocess_call(logger,"git add --all config",shell=True)
       rc = utils.subprocess_call(logger,"git add --all kickstarts",shell=True)
       rc = utils.subprocess_call(logger,"git add --all snippets",shell=True)
       rc = utils.subprocess_call(logger,"git commit -m 'API update' --author 'cobbler <root@localhost.localdomain>'",shell=True)
       rc= utils.subprocess_call(logger,"git push -u origin master/develop/test/dev/whatever",shell=True)

Does this seem feasible as a possible addition to 2.4.x?  I intend to maintain my local copy of 2.2.3 in this manner until I run into an issue.

**Comment by bstrdsmkr** [comment]
We have the same need, but found a work around (posting for those arriving by Google). We added the following in `/var/lib/cobbler/.git/hooks/post-commit`
```shell
#!/bin/sh

main() {
  local GIT_SSH_COMMAND="exec /usr/bin/ssh -i /root/.ssh/id_rsa ${@}"
  git push gitlab master
}

main "${@}"
```

This just temporarily overrides what git uses to ssh to the remote so that we can specify an ssh key to be used. If the user cobbler is running as already has a key for the remote, then all that's unnecessary and can be chopped down to `git push origin master` or etc. 

Now whenever a commit is made to the local repo, it gets shipped off to the remote hands free.

Hope that helps someone!

**Comment by jmaas** [comment]
Implemented in master.
