### ISSUE TITLE
Issue with manage_tftpd_py copying files to wrong directory

### ISSUE THREAD

**Issue by ghost** [cobbler/cobbler#530]
Small issue with the python managed tftp server. In the file manage_tftpd_py.py this function:

``` python
def write_tftpd_files(self):
        """
        xinetd files are written when manage_tftp is set in
        /var/lib/cobbler/settings.
        """
        template_file = "/etc/cobbler/tftpd.template"

        try:
            f = open(template_file,"r")
        except:
            raise CX(_("error reading template %s") % template_file)
        template_data = ""
        template_data = f.read()
        f.close()

        metadata = {
            "user"      : "nobody",
            "binary"    : "/usr/sbin/tftpd.py",
            "args"      : "-v"
        }

        self.logger.info("generating %s" % self.settings_file)
        self.templar.render(template_data, metadata, self.settings_file, None)
```

The value 'args' is using the flag "-v" as the folder to save the tftp server files (such as pxelinux.0). We'd have situations where a folder called '-v' would be created in '/' with all the files put in it.

The fix we've been using is to remove $args from tftpd.template and just hardcode the file directory.

**Comment by SchoolGuy** [comment]
The integrated TFTP Server in Python will be either deprecated or split. Thus closing this.
