### ISSUE TITLE
Log when a config object is ignored because a dependency is missing

### ISSUE THREAD

**Issue by criemen** [cobbler/cobbler#532]
Currentlya Distro object will not show up when the kernel is missing, which will result in the profile not showing up, because the distro is missing etc.
This is in principle okay, but as a user, one doesn't even get a warning in the log, which is bad. It doesn't seem to hard to just log when silently discarding an object, making it simpler to debug why stuff doesn't show up in the web interface.

**Comment by SchoolGuy** [comment]
This is implemented as of https://github.com/cobbler/cobbler/pull/3313
