### ISSUE TITLE
no debug info when execute genks within cobbler.log

### ISSUE THREAD

**Issue by wushuzh** [cobbler/cobbler#557]
I have a large ks file which works well without cobbler, now I am trying to migrate to cobbler.

So the 1st step I want to make it work without translate original ks to ks template. I think setting system ks would help me. But I get error msg when I execute 

'cobbler system getks --name=vmnio72'
  # This kickstart had errors that prevented it from being rendered correctly.
  # The cobbler.log should have information relating to this failure.

I am sure which part goes wrong, I check the /var/log/cobbler/cobbler.log, there is no useful dubeg info in there

  Tue Jul 30 14:01:59 2013 - INFO | REMOTE generate_kickstart; user(?)
  Tue Jul 30 14:01:59 2013 - INFO | generate_kickstart

Any suggestion on how to investigate next ?

(by the way, I asked to join the maillist serveral times but the request has not been approved ? my mail address is zhangjiaqiang@gmail.com)

**Comment by Ralithune** [comment]
I ran in to this today and there was no debug info in cobbler.log still....

**Comment by Ralithune** [comment]
I was able to figure it out through trial and error of removing lines.  Very painful process.
