### ISSUE TITLE
Cobbler doesn't assert mandatory interface

### ISSUE THREAD

**Issue by QuinnyPig** [cobbler/cobbler#564]
I realize I'm not specifying an interface in the first line, but cobbler accepts it under 2.4.0. It then complains about multiple interfaces on every cobbler action (including throwing tracebacks on cobbler sync) until the json file for the afflicted system is removed.

``` bash
# cobbler system add --name=cobbler1 --profile=minimal --mac=00:1e:67:7d:05:76
#cobbler system edit --name cobbler1 --interface eth0 --ip-address=10.2.0.5 --netmask=255.255.255.0  --static=1 --dns-name=cobbler1.localdomain
```

**Comment by SchoolGuy** [comment]
This is so old I will close it. If this is still present please reopen this and provide the updated information.
