### ISSUE TITLE
Detect and mount Cd rom when use cobbler to install debian

### ISSUE THREAD

**Issue by chubodoibenho** [cobbler/cobbler#588]
Hello.
when import distro debian : 
# cobbler import --name=debian-i386 --path=/media --arch=i386 --breed=debian

this import completed and i have result:
# cobbler distro report

Name                           : test_debian-i386
Architecture                   : i386
TFTP Boot Files                : {}
Breed                          : debian
Comment                        :
Fetchable Files                : {}
Initrd                         : /var/www/cobbler/ks_mirror/test_debian-i386/ins                                                                                                 tall.386/initrd.gz
Kernel                         : /var/www/cobbler/ks_mirror/test_debian-i386/ins                                                                                                 tall.386/vmlinuz
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Kickstart Metadata             : {'tree': 'http://@@http_server@@/cblr/links/tes                                                                                                 t_debian-i386'}
Management Classes             : []
OS Version                     : squeeze
Owners                         : ['admin']
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Template Files                 : {}
# cobbler profile report

Name                           : test_debian-i386
TFTP Boot Files                : {}
Comment                        :
DHCP Tag                       : default
Distribution                   : test_debian-i386
Enable gPXE?                   : 0
Enable PXE Menu?               : 1
Fetchable Files                : {}
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Kickstart                      : /var/lib/cobbler/kickstarts/sample.seed
Kickstart Metadata             : {}
Management Classes             : []
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Owners                         : ['admin']
Parent Profile                 :
Proxy                          :
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Repos                          : []
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : 1
Virt Bridge                    : xenbr0
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : 5
Virt Path                      :
Virt RAM (MB)                  : 512
Virt Type                      : kvm
# nano /var/lib/tftpboot/pxelinux.cfg/default

LABEL Debian_i386
        kernel /images/Debian-squeeze-i386/vmlinuz
        MENU LABEL Debian_i386
        append initrd=/images/Debian-squeeze-i386/initrd.gz ksdevice=bootif lang=  text  auto-install/enable=true priority=critical url=http://192.168.1.119/cblr/svc/op/ks/prof$
        ipappend 2

but when i pxeboot to this profile this have error : Detect and Mount Cd-rom not found
so i can't install debian6.x to my client.
where is my error in my config ?

**Comment by wcd923** [comment]
Hi! I'm having the same problem with cobbler/debian. Have you found the solution?
