### ISSUE TITLE
Support spice in VMs

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#593]
It doesn't look like cobbler supports using spice with VMs.  Is that correct.  We should fix that.

**Comment by SchoolGuy** [comment]
I have the impression, that this has nothing to do with Cobbler. As far as I can see, this has to be passed with the [graphics option](https://github.com/cobbler/koan/blob/master/koan/app.py#L223-L228) in Koan. Please reopen if you feel otherwise.
