### ISSUE TITLE
'cobbler check' tells fedora 20 to deal with xinetd without docs

### ISSUE THREAD

**Issue by mykelalvis** [cobbler/cobbler#791]
Executing cobbler check produces this result:

    [root@test cobbler]# cobbler check
    The following are potential configuration items that you may want to fix:
    
    1 : file /etc/xinetd.d/rsync does not exist
    
    Restart cobblerd and then run 'cobbler sync' to apply changes.
    

I see no references in the documentation to managing rsync in xinetd.d regarding cobbler.  Some previous editions of Fedora delivered an rsync config in xinetd.d.  Apparently that's no longer true after The Massive Change In EVERYTHING Fedora.

So how should I proceed?

**Comment by jmaas** [comment]
Looking at the code there i see that most checks aren't even implemented for the ubuntu & debian cases. And then the implementation for the rpm based systems is outdated (no systemd checks). 

I really dislike this coupling of deployment scenarios in the code.

**Comment by alanoe** [comment]
JM> Looking at the code there i see that most checks aren't even implemented for the ubuntu & debian cases. And then the implementation for the rpm based systems is outdated (no systemd checks). 

As I mentioned above, we could document which target distros and distro versions were tested, this makes easier for a Cobbler developer who wants to improve the feature and makes easier for users who then would know in which distros the feature works and would not even try if they are using something else. imho we do not need to support all distros.

I am sure "cobbler check" helps the user, but we can drop it if we conclude we are not able to support the diversity of available Linux distributions (mainly Red Hat / Debian differences).

**Comment by jmaas** [comment]
cobbler check has been updated to support the systemd case for rsync.
