### ISSUE TITLE
network install fails on parsing preseed file

### ISSUE THREAD

**Issue by thirstycat** [cobbler/cobbler#938]
version:
Cobbler 2.7.0
  source: e4cb483, Sun Apr 27 10:51:17 2014 +0200
  build time: Mon May  5 15:21:23 2014

When provisioning a new Ubuntu (14.04) system, it seems cobbler is choking on the root password hash in the preseed file:

from cobbler.log...

Tue May  6 17:03:43 2014 - INFO | REMOTE generate_kickstart; user(?)
Tue May  6 17:03:43 2014 - INFO | generate_kickstart
Tue May  6 17:03:43 2014 - WARNING | errors were encountered rendering the template
Tue May  6 17:03:43 2014 - WARNING | 
[{'code': u'VFFSL(SL,"ArGzKX2YeQ3G6U.mlOO3A.NaL22Ewgz8Fi4qqz.Ns7EMKjEJRIW2Pm",True)',
  'exc_val': NotFound("cannot find 'ArGzKX2YeQ3G6U'",),
  'lineCol': (46, 61),
  'rawCode': u'$ArGzKX2YeQ3G6U',
  'time': 'Tue May  6 17:03:43 2014'}]

the relevant line from my preseed file is:

d-i     passwd/user-password-crypted    password $6$.1eHH0iY$ArGzKX2YeQ3G6U
d-i     passwd/user-uid string

(hash changed to protect the guilty ;-)

**Comment by BijoyPrajapati** [comment]
Hi I have a cobbler for pxe installation. When I try to network installation, it started but it goes stopped installation in  the following path and asking lots of question : I tried in a vm with the same kickstart file, but there is no error like this and installation completed. I only have this error in another physical machine. What could be the cause

![image](https://user-images.githubusercontent.com/52848005/66912994-5b757980-f031-11e9-9335-256eee41b114.png)
![IMG_20191011_122437](https://user-images.githubusercontent.com/52848005/66913007-6b8d5900-f031-11e9-9699-ba1e4ca0bb1f.jpg)
