### ISSUE TITLE
Collecting messages in one file.

### ISSUE THREAD

**Issue by sandlbn** [cobbler/cobbler#943]
It would be nice to collect all the error messages in one file. At the moment they are scattered across different files and hard to catch what they refer to. I think it would be good also to catalog them by type. eg. VIRT_ERROR, ACCESS_ERROR etc...

**Comment by SchoolGuy** [comment]
Sooo this should be fixed with https://github.com/cobbler/cobbler/pull/2139. However now we haven't made it possible afaik to separate the task logs. Maybe it is possible via the Python `logging.conf` but I am not sure. Feel free to reopen if you feel that this ticket is not closed.
