### ISSUE TITLE
Allow yum groups in Package resources

### ISSUE THREAD

**Issue by verdurin** [cobbler/cobbler#952]
When I tried to add a yum group as a package ('@editors'), there was an error:

An error has occurred. You may find more information in /var/log/cobbler/cobbler.log on the server should this error not be self explanatory.

<Fault 1: '<class \'cobbler.cexceptions.CX\'>:"invalid characters in name: \'@editors\'"'>

cobbler-2.4.4-1.el6.noarch

**Comment by SchoolGuy** [comment]
This is very old and there is a lot of context missing for me to understand it. Thus closing it. Pls reopen if needed.
