### ISSUE TITLE
Koan runs extremely slowly since 2.4

### ISSUE THREAD

**Issue by mlg9000** [cobbler/cobbler#953]
Since switching from libvirt-python to virsh in koan 2.4, koan is completely unusable on Centos 6.x.  There are no errors or logs that indicate any obvious errors that I can find.  The OS installer (also Centos 6) does run, just extremely slowly.  Where an install took 5 minutes with koan 2.2, 2.4 and 2.6 take 12+ hours.  I have only tested this with KVM and Centos 6x hosts/guests.

**Comment by jmaas** [comment]
Copied to cobbler/koan repo.
